const CORE_LANGS=["ar","en","nl","es","he"];
const TXT={
ar:{sub:"22 يوليو 2026 · حادثة، جسر، وسؤال عن الاتصال والإرادة",intro:"بحث حي يبدأ من تصادم ترام على جسر إيراسموس ثم يتفرع إلى الجسر، إيراسموس الإنسان، الإرادة الحرة، السلام، الجامعة، التاريخ والقراءات الرمزية. المصادفة تُوثق أولاً، تُختبر ثانياً، وتُفسر أخيراً.",v:"موثّق",p:"مرجّح",h:"قراءة رمزية",o:"مفتوح",x:"مرفوض",tree:"الشجرة",time:"الزمن",report:"التقرير الحالي",sources:"المصادر",all:"كل الفروع",doc:"الموثق فقط",hyp:"الفرضيات والأسئلة",cross:"الخط الذهبي المنقط = علاقة تفسيرية بين فرعين مستقلين",method:"المنهج: لا نفترض أن المصادفة تعني السببية. كل عقدة تحتفظ بدرجة ثقة ومصدر، والفروع الضعيفة لا تُحذف بل تُعلّم كمرفوضة عند سقوطها.",close:"إغلاق",open:"فتح المصدر",snapshot:"هذه لقطة تنفيذية من النسخة الحية v0.1. عند تحديث الأدلة تتغير الشجرة، ويُعاد توليد التقرير من آخر حالة موثقة."},
en:{sub:"22 July 2026 · A collision, a bridge, and a question of connection and will",intro:"A living investigation beginning with the tram collision on the Erasmus Bridge, branching into the bridge, Erasmus the thinker, free will, peace, the university, chronology and symbolic readings. Coincidence is documented first, tested second, interpreted last.",v:"Verified",p:"Probable",h:"Symbolic reading",o:"Open",x:"Rejected",tree:"Tree",time:"Timeline",report:"Current report",sources:"Sources",all:"All branches",doc:"Documented only",hyp:"Hypotheses & questions",cross:"Dotted gold = interpretive relation between independent branches",method:"Method: coincidence is not assumed to imply causation. Every node keeps a confidence state and source; failed branches remain visible as rejected rather than disappearing.",close:"Close",open:"Open source",snapshot:"This is an executive snapshot of living version v0.1. As evidence changes, the tree changes and the report is regenerated from the latest verified state."},
nl:{sub:"22 juli 2026 · Een botsing, een brug en een vraag over verbinding en wil",intro:"Een levend onderzoek dat begint bij de trambotsing op de Erasmusbrug en vertakt naar de brug, Erasmus als denker, vrije wil, vrede, de universiteit, chronologie en symbolische lezingen. Toeval wordt eerst gedocumenteerd, daarna getest en pas dan geïnterpreteerd.",v:"Geverifieerd",p:"Waarschijnlijk",h:"Symbolische lezing",o:"Open",x:"Verworpen",tree:"Boom",time:"Tijdlijn",report:"Huidig rapport",sources:"Bronnen",all:"Alle takken",doc:"Alleen gedocumenteerd",hyp:"Hypothesen & vragen",cross:"Gouden stippellijn = interpretatieve relatie tussen onafhankelijke takken",method:"Methode: toeval wordt niet als causaliteit behandeld. Elke knoop bewaart bron en zekerheid; mislukte verbanden blijven zichtbaar als verworpen.",close:"Sluiten",open:"Bron openen",snapshot:"Dit is een uitvoerende momentopname van levende versie v0.1. Bij nieuw bewijs verandert de boom en wordt het rapport opnieuw opgebouwd."},
es:{sub:"22 de julio de 2026 · Una colisión, un puente y una pregunta sobre conexión y voluntad",intro:"Investigación viva que parte del choque de tranvías en el puente Erasmus y se ramifica hacia el puente, Erasmus, el libre albedrío, la paz, la universidad, la cronología y las lecturas simbólicas. La coincidencia se documenta primero, se prueba después y se interpreta al final.",v:"Verificado",p:"Probable",h:"Lectura simbólica",o:"Abierto",x:"Rechazado",tree:"Árbol",time:"Cronología",report:"Informe actual",sources:"Fuentes",all:"Todas las ramas",doc:"Solo documentado",hyp:"Hipótesis y preguntas",cross:"Línea dorada punteada = relación interpretativa entre ramas independientes",method:"Método: no se supone que coincidencia implique causalidad. Cada nodo conserva fuente y grado de confianza; las conexiones fallidas quedan visibles como rechazadas.",close:"Cerrar",open:"Abrir fuente",snapshot:"Instantánea ejecutiva de la versión viva v0.1. Con nueva evidencia cambia el árbol y se regenera el informe."},
he:{sub:"22 ביולי 2026 · התנגשות, גשר ושאלה על חיבור ורצון",intro:"מחקר חי שמתחיל בהתנגשות החשמליות על גשר ארסמוס ומסתעף אל הגשר, ארסמוס ההוגה, רצון חופשי, שלום, האוניברסיטה, ציר הזמן וקריאות סמליות. תחילה מתעדים את הצירוף, אחר כך בודקים ורק לבסוף מפרשים.",v:"מאומת",p:"סביר",h:"קריאה סמלית",o:"פתוח",x:"נדחה",tree:"עץ",time:"ציר זמן",report:"דוח נוכחי",sources:"מקורות",all:"כל הענפים",doc:"מתועד בלבד",hyp:"השערות ושאלות",cross:"קו זהב מקווקו = קשר פרשני בין ענפים עצמאיים",method:"שיטה: אין מניחים שצירוף מקרים הוא סיבתיות. לכל צומת נשמרים מקור ורמת ביטחון; קשרים שנכשלו נשארים גלויים כנדחים.",close:"סגירה",open:"פתיחת מקור",snapshot:"זוהי תמונת מצב מנהלית של גרסה חיה v0.1. עם שינוי הראיות משתנה העץ והדוח נבנה מחדש."}};
const SOURCES=[
["S1","NOS","Trambotsing Erasmusbrug: 15 gewonden; ongeveer 11:10; oorzaak nog onderzocht","https://nos.nl/artikel/2623974-vijftien-gewonden-bij-botsing-trams-op-erasmusbrug-in-rotterdam-vreselijk-ongeluk"],
["S2","Stadsarchief Rotterdam","Erasmusbrug gepland als symbool van een ongedeelde stad; naam officieel in 1992","https://stadsarchief.rotterdam.nl/erasmusbrug"],
["S3","Erasmus University Rotterdam","Erasmian values: connecting, cooperation, dialogue and building bridges","https://www.eur.nl/en/about-university/vision-strategy-2030/erasmian-values"],
["S4","Vatican News","22 July 2026 is the Feast of Mary Magdalene in the Catholic calendar","https://www.vaticannews.va/en/word-of-the-day/2026/07/22.html"],
["S5","Britannica","Erasmus: Christian humanist, scholar, reform-minded critic and author","https://www.britannica.com/biography/Desiderius-Erasmus"],
["S6","Stanford Encyclopedia of Philosophy","Erasmus on free will and the controversy with Luther","https://plato.stanford.edu/entries/erasmus/"],
["S7","Internet Archive / public-domain Erasmus texts","Primary-text trail for The Complaint of Peace and related works","https://archive.org/search?query=creator%3A%22Erasmus%2C+Desiderius%22"]];
const N=[
{id:"collision",p:null,s:"verified",ar:"22·07·2026 · التصادم",en:"22·07·2026 · Collision",nl:"22·07·2026 · Botsing",es:"22·07·2026 · Colisión",he:"22·07·2026 · התנגשות",arD:"نحو 11:10 صباحاً اصطدمت ترام بترام أخرى متوقفة على Erasmusbrug بسبب فتح الجزء المتحرك من الجسر. أُعلن لاحقاً عن 15 مصاباً، أحدهم إصابته خطيرة. سبب التصادم بقي قيد التحقيق في التقارير الأولية.",enD:"At about 11:10 a tram struck another tram that was stopped on the Erasmusbrug because the movable bridge section was open. The later reported total was 15 injured, one seriously. The cause remained under investigation in initial reporting.",src:["S1"]},
{id:"bridge",p:"collision",s:"verified",ar:"Erasmusbrug",en:"Erasmus Bridge",nl:"Erasmusbrug",es:"Puente Erasmus",he:"גשר ארסמוס",arD:"الجسر نفسه صُمم ضمن مشروع Kop van Zuid ليكون رمزاً لمدينة غير منقسمة، أي أن معنى الاتصال ليس اختراعاً لاحقاً من البحث.",enD:"The bridge was conceived within Kop van Zuid as a symbol of an undivided city, so connection is not a meaning invented only after the collision.",src:["S2"]},
{id:"stop",p:"collision",s:"verified",ar:"توقف ↔ حركة",en:"Stop ↔ movement",nl:"Stop ↔ beweging",es:"Parada ↔ movimiento",he:"עצירה ↔ תנועה",arD:"البنية المادية للحادث: ترام توقفت بسبب الجسر المفتوح، وأخرى واصلت الحركة حتى وقع التصادم. هذا الوصف لا يحدد سبب الخطأ.",enD:"Material structure of the event: one tram stopped because the bridge was open; another continued until collision. This does not determine the cause of error.",src:["S1"]},
{id:"cause",p:"collision",s:"open",ar:"سبب الحادث",en:"Cause of collision",nl:"Oorzaak",es:"Causa",he:"סיבת התאונה",arD:"عقدة مفتوحة. لا تُملأ بفرضية السائق أو الفرامل أو التقنية قبل نتائج التحقيق الموثقة.",enD:"Open node. It is not filled with driver, brake or technical explanations before documented investigation results.",src:["S1"]},
{id:"erasmus",p:"bridge",s:"verified",ar:"إيراسموس الإنسان",en:"Erasmus the thinker",nl:"Erasmus de denker",es:"Erasmus, el pensador",he:"ארסמוס ההוגה",arD:"Desiderius Erasmus من Rotterdam: إنساني مسيحي وعالم ولاهوتي وكاتب نقدي ترك أثراً واسعاً في أوروبا الحديثة المبكرة.",enD:"Desiderius Erasmus of Rotterdam: Christian humanist, scholar, theologian and critical writer with major influence on early modern Europe.",src:["S5"]},
{id:"will",p:"erasmus",s:"verified",ar:"الإرادة الحرة",en:"Free will",nl:"Vrije wil",es:"Libre albedrío",he:"רצון חופשי",arD:"دخل إيراسموس في جدل شهير مع مارتن لوثر حول حرية الإرادة ومسؤولية الإنسان. هذا موضوع تاريخي ثابت، أما ربطه بالحادث فهو سؤال فلسفي لا نبوءة.",enD:"Erasmus entered a famous controversy with Martin Luther over free will and human responsibility. That history is established; connecting it to the collision is a philosophical question, not prophecy.",src:["S6"]},
{id:"peace",p:"erasmus",s:"verified",ar:"السلام والحرب",en:"Peace & war",nl:"Vrede & oorlog",es:"Paz y guerra",he:"שלום ומלחמה",arD:"كتابات إيراسموس تنتقد الحرب والانقسام المسيحي وتدافع عن السلام. البحث سيختبر نصوصه الأصلية قبل وصف أي تحذير بأنه نبوءة.",enD:"Erasmus wrote against war and Christian division and in favor of peace. The project tests primary texts before calling any warning a prophecy.",src:["S7"]},
{id:"prophecy",p:"peace",s:"open",ar:"نبوءات؟",en:"Prophecies?",nl:"Profetieën?",es:"¿Profecías?",he:"נבואות?",arD:"فرع تدقيقي: نفرق بين تنبؤ صريح، تحذير سياسي أو أخلاقي، وقراءة لاحقة. علامة الاستفهام جزء من المنهج.",enD:"Audit branch: distinguish explicit prediction, political or ethical warning, and retrospective reading. The question mark is part of the method.",src:["S7"]},
{id:"university",p:"erasmus",s:"verified",ar:"جامعة إيراسموس",en:"Erasmus University",nl:"Erasmus Universiteit",es:"Universidad Erasmus",he:"אוניברסיטת ארסמוס",arD:"الجامعة المعاصرة تجعل الاتصال والحوار والتعاون وبناء الجسور جزءاً صريحاً من Erasmian values.",enD:"The contemporary university explicitly includes connection, dialogue, cooperation and building bridges in its Erasmian values.",src:["S3"]},
{id:"connection",p:"bridge",s:"hypothesis",ar:"اتصال يصطدم باتصال",en:"Connection collides with connection",nl:"Verbinding botst op verbinding",es:"Conexión choca con conexión",he:"חיבור מתנגש בחיבור",arD:"قراءة رمزية: وسيلتا نقل عام تتصادمان فوق بنية وظيفتها الربط وتحمل اسم مفكر ارتبط بالحوار والسلام. قوة المعنى لا تثبت السببية أو القصد.",enD:"Symbolic reading: two public-transport vehicles collide on infrastructure built to connect, named for a thinker associated with dialogue and peace. Meaning does not establish causation or intent.",src:["S1","S2","S3"]},
{id:"date",p:"collision",s:"verified",ar:"22 يوليو",en:"22 July",nl:"22 juli",es:"22 de julio",he:"22 ביולי",arD:"التاريخ مثبت للحادث. تُدرس أحداث اليوم الأخرى فقط إذا وُجد رابط مستقل، لا لمجرد اشتراك التاريخ.",enD:"The collision date is established. Other events on the date enter the tree only when an independent link exists, not merely because the date matches.",src:["S1"]},
{id:"magdalene",p:"date",s:"probable",ar:"مريم المجدلية",en:"Mary Magdalene",nl:"Maria Magdalena",es:"María Magdalena",he:"מרים המגדלית",arD:"22 يوليو هو عيد مريم المجدلية في التقويم الكاثوليكي. وجوده في التاريخ حقيقة؛ علاقته بحادث إيراسموس ضعيفة حالياً ولا تُرفع إلى أكثر من تقاطع سياقي.",enD:"22 July is the Catholic feast of Mary Magdalene. The calendar fact is verified; its relation to the Erasmus collision is currently weak and remains contextual.",src:["S4"]},
{id:"time",p:"collision",s:"probable",ar:"≈ 11:10",en:"≈ 11:10",nl:"≈ 11:10",es:"≈ 11:10",he:"≈ 11:10",arD:"التوقيت المنشور تقريبي. لا نستخدم 11:10 في حسابات عددية أو رمزية دقيقة قبل تثبيت توقيت أدق من مصدر أولي أو فيديو موثوق.",enD:"Published timing is approximate. 11:10 is not used for precise numerical or symbolic claims until a more exact primary-source or reliable video timestamp is established.",src:["S1"]},
{id:"aljazeera",p:"time",s:"open",ar:"فيديو الجزيرة",en:"Al Jazeera video",nl:"Al Jazeera-video",es:"Video de Al Jazeera",he:"סרטון אל-ג'זירה",arD:"عقدة مفتوحة للعثور على النسخة الأصلية وتوقيت النشر/البث بدقة. لا يُنسب توقيت غير مثبت للقناة.",enD:"Open node for locating the original item and exact publication/broadcast time. No unverified timestamp is attributed to the channel.",src:[]},
{id:"numbers",p:"time",s:"pruned",ar:"مطابقات رقمية غير مثبتة",en:"Unverified numerology",nl:"Onbevestigde numerologie",es:"Numerología no verificada",he:"נומרולוגיה לא מאומתת",arD:"موقوف حالياً: لا تُستخرج دلالات من 22/7 أو 11:10 بعد رؤية النتائج. أي اختبار عددي لاحق يجب تحديد قاعدته مسبقاً.",enD:"Paused: meanings are not mined from 22/7 or 11:10 after seeing outcomes. Any later numerical test must define its rule in advance.",src:[]}
];
const STATUS={verified:{c:"#63ff9b"},probable:{c:"#85ba68"},hypothesis:{c:"#76648f"},open:{c:"#57798a"},pruned:{c:"#5e5a51"}};
const POS={collision:[600,690],bridge:[410,520],stop:[610,525],cause:[790,530],erasmus:[325,365],connection:[510,355],date:[760,375],time:[930,390],will:[180,220],peace:[315,205],university:[455,215],prophecy:[255,90],magdalene:[720,225],aljazeera:[925,235],numbers:[1040,175]};
const CROSS=[["connection","university","hypothesis"],["connection","peace","hypothesis"],["stop","will","hypothesis"],["bridge","university","verified"]];
const EVENTS=[["c. 1466–1536","Desiderius Erasmus","حياة إيراسموس ومشروعه الإنساني المسيحي ونقاشاته حول الإصلاح والسلام والإرادة","Life of Erasmus and his Christian-humanist work on reform, peace and free will"],["1524","De libero arbitrio","نشر إيراسموس بحثه في الإرادة الحرة ودخل في جدله الأشهر مع لوثر","Erasmus publishes his work on free will, entering his famous controversy with Luther"],["1992","Erasmusbrug","اعتماد الاسم الرسمي للجسر خلال تطوير Kop van Zuid","The bridge receives its official name during Kop van Zuid development"],["1996","Opening","افتتاح الجسر الذي أرادته المدينة رمزاً لروتردام غير المنقسمة","Opening of the bridge intended as a symbol of an undivided Rotterdam"],["22 JUL 2026 · ≈11:10","Tram collision","تصادم ترام على الجسر؛ 15 مصاباً في الحصيلة اللاحقة المنشورة؛ السبب يبقى عقدة تحقيق","Tram collision on the bridge; later reported total 15 injured; cause remains an investigation node"],["10 AUG 2026","Living Research 002","فتح شجرة Erasmus v0.1 مع فصل الحقائق عن القراءة الرمزية والأسئلة المفتوحة","Erasmus tree v0.1 opened with facts separated from symbolic readings and open questions"]];
function lang(){return CORE_LANGS.includes(document.documentElement.lang)?document.documentElement.lang:"en"} function tx(k){return (TXT[lang()]||TXT.en)[k]||TXT.en[k]}
function label(n){return n[lang()]||n.en} function desc(n){return n[lang()+"D"]||n.enD}
function localize(){sub.textContent=tx("sub");intro.textContent=tx("intro");lgV.textContent=tx("v");lgP.textContent=tx("p");lgH.textContent=tx("h");lgO.textContent=tx("o");lgX.textContent=tx("x");tabTree.textContent=tx("tree");tabTime.textContent=tx("time");tabReport.textContent=tx("report");tabSources.textContent=tx("sources");allBtn.textContent=tx("all");docBtn.textContent=tx("doc");hypBtn.textContent=tx("hyp");crossNote.textContent=tx("cross");method.textContent=tx("method");renderTree();renderTimeline();renderSources();renderReport()}
let mode="all"; const svg=document.getElementById("livingTree"),drawer=document.getElementById("nodeDrawer");
function path(a,b){let [x1,y1]=POS[a],[x2,y2]=POS[b];return `M${x1},${y1} Q${(x1+x2)/2},${(y1+y2)/2-35} ${x2},${y2}`}
function cart(x,y,w,h){let l=x-w/2,r=x+w/2,t=y-h/2,b=y+h/2;return `M${l+9},${t}H${r-20}Q${r-10},${t}${r-10},${t+9}L${r},${y}L${r-10},${b-9}Q${r-10},${b}${r-20},${b}H${l+20}Q${l+10},${b}${l+10},${b-9}L${l},${y}L${l+10},${t+9}Q${l+10},${t}${l+20},${t}Z`}
function visible(){return N.filter(n=>mode==="doc"?["verified","probable"].includes(n.s):mode==="hyp"?["hypothesis","open","pruned"].includes(n.s)||n.id==="collision":n.s!=="pruned")}
function renderTree(){let v=visible(),ids=new Set(v.map(n=>n.id));svg.innerHTML=`<defs><linearGradient id="trunkG" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#0b2c19"/><stop offset=".65" stop-color="#1edb72"/><stop offset="1" stop-color="#7dffae"/></linearGradient></defs><path d="M600 760 C590 720 606 690 600 650" stroke="url(#trunkG)" stroke-width="18" fill="none" stroke-linecap="round"/><circle cx="600" cy="690" r="34" class="tree-ring"/><circle cx="600" cy="690" r="8" class="tree-heart"/><text x="600" y="744" text-anchor="middle" class="tree-root-label">LIVING RESEARCH 002</text>`;N.filter(n=>n.p&&ids.has(n.id)&&ids.has(n.p)).forEach(n=>{let p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",path(n.p,n.id));p.setAttribute("class",`branch-main ${n.s}`);p.setAttribute("stroke",STATUS[n.s].c);p.setAttribute("stroke-width",n.s==="verified"?5:n.s==="probable"?3.5:2.2);p.setAttribute("opacity",.72);svg.appendChild(p)});CROSS.filter(c=>ids.has(c[0])&&ids.has(c[1])).forEach(c=>{let p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",path(c[0],c[1]));p.setAttribute("class",`branch-cross ${c[2]}`);svg.appendChild(p)});v.forEach(n=>{let [x,y]=POS[n.id],g=document.createElementNS("http://www.w3.org/2000/svg","g"),w=Math.max(92,Math.min(170,label(n).length*8+34));g.setAttribute("class",`leaf ${n.s}`);let p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",cart(x,y,w,32));p.setAttribute("class","cartouche");let t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("x",x);t.setAttribute("y",y+4);t.setAttribute("text-anchor","middle");t.textContent=label(n);g.append(p,t);g.onclick=()=>openNode(n);svg.appendChild(g)})}
function openNode(n){drawer.classList.add("show");drawer.innerHTML=`<div class="eyebrow" style="color:${STATUS[n.s].c}">${n.s.toUpperCase()}</div><h3>${label(n)}</h3><p>${desc(n)}</p><div class="sources-mini">${(n.src||[]).map(id=>{let s=SOURCES.find(x=>x[0]===id);return s?`<a href="${s[3]}" target="_blank" rel="noopener">${s[0]}</a>`:""}).join("")}</div><p><button id="closeNode">${tx("close")}</button></p>`;closeNode.onclick=()=>drawer.classList.remove("show")}
function setMode(m,b){mode=m;document.querySelectorAll(".tree-toolbar button").forEach(x=>x.classList.remove("on"));b.classList.add("on");drawer.classList.remove("show");renderTree()} allBtn.onclick=()=>setMode("all",allBtn);docBtn.onclick=()=>setMode("doc",docBtn);hypBtn.onclick=()=>setMode("hyp",hypBtn);
function renderTimeline(){timeline.innerHTML=EVENTS.map(e=>`<div class="timeline-event"><div class="year">${e[0]}</div><h3>${e[1]}</h3><p>${lang()==="ar"?e[2]:e[3]}</p></div>`).join("")}
function renderSources(){sourcesList.innerHTML=SOURCES.map(s=>`<div class="source-row"><b>${s[0]} · ${s[1]}</b><small>${s[2]}</small><a href="${s[3]}" target="_blank" rel="noopener">${tx("open")} ↗</a></div>`).join("")}
function renderReport(){let ar=lang()==="ar";report.innerHTML=`<div class="source-row"><b>${ar?"الملخص التنفيذي · Erasmus v0.1":"Executive snapshot · Erasmus v0.1"}</b><small>${tx("snapshot")}</small></div>${N.filter(n=>n.s==="verified").map(n=>`<div class="source-row"><b>${label(n)}</b><small>${desc(n)}</small></div>`).join("")}<div class="source-row"><b>${ar?"قراءة قيد الاختبار":"Interpretation under test"}</b><small>${desc(N.find(n=>n.id==="connection"))}</small></div><div class="source-row"><b>${ar?"ما لم يثبت بعد":"Not yet established"}</b><small>${ar?"السبب النهائي للحادث، التوقيت الدقيق بالثواني، النسخة الأصلية من فيديو الجزيرة وتوقيت نشره، وأي ادعاء بأن كتابات إيراسموس تنبأت بهذا الحادث":"Final collision cause, second-level exact timing, the original Al Jazeera item and publication time, and any claim that Erasmus predicted this collision"}</small></div>`}
document.querySelectorAll(".r-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".r-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".r-view").forEach(v=>v.classList.remove("active"));document.getElementById(b.dataset.view).classList.add("active")});document.addEventListener("luxlang",()=>setTimeout(localize,0));nodeStat.textContent=N.length;sourceStat.textContent=SOURCES.length;window.addEventListener("DOMContentLoaded",localize);
