(()=>{"use strict";
const C=document.getElementById('matrix'),x=C.getContext('2d'),signals=document.getElementById('signals'),gate=document.getElementById('gate'),enter=document.getElementById('enter'),sound=document.getElementById('sound'),sub=document.getElementById('sub'),eyebrow=document.getElementById('eyebrow'),micro=document.getElementById('micro'),burst=document.getElementById('burst'),statusA=document.getElementById('statusA'),statusB=document.getElementById('statusB');
const ordinary=[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ','ｱ','ｲ','ｳ','ｴ','ｵ','ｶ','ｷ','ｸ','ｹ','ｺ','+','−','=','∴','∞','Δ','Ω','φ'];
const rare=['LUX','DOT','MEMORY','WITNESS','TRUTH','CARE','PEACE','SIGNAL','نور','ذاكرة','حقيقة','رحمة','إشارة','GEHEUGEN','GETUIGENIS','WAARHEID','ZORG','VREDE','E=mc²','DNA','AI'];
let W,H,dpr,fs,cols=[],last=0,clarity=0,lastPoint={x:innerWidth/2,y:innerHeight/2};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;C.style.width=W+'px';C.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);fs=W<700?13:16;cols=Array.from({length:Math.ceil(W/fs)},(_,i)=>({x:i*fs,y:Math.random()*H,s:.55+Math.random()*1.45,a:.12+Math.random()*.45}))}addEventListener('resize',resize);resize();
function frame(t){if(t-last<42){requestAnimationFrame(frame);return}last=t;x.fillStyle='rgba(0,4,1,.13)';x.fillRect(0,0,W,H);x.font=`${fs}px monospace`;for(const c of cols){const special=Math.random()<.005+clarity*.005,ch=special?rare[(Math.random()*rare.length)|0]:ordinary[(Math.random()*ordinary.length)|0];x.fillStyle=special?`rgba(215,255,226,${.35+c.a})`:`rgba(39,255,104,${c.a})`;x.shadowBlur=special?14:0;x.shadowColor='#4aff89';x.fillText(ch,c.x,c.y);x.shadowBlur=0;c.y+=fs*c.s;if(c.y>H+30&&Math.random()>.91)c.y=-30}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function ghost(){const e=document.createElement('span');e.className='ghost';e.textContent=rare[(Math.random()*rare.length)|0];e.style.left=(5+Math.random()*88)+'%';e.style.top=(7+Math.random()*82)+'%';e.style.fontSize=(8+Math.random()*5)+'px';signals.appendChild(e);setTimeout(()=>e.remove(),6200)}setInterval(ghost,900);for(let i=0;i<7;i++)setTimeout(ghost,i*240);
const L={ar:{dir:'rtl',sub:'نقطة الضوء الأولى · حيث يبدأ الفهم',eye:'تقليل الضجيج · زيادة الإشارة',enter:'ادخل الإشارة',micro:'من الضجيج إلى الذاكرة',a:'الإشارة / كامنة',b:'الضجيج ← الوضوح',acq:'الإشارة / تم التقاطها',mem:'الضجيج ← الذاكرة'},en:{dir:'ltr',sub:'The First Point of Light · Where Understanding Begins',eye:'REDUCING NOISE · INCREASING SIGNAL',enter:'ENTER SIGNAL',micro:'from noise into memory',a:'SIGNAL / LATENT',b:'NOISE → CLARITY',acq:'SIGNAL / ACQUIRED',mem:'NOISE → MEMORY'},nl:{dir:'ltr',sub:'Het eerste lichtpunt · Waar begrip begint',eye:'MINDER RUIS · MEER SIGNAAL',enter:'BETREED HET SIGNAAL',micro:'van ruis naar herinnering',a:'SIGNAAL / LATENT',b:'RUIS → HELDERHEID',acq:'SIGNAAL / GEVONDEN',mem:'RUIS → GEHEUGEN'},id:{dir:'ltr',sub:'Titik cahaya pertama · Tempat pemahaman dimulai',eye:'MENGURANGI BISING · MENINGKATKAN SINYAL',enter:'MASUKI SINYAL',micro:'dari bising menuju memori',a:'SINYAL / LATEN',b:'BISING → JERNIH',acq:'SINYAL / DITEMUKAN',mem:'BISING → MEMORI'}};
let lang=localStorage.getItem('luxdot.lang');if(!L[lang]){const n=(navigator.language||'en').toLowerCase();lang=n.startsWith('ar')?'ar':n.startsWith('nl')?'nl':n.startsWith('id')?'id':'en'}
function setLang(l){if(!L[l])return;lang=l;localStorage.setItem('luxdot.lang',l);document.documentElement.lang=l;document.documentElement.dir=L[l].dir;sub.textContent=L[l].sub;eyebrow.textContent=L[l].eye;enter.textContent=L[l].enter;micro.textContent=L[l].micro;statusA.textContent=L[l].a;statusB.textContent=L[l].b;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('on',b.dataset.lang===l))}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',e=>{rememberPoint(e);startAmbient();setLang(b.dataset.lang)}));setLang(lang);
let audioCtx,master,on=false,nodes=[];
function startAmbient(){if(on)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioCtx=new AC();master=audioCtx.createGain();master.gain.value=.0001;master.connect(audioCtx.destination);const low=audioCtx.createOscillator();low.type='sine';low.frequency.value=43;const lowGain=audioCtx.createGain();lowGain.gain.value=.022;const fifth=audioCtx.createOscillator();fifth.type='sine';fifth.frequency.value=64.5;const fifthGain=audioCtx.createGain();fifthGain.gain.value=.006;const lfo=audioCtx.createOscillator(),lfoGain=audioCtx.createGain();lfo.frequency.value=.11;lfoGain.gain.value=.003;lfo.connect(lfoGain).connect(lowGain.gain);low.connect(lowGain).connect(master);fifth.connect(fifthGain).connect(master);low.start();fifth.start();lfo.start();master.gain.exponentialRampToValueAtTime(.7,audioCtx.currentTime+.9);nodes=[low,fifth,lfo];on=true;sound.classList.add('on')}
function stopAmbient(){if(!on)return;master.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.28);setTimeout(()=>{nodes.forEach(n=>{try{n.stop()}catch{}});audioCtx.close();on=false;nodes=[];sound.classList.remove('on')},320)}
function toggleSound(){on?stopAmbient():startAmbient()}sound.addEventListener('click',e=>{e.stopPropagation();rememberPoint(e);toggleSound()});
function rememberPoint(e){if(e&&Number.isFinite(e.clientX)){lastPoint={x:e.clientX,y:e.clientY}}}
document.addEventListener('pointerdown',e=>{rememberPoint(e);if(!on&&e.target!==sound)startAmbient()},{once:true});
function cross(e){rememberPoint(e);startAmbient();clarity=1;statusA.textContent=L[lang].acq;statusB.textContent=L[lang].mem;const px=(lastPoint.x/innerWidth*100).toFixed(2),py=(lastPoint.y/innerHeight*100).toFixed(2);sessionStorage.setItem('luxdot.entry.point',JSON.stringify({x:px,y:py}));burst.style.setProperty('--bx',lastPoint.x+'px');burst.style.setProperty('--by',lastPoint.y+'px');burst.classList.remove('go');void burst.offsetWidth;burst.classList.add('go');gate.classList.add('leave');setTimeout(()=>location.href='home.html',820)}
enter.addEventListener('click',cross);
})();