(()=>{"use strict";
const C=document.getElementById('matrix'),x=C.getContext('2d'),signals=document.getElementById('signals'),enter=document.getElementById('enter'),sound=document.getElementById('sound'),sub=document.getElementById('sub'),eyebrow=document.getElementById('eyebrow'),micro=document.getElementById('micro'),burst=document.getElementById('burst'),statusA=document.getElementById('statusA'),statusB=document.getElementById('statusB');
const ordinary=[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ','ｱ','ｲ','ｳ','ｴ','ｵ','ｶ','ｷ','ｸ','ｹ','ｺ','+','−','=','∴','∞','Δ','Ω','φ'];
const WORDS=[
'LIGHT','MEMORY','CARE','TRUTH','SIGNAL','NOISE','CLARITY','UNDERSTANDING','AWARENESS','CODE','CIPHER','DECODE','FILTER','LISTEN','WITNESS','DIGNITY','MERCY','PEACE','JUSTICE','BRIDGE','HUMANITY','SERVICE','KNOWLEDGE','MEANING','ATTENTION','PERCEPTION','PATTERN','SOURCE','CONTEXT','VERIFY',
'نور','ذاكرة','رعاية','حقيقة','إشارة','ضجيج','وضوح','فهم','إدراك','ترميز','تشفير','فك','إنصات','شهادة','كرامة','رحمة','سلام','عدل','جسر','إنسانية','خدمة','معرفة','معنى',
'LICHT','GEHEUGEN','ZORG','WAARHEID','SIGNAAL','RUIS','HELDERHEID','BEGRIP','AANDACHT','WAARNEMING','CODE','ONTcijfer','GETUIGENIS','WAARDIGHEID','VREDE','RECHT',
'CAHYA','PANGELING','KAWELASAN','KABENERAN','TANDHA','SWARA','CETHA','PANGERTEN','KAWERUH','RUKUN','LAYANAN','MANUNGSA',
'אור','זיכרון','דאגה','אמת','אות','רעש','בהירות','הבנה','מודעות','קוד','פענוח','עדות','כבוד','חמלה','שלום','צדק','אנושות','שירות','ידע'
];
const L={ar:{dir:'rtl',sub:'نقطة الضوء الأولى · حيث يبدأ الفهم',eye:'تقليل الضجيج · زيادة الإشارة',enter:'استقبل الإشارة',micro:'من الضجيج إلى الذاكرة',a:'الإشارة / كامنة',b:'الضجيج ← الوضوح',acq:'الإشارة / تم التقاطها',mem:'الضجيج ← الذاكرة'},en:{dir:'ltr',sub:'The First LuxDot · Where Understanding Begins',eye:'REDUCING NOISE · INCREASING SIGNAL',enter:'RECEIVE THE SIGNAL',micro:'FROM NOISE INTO MEMORY',a:'SIGNAL / LATENT',b:'NOISE → CLARITY',acq:'SIGNAL / ACQUIRED',mem:'NOISE → MEMORY'},nl:{dir:'ltr',sub:'Het eerste lichtpunt · Waar begrip begint',eye:'MINDER RUIS · MEER SIGNAAL',enter:'ONTVANG HET SIGNAAL',micro:'VAN RUIS NAAR HERINNERING',a:'SIGNAAL / LATENT',b:'RUIS → HELDERHEID',acq:'SIGNAAL / GEVONDEN',mem:'RUIS → GEHEUGEN'},jv:{dir:'ltr',sub:'Titik cahya kapisan · Papan pangerten diwiwiti',eye:'NYUDA SWARA · NGUWATAKE TANDHA',enter:'TAMPA TANDHA',micro:'SAKA SWARA TUMUJU PANGELING',a:'TANDHA / MENENG',b:'SWARA → CETHA',acq:'TANDHA / KATAMPA',mem:'SWARA → PANGELING'},he:{dir:'rtl',sub:'נקודת האור הראשונה · המקום שבו ההבנה מתחילה',eye:'מפחיתים רעש · מגבירים אות',enter:'קבל את האות',micro:'מרעש אל זיכרון',a:'אות / חבוי',b:'רעש ← בהירות',acq:'אות / נקלט',mem:'רעש ← זיכרון'}};
let lang='ar',W,H,dpr,fs,cols=[],last=0,clarity=0,lastPoint={x:innerWidth/2,y:innerHeight/2};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;C.style.width=W+'px';C.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);fs=W<700?13:16;cols=Array.from({length:Math.ceil(W/fs)},(_,i)=>({x:i*fs,y:Math.random()*H,s:.55+Math.random()*1.35,a:.11+Math.random()*.38}))}addEventListener('resize',resize);resize();
function frame(t){if(t-last<44){requestAnimationFrame(frame);return}last=t;x.fillStyle='rgba(0,4,1,.15)';x.fillRect(0,0,W,H);x.font=`${fs}px monospace`;for(const c of cols){const special=Math.random()<.0028,ch=special?WORDS[(Math.random()*WORDS.length)|0]:ordinary[(Math.random()*ordinary.length)|0];x.fillStyle=special?`rgba(215,255,226,${.35+c.a})`:`rgba(39,255,104,${c.a})`;x.shadowBlur=special?14:0;x.shadowColor='#4aff89';x.fillText(ch,c.x,c.y);x.shadowBlur=0;c.y+=fs*c.s;if(c.y>H+30&&Math.random()>.91)c.y=-30}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function ghost(){const e=document.createElement('span');e.className='ghost';e.textContent=WORDS[(Math.random()*WORDS.length)|0];e.style.left=(4+Math.random()*89)+'%';e.style.top=(7+Math.random()*82)+'%';e.style.fontSize=(10+Math.random()*5)+'px';signals.appendChild(e);setTimeout(()=>e.remove(),2400)}setInterval(ghost,1150);for(let i=0;i<5;i++)setTimeout(ghost,i*320);
function persistLang(l){try{localStorage.setItem('luxdot.lang',l);localStorage.setItem('luxdot.lang.explicit','1')}catch{}}
function setLang(l,selected=false){if(!L[l])return;lang=l;if(selected)persistLang(l);document.documentElement.lang=l;document.documentElement.dir=L[l].dir;sub.textContent=L[l].sub;eyebrow.textContent=L[l].eye;enter.textContent=L[l].enter;micro.textContent=L[l].micro;statusA.textContent=L[l].a;statusB.textContent=L[l].b;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('on',b.dataset.lang===l))}
setLang('ar',false);
let audioCtx,master,on=false,nodes=[],morseTimer;
function beep(start,dur,f=730,g=.024){const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type='sine';o.frequency.value=f;v.gain.setValueAtTime(.0001,start);v.gain.exponentialRampToValueAtTime(g,start+.008);v.gain.setValueAtTime(g,start+dur-.01);v.gain.exponentialRampToValueAtTime(.0001,start+dur);o.connect(v).connect(master);o.start(start);o.stop(start+dur+.02)}
function playSOS(){if(!on||!audioCtx)return;const unit=.085,seq=['.','.','.','-','-','-','.','.','.'];let t=audioCtx.currentTime+.15;seq.forEach((s,i)=>{const d=s==='.'?unit:unit*3;beep(t,d);t+=d+unit;if(i===2||i===5)t+=unit*2});}
function scheduleSOS(){clearInterval(morseTimer);playSOS();morseTimer=setInterval(playSOS,12000)}
function startAmbient(){if(on)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioCtx=new AC();master=audioCtx.createGain();master.gain.value=.0001;master.connect(audioCtx.destination);const low=audioCtx.createOscillator(),lg=audioCtx.createGain(),fifth=audioCtx.createOscillator(),fg=audioCtx.createGain();low.type='sine';low.frequency.value=43;lg.gain.value=.018;fifth.type='sine';fifth.frequency.value=64.5;fg.gain.value=.004;low.connect(lg).connect(master);fifth.connect(fg).connect(master);low.start();fifth.start();master.gain.exponentialRampToValueAtTime(.65,audioCtx.currentTime+.7);nodes=[low,fifth];on=true;sound.classList.add('on');scheduleSOS()}
function stopAmbient(){if(!on)return;clearInterval(morseTimer);master.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.2);setTimeout(()=>{nodes.forEach(n=>{try{n.stop()}catch{}});audioCtx.close();on=false;nodes=[];sound.classList.remove('on')},240)}
sound.addEventListener('click',e=>{e.stopPropagation();rememberPoint(e);on?stopAmbient():startAmbient()});function rememberPoint(e){if(e&&Number.isFinite(e.clientX))lastPoint={x:e.clientX,y:e.clientY}}document.addEventListener('pointerdown',e=>{rememberPoint(e);if(!on&&e.target!==sound)startAmbient()},{once:true});
function cross(e){rememberPoint(e);persistLang(lang);startAmbient();clarity=1;statusA.textContent=L[lang].acq;statusB.textContent=L[lang].mem;const px=(lastPoint.x/innerWidth*100).toFixed(2),py=(lastPoint.y/innerHeight*100).toFixed(2);try{sessionStorage.setItem('luxdot.entry.point',JSON.stringify({x:px,y:py}))}catch{}burst.style.setProperty('--bx',lastPoint.x+'px');burst.style.setProperty('--by',lastPoint.y+'px');burst.classList.remove('go');void burst.offsetWidth;burst.classList.add('go');document.documentElement.style.setProperty('--crt-x',lastPoint.x+'px');document.documentElement.style.setProperty('--crt-y',lastPoint.y+'px');document.body.classList.add('crt-out');setTimeout(()=>location.href='home.html',760)}enter.addEventListener('click',cross);
})();