(()=>{'use strict';
const SUP=['ar','en','nl','jv','he'];
const DIR={ar:'rtl',en:'ltr',nl:'ltr',jv:'ltr',he:'rtl'};
const NAME={ar:'العربية',en:'English',nl:'Nederlands',jv:'Basa Jawa',he:'עברית'};
const BRAND={ar:'نقطة نور',en:'LuxDot',nl:'LuxDot',jv:'LuxDot',he:'LuxDot'};
const NAV={ar:{home:'الرئيسية',library:'المكتبة',faith:'الإيمان والحكمة',nusantara:'نوسانتارا',memory:'الذاكرة',research:'الأبحاث',projects:'المشاريع'},en:{home:'Home',library:'Library',faith:'Faith & Wisdom',nusantara:'Nusantara',memory:'Memory',research:'Research',projects:'Projects'},nl:{home:'Home',library:'Bibliotheek',faith:'Geloof & wijsheid',nusantara:'Nusantara',memory:'Geheugen',research:'Onderzoek',projects:'Projecten'},jv:{home:'Ngarep',library:'Pustaka',faith:'Iman lan kawicaksanan',nusantara:'Nusantara',memory:'Pangeling',research:'Panliten',projects:'Proyek'},he:{home:'ראשי',library:'ספרייה',faith:'אמונה וחכמה',nusantara:'נוסנטרה',memory:'זיכרון',research:'מחקר',projects:'פרויקטים'}};
function saved(){const s=localStorage.getItem('luxdot.lang');return SUP.includes(s)?s:null}
function query(){const q=new URLSearchParams(location.search).get('lang');return SUP.includes(q)?q:null}
function current(){return SUP.includes(window.__LUX_LANG)?window.__LUX_LANG:(query()||saved()||'en')}
function setDoc(l){document.documentElement.lang=l;document.documentElement.dir=DIR[l];document.documentElement.dataset.luxLang=l;if(document.body){document.body.dataset.lang=l;document.body.classList.toggle('rtl-core',DIR[l]==='rtl')}}
function set(l,mark=true){if(!SUP.includes(l))l='en';window.__LUX_LANG=l;if(mark)localStorage.setItem('luxdot.lang',l);setDoc(l);document.dispatchEvent(new CustomEvent('luxlang',{detail:{lang:l}}));window.dispatchEvent(new CustomEvent('luxdot-language',{detail:{lang:l}}))}
function navigate(l){if(!SUP.includes(l))l='en';localStorage.setItem('luxdot.lang',l);const u=new URL(location.href);u.searchParams.set('lang',l);location.assign(u.pathname+u.search+u.hash)}
function bootstrap(){const l=query()||saved()||'en';window.__LUX_LANG=l;localStorage.setItem('luxdot.lang',l);setDoc(l)}
function selectors(){const l=current();document.querySelectorAll('[data-lang-select],select.lang-select,select.lang').forEach(s=>{if(s.tagName!=='SELECT')return;s.innerHTML=SUP.map(x=>`<option value="${x}">${NAME[x]}</option>`).join('');s.value=l;if(!s.dataset.coreLangBound){s.dataset.coreLangBound='1';s.addEventListener('change',e=>{e.stopImmediatePropagation();navigate(e.target.value)})}})}
function common(){const l=current(),n=NAV[l];document.querySelectorAll('[data-lux-brand],header .logo,.top .logo').forEach(e=>e.textContent=BRAND[l]);document.querySelectorAll('header a[href],header nav a[href]').forEach(a=>{const f=(a.getAttribute('href')||'').split('/').pop().split('?')[0].split('#')[0],k={'home.html':'home','library.html':'library','faith.html':'faith','nusantara.html':'nusantara','memory.html':'memory','research.html':'research','projects.html':'projects'}[f];if(k&&!a.hasAttribute('data-preserve-label'))a.textContent=n[k]})}
function locales(){const l=current(),bs=[...document.querySelectorAll('[data-locale]')];if(!bs.length)return;bs.forEach(b=>b.hidden=true);let b=bs.find(x=>x.dataset.locale===l);if(!b&&l==='jv')b=bs.find(x=>x.dataset.locale==='jv')||bs.find(x=>x.dataset.locale==='id');if(!b)b=bs.find(x=>x.dataset.locale==='en');if(b)b.hidden=false}
function init(){setDoc(current());selectors();common();locales();document.body?.classList.add('lux-lang-ready')}
bootstrap();window.LuxLang={get:current,set,navigate,names:NAME,dir:DIR,nav:NAV};document.addEventListener('DOMContentLoaded',init);document.addEventListener('luxlang',()=>setTimeout(init,0));})();
