(()=>{
 const commonsFile=(name)=>'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(name).replace(/%2F/g,'/');
 const commonsPage=(name)=>'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(name).replace(/%20/g,'_');
 const TRACKS={
  min1:{title:'سورة الفاتحة · Al-Fātiḥa',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:51.958,url:commonsFile('Sura Minshawi 1.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 1.ogg')},
  min2:{title:'سورة البقرة · Al-Baqarah',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:8217,url:commonsFile('Sura Minshawi 2.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 2.ogg')},
  min4:{title:'سورة النساء · An-Nisāʾ',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:5170,url:commonsFile('Sura Minshawi 4.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 4.ogg')},
  min5:{title:'سورة المائدة · Al-Māʾidah',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:4036,url:commonsFile('Sura Minshawi 5.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 5.ogg')},
  min12:{title:'سورة يوسف · Yūsuf',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:2701,url:commonsFile('Sura Minshawi 12.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 12.ogg')},
  min14:{title:'سورة إبراهيم · Ibrāhīm',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:1118,url:commonsFile('Sura Minshawi 14.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 14.ogg')},
  min20:{title:'سورة طه · Ṭā-Hā',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:1627,url:commonsFile('Sura Minshawi 20.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 20.ogg')},
  min25:{title:'سورة الفرقان · Al-Furqān',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:1082,url:commonsFile('Sura Minshawi 25.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 25.ogg')},
  min26:{title:'سورة الشعراء · Ash-Shuʿarāʾ',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:1617,url:commonsFile('Sura Minshawi 26.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 26.ogg')},
  min27:{title:'سورة النمل · An-Naml',artist:'محمد صديق المنشاوي',culture:'Qur’an · تلاوة مقدسة',kind:'sacred',duration:1468,url:commonsFile('Sura Minshawi 27.ogg'),license:'Public domain · Egypt',source:commonsPage('Sura Minshawi 27.ogg')},
  syriac:{title:'Abun d-bashmayo · الصلاة الربانية',artist:'Western Syriac rite',culture:'Syriac / Aramaic Christian',kind:'sacred',duration:80.171,url:commonsFile('Abunbshmayo.ogg'),license:'CC0 1.0',source:commonsPage('Abunbshmayo.ogg')},
  gregorian:{title:'Veni Sancte Spiritus · Gregorian chant',artist:'Membeth',culture:'Latin Christian',kind:'sacred',duration:157,url:commonsFile('Veni.sancte.spiritus.ogg'),license:'Public domain',source:commonsPage('Veni.sancte.spiritus.ogg')},
  jewish:{title:'Broisch haschoni · Cantorial heritage',artist:'Gershon Sirota',culture:'Jewish / Ashkenazi',kind:'sacred',duration:164.493,url:commonsFile('Broisch haschoni (1908).ogg'),license:'Public domain',source:commonsPage('Broisch haschoni (1908).ogg')},
  qawwali:{title:'Sohini Qawwali',artist:'Imdad Khan',culture:'South Asia / Sufi tradition',kind:'spiritual',duration:185,url:commonsFile('Sohini Qawwali.ogg'),license:'Public domain',source:commonsPage('Sohini Qawwali.ogg')},
  gamelan:{title:'Gamelan Anklung Berong Pengetjet',artist:'Traditional ensemble',culture:'Bali / Nusantara',kind:'harmony',duration:177,url:commonsFile('Gamelan Anklung Berong Pengetjet (1931).ogg'),license:'Public domain',source:commonsPage('Gamelan Anklung Berong Pengetjet (1931).ogg')},
  persia:{title:'Baiaty · Chiraz · Rast',artist:'Traditional Persian music',culture:'Persia / Iran',kind:'harmony',duration:183,url:commonsFile('Baiaty Chiraz Rast .ogg'),license:'Public domain',source:commonsPage('Baiaty Chiraz Rast .ogg')},
  china:{title:'Yu Wang Tan Ming',artist:'Jianhong He',culture:'China',kind:'harmony',duration:179,url:commonsFile('Yu Wang Tan Ming (c. 1920).ogg'),license:'Public domain',source:commonsPage('Yu Wang Tan Ming (c. 1920).ogg')},
  japan:{title:'Koromogo-e',artist:'Kunai-sho gakubu',culture:'Japan',kind:'harmony',duration:159,url:commonsFile('Koromogo-e (c. 1930).ogg'),license:'Public domain',source:commonsPage('Koromogo-e (c. 1930).ogg')},
  africa:{title:'Music for the Lela Celebration',artist:'Traditional',culture:'Africa / Cameroon',kind:'heritage',duration:134,url:commonsFile('Music for the Lela Celebration.ogg'),license:'Public domain',source:commonsPage('Music for the Lela Celebration.ogg')},
  bach:{title:'Air · BWV 1068',artist:'J. S. Bach',culture:'Europe',kind:'harmony',duration:259.9,url:commonsFile('Air (Bach).ogg'),license:'Public domain',source:commonsPage('Air (Bach).ogg')},
  mozart:{title:'Eine kleine Nachtmusik · Allegro',artist:'W. A. Mozart',culture:'Europe',kind:'classical',duration:355,url:commonsFile('Mozart - Eine kleine Nachtmusik - 1. Allegro.ogg'),license:'Commons licensed',source:commonsPage('Mozart - Eine kleine Nachtmusik - 1. Allegro.ogg')},
  oud:{title:'Arabic Oud · عود عربي',artist:'Houssem Bettaibi',culture:'Arab world',kind:'harmony',duration:49.64,url:commonsFile('OUD.ogg'),license:'CC BY-SA 3.0',source:commonsPage('OUD.ogg')}
 };
 const QURAN=['min2','min12','min20','min4','min14','min5','min26','min27','min25'];
 const SPIRITUAL_LIBRARY=['syriac','gregorian','jewish','qawwali','oud','persia','gamelan','china','japan','africa','bach','mozart'];
 const audio=new Audio(); audio.preload='auto'; let currentId=''; let wantedOffset=0; let userOn=localStorage.getItem('luxdot.radio.on')==='1'; let loadToken=0; let status='جاهز · Ready';
 function chaamParts(date=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Amsterdam',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(date);return Object.fromEntries(parts.map(p=>[p.type,p.value]));}
 function secondsOfDay(){const p=chaamParts();return (+p.hour)*3600+(+p.minute)*60+(+p.second)}
 function quranLive(){const list=QURAN.map(id=>({id,...TRACKS[id]}));const total=list.reduce((a,t)=>a+t.duration,0);let x=secondsOfDay()%total,chosen=list[0];for(const t of list){if(x<t.duration){chosen=t;break}x-=t.duration}return{program:{name:'Qur’an Live from Chaam · قرآن من شام',mode:'quran'},track:chosen,offset:x,list};}
 function live(){return quranLive()}
 function next24(){const now=new Date(),rows=[];for(let i=0;i<24;i++){const d=new Date(now.getTime()+i*3600000),p=chaamParts(d);const s=(+p.hour)*3600;const list=QURAN.map(id=>({id,...TRACKS[id]})),total=list.reduce((a,t)=>a+t.duration,0);let x=s%total,t=list[0];for(const a of list){if(x<a.duration){t=a;break}x-=a.duration}rows.push({time:`${p.hour}:00`,day:p.weekday,track:t})}return rows}
 function ensureDock(){if(document.getElementById('luxdot-radio-dock'))return;const d=document.createElement('div');d.id='luxdot-radio-dock';d.innerHTML='<div class="lrd-main"><button id="luxdot-radio-play" aria-label="Play LuxDot Radio">▶</button><div><div class="lrd-title"><span class="lrd-pulse"></span>LuxDot Radio</div><div class="lrd-track" id="luxdot-radio-track">قرآن مباشر من شام</div></div><span class="lrd-live">LIVE</span></div><div class="lrd-sub"><span id="luxdot-radio-day">Chaam · شام · 24/7</span><a href="radio.html">OPEN ↗</a></div>';document.body.appendChild(d);document.getElementById('luxdot-radio-play').onclick=toggle;}
 function setStatus(v){status=v;document.dispatchEvent(new CustomEvent('luxdotradio-status',{detail:v}))}
 function loadTrack(s,autoplay){const token=++loadToken;currentId=s.track.id;wantedOffset=Math.max(0,Math.min(s.offset,s.track.duration-1));setStatus('تحميل التلاوة… · Loading…');audio.pause();audio.removeAttribute('src');audio.load();audio.src=s.track.url;audio.load();const ready=()=>{if(token!==loadToken)return;try{if(Number.isFinite(audio.duration)&&wantedOffset<audio.duration)audio.currentTime=wantedOffset}catch(e){} if(autoplay){audio.play().then(()=>setStatus('يبث الآن من شام · LIVE from Chaam')).catch(e=>setStatus('اضغط تشغيل للسماح بالصوت · Tap play to allow audio'))}else setStatus('جاهز · Ready')};audio.addEventListener('loadedmetadata',ready,{once:true});audio.addEventListener('canplay',()=>{if(token===loadToken&&autoplay&&audio.paused)audio.play().catch(()=>{})},{once:true});}
 function sync(force=false){const s=live();ensureDock();const tr=document.getElementById('luxdot-radio-track');if(tr)tr.textContent=s.track.title+' · '+s.track.artist;const day=document.getElementById('luxdot-radio-day');if(day)day.textContent='Chaam · شام · قرآن 24/7';if(force||currentId!==s.track.id)loadTrack(s,userOn);else if(userOn&&!audio.paused&&Math.abs((audio.currentTime||0)-s.offset)>20){try{audio.currentTime=s.offset}catch(e){}}updateBtn();document.dispatchEvent(new CustomEvent('luxdotradio',{detail:s}));}
 function updateBtn(){const b=document.getElementById('luxdot-radio-play');if(b)b.textContent=userOn&&!audio.paused?'❚❚':'▶'}
 function toggle(){ensureDock();if(!userOn||audio.paused){userOn=true;localStorage.setItem('luxdot.radio.on','1');const s=live();if(currentId!==s.track.id||!audio.src)loadTrack(s,true);else audio.play().then(()=>setStatus('يبث الآن من شام · LIVE from Chaam')).catch(()=>setStatus('تعذر التشغيل؛ جرّب فتح صفحة الراديو · Playback blocked'));}else{userOn=false;localStorage.setItem('luxdot.radio.on','0');audio.pause();setStatus('متوقف مؤقتاً · Paused')}updateBtn()}
 audio.addEventListener('ended',()=>sync(true));audio.addEventListener('play',updateBtn);audio.addEventListener('pause',updateBtn);audio.addEventListener('error',()=>{const code=audio.error?audio.error.code:'?';setStatus('تعذر تحميل المصدر الصوتي ('+code+') · جرّب إعادة التشغيل'); if(userOn)setTimeout(()=>sync(true),2500)});
 window.LuxDotRadio={TRACKS,QURAN,SPIRITUAL_LIBRARY,live,next24,audio,toggle,sync,getStatus:()=>status};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureDock();sync(false);setInterval(()=>sync(false),15000)});else{ensureDock();sync(false);setInterval(()=>sync(false),15000)}
})();
