(()=>{
 const W='https://commons.wikimedia.org/wiki/Special:Redirect/file/';
 const TRACKS={
  fatiha:{title:'Al-Fātiḥa · CC0 recitation',artist:'kuran*sunnet*islam*',culture:'Qur’an',duration:48.432,url:W+'001Fatiha.ogg',license:'CC0 1.0',source:'https://commons.wikimedia.org/wiki/File:001Fatiha.ogg'},
  syriac:{title:'Abun d-bashmayo · Lord’s Prayer',artist:'Western Syriac rite',culture:'Syriac / Aramaic Christian',duration:80.171,url:W+'Abunbshmayo.ogg',license:'CC0 1.0',source:'https://commons.wikimedia.org/wiki/File:Abunbshmayo.ogg'},
  gregorian:{title:'Veni Sancte Spiritus · Gregorian chant',artist:'Membeth',culture:'Latin Christian',duration:157,url:W+'Veni.sancte.spiritus.ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Veni.sancte.spiritus.ogg'},
  jewish:{title:'Broisch haschoni · 1908 cantorial recording',artist:'Gershon Sirota',culture:'Jewish / Ashkenazi',duration:164.493,url:W+'Broisch_haschoni_(1908).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Broisch_haschoni_(1908).ogg'},
  qawwali:{title:'Sohini Qawwali · historical recording',artist:'Imdad Khan',culture:'South Asia / Sufi tradition',duration:185,url:W+'Sohini_Qawwali.ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Sohini_Qawwali.ogg'},
  india:{title:'Jevi Karay Je Karni · c. 1928',artist:'Master Laloo',culture:'India',duration:198,url:W+'Jevi_Karay_Je_Karni,_Tevi_Tarat_Faday_Chhe_(c._1928).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Jevi_Karay_Je_Karni,_Tevi_Tarat_Faday_Chhe_(c._1928).ogg'},
  gamelan:{title:'Gamelan Anklung Berong Pengetjet · 1931',artist:'Traditional ensemble',culture:'Bali / Nusantara',duration:177,url:W+'Gamelan_Anklung_Berong_Pengetjet_(1931).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Gamelan_Anklung_Berong_Pengetjet_(1931).ogg'},
  persia:{title:'Baiaty · Chiraz · Rast',artist:'Traditional Persian music · pre-1910 recording',culture:'Persia / Iran',duration:183,url:W+'Baiaty_Chiraz_Rast_.ogg',license:'Public Domain Mark 1.0',source:'https://commons.wikimedia.org/wiki/File:Baiaty_Chiraz_Rast_.ogg'},
  china:{title:'Yu Wang Tan Ming · c. 1920',artist:'Jianhong He',culture:'China',duration:179,url:W+'Yu_Wang_Tan_Ming_(c._1920).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Yu_Wang_Tan_Ming_(c._1920).ogg'},
  japan:{title:'Koromogo-e · c. 1930',artist:'Kunai-sho gakubu',culture:'Japan',duration:159,url:W+'Koromogo-e_(c._1930).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Koromogo-e_(c._1930).ogg'},
  africa:{title:'Music for the Lela Celebration · 1908',artist:'Traditional · Bali, Cameroon',culture:'Africa / Cameroon',duration:134,url:W+'Music_for_the_Lela_Celebration.ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Music_for_the_Lela_Celebration.ogg'},
  andalusia:{title:'Himno de Andalucía · instrumental',artist:'Traditional Andalusian identity',culture:'Andalusia',duration:145,url:W+'Himno_de_Andalucía.ogg',license:'CC0 1.0',source:'https://commons.wikimedia.org/wiki/File:Himno_de_Andalucía.ogg'},
  bach:{title:'Air on the G String · BWV 1068',artist:'J. S. Bach · historical recording',culture:'Europe',duration:259.9,url:W+'Air_(Bach).ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Air_(Bach).ogg'},
  mozart:{title:'Eine kleine Nachtmusik · Allegro',artist:'Mozart · Advent Chamber Orchestra',culture:'Europe',duration:355,url:W+'Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg',license:'Commons licensed',source:'https://commons.wikimedia.org/wiki/File:Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg'},
  beethoven1:{title:'Symphony No. 5 · I. Allegro con brio',artist:'Beethoven · Skidmore College Orchestra',culture:'Europe',duration:425,url:W+'Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_i._allegro_con_brio.ogg',license:'Public domain recording',source:'https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_i._allegro_con_brio.ogg'},
  beethoven2:{title:'Symphony No. 5 · II. Andante con moto',artist:'Beethoven · Skidmore College Orchestra',culture:'Europe',duration:599,url:W+'Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_ii._andante_con_moto.ogg',license:'Public domain recording',source:'https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_ii._andante_con_moto.ogg'},
  oud:{title:'Arabic Oud · instrumental excerpt',artist:'Houssem Bettaibi',culture:'Arab world',duration:49.64,url:W+'OUD.ogg',license:'CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:OUD.ogg'},
  auld:{title:'Auld Lang Syne · historical recording',artist:'Traditional',culture:'Scotland / world',duration:180,url:W+'Auld_Lang_Syne.ogg',license:'Public domain',source:'https://commons.wikimedia.org/wiki/File:Auld_Lang_Syne.ogg'}
 };
 const DAY=[
  {name:'Bridges · جسور',ids:['fatiha','syriac','jewish','oud','gamelan','bach','africa','china','beethoven2']},
  {name:'Contemplation · تأمل',ids:['fatiha','gregorian','persia','japan','bach','syriac','beethoven2']},
  {name:'East & West · شرق وغرب',ids:['oud','india','mozart','jewish','china','beethoven1','persia','auld']},
  {name:'Symphonies & Civilisations · سمفونيات وحضارات',ids:['beethoven1','gamelan','mozart','africa','bach','india','beethoven2']},
  {name:'Sacred Voices · أصوات روحية',ids:['fatiha','syriac','jewish','gregorian','qawwali','persia','bach']},
  {name:'Common Ground · أرض مشتركة',ids:['andalusia','oud','gamelan','china','japan','africa','mozart','qawwali','beethoven2']},
  {name:'Peace · سلام',ids:['fatiha','syriac','bach','india','jewish','oud','china','japan','beethoven2','auld']}
 ];
 const FEATURED=[{id:'omar-khairat',name:'Omar Khairat · عمر خيرت',culture:'Egypt / Arab world',kind:'Contemporary featured artist',rights:'Official-source playback only — not copied or rebroadcast by LuxDot without a licence.',official:'https://www.omarkhairat.com/ar',videos:['https://www.youtube.com/embed/AzpG1B9Nqc0','https://www.youtube.com/embed/QyjKFR1VeAY']}];
 function amsterdamParts(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Amsterdam',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());return Object.fromEntries(parts.map(p=>[p.type,p.value]));}
 function dayIndex(w){return ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(w)}
 function live(){const p=amsterdamParts(),di=Math.max(0,dayIndex(p.weekday)),prog=DAY[di],list=prog.ids.map(id=>({id,...TRACKS[id]})),sec=(+p.hour)*3600+(+p.minute)*60+(+p.second),total=list.reduce((a,t)=>a+t.duration,0),x=sec%total,chosen=list[0];for(const t of list){if(x<t.duration){chosen=t;break}x-=t.duration}return{program:prog,track:chosen,offset:x,list};}
 const audio=new Audio();audio.preload='metadata';audio.crossOrigin='anonymous';let currentId='';let userOn=localStorage.getItem('luxdot.radio.on')==='1';
 function ensureDock(){if(document.getElementById('luxdot-radio-dock'))return;const d=document.createElement('div');d.id='luxdot-radio-dock';d.innerHTML='<div class="lrd-main"><button id="luxdot-radio-play" aria-label="Play LuxDot Radio">▶</button><div><div class="lrd-title"><span class="lrd-pulse"></span>LuxDot Radio</div><div class="lrd-track" id="luxdot-radio-track">Loading live schedule…</div></div><span class="lrd-live">LIVE</span></div><div class="lrd-sub"><span id="luxdot-radio-day">Amsterdam 24/7</span><a href="radio.html">OPEN ↗</a></div>';document.body.appendChild(d);document.getElementById('luxdot-radio-play').onclick=toggle;}
 function sync(force=false){const s=live();ensureDock();document.getElementById('luxdot-radio-track').textContent=s.track.title;document.getElementById('luxdot-radio-day').textContent=s.program.name;if(force||currentId!==s.track.id){currentId=s.track.id;audio.src=s.track.url;audio.currentTime=Math.max(0,s.offset);if(userOn)audio.play().catch(()=>{userOn=false;updateBtn()})}else if(Math.abs((audio.currentTime||0)-s.offset)>12&&userOn){audio.currentTime=s.offset}updateBtn();document.dispatchEvent(new CustomEvent('luxdotradio',{detail:s}));}
 function updateBtn(){const b=document.getElementById('luxdot-radio-play');if(b)b.textContent=userOn&&!audio.paused?'❚❚':'▶'}
 function toggle(){if(!userOn||audio.paused){userOn=true;localStorage.setItem('luxdot.radio.on','1');sync(true);audio.play().then(updateBtn).catch(updateBtn)}else{userOn=false;localStorage.setItem('luxdot.radio.on','0');audio.pause();updateBtn()}}
 audio.addEventListener('ended',()=>sync(true));audio.addEventListener('play',updateBtn);audio.addEventListener('pause',updateBtn);
 window.LuxDotRadio={TRACKS,DAY,FEATURED,live,audio,toggle,sync};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureDock();sync(true);setInterval(()=>sync(false),10000)});else{ensureDock();sync(true);setInterval(()=>sync(false),10000)}
})();
