(()=>{'use strict';
const $=s=>document.querySelector(s);
const SUP=['ar','en','nl','he','jv','id','fr','es','de','tr'];
const I={
 ar:{radar:'المرصد الحي',radarTitle:'تقاليد المخلّص الآن',radarNote:'اضغط أي تقليد لتصفية المواد. الشرائط تقيس كثافة التداول الحديث الذي وجدناه، لا صحة الادعاء.',home:'الرئيسية',research:'الأبحاث',media:'ميديا / أخبار',title:'ميديا وأخبار',lead:'طبقة متابعة موثّقة للفيديوهات والمنشورات والتغطيات المعاصرة المرتبطة بأبحاث لوكسدوت.',kicker:'الفئة',cat:'المخلّص · التداول الحالي',catlead:'ما يُتداول الآن حول المشيح والمهدي وعودة المسيح وكالكي وبقية تقاليد المخلّص. الإدراج هنا يوثّق التداول ولا يعني أن لوكسدوت يقرّ بتحقق النبوءة.',atlas:'افتح أطلس المخلّص ↗',allBeliefs:'كل المعتقدات',allTypes:'كل أنواع الميديا',allStatus:'كل الحالات',search:'ابحث بالاسم أو الادعاء…',source:'المصدر ↗',researchBtn:'البحث',results:'مادة',updated:'آخر تحديث'},
 en:{radar:'LIVE RADAR',radarTitle:'Savior traditions now',radarNote:'Select a tradition to filter. Bars show the density of recent material found, not truth or doctrinal weight.',home:'Home',research:'Research',media:'Media / News',title:'Media & News',lead:'A sourced monitoring layer for contemporary videos, posts and reporting connected to LuxDot research.',kicker:'CATEGORY',cat:'The Savior · Current discourse',catlead:'What people are saying now about the Messiah, Mahdi, Second Coming, Kalki and other savior traditions. Inclusion documents circulation; it does not certify a prophecy as fulfilled.',atlas:'Open Savior Atlas ↗',allBeliefs:'All traditions',allTypes:'All media',allStatus:'All statuses',search:'Search name or claim…',source:'Source ↗',researchBtn:'Research',results:'items',updated:'Updated'},
 nl:{radar:'LIVE RADAR',radarTitle:'Verlossertradities nu',radarNote:'Kies een traditie om te filteren. De balken tonen de hoeveelheid recent materiaal, niet de waarheid van de claim.',home:'Home',research:'Onderzoek',media:'Media / Nieuws',title:'Media & Nieuws',lead:'Een gedocumenteerde monitorlaag voor actuele video’s, posts en berichtgeving rond LuxDot-onderzoek.',kicker:'CATEGORIE',cat:'De Verlosser · actueel discours',catlead:'Wat nu wordt gezegd over de Messias, Mahdi, Wederkomst, Kalki en andere verlosserstradities. Opname documenteert verspreiding; het bevestigt geen vervulde profetie.',atlas:'Open Verlosseratlas ↗',allBeliefs:'Alle tradities',allTypes:'Alle media',allStatus:'Alle statussen',search:'Zoek naam of claim…',source:'Bron ↗',researchBtn:'Onderzoek',results:'items',updated:'Bijgewerkt'},
 he:{radar:'רדאר חי',radarTitle:'מסורות מושיע עכשיו',radarNote:'בחרו מסורת לסינון. הפסים מודדים את צפיפות החומר העדכני שנמצא, לא את אמיתות הטענה.',home:'ראשי',research:'מחקר',media:'מדיה / חדשות',title:'מדיה וחדשות',lead:'שכבת מעקב מתועדת לסרטונים, פוסטים ודיווחים עכשוויים הקשורים למחקרי LuxDot.',kicker:'קטגוריה',cat:'המושיע · השיח הנוכחי',catlead:'מה נאמר כעת על המשיח, המהדי, הביאה השנייה, קלקי ומסורות מושיע אחרות. הכללה מתעדת שיח ואינה מאשרת שנבואה התגשמה.',atlas:'פתח אטלס המושיע ↗',allBeliefs:'כל המסורות',allTypes:'כל המדיה',allStatus:'כל הסטטוסים',search:'חיפוש…',source:'מקור ↗',researchBtn:'מחקר',results:'פריטים',updated:'עודכן'},
 jv:{radar:"RADAR URIP",radarTitle:"Tradhisi pamarta saiki",radarNote:"Pilih tradhisi kanggo nyaring. Bar nuduhake kapadhetan materi anyar, dudu bebener klaim.",home:'Ngarep',research:'Panaliten',media:'Media / Pawarta',title:'Media & Pawarta',lead:'Lapisan ngawasi sumber video, kiriman lan pawarta saiki sing gegandhengan karo panaliten LuxDot.',kicker:'KATEGORI',cat:'Sang Pamarta · wacana saiki',catlead:'Cathetan babagan apa sing saiki diandharake bab Messiah, Mahdi, Rawuhe Kapindho, Kalki lan tradhisi pamarta liyane. Kalebu ing kene ora ateges ramalan wis kabukten.',atlas:'Bukak Atlas Pamarta ↗',allBeliefs:'Kabeh tradhisi',allTypes:'Kabeh media',allStatus:'Kabeh status',search:'Goleki…',source:'Sumber ↗',researchBtn:'Panaliten',results:'item',updated:'Dianyari'},
 id:{radar:"RADAR LANGSUNG",radarTitle:"Tradisi penyelamat sekarang",radarNote:"Pilih tradisi untuk menyaring. Bar menunjukkan kepadatan materi terbaru, bukan kebenaran klaim.",home:'Beranda',research:'Riset',media:'Media / Berita',title:'Media & Berita',lead:'Lapisan pemantauan bersumber untuk video, unggahan, dan laporan terkini yang terkait dengan riset LuxDot.',kicker:'KATEGORI',cat:'Sang Penyelamat · wacana terkini',catlead:'Apa yang kini dibicarakan tentang Mesias, Mahdi, Kedatangan Kedua, Kalki, dan tradisi penyelamat lainnya. Pencantuman mendokumentasikan peredaran klaim, bukan membuktikan nubuat.',atlas:'Buka Atlas Penyelamat ↗',allBeliefs:'Semua tradisi',allTypes:'Semua media',allStatus:'Semua status',search:'Cari…',source:'Sumber ↗',researchBtn:'Riset',results:'item',updated:'Diperbarui'},
 fr:{radar:"RADAR EN DIRECT",radarTitle:"Traditions du sauveur aujourd’hui",radarNote:"Sélectionnez une tradition. Les barres indiquent la densité de contenu récent, pas la vérité de l’affirmation.",home:'Accueil',research:'Recherches',media:'Médias / Actualités',title:'Médias & Actualités',lead:'Une couche de veille sourcée pour les vidéos, publications et reportages contemporains liés aux recherches LuxDot.',kicker:'CATÉGORIE',cat:'Le Sauveur · discours actuel',catlead:'Ce qui se dit aujourd’hui sur le Messie, le Mahdi, le Second Avènement, Kalki et d’autres traditions du sauveur. L’inclusion documente la circulation d’une affirmation, elle ne prouve pas une prophétie.',atlas:'Ouvrir l’Atlas du Sauveur ↗',allBeliefs:'Toutes les traditions',allTypes:'Tous les médias',allStatus:'Tous les statuts',search:'Rechercher…',source:'Source ↗',researchBtn:'Recherche',results:'éléments',updated:'Mis à jour'},
 es:{radar:"RADAR EN VIVO",radarTitle:"Tradiciones del salvador ahora",radarNote:"Elige una tradición. Las barras indican la densidad de material reciente, no la verdad de la afirmación.",home:'Inicio',research:'Investigación',media:'Medios / Noticias',title:'Medios & Noticias',lead:'Una capa de seguimiento con fuentes para videos, publicaciones y reportajes actuales vinculados con la investigación LuxDot.',kicker:'CATEGORÍA',cat:'El Salvador · discurso actual',catlead:'Qué se dice ahora sobre el Mesías, el Mahdi, la Segunda Venida, Kalki y otras tradiciones del salvador. La inclusión documenta circulación; no demuestra una profecía.',atlas:'Abrir Atlas del Salvador ↗',allBeliefs:'Todas las tradiciones',allTypes:'Todos los medios',allStatus:'Todos los estados',search:'Buscar…',source:'Fuente ↗',researchBtn:'Investigación',results:'elementos',updated:'Actualizado'},
 de:{radar:"LIVE-RADAR",radarTitle:"Erlösertraditionen jetzt",radarNote:"Tradition auswählen. Die Balken zeigen die Dichte aktueller Inhalte, nicht den Wahrheitsgehalt.",home:'Start',research:'Forschung',media:'Medien / Nachrichten',title:'Medien & Nachrichten',lead:'Eine quellenbasierte Beobachtungsebene für aktuelle Videos, Posts und Berichte mit Bezug zur LuxDot-Forschung.',kicker:'KATEGORIE',cat:'Der Erlöser · aktueller Diskurs',catlead:'Was derzeit über Messias, Mahdi, Wiederkunft, Kalki und andere Erlösertraditionen gesagt wird. Aufnahme dokumentiert Verbreitung und beweist keine erfüllte Prophezeiung.',atlas:'Erlöser-Atlas öffnen ↗',allBeliefs:'Alle Traditionen',allTypes:'Alle Medien',allStatus:'Alle Status',search:'Suchen…',source:'Quelle ↗',researchBtn:'Forschung',results:'Einträge',updated:'Aktualisiert'},
 tr:{radar:"CANLI RADAR",radarTitle:"Güncel kurtarıcı gelenekleri",radarNote:"Filtrelemek için bir gelenek seçin. Çubuklar güncel içerik yoğunluğunu gösterir, iddianın doğruluğunu değil.",home:'Ana sayfa',research:'Araştırma',media:'Medya / Haberler',title:'Medya & Haberler',lead:'LuxDot araştırmalarıyla bağlantılı güncel video, gönderi ve haberler için kaynaklı izleme katmanı.',kicker:'KATEGORİ',cat:'Kurtarıcı · güncel söylem',catlead:'Mesih, Mehdi, İkinci Geliş, Kalki ve diğer kurtarıcı gelenekleri hakkında bugün söylenenler. Buraya dahil edilmek bir kehanetin gerçekleştiğini kanıtlamaz.',atlas:'Kurtarıcı Atlasını aç ↗',allBeliefs:'Tüm gelenekler',allTypes:'Tüm medya',allStatus:'Tüm durumlar',search:'Ara…',source:'Kaynak ↗',researchBtn:'Araştırma',results:'öğe',updated:'Güncellendi'}
};
const fallback=I.en;
let data=[], beliefs={}, editorialNote={}, lang='en';
function L(o){return typeof o==='string'?o:(o?.[lang]||o?.en||o?.ar||'')}
function queryLang(){const q=new URLSearchParams(location.search).get('lang');const s=localStorage.getItem('luxdot.lang');return SUP.includes(q)?q:SUP.includes(s)?s:'en'}
function setLang(l){lang=SUP.includes(l)?l:'en';localStorage.setItem('luxdot.lang',lang);document.documentElement.lang=lang;document.documentElement.dir=['ar','he'].includes(lang)?'rtl':'ltr';const t=I[lang]||fallback;
 const nh=$('[data-label="home"]'),nr=$('[data-label="research"]'),nm=$('[data-label="media"]');if(nh)nh.textContent=t.home;if(nr)nr.textContent=t.research;if(nm)nm.textContent=t.media;
 $('#pageTitle').textContent=t.title;$('#radarKicker').textContent=t.radar;$('#radarTitle').textContent=t.radarTitle;$('#radarNote').textContent=t.radarNote;$('#editorialNote').textContent=L(editorialNote);$('#pageLead').textContent=t.lead;$('#categoryKicker').textContent=t.kicker;$('#categoryTitle').textContent=t.cat;$('#categoryLead').textContent=t.catlead;$('#atlasLink').textContent=t.atlas;$('#mediaSearch').placeholder=t.search;
 $('#beliefFilter').options[0].textContent=t.allBeliefs;$('#typeFilter').options[0].textContent=t.allTypes;$('#stanceFilter').options[0].textContent=t.allStatus;
 ['home.html','research.html','savior-atlas.html'].forEach((f,i)=>{const a=i===0?$('[data-label="home"]'):i===1?$('[data-label="research"]'):$('#atlasLink');if(a)a.href=f+'?lang='+lang});
 const ml=$('#mediaLang');if(ml)ml.value=lang;renderOptions();render();
}

function renderRadar(){
 const rail=$('#beliefRail');if(!rail)return;rail.innerHTML='';const bf=$('#beliefFilter');
 Object.entries(beliefs).forEach(([key,b])=>{
   const count=data.filter(x=>x.belief===key).length,btn=document.createElement('button');btn.className='belief-node'+(bf.value===key?' active':'');btn.type='button';
   btn.innerHTML=`<div class="belief-node-top"><span class="belief-icon">${b.icon||'✦'}</span><span class="belief-count">${count}</span></div><b>${L(b.label)}</b><span class="heat">${[1,2,3,4,5].map(i=>`<i class="${i<=Number(b.heat||1)?'on':''}"></i>`).join('')}</span>`;
   btn.onclick=()=>{bf.value=bf.value===key?'all':key;render();};rail.append(btn);
 });
}

function unique(k){return [...new Set(data.map(x=>x[k]))].sort()}
function renderOptions(){
 const bf=$('#beliefFilter'),tf=$('#typeFilter'),sf=$('#stanceFilter');
 const old=[bf.value,tf.value,sf.value];
 bf.length=tf.length=sf.length=1;
 unique('belief').forEach(v=>bf.add(new Option(L(data.find(x=>x.belief===v).belief_label),v)));
 unique('type').forEach(v=>tf.add(new Option(L(data.find(x=>x.type===v).type_label),v)));
 unique('status').forEach(v=>sf.add(new Option(L(data.find(x=>x.status===v).status_label),v)));
 [bf,tf,sf].forEach((e,i)=>{if([...e.options].some(o=>o.value===old[i]))e.value=old[i]});
}
function render(){
 const q=$('#mediaSearch').value.trim().toLowerCase(), b=$('#beliefFilter').value, ty=$('#typeFilter').value, st=$('#stanceFilter').value;
 const rows=data.filter(x=>(b==='all'||x.belief===b)&&(ty==='all'||x.type===ty)&&(st==='all'||x.status===st)&&(!q||[L(x.title),L(x.claim),L(x.source),L(x.belief_label)].join(' ').toLowerCase().includes(q)));
 const g=$('#mediaGrid');g.innerHTML='';const t=I[lang]||fallback;renderRadar();
 rows.forEach(x=>{const n=$('#mediaCardTemplate').content.cloneNode(true);const card=n.querySelector('.media-card');card.dataset.belief=x.belief;n.querySelector('.belief-pill').textContent=L(x.belief_label);n.querySelector('.type-pill').textContent=L(x.type_label);n.querySelector('h3').textContent=L(x.title);n.querySelector('.claim').textContent=L(x.claim);n.querySelector('.source-line').textContent=`${L(x.source)} · ${x.published||''}`;const sp=n.querySelector('.status-pill');sp.textContent=L(x.status_label);sp.dataset.status=x.status;const r=n.querySelector('.research-link');r.textContent=t.researchBtn;r.href=x.research+'?lang='+lang;const s=n.querySelector('.source-link');s.textContent=t.source;s.href=x.url;g.append(n)});
 $('#resultCount').textContent=`${rows.length} ${t.results}`;$('#updatedAt').textContent=`${t.updated}: ${data.meta_updated||'2026-08-20'}`;
}
fetch('data/media-news.json').then(r=>r.json()).then(j=>{data=j.items||[];data.meta_updated=j.updated;beliefs=j.beliefs||{};editorialNote=j.editorial_note||{};lang=queryLang();setLang(lang)}).catch(console.error);
$('#mediaLang')?.addEventListener('change',e=>{const u=new URL(location.href);u.searchParams.set('lang',e.target.value);history.replaceState(null,'',u);setLang(e.target.value)});
['mediaSearch','beliefFilter','typeFilter','stanceFilter'].forEach(id=>$('#'+id).addEventListener(id==='mediaSearch'?'input':'change',render));
})();
