(()=>{
"use strict";
let DB=null,view='brain';
const V=document.getElementById('memoryView'),D=document.getElementById('nodeDialog'),titleEl=document.getElementById('memTitle'),leadEl=document.getElementById('memLead');
if(!V||!D||!titleEl||!leadEl){console.error('LuxDot Memory: required DOM nodes missing');return}
const UI={
 en:{title:'Memory is not a list of dates',lead:'A living atlas of people, places, crimes, rescue, resistance and reconciliation — sourced, versioned and open to correction',loading:'Loading living memory…',error:'Memory data could not be loaded',center:'LIVING MEMORY',documented:'Documented'},
 ar:{title:'الذاكرة ليست قائمة تواريخ',lead:'أطلس حي للأشخاص والأماكن والجرائم والإنقاذ والمقاومة والمصالحة — موثّق، مؤرشف بالإصدارات، وقابل للتصحيح',loading:'جارٍ تحميل الذاكرة الحيّة…',error:'تعذر تحميل بيانات الذاكرة',center:'الذاكرة الحيّة',documented:'موثّق'},
 nl:{title:'Herinnering is geen lijst met data',lead:'Een levende atlas van mensen, plaatsen, misdaden, redding, verzet en verzoening — met bronnen, versies en ruimte voor correctie',loading:'Levend geheugen laden…',error:'Geheugengegevens konden niet worden geladen',center:'LEVEND GEHEUGEN',documented:'Gedocumenteerd'},
 id:{title:'Memori bukan daftar tanggal',lead:'Atlas hidup tentang manusia, tempat, kejahatan, penyelamatan, perlawanan dan rekonsiliasi — bersumber, berversi dan terbuka untuk koreksi',loading:'Memuat memori hidup…',error:'Data memori tidak dapat dimuat',center:'MEMORI HIDUP',documented:'Terdokumentasi'},jv:{title:'Pangeling dudu mung dhaptar tanggal',lead:'Atlas urip bab wong, papan, kadurjanan, pitulungan, perlawanan lan rekonsiliasi — nganggo sumber lan bisa didandani',loading:'Muat pangeling urip…',error:'Data pangeling ora bisa dimuat',center:'PANGELING URIP',documented:'Kacathet'},he:{title:'זיכרון אינו רשימת תאריכים',lead:'אטלס חי של אנשים, מקומות, פשעים, הצלה, התנגדות ופיוס — מבוסס מקורות, מנוהל בגרסאות ופתוח לתיקון',loading:'טוען זיכרון חי…',error:'לא ניתן לטעון את נתוני הזיכרון',center:'זיכרון חי',documented:'מתועד'}
};
const VIEW_LABELS={
ar:{brain:'العقل الحي',timeline:'الزمن',map:'الخريطة',field:'الميدان',sources:'المصادر'},
en:{brain:'Living Mind',timeline:'Time',map:'Map',field:'Field',sources:'Sources'},
nl:{brain:'Levend brein',timeline:'Tijd',map:'Kaart',field:'Veld',sources:'Bronnen'},
he:{brain:'המוח החי',timeline:'זמן',map:'מפה',field:'שטח',sources:'מקורות'},
jv:{brain:'Pikiran Urip',timeline:'Wektu',map:'Peta',field:'Lapangan',sources:'Sumber'},
id:{brain:'Pikiran Hidup',timeline:'Waktu',map:'Peta',field:'Lapangan',sources:'Sumber'},
fr:{brain:'Esprit vivant',timeline:'Temps',map:'Carte',field:'Terrain',sources:'Sources'},
es:{brain:'Mente viva',timeline:'Tiempo',map:'Mapa',field:'Campo',sources:'Fuentes'},
de:{brain:'Lebendiges Gedächtnis',timeline:'Zeit',map:'Karte',field:'Feld',sources:'Quellen'},
tr:{brain:'Yaşayan Zihin',timeline:'Zaman',map:'Harita',field:'Saha',sources:'Kaynaklar'}};
const I18N={
 'rufina-secunda':{ar:{theme:'استشهاد / تقليد',title:'روفينا وسيكوندا',place:'روما · طريق كورنيليا',summary:'يحيي الاستشهاد الروماني ذكرى روفينا وسيكوندا في 10 يوليو. تؤكد مصادر الفاتيكان قدم التذكار واستشهادهما قرب روما، بينما تعود الرواية التفصيلية عن آلامهما إلى طبقة لاحقة يجب تمييزها عن النواة الأقدم',question:'كيف نكرّم تقليداً قديماً ونفصل في الوقت نفسه بين الدليل المبكر والتفاصيل اللاحقة؟'},nl:{theme:'MARTELAARSCHAP / TRADITIE',title:'Rufina & Secunda',place:'Rome · Via Cornelia',summary:'Het Romeins Martyrologium gedenkt Rufina en Secunda op 10 juli. Vaticaanse bronnen plaatsen hun martelaarschap nabij Rome in de derde eeuw; het uitvoerige lijdensverhaal is later en wordt daarom apart gehouden van de oudere verering',question:'Hoe eren we een oude traditie en blijven we tegelijk eerlijk over de ouderdom van het bewijs?'}},
 'justa-rufina':{ar:{theme:'استشهاد / ذاكرة',title:'يوستا وروفينا الإشبيليتان',place:'إشبيلية · إسبانيا',summary:'تحيي كاتدرائية إشبيلية ذكرى يوستا وروفينا في 17 يوليو. العبادة المرتبطة بهما قديمة، لكن الكاتدرائية نفسها تنبّه إلى أن أول الإشارات المكتوبة لسيرتهما واستشهادهما جاءت بعد حياتهما بقرون. بقيتا في ذاكرة المدينة كخزّافتين وشفيعتين لإشبيلية',question:'حين تحفظ الفنون والطقوس الذاكرة، كيف نصون معناها من دون إخفاء عدم اليقين التاريخي؟'},nl:{theme:'MARTELAARSCHAP / HERINNERING',title:'Justa & Rufina van Sevilla',place:'Sevilla · Spanje',summary:'De kathedraal van Sevilla gedenkt Justa en Rufina op 17 juli. Hun verering is oud, maar de kathedraal merkt zelf op dat de eerste geschreven levensverhalen pas eeuwen later verschijnen. Als pottenbaksters en patrones van Sevilla bleven zij sterk aanwezig in kunst en stedelijk geheugen',question:'Hoe bewaren we de betekenis van een herinnering zonder historische onzekerheid te verbergen?'}},
 'edith-stein':{ar:{theme:'تعاطف / كرامة / حقيقة',title:'إديث شتاين · تريزا بندكتا للصليب',place:'بريسلاو ← كولونيا ← إيخت ← فيستربورك ← أوشفيتز–بيركيناو',summary:'إديث شتاين (1891–1942) فيلسوفة ألمانية يهودية الأصل، من تلامذة إدموند هوسرل وصاحبة أطروحة «مشكلة التعاطف». خدمت ممرضة في الحرب العالمية الأولى، ودرّست وكتبت وترجمت، ثم دخلت الرهبنة الكرملية. اعتقلها النازيون في إيخت ورُحلت مع أختها روزا عبر فيستربورك إلى أوشفيتز–بيركيناو حيث قُتلتا في 9 أغسطس 1942.',question:'كيف يتحول إدراك الآخر بوصفه إنساناً حقيقياً إلى مسؤولية عندما تحاول الدولة اختزاله إلى فئة أو رقم؟'},nl:{theme:'EMPATHIE / WAARDIGHEID',title:'Edith Stein · Teresa Benedicta van het Kruis',place:'Echt → Westerbork → Auschwitz-Birkenau',summary:'Edith Stein (1891–1942), Duits-Joodse filosofe en later karmelietes, werd vanuit Nederland gedeporteerd en op 9 augustus 1942 in Auschwitz-Birkenau vermoord. LuxDot bewaart haar herinnering via de vraag die ons onderzoek van 9 augustus droeg: zien wij de mens vóór het etiket?',question:'Kan empathie verantwoordelijkheid worden zodra iemands waardigheid wordt bedreigd?'}},
 'lawrence-rome':{ar:{theme:'خدمة / مستضعفون',title:'لورنس الروماني',place:'روما · إيطاليا',summary:'لورنس شماس وشهيد من روما يُذكر في 10 أغسطس. تركز مصادر الفاتيكان على خدمته للفقراء والأرامل والأيتام. في تحقيق نقطة نور أصبح السؤال: ما الكنز الحقيقي للمجتمع؟',question:'إذا كان المستضعفون هم كنز المجتمع الحقيقي، فما أول ما ينبغي لمؤسساته أن تحميه؟'},nl:{theme:'DIENST / KWETSBAREN',title:'Laurentius van Rome',place:'Rome · Italië',summary:'Laurentius, diaken en martelaar van Rome, wordt op 10 augustus herdacht. Vaticaanse bronnen benadrukken zijn zorg voor wezen, weduwen en armen. In het LuxDot-onderzoek werd zijn herinnering een vraag naar de ware schat van een gemeenschap',question:'Als kwetsbare mensen de ware schat van een gemeenschap zijn, wat moeten haar instellingen dan eerst beschermen?'}},
 westerweel:{
  ar:{theme:'إنقاذ',title:'يوب فيسترفيل',place:'كامب فوخت · هولندا',summary:'مدرس هولندي، مسالم ومنظم في المقاومة. ساعد يهودًا وشبانًا من رواد فلسطين على الاختباء والهرب. أُعدم في كامب فوخت في 11 أغسطس 1944',question:'ماذا تتطلب الحماية منا عندما يكون الصمت أكثر أماناً لكنه أقل إنسانية؟',dossier:'الحارس الذي لم يُدر وجهه — كان يوب فيسترفيل معلماً ومسالماً ومنظماً في المقاومة. ساعد لاجئين يهوداً وشباناً على الاختباء والهرب. بالنسبة إلى نقطة نور لا تكمن الفكرة في صناعة بطل خارق، بل في جعل الحماية فعلاً عملياً حين كان غضّ النظر أكثر أماناً. وحتى رسائله من السجن تحذر من مثاليته وتعيد الشجاعة إلى حجمها الإنساني.'},
  nl:{theme:'REDDING',title:'Joop Westerweel',place:'Kamp Vught · Nederland',summary:'Nederlandse leraar, pacifist en verzetsorganisator. Hij hielp Joden en jonge Palestinapioniers onderduiken en ontsnappen. Op 11 augustus 1944 werd hij in Kamp Vught geëxecuteerd',question:'Wat vraagt bescherming van ons wanneer zwijgen veiliger is, maar minder menselijk?',dossier:'De bewaker die niet wegkeek — Joop Westerweel was leraar, pacifist en verzetsman. Hij hielp Joodse vluchtelingen en jongeren onderduiken en ontsnappen. Voor LuxDot ligt de kern niet in heldenverering, maar in het praktisch maken van bescherming toen wegkijken veiliger was. Zijn eigen gevangenisbrieven waarschuwen bovendien tegen idealisering: moed blijft menselijk.'}},
 stazzema:{ar:{theme:'مدنيون',title:'سانت آنا دي ستاتسيما',place:'توسكانا · إيطاليا',summary:'في 12 أغسطس 1944 قُتل مدنيون في سانت آنا دي ستاتسيما والقرى المجاورة على يد قوات ألمانية من الإس إس مع متعاونين فاشيين. أصبح الموقع لاحقًا حديقة وطنية للسلام',question:'كيف يمكن لمكان مجزرة أن يعلّم السلام من دون محو ما حدث؟'},nl:{theme:'BURGERS',title:'Sant’Anna di Stazzema',place:'Toscane · Italië',summary:'Op 12 augustus 1944 werden burgers in Sant’Anna di Stazzema en omliggende gehuchten vermoord door Duitse SS-troepen met fascistische collaborateurs. De plek werd later een Nationaal Vredespark',question:'Hoe kan een plaats van massamoord vrede onderwijzen zonder uit te wissen wat er gebeurde?'}},
 deportation:{ar:{theme:'ترحيل',title:'آلة الترحيل',place:'أوروبا · 1942',summary:'يكشف أغسطس 1942 كيف يتحول الاضطهاد إلى لوجستيات: غيتوات ونقل وتنسيق إداري وترحيل. نستخدم ريمانوف ورادوم هنا كنوافذ موثقة لا كرمزين لكل التجارب',question:'متى تتحول البيروقراطية إلى مشاركة في العنف؟'},nl:{theme:'DEPORTATIE',title:'De machine van deportatie',place:'Europa · 1942',summary:'Augustus 1942 laat zien hoe vervolging logistiek wordt: getto’s, transporten, administratieve coördinatie en deportatie. Rymanów en Radom dienen hier als gedocumenteerde vensters, niet als symbool voor alle ervaringen',question:'Wanneer wordt bureaucratie deelname aan geweld?'}},
 kolbe:{ar:{theme:'تضحية',title:'ماكسيميليان كولبه',place:'أوشفيتز 1 · بولندا',summary:'تطوع كولبه ليأخذ مكان فرانتشيشك غايوفنيتشيك الذي اختير للموت جوعًا. قُتل كولبه بحقنة سامة في 14 أغسطس 1941 داخل المبنى 11',question:'كيف نحفظ نور التضحية من دون تحويل المعاناة إلى استعراض؟'},nl:{theme:'OPOFFERING',title:'Maximilian Kolbe',place:'Auschwitz I · Polen',summary:'Kolbe bood aan de plaats in te nemen van Franciszek Gajowniczek, die was uitgekozen om van honger te sterven. Kolbe werd op 14 augustus 1941 in Blok 11 met een gifinjectie gedood',question:'Hoe vertellen we over opoffering zonder lijden tot spektakel te maken?'}},
 indies:{id:{theme:'PERINGATAN',title:'15 Agustus — Breda mengenang',place:'Raffy · Breda · Belanda',summary:'Pada 15 Agustus 2026 peringatan Indië diadakan di Monumen Indië di taman Raffy, Breda, dengan tema Belajar memahami sejarah. Acara dimulai pukul 14.00 dan mencakup Raffykoor, Indisch Onze Vader, satu menit hening, pengibaran bendera, peletakan bunga dan defilé',question:'Bagaimana memori menjadi warisan hidup bagi generasi berikutnya tanpa menyederhanakan sejarah yang rumit?'},ar:{theme:'ذاكرة',title:'15 أغسطس — هولندا تتذكر',place:'بريدا · لاهاي · هولندا',summary:'تحيي هولندا ذكرى نهاية الحرب العالمية الثانية بالنسبة للمملكة وضحايا الحرب ضد اليابان والاحتلال الياباني لجزر الهند الشرقية الهولندية السابقة. ويضم النصب الهندي في لاهاي جرسًا برونزيًا للذاكرة',question:'كيف تصبح الذاكرة العامة شيئًا يرثه الجيل التالي بدل أن يكتفي بمشاهدته؟'},nl:{theme:'HERDENKING',title:'15 augustus — Nederland herdenkt',place:'Breda · Den Haag · Nederland',summary:'Nederland herdenkt het einde van de Tweede Wereldoorlog voor het Koninkrijk en de slachtoffers van de oorlog tegen Japan en de Japanse bezetting van voormalig Nederlands-Indië. Bij het Indisch Monument in Den Haag staat een bronzen herdenkingsklok',question:'Hoe wordt openbare herdenking iets dat een volgende generatie kan erven in plaats van alleen bekijken?'}},
 'roger-bialystok':{ar:{theme:'مقاومة / مصالحة',title:'الأخ روجيه · بياويستوك',place:'تيزيه / بياويستوك',summary:'نضع ذاكرتين منفصلتين جنبًا إلى جنب من دون دمجهما: المقاومة اليهودية المسلحة أثناء تصفية غيتو بياويستوك سنة 1943، وحياة الأخ روجيه من تيزيه الذي قُتل أثناء صلاة المساء في 16 أغسطس 2005 بعد حياة كرّسها للمصالحة والتضامن',question:'متى تتطلب حماية الحياة مقاومة، ومتى يتطلب الشفاء مصالحة؟'},nl:{theme:'VERZET / VERZOENING',title:'Broeder Roger · Białystok',place:'Taizé / Białystok',summary:'Twee verschillende herinneringen staan naast elkaar, zonder ze samen te voegen: het Joodse gewapende verzet tijdens de liquidatie van het getto van Białystok in 1943, en het leven van broeder Roger van Taizé, die op 16 augustus 2005 tijdens het avondgebed werd gedood na een leven van verzoening en solidariteit',question:'Wanneer vraagt bescherming van leven om verzet, en wanneer vraagt genezing om verzoening?'}},
 'name-truth':{ar:{theme:'هوية / حقيقة',title:'الاسم والكذبة',place:'ألمانيا / لندن',summary:'في 17 أغسطس 1938 فرضت ألمانيا النازية أسماء إضافية، «إسرائيل» على كثير من الرجال اليهود و«سارا» على كثير من النساء اليهوديات، كعلامة إدارية. وفي 17 أغسطس 1921 نشرت صحيفة التايمز تحقيق فيليب غريفز الذي كشف سرقة النصوص التي بُني عليها تزوير «البروتوكولات» المعادي لليهود',question:'كيف تسهّل التصنيفات الاضطهاد، وكيف يفكك التحقق الصارم من المصادر كذبةً مسلّحة؟'},nl:{theme:'IDENTITEIT / WAARHEID',title:'De naam en de leugen',place:'Duitsland / Londen',summary:'Op 17 augustus 1938 legde nazi-Duitsland extra namen op: Israel voor veel Joodse mannen en Sara voor veel Joodse vrouwen, als administratief kenmerk. Op 17 augustus 1921 publiceerde The Times Philip Graves’ onthulling van het plagiaat achter de antisemitische vervalsing van de Protocollen',question:'Hoe maken etiketten vervolging gemakkelijker, en wat doet grondige broncontrole met een bewapende leugen?'}}
};
const FIELD={
 ar:{visit:'زيارة',official:'رسمي',titles:{'Vught':'النصب الوطني كامب فوخت','Sant’Anna di Stazzema':'الذكرى 82 لمجزرة سانت آنا دي ستاتسيما','Oświęcim / Harmęże':'الذكرى 85 لوفاة ماكسيميليان كولبه','Breda':'إحياء ذكرى الهند الشرقية في رافي','Den Haag':'الذكرى الوطنية لـ15 أغسطس 1945','Bergen op Zoom':'إحياء ذكرى الهند الشرقية — الوعد'},notes:{
  '2026-08-11':'لم نجد فعالية سنوية خاصة منشورة؛ المتحف وأرض المعسكر السابق مفتوحان. تُعامل الزيارة كمحطة ذكرى موثقة',
  '2026-08-12':'قداس 08:30، أكاليل، مراسم رسمية عند النصب من 09:45، كلمات من 10:00، ومعرض ألوان من أجل السلام 11:30',
  '2026-08-14':'طقس تذكاري 08:00، مسيرات، زهور 10:00، قداس مركزي قرب المبنى 11 الساعة 10:30، وصلوات إضافية',
  'Breda':'تبدأ 14:00 ويُطلب الجلوس قبل 13:45؛ مرور تذكاري ووضع الزهور 15:30',
  'Den Haag':'يفتح الميدان 17:00؛ المراسم 18:45–20:00. مقاعد إضافية وفق أسبقية الوصول من دون تذكرة',
  'Bergen op Zoom':'ذكرى إقليمية مع شهادات أربعة أجيال وموسيقى ولقاء بعد المراسم'}},
 id:{visit:'kunjungan',official:'resmi',titles:{'Vught':'Monumen Nasional Kamp Vught','Sant’Anna di Stazzema':'Peringatan ke-82 pembantaian','Oświęcim / Harmęże':'Peringatan ke-85 wafat Maximilian Kolbe','Breda':'Peringatan Indië di Raffy','Den Haag':'Peringatan Nasional 15 Agustus 1945','Bergen op Zoom':'Peringatan Indië — De belofte'},notes:{'2026-08-11':'Tidak ditemukan acara peringatan tahunan khusus; museum dan bekas kamp terbuka. Perlakukan kunjungan sebagai titik memori terdokumentasi','2026-08-12':'Misa 08.30; peletakan karangan bunga; upacara resmi di Ossuary mulai 09.45; pidato mulai 10.00; Colors for Peace 11.30','2026-08-14':'Transitus 08.00; ziarah; bunga 10.00; misa utama dekat Blok 11 pukul 10.30; ibadat lanjutan','Breda':'Mulai 14.00; pengunjung diminta duduk pukul 13.45; defilé dan peletakan bunga pukul 15.30','Den Haag':'Area dibuka 17.00; upacara 18.45–20.00. Tempat duduk tambahan berdasarkan urutan kedatangan tanpa tiket','Bergen op Zoom':'Peringatan regional dengan kisah empat generasi, musik dan pertemuan setelah upacara'}},
 nl:{visit:'bezoek',official:'officieel',titles:{'Vught':'Nationaal Monument Kamp Vught','Sant’Anna di Stazzema':'82e herdenking van de massamoord','Oświęcim / Harmęże':'85e herdenking van de dood van Maximilian Kolbe','Breda':'Indië-herdenking bij Raffy','Den Haag':'Nationale Herdenking 15 augustus 1945','Bergen op Zoom':'Indië-herdenking — De belofte'},notes:{
  '2026-08-11':'Geen specifieke jaarlijkse Westerweel-herdenking gevonden; museum en voormalig kampterrein zijn open. Behandel het bezoek als een gedocumenteerde herdenkingsstop',
  '2026-08-12':'Mis 08:30; kranslegging; officiële ceremonie bij het Ossuarium vanaf 09:45; toespraken vanaf 10:00; Colors for Peace om 11:30',
  '2026-08-14':'Transitus 08:00; pelgrimstochten; bloemen 10:00; centrale mis bij Blok 11 om 10:30; verdere diensten later op de dag',
  'Breda':'Start 14:00; bezoekers worden gevraagd om 13:45 te zitten; defilé en bloemenlegging om 15:30',
  'Den Haag':'Veld open 17:00; ceremonie 18:45–20:00. Extra zitplaatsen op volgorde van aankomst, zonder ticket',
  'Bergen op Zoom':'Regionale herdenking met verhalen van vier generaties, muziek en ontmoeting na afloop'}}
};
const MEMORY_FALLBACK={
en:{
'rufina-secunda':['MARTYRDOM / TRADITION','Rufina & Secunda','Rome · Via Cornelia','The Roman martyrology remembers Rufina and Secunda on 10 July. Vatican sources support an old cult and a martyrdom tradition near Rome, while the detailed passion narrative belongs to a later textual layer.','How can an old tradition be honoured while keeping later narrative details distinct from earlier evidence?'],
'justa-rufina':['MARTYRDOM / MEMORY','Justa & Rufina of Seville','Seville · Spain','Seville Cathedral commemorates Justa and Rufina on 17 July. Their cult is old, while detailed written lives appear centuries later; their identity as potters became part of the city’s artistic memory.','How can art and devotion preserve memory without hiding historical uncertainty?'],
'edith-stein':['EMPATHY / DIGNITY / TRUTH','Edith Stein · Teresa Benedicta of the Cross','Breslau → Cologne → Echt → Westerbork → Auschwitz-Birkenau','Edith Stein (1891–1942) was a German-Jewish philosopher, former assistant to Edmund Husserl and author on empathy. She later became a Carmelite nun and was deported from the Netherlands with her sister Rosa to Auschwitz-Birkenau, where they were killed on 9 August 1942.','How does recognition of another person become responsibility when a state reduces people to categories and numbers?'],
'lawrence-rome':['SERVICE / VULNERABLE PEOPLE','Saint Lawrence of Rome','Rome · Italy','Lawrence, deacon and martyr of Rome, is commemorated on 10 August. Vatican sources emphasize his service to the poor, widows and orphans; LuxDot uses his memory to ask what a community considers its real treasure.','If vulnerable people are a community’s true treasure, what should its institutions protect first?'],
'westerweel':['RESCUE','Joop Westerweel','Kamp Vught · Netherlands','Dutch teacher and resistance organizer Joop Westerweel helped Jewish refugees and young Zionist pioneers hide and escape. He was arrested after returning from France and executed at Kamp Vught on 11 August 1944.','What does protection demand when silence is safer but less humane?'],
'stazzema':['MASSACRE / CIVILIAN MEMORY','Sant’Anna di Stazzema','Tuscany · Italy','The memory node follows the massacre of civilians at Sant’Anna di Stazzema and the continuing work of local and European remembrance.','How should places of mass violence be remembered without turning victims into symbols detached from their lives?'],
'deportation':['DEPORTATION / SYSTEM','The deportation machine','Europe · 1942','This node studies deportation as an administrative system: registration, isolation, transport, camps and the institutions that made mass persecution operational.','How does ordinary administration become part of extraordinary violence?'],
'kolbe':['SACRIFICE / MEMORY','Maximilian Maria Kolbe','Auschwitz I · Poland','Franciscan priest Maximilian Kolbe volunteered to die in place of fellow prisoner Franciszek Gajowniczek at Auschwitz and died on 14 August 1941. The node separates documented events from later devotional interpretation.','What can one act of self-sacrifice reveal about dignity inside a system built to erase it?'],
'indies':['COLONIAL MEMORY / RECONCILIATION','15 August — Breda remembers','Raffy · Breda · Netherlands','The Breda commemoration connects the end of the war against Japan, the Dutch East Indies, decolonisation, migration and the memories of Indisch and Moluccan communities.','How can a public commemoration hold different family memories without forcing them into one story?'],
'roger-bialystok':['RECONCILIATION / ECUMENISM','Brother Roger · Białystok','Taizé / Białystok','The node links the memory of Brother Roger and the ecumenical tradition of Taizé with a wider question of reconciliation across Christian divisions and European memory.','What practices make reconciliation more than a slogan?'],
'name-truth':['IDENTITY / PROPAGANDA','The name and the lie','Germany / London','This node examines the political use of names, labels and repeated falsehoods: how language can humanize, erase or prepare a society to accept exclusion.','When does naming stop describing people and start controlling how others are allowed to see them?'],
'denhaag-deportation':['DEPORTATION / LOCAL MEMORY','18 August — mass deportation from The Hague','The Hague → Westerbork','This node follows the beginning of mass deportations of Jewish residents from The Hague, connecting local streets and institutions to the wider deportation system.','How does a familiar city become part of a machinery of exclusion and deportation?'],
'humanitarian-day':['HUMANITARIAN SERVICE','19 August — those who help under danger','Baghdad · Iraq','World Humanitarian Day remembers humanitarian workers and civilians affected by conflict, with 19 August tied to the 2003 bombing of the UN headquarters in Baghdad.','What does principled help require when the people providing it are themselves in danger?'],
'saint-genis':['MASSACRE / RESISTANCE MEMORY','20 August — Saint-Genis-Laval','Saint-Genis-Laval · France','The node remembers prisoners murdered at Fort de Côte-Lorette in Saint-Genis-Laval in August 1944 and the local work of preserving their names.','How can local memory restore individual names after mass violence tried to reduce people to numbers?'],
'ghouta-chemical':['CHEMICAL WARFARE / CIVILIAN MEMORY','21 August — Ghouta: sarin memory','Ghouta · Damascus · Syria','The node remembers the 21 August 2013 chemical attacks in Ghouta and separates documented evidence about sarin exposure and civilian deaths from later political claims that require their own proof.','How can evidence and human memory be preserved when a mass-casualty event becomes a battlefield of competing narratives?'],
'belief-violence':['FREEDOM OF BELIEF / VICTIMS','22 August — victims of violence based on religion or belief','Global memory','This node marks the international day for victims of acts of violence based on religion or belief and connects it to freedom of conscience and protection of minorities.','How can societies defend belief and non-belief without turning either into a reason for violence?'],
'totalitarian-victims':['TOTALITARIANISM / EUROPEAN MEMORY','23 August — victims of totalitarian and authoritarian regimes','Europe','The node connects European remembrance of victims of totalitarian and authoritarian regimes with the need to study distinct systems without erasing their differences.','How can comparison illuminate patterns of repression without flattening unlike histories into one story?'],
'st-bartholomew':['RELIGIOUS VIOLENCE / MASSACRE','24 August — St Bartholomew’s Day massacre','Paris · France','The node follows the 1572 St Bartholomew’s Day massacre and the spread of anti-Huguenot violence, treating it as a study in political power, confessional conflict and collective memory.','What allows religious and political hostility to cross the threshold into organized mass violence?']},
nl:{
'denhaag-deportation':['DEPORTATIE / LOKALE HERINNERING','18 augustus — begin massale deportatie uit Den Haag','Den Haag → Westerbork','Deze knoop volgt het begin van de massale deportaties van Joodse inwoners uit Den Haag en verbindt lokale straten en instellingen met het bredere deportatiesysteem.','Hoe wordt een vertrouwde stad onderdeel van een machine van uitsluiting en deportatie?'],
'humanitarian-day':['HUMANITAIRE HULP','19 augustus — wie helpt onder gevaar','Bagdad · Irak','Wereldhumanitaire dag herdenkt hulpverleners en burgers die door conflict worden getroffen; 19 augustus verwijst naar de aanslag op het VN-hoofdkwartier in Bagdad in 2003.','Wat vraagt principiële hulp wanneer ook de hulpverleners zelf gevaar lopen?'],
'saint-genis':['MASSAMOORD / VERZETSHERINNERING','20 augustus — Saint-Genis-Laval','Saint-Genis-Laval · Frankrijk','Deze knoop herdenkt gevangenen die in augustus 1944 bij Fort de Côte-Lorette in Saint-Genis-Laval werden vermoord en het lokale werk om hun namen te bewaren.','Hoe kan lokale herinnering individuele namen herstellen nadat massaal geweld mensen tot nummers probeerde te reduceren?'],
'ghouta-chemical':['CHEMISCHE OORLOG / BURGERHERINNERING','21 augustus — Ghouta: herinnering aan sarin','Ghouta · Damascus · Syrië','Deze knoop herdenkt de chemische aanvallen van 21 augustus 2013 in Ghouta en scheidt gedocumenteerd bewijs over sarin en burgerslachtoffers van latere politieke claims die afzonderlijk bewijs vereisen.','Hoe bewaren we bewijs en menselijke herinnering wanneer een massaal geweldsincident zelf een strijdtoneel van verhalen wordt?'],
'belief-violence':['VRIJHEID VAN GELOOF / SLACHTOFFERS','22 augustus — slachtoffers van geweld vanwege religie of overtuiging','Wereldwijde herinnering','Deze knoop markeert de internationale dag voor slachtoffers van geweld op grond van religie of overtuiging en koppelt die aan gewetensvrijheid en bescherming van minderheden.','Hoe beschermen samenlevingen geloof én ongeloof zonder dat een van beide reden voor geweld wordt?'],
'totalitarian-victims':['TOTALITARISME / EUROPESE HERINNERING','23 augustus — slachtoffers van totalitaire en autoritaire regimes','Europa','Deze knoop verbindt de Europese herdenking van slachtoffers van totalitaire en autoritaire regimes met de noodzaak verschillende systemen te bestuderen zonder hun verschillen uit te wissen.','Hoe kan vergelijking patronen van repressie tonen zonder verschillende geschiedenissen tot één verhaal plat te slaan?'],
'st-bartholomew':['RELIGIEUS GEWELD / MASSAMOORD','24 augustus — Bartholomeusnacht','Parijs · Frankrijk','Deze knoop volgt de Bartholomeusnacht van 1572 en de verspreiding van geweld tegen hugenoten als studie van politieke macht, confessioneel conflict en collectieve herinnering.','Wat maakt dat religieuze en politieke vijandigheid de grens naar georganiseerd massaal geweld overschrijdt?']}}
function nonArabicFallback(n,l){const z=MEMORY_FALLBACK[l]?.[n.id]||MEMORY_FALLBACK.en[n.id];if(!z)return {...n,title:String(n.id).replace(/-/g,' '),theme:l==='nl'?'GEHEUGEN':'MEMORY',place:'',summary:l==='nl'?'Deze herinneringsknoop wordt momenteel vertaald. De bronnen blijven beschikbaar.':'This memory node is currently being translated. Its sources remain available.',question:l==='nl'?'Welke bronnen ondersteunen deze herinnering?':'Which sources support this memory?'};return {...n,theme:z[0],title:z[1],place:z[2],summary:z[3],question:z[4],dossier:''}}

function lang(){const raw=(window.LuxLang&&window.LuxLang.get())||'en';return ['ar','en','nl','jv','he'].includes(raw)?raw:'en'}
function ui(){return UI[lang()]||UI.en}
function trNode(n){const l=lang();const z=I18N[n.id]?.[l]||(l==='jv'?I18N[n.id]?.id:null);if(z)return {...n,...z};if(l!=='ar')return nonArabicFallback(n,l);return n}
function localPage(url){if(!url)return url;const sep=String(url).includes('?')?'&':'?';return String(url)+sep+'lang='+encodeURIComponent(lang())}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(d){try{return new Intl.DateTimeFormat(lang(),{weekday:'short',day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00'))}catch{return d}}
function translateHead(){titleEl.textContent=ui().title;leadEl.textContent=ui().lead}
function fieldNote(f){const l=lang();if(l==='ar')return f.note;const x=FIELD[l]||FIELD[l==='jv'?'id':'en'];return x?.notes?.[f.city]||x?.notes?.[f.date]||({en:'See official event source.',nl:'Zie de officiële evenementbron.',jv:'Delengen sumber acara resmi.',he:'ראו את מקור האירוע הרשמי.'}[l])}
function fieldKind(f){const l=lang();if(l==='ar')return String(f.kind||'').toUpperCase();const x=FIELD[l]||FIELD[l==='jv'?'id':'en'];return (x?.[f.kind]||f.kind||'').toUpperCase()}
function fieldTitle(f){const l=lang();if(l==='ar')return f.title;const x=FIELD[l]||FIELD[l==='jv'?'id':'en'];return x?.titles?.[f.city]||String(f.city||f.title||'')}

const MEMORY_SYMBOLS={
 'rufina-secunda':[['✝','faith'],['⚔','violence']],
 'justa-rufina':[['✝','faith'],['⚔','violence']],
 'edith-stein':[['✡','faith'],['▣','detention'],['☠','death']],
 'lawrence-rome':[['✝','faith'],['🔥','fire'],['☠','death']],
 'westerweel':[['⛓','detention'],['⚖','justice'],['☠','death']],
 'stazzema':[['⌖','civilian'],['⚔','violence'],['☠','death']],
 'deportation':[['⛓','detention'],['➜','transport'],['☠','death']],
 'kolbe':[['⛓','detention'],['☠','toxic'],['✝','faith']],
 'indies':[['⚔','violence'],['⌖','civilian'],['🕯','memory']],
 'roger-bialystok':[['⚔','violence'],['✝','faith'],['🕊','peace']],
 'name-truth':[['▤','document'],['⚠','persecution']],
 'denhaag-deportation':[['⛓','detention'],['➜','transport']],
 'humanitarian-day':[['✚','aid'],['💥','explosion'],['☠','death']],
 'saint-genis':[['⛓','detention'],['⚔','violence'],['☠','death']],
 'ghouta-chemical':[['☠','chemical'],['≋','gas'],['◉','nerve']],
 'belief-violence':[['☸','belief'],['⚔','violence'],['🕯','memory']],
 'totalitarian-victims':[['⚠','oppression'],['⛓','detention'],['🕯','memory']],
 'st-bartholomew':[['✝','faith'],['⚔','violence'],['☠','death']]
};
const TRAGEDY_IDS=new Set(Object.keys(MEMORY_SYMBOLS));
function tragedy(id){return TRAGEDY_IDS.has(id)}
function symbolCartouche(id){const a=MEMORY_SYMBOLS[id];if(!a?.length)return '';return `<span class="sls-memory-cartouche" aria-hidden="true">${a.map(([g,c])=>`<i class="sls-symbol sls-${c}">${g}</i>`).join('')}</span>`}
function bloodMark(id){return symbolCartouche(id)}
function openNode(id){const raw=DB?.nodes?.find(x=>x.id===id);if(!raw)return;const n=trNode(raw);D.innerHTML=`<article class="node-panel ${tragedy(n.id)?'has-tragedy':''}">${bloodMark(n.id)}<button class="closex" aria-label="${esc(lang()==='ar'?'إغلاق':lang()==='nl'?'Sluiten':'Close')}">×</button><div class="node-meta">${fmt(n.date)} / ${esc(n.theme)} / ${esc(lang()==='en'?n.status:ui().documented)}</div><h2>${esc(n.title)}</h2><div class="node-meta">${esc(n.place)}</div>${n.image?`<img src="${esc(n.image)}" alt="${esc(n.title)}" loading="lazy" referrerpolicy="no-referrer"><div class="credit">${esc(n.imageCredit||'')}</div>`:''}<p>${esc(n.summary)}</p>${n.dossier?`<div class="memory-dossier"><p>${esc(n.dossier)}</p></div>`:''}${n.page?`<div class="memory-dossier-link"><a href="${esc(localPage(n.page))}">${esc(lang()==='ar'?'فتح ملف الذاكرة الكامل':lang()==='nl'?'Open volledig geheugendossier':'Open full memory dossier')} →</a></div>`:''}<p class="question">${esc(n.question)}</p><div class="link-row">${[...(n.sources||[]),...(n.media||[])].map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('')}</div></article>`;D.classList.add('on');D.setAttribute('aria-hidden','false');D.querySelector('.closex')?.addEventListener('click',close)}
function close(){D.classList.remove('on');D.setAttribute('aria-hidden','true')}
D.addEventListener('click',e=>{if(e.target===D)close()});addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function brain(){
 const nodes=(DB.nodes||[]).map(trNode),W=1000,H=620;
 const zones=[{id:'people',ar:'أشخاص',en:'PEOPLE',x:300,y:205,rx:185,ry:120},{id:'violence',ar:'حروب وجرائم',en:'VIOLENCE / CRIMES',x:690,y:205,rx:190,ry:120},{id:'rescue',ar:'إنقاذ ورعاية',en:'RESCUE / CARE',x:285,y:410,rx:175,ry:115},{id:'places',ar:'أماكن وشهادات',en:'PLACES / WITNESS',x:700,y:410,rx:185,ry:115}];
 function zoneOf(n){const x=(n.theme+' '+n.summary+' '+n.place).toLowerCase();if(/قتل|مجز|حرب|ترحيل|عنف|ضحايا|martyr|war|victim|deport|violence|chemical|gas/.test(x))return 'violence';if(/إنقاذ|رعاية|تضحي|خدمة|مسعف|rescue|care|service|humanitarian/.test(x))return 'rescue';if(/روما|بريدا|هولندا|إيطاليا|سوريا|غوطة|place|netherlands|syria|rome|italy/.test(x))return 'places';return 'people'}
 const grouped={people:[],violence:[],rescue:[],places:[]};nodes.forEach(n=>grouped[zoneOf(n)].push(n));const pos={};
 zones.forEach(z=>{const arr=grouped[z.id],c=Math.max(arr.length,1);arr.forEach((n,i)=>{const ang=Math.PI*2*i/c+(z.id==='violence'?.35:0),ring=.42+.45*((i%3)/2);pos[n.id]=[z.x+Math.cos(ang)*z.rx*ring,z.y+Math.sin(ang)*z.ry*ring]})});
 const links=[];zones.forEach(z=>{const arr=grouped[z.id];arr.forEach((n,i)=>{if(arr.length>1)links.push([n.id,arr[(i+1)%arr.length].id,'local'])})});
 for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const x=nodes[i],y=nodes[j];if(zoneOf(x)===zoneOf(y))continue;const px=String(x.place||'').split(/[·•]/)[0].trim(),py=String(y.place||'').split(/[·•]/)[0].trim();if(px&&px===py)links.push([x.id,y.id,'cross'])}
 const outline='M500 64 C390 20 270 66 215 158 C115 190 104 319 176 378 C151 481 257 557 367 532 C417 594 505 567 523 522 C573 573 671 566 710 509 C825 524 901 437 866 343 C933 257 873 146 786 139 C727 62 608 35 500 64 Z';
 const paths=links.slice(0,110).map(([x,y,k],i)=>{const p=pos[x],q=pos[y];if(!p||!q)return'';const mx=(p[0]+q[0])/2,bend=(i%2?1:-1)*(18+(i%5)*4),d=`M${p[0].toFixed(1)},${p[1].toFixed(1)} Q${mx.toFixed(1)},${((p[1]+q[1])/2+bend).toFixed(1)} ${q[0].toFixed(1)},${q[1].toFixed(1)}`;return `<path class="brain-synapse ${k}" data-a="${esc(x)}" data-b="${esc(y)}" d="${d}"/><path class="brain-impulse ${k}" d="${d}" style="animation-delay:${(i%13)*.23}s"/>`}).join('');
 V.innerHTML=`<div class="living-mind"><div class="mind-symbolism"><b>${lang()==='ar'?'العقل الحي · Living Mind':'Living Mind'}</b><span>${lang()==='ar'?'الذكريات ليست فروعاً ثابتة؛ هي نبضات. تضيء الذكرى وتسافر عبر مسار عصبي فتوقظ علاقات قريبة. حجم النبضة لا يعني قيمة إنسان أكبر؛ التوثيق منفصل عن الكرامة.':'Memories are pulses, not branches. A memory lights up, travels a neural path and awakens related memories. Pulse size never ranks human worth; documentation is separate from dignity.'}</span></div><svg class="brain-map" viewBox="0 0 1000 620"><path class="brain-outline" d="${outline}"/><path class="brain-midline" d="M500 79 C470 130 488 181 501 220 C475 260 480 310 506 341 C483 382 484 431 514 463 C494 492 493 520 523 545"/>${zones.map(z=>`<ellipse class="brain-zone" cx="${z.x}" cy="${z.y}" rx="${z.rx}" ry="${z.ry}"/><text class="brain-zone-label" x="${z.x}" y="${z.y-z.ry+24}">${lang()==='ar'?z.ar:z.en}</text>`).join('')}<g>${paths}</g></svg><div class="brain-nodes">${nodes.map((n,i)=>{const q=pos[n.id]||[500,315];return `<button class="brain-memory ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}" style="left:${(q[0]/W*100).toFixed(2)}%;top:${(q[1]/H*100).toFixed(2)}%;--delay:${(i%17)*.17}s"><span class="neuron-core"></span><span class="neuron-copy"><b>${esc(n.title)}</b><small>${fmt(n.date)} · ${esc(n.theme)}</small></span></button>`}).join('')}</div><div class="brain-legend"><span>MEMORY PULSE</span><span>SYNAPSE</span><span>DOCUMENTATION ≠ HUMAN WORTH</span></div></div>`;
 bindNodes();
 V.querySelectorAll('.brain-memory').forEach(n=>n.addEventListener('mouseenter',()=>{const id=n.dataset.id,rel=new Set([id]);V.querySelectorAll('.brain-memory,.brain-synapse').forEach(x=>x.classList.remove('active','related','dim'));V.querySelectorAll(`.brain-synapse[data-a="${CSS.escape(id)}"],.brain-synapse[data-b="${CSS.escape(id)}"]`).forEach(e=>{e.classList.add('active');rel.add(e.dataset.a);rel.add(e.dataset.b)});V.querySelectorAll('.brain-memory').forEach(x=>x.classList.add(rel.has(x.dataset.id)?(x.dataset.id===id?'active':'related'):'dim'))}))
}
function timeline(){V.innerHTML=`<div class="timeline">${(DB.nodes||[]).map(trNode).map(n=>`<article class="time-row ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}">${bloodMark(n.id)}<div class="time-date">${fmt(n.date)}</div><div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p></div></article>`).join('')}</div>`;bindNodes()}
function map(){
 const nodes=(DB.nodes||[]).filter(n=>Number.isFinite(n.lat)&&Number.isFinite(n.lon)).map(trNode);
 V.innerHTML=`<div class="map-wrap"><div id="memoryLeafletMap" aria-label="Memory atlas map"></div><div class="map-list">${nodes.map(n=>`<article class="map-card ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}">${bloodMark(n.id)}<b>${esc(n.title)}</b><small>${esc(n.place)} · ${fmt(n.date)}</small></article>`).join('')}</div></div>`;bindNodes();
 if(!window.L){document.getElementById('memoryLeafletMap').innerHTML=`<div class="status">${esc(({ar:'تعذر تحميل خادم الخريطة. تبقى بيانات الأطلس متاحة في القائمة والشجرة',en:'Map service could not load. Atlas data remains available in the list and tree.',nl:'De kaartservice kon niet laden. De atlasgegevens blijven beschikbaar in lijst en boom.',jv:'Layanan peta ora bisa dimuat. Data atlas tetep ana ing dhaptar lan wit.',he:'שירות המפה לא נטען. נתוני האטלס נשארים זמינים ברשימה ובעץ.'})[lang()]||'Map unavailable')}</div>`;return}
 const m=L.map('memoryLeafletMap',{zoomControl:true,worldCopyJump:true}).setView([50.6,8.0],4);
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m);
 const icon=L.divIcon({className:'lux-pin-wrap',html:'<span class="lux-map-pin"><span class="lux-map-pin-core"></span></span>',iconSize:[30,42],iconAnchor:[15,39],popupAnchor:[0,-38],tooltipAnchor:[0,-34]});
 const group=[];nodes.forEach(n=>{const mk=L.marker([n.lat,n.lon],{icon}).addTo(m);mk.bindTooltip(esc(n.title),{direction:'top'});mk.on('click',()=>openNode(n.id));group.push(mk)});if(group.length){const fg=L.featureGroup(group);m.fitBounds(fg.getBounds().pad(.22),{maxZoom:6})}
}
function field(){V.innerHTML=`<div class="field-grid">${(DB.field||[]).map(f=>`<article class="field-card"><span class="badge">${fmt(f.date)} / ${esc(fieldKind(f))}</span><b>${esc(fieldTitle(f))}</b><small>${esc(f.city)} · ${esc(f.time)}<br>${esc(f.address)}<br><br>${esc(fieldNote(f))}</small></article>`).join('')}</div>`}
function sources(){let all=[];(DB.nodes||[]).forEach(raw=>{const n=trNode(raw);(n.sources||[]).forEach(s=>all.push({...s,node:n.title,date:n.date}))});V.innerHTML=`<div class="source-grid">${all.map(s=>`<article class="source-card"><small>${fmt(s.date)} · ${esc(s.node)}</small><br><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a></article>`).join('')}</div>`}
function bindNodes(){V.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>openNode(el.dataset.id)))}
function applyViewLabels(){const x=VIEW_LABELS[lang()]||VIEW_LABELS.en;const b=document.querySelector('[data-memory-view-label="brain"]');if(b)b.textContent=x.brain;document.querySelectorAll('.memory-controls [data-view]').forEach(q=>{if(q.dataset.view!=='brain'&&x[q.dataset.view])q.textContent=x[q.dataset.view]})} function render(){if(!DB)return;applyViewLabels();({brain,timeline,map,field,sources}[view]||brain)()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('on',x===b));render()}));
document.addEventListener('luxlang',()=>{translateHead();render()});
let bootTries=0;function boot(){translateHead();if(!DB)V.innerHTML=`<div class="status">${esc(ui().loading)}</div>`;if(window.LUXDOT_MEMORY_DB&&Array.isArray(window.LUXDOT_MEMORY_DB.nodes)){DB=window.LUXDOT_MEMORY_DB;render();return}bootTries++;if(bootTries<25){setTimeout(boot,80);return}console.error('LuxDot Memory: embedded dataset missing');V.innerHTML=`<div class="status">${esc(ui().error)}</div>`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();