(()=>{
"use strict";
let DB=null,view='tree';
const V=document.getElementById('memoryView'),D=document.getElementById('nodeDialog'),titleEl=document.getElementById('memTitle'),leadEl=document.getElementById('memLead');
if(!V||!D||!titleEl||!leadEl){console.error('LuxDot Memory: required DOM nodes missing');return}
const UI={
 en:{title:'Memory is not a list of dates',lead:'A living atlas of people, places, crimes, rescue, resistance and reconciliation — sourced, versioned and open to correction',loading:'Loading living memory…',error:'Memory data could not be loaded',center:'LIVING MEMORY',documented:'Documented'},
 ar:{title:'الذاكرة ليست قائمة تواريخ',lead:'أطلس حي للأشخاص والأماكن والجرائم والإنقاذ والمقاومة والمصالحة — موثّق، مؤرشف بالإصدارات، وقابل للتصحيح',loading:'جارٍ تحميل الذاكرة الحيّة…',error:'تعذر تحميل بيانات الذاكرة',center:'الذاكرة الحيّة',documented:'موثّق'},
 nl:{title:'Herinnering is geen lijst met data',lead:'Een levende atlas van mensen, plaatsen, misdaden, redding, verzet en verzoening — met bronnen, versies en ruimte voor correctie',loading:'Levend geheugen laden…',error:'Geheugengegevens konden niet worden geladen',center:'LEVEND GEHEUGEN',documented:'Gedocumenteerd'},
 id:{title:'Memori bukan daftar tanggal',lead:'Atlas hidup tentang manusia, tempat, kejahatan, penyelamatan, perlawanan dan rekonsiliasi — bersumber, berversi dan terbuka untuk koreksi',loading:'Memuat memori hidup…',error:'Data memori tidak dapat dimuat',center:'MEMORI HIDUP',documented:'Terdokumentasi'}
};
const I18N={
 'rufina-secunda':{ar:{theme:'استشهاد / تقليد',title:'روفينا وسيكوندا',place:'روما · طريق كورنيليا',summary:'يحيي الاستشهاد الروماني ذكرى روفينا وسيكوندا في 10 يوليو. تؤكد مصادر الفاتيكان قدم التذكار واستشهادهما قرب روما، بينما تعود الرواية التفصيلية عن آلامهما إلى طبقة لاحقة يجب تمييزها عن النواة الأقدم',question:'كيف نكرّم تقليداً قديماً ونفصل في الوقت نفسه بين الدليل المبكر والتفاصيل اللاحقة؟'},nl:{theme:'MARTELAARSCHAP / TRADITIE',title:'Rufina & Secunda',place:'Rome · Via Cornelia',summary:'Het Romeins Martyrologium gedenkt Rufina en Secunda op 10 juli. Vaticaanse bronnen plaatsen hun martelaarschap nabij Rome in de derde eeuw; het uitvoerige lijdensverhaal is later en wordt daarom apart gehouden van de oudere verering',question:'Hoe eren we een oude traditie en blijven we tegelijk eerlijk over de ouderdom van het bewijs?'}},
 'justa-rufina':{ar:{theme:'استشهاد / ذاكرة',title:'يوستا وروفينا الإشبيليتان',place:'إشبيلية · إسبانيا',summary:'تحيي كاتدرائية إشبيلية ذكرى يوستا وروفينا في 17 يوليو. العبادة المرتبطة بهما قديمة، لكن الكاتدرائية نفسها تنبّه إلى أن أول الإشارات المكتوبة لسيرتهما واستشهادهما جاءت بعد حياتهما بقرون. بقيتا في ذاكرة المدينة كخزّافتين وشفيعتين لإشبيلية',question:'حين تحفظ الفنون والطقوس الذاكرة، كيف نصون معناها من دون إخفاء عدم اليقين التاريخي؟'},nl:{theme:'MARTELAARSCHAP / HERINNERING',title:'Justa & Rufina van Sevilla',place:'Sevilla · Spanje',summary:'De kathedraal van Sevilla gedenkt Justa en Rufina op 17 juli. Hun verering is oud, maar de kathedraal merkt zelf op dat de eerste geschreven levensverhalen pas eeuwen later verschijnen. Als pottenbaksters en patrones van Sevilla bleven zij sterk aanwezig in kunst en stedelijk geheugen',question:'Hoe bewaren we de betekenis van een herinnering zonder historische onzekerheid te verbergen?'}},
 'edith-stein':{ar:{theme:'تعاطف / كرامة',title:'إديث شتاين · تيريزا بنديكتا للصليب',place:'إيخت ← فيستربورك ← أوشفيتز',summary:'إديث شتاين (1891–1942) فيلسوفة ألمانية يهودية الأصل أصبحت راهبة كرمليّة. رُحلت من هولندا وقُتلت في أوشفيتز-بيركيناو في 9 أغسطس 1942. حفظ بحث نقطة نور ذكراها عبر سؤال التعاطف والكرامة: هل نرى الإنسان قبل التصنيف؟',question:'هل نستطيع أن نرى الإنسان قبل التصنيف، وأن يتحول هذا الإدراك إلى مسؤولية؟'},nl:{theme:'EMPATHIE / WAARDIGHEID',title:'Edith Stein · Teresa Benedicta van het Kruis',place:'Echt → Westerbork → Auschwitz-Birkenau',summary:'Edith Stein (1891–1942), Duits-Joodse filosofe en later karmelietes, werd vanuit Nederland gedeporteerd en op 9 augustus 1942 in Auschwitz-Birkenau vermoord. LuxDot bewaart haar herinnering via de vraag die ons onderzoek van 9 augustus droeg: zien wij de mens vóór het etiket?',question:'Kan empathie verantwoordelijkheid worden zodra iemands waardigheid wordt bedreigd?'}},
 'lawrence-rome':{ar:{theme:'خدمة / مستضعفون',title:'لورنس الروماني',place:'روما · إيطاليا',summary:'لورنس شماس وشهيد من روما يُذكر في 10 أغسطس. تركز مصادر الفاتيكان على خدمته للفقراء والأرامل والأيتام. في تحقيق نقطة نور أصبح السؤال: ما الكنز الحقيقي للمجتمع؟',question:'إذا كان المستضعفون هم كنز المجتمع الحقيقي، فما أول ما ينبغي لمؤسساته أن تحميه؟'},nl:{theme:'DIENST / KWETSBAREN',title:'Laurentius van Rome',place:'Rome · Italië',summary:'Laurentius, diaken en martelaar van Rome, wordt op 10 augustus herdacht. Vaticaanse bronnen benadrukken zijn zorg voor wezen, weduwen en armen. In het LuxDot-onderzoek werd zijn herinnering een vraag naar de ware schat van een gemeenschap',question:'Als kwetsbare mensen de ware schat van een gemeenschap zijn, wat moeten haar instellingen dan eerst beschermen?'}},
 westerweel:{
  ar:{theme:'إنقاذ',title:'يوب فيسترفيل',place:'كامب فوخت · هولندا',summary:'مدرس هولندي، مسالم ومنظم في المقاومة. ساعد يهودًا وشبانًا من رواد فلسطين على الاختباء والهرب. أُعدم في كامب فوخت في 11 أغسطس 1944',question:'ماذا تتطلب الحماية منا عندما يكون الصمت أكثر أماناً لكنه أقل إنسانية؟',dossier:'الحارس الذي لم يُدر وجهه — كان يوب فيسترفيل معلماً ومسالماً ومنظماً في المقاومة. ساعد لاجئين يهوداً وشباناً على الاختباء والهرب. بالنسبة إلى نقطة نور لا تكمن الفكرة في صناعة بطل خارق، بل في جعل الحماية فعلاً عملياً حين كان غضّ النظر أكثر أماناً. وحتى رسائله من السجن تحذر من مثاليته وتعيد الشجاعة إلى حجمها الإنساني.'},
  nl:{theme:'REDDING',title:'Joop Westerweel',place:'Kamp Vught · Nederland',summary:'Nederlandse leraar, pacifist en verzetsorganisator. Hij hielp Joden en jonge Palestinapioniers onderduiken en ontsnappen. Op 11 augustus 1944 werd hij in Kamp Vught geëxecuteerd',question:'Wat vraagt bescherming van ons wanneer zwijgen veiliger is, maar minder menselijk?',dossier:'De bewaker die niet wegkeek — Joop Westerweel was leraar, pacifist en verzetsman. Hij hielp Joodse vluchtelingen en jongeren onderduiken en ontsnappen. Voor LuxDot ligt de kern niet in heldenverering, maar in het praktisch maken van bescherming toen wegkijken veiliger was. Zijn eigen gevangenisbrieven waarschuwen bovendien tegen idealisering: moed blijft menselijk.'}},
 stazzema:{ar:{theme:'مدنيون',title:'سانت آنا دي ستاتسيما',place:'توسكانا · إيطاليا',summary:'في 12 أغسطس 1944 قُتل مدنيون في سانت آنا دي ستاتسيما والقرى المجاورة على يد قوات ألمانية من الإس إس مع متعاونين فاشيين. أصبح الموقع لاحقًا حديقة وطنية للسلام',question:'كيف يمكن لمكان مجزرة أن يعلّم السلام من دون محو ما حدث؟'},nl:{theme:'BURGERS',title:'Sant’Anna di Stazzema',place:'Toscane · Italië',summary:'Op 12 augustus 1944 werden burgers in Sant’Anna di Stazzema en omliggende gehuchten vermoord door Duitse SS-troepen met fascistische collaborateurs. De plek werd later een Nationaal Vredespark',question:'Hoe kan een plaats van massamoord vrede onderwijzen zonder uit te wissen wat er gebeurde?'}},
 deportation:{ar:{theme:'ترحيل',title:'آلة الترحيل',place:'أوروبا · 1942',summary:'يكشف أغسطس 1942 كيف يتحول الاضطهاد إلى لوجستيات: غيتوات ونقل وتنسيق إداري وترحيل. نستخدم ريمانوف ورادوم هنا كنوافذ موثقة لا كرمزين لكل التجارب',question:'متى تتحول البيروقراطية إلى مشاركة في العنف؟'},nl:{theme:'DEPORTATIE',title:'De machine van deportatie',place:'Europa · 1942',summary:'Augustus 1942 laat zien hoe vervolging logistiek wordt: getto’s, transporten, administratieve coördinatie en deportatie. Rymanów en Radom dienen hier als gedocumenteerde vensters, niet als symbool voor alle ervaringen',question:'Wanneer wordt bureaucratie deelname aan geweld?'}},
 kolbe:{ar:{theme:'تضحية',title:'ماكسيميليان كولبه',place:'أوشفيتز 1 · بولندا',summary:'تطوع كولبه ليأخذ مكان فرانتشيشك غايوفنيتشيك الذي اختير للموت جوعًا. قُتل كولبه بحقنة سامة في 14 أغسطس 1941 داخل المبنى 11',question:'كيف نحفظ نور التضحية من دون تحويل المعاناة إلى استعراض؟'},nl:{theme:'OPOFFERING',title:'Maximilian Kolbe',place:'Auschwitz I · Polen',summary:'Kolbe bood aan de plaats in te nemen van Franciszek Gajowniczek, die was uitgekozen om van honger te sterven. Kolbe werd op 14 augustus 1941 in Blok 11 met een gifinjectie gedood',question:'Hoe vertellen we over opoffering zonder lijden tot spektakel te maken?'}},
 indies:{id:{theme:'PERINGATAN',title:'15 Agustus — Breda mengenang',place:'Raffy · Breda · Belanda',summary:'Pada 15 Agustus 2026 peringatan Indië diadakan di Monumen Indië di taman Raffy, Breda, dengan tema Belajar memahami sejarah. Acara dimulai pukul 14.00 dan mencakup Raffykoor, Indisch Onze Vader, satu menit hening, pengibaran bendera, peletakan bunga dan defilé',question:'Bagaimana memori menjadi warisan hidup bagi generasi berikutnya tanpa menyederhanakan sejarah yang rumit?'},ar:{theme:'ذاكرة',title:'15 أغسطس — هولندا تتذكر',place:'بريدا · لاهاي · هولندا',summary:'تحيي هولندا ذكرى نهاية الحرب العالمية الثانية بالنسبة للمملكة وضحايا الحرب ضد اليابان والاحتلال الياباني لجزر الهند الشرقية الهولندية السابقة. ويضم النصب الهندي في لاهاي جرسًا برونزيًا للذاكرة',question:'كيف تصبح الذاكرة العامة شيئًا يرثه الجيل التالي بدل أن يكتفي بمشاهدته؟'},nl:{theme:'HERDENKING',title:'15 augustus — Nederland herdenkt',place:'Breda · Den Haag · Nederland',summary:'Nederland herdenkt het einde van de Tweede Wereldoorlog voor het Koninkrijk en de slachtoffers van de oorlog tegen Japan en de Japanse bezetting van voormalig Nederlands-Indië. Bij het Indisch Monument in Den Haag staat een bronzen herdenkingsklok',question:'Hoe wordt openbare herdenking iets dat een volgende generatie kan erven in plaats van alleen bekijken?'}},
 'roger-bialystok':{ar:{theme:'مقاومة / مصالحة',title:'الأخ روجيه · بياويستوك',place:'تيزيه / بياويستوك',summary:'نضع ذاكرتين منفصلتين جنبًا إلى جنب من دون دمجهما: المقاومة اليهودية المسلحة أثناء تصفية غيتو بياويستوك سنة 1943، وحياة الأخ روجيه من تيزيه الذي قُتل أثناء صلاة المساء في 16 أغسطس 2005 بعد حياة كرّسها للمصالحة والتضامن',question:'متى تتطلب حماية الحياة مقاومة، ومتى يتطلب الشفاء مصالحة؟'},nl:{theme:'VERZET / VERZOENING',title:'Broeder Roger · Białystok',place:'Taizé / Białystok',summary:'Twee verschillende herinneringen staan naast elkaar, zonder ze samen te voegen: het Joodse gewapende verzet tijdens de liquidatie van het getto van Białystok in 1943, en het leven van broeder Roger van Taizé, die op 16 augustus 2005 tijdens het avondgebed werd gedood na een leven van verzoening en solidariteit',question:'Wanneer vraagt bescherming van leven om verzet, en wanneer vraagt genezing om verzoening?'}},
 'name-truth':{ar:{theme:'هوية / حقيقة',title:'الاسم والكذبة',place:'ألمانيا / لندن',summary:'في 17 أغسطس 1938 فرضت ألمانيا النازية أسماء إضافية، «إسرائيل» على كثير من الرجال اليهود و«سارا» على كثير من النساء اليهوديات، كعلامة إدارية. وفي 17 أغسطس 1921 نشرت صحيفة التايمز تحقيق فيليب غريفز الذي كشف سرقة النصوص التي بُني عليها تزوير «البروتوكولات» المعادي لليهود',question:'كيف تسهّل التصنيفات الاضطهاد، وكيف يفكك التحقق الصارم من المصادر كذبةً مسلّحة؟'},nl:{theme:'IDENTITEIT / WAARHEID',title:'De naam en de leugen',place:'Duitsland / Londen',summary:'Op 17 augustus 1938 legde nazi-Duitsland extra namen op: Israel voor veel Joodse mannen en Sara voor veel Joodse vrouwen, als administratief kenmerk. Op 17 augustus 1921 publiceerde The Times Philip Graves’ onthulling van het plagiaat achter de antisemitische vervalsing van de Protocollen',question:'Hoe maken etiketten vervolging gemakkelijker, en wat doet grondige broncontrole met een bewapende leugen?'}}
};
const FIELD={
 ar:{visit:'زيارة',official:'رسمي',titles:{'Vught':'النصب الوطني كامب فوخت','Sant’Anna di Stazzema':'الذكرى 82 لمجزرة سانت آنا دي ستاتسيما','Oświęcim / Harmęże':'الذكرى 85 لوفاة ماكسيميليان كولبه','Breda':'إحياء ذكرى الهند الشرقية في رافي','Den Haag':'الذكرى الوطنية لـ15 أغسطس 1945','Bergen op Zoom':'إحياء ذكرى الهند الشرقية — الوعد'},notes:{
  '2026-08-11':'لم نجد فعالية سنوية خاصة منشورة؛ المتحف وأرض المعسكر السابق مفتوحان. تُعامل الزيارة كمحطة ذكرى موثقة',
  '2026-08-12':'قداس 08:30، أكاليل، مراسم رسمية عند النصب من 09:45، كلمات من 10:00، ومعرض ألوان من أجل السلام 11:30',
  '2026-08-14':'طقس تذكاري 08:00، مسيرات، زهور 10:00، قداس مركزي قرب المبنى 11 الساعة 10:30، وصلوات إضافية',
  'Breda':'تبدأ 14:00 ويُطلب الجلوس قبل 13:45؛ مرور تذكاري ووضع الزهور 15:30',
  'Den Haag':'يفتح الميدان 17:00؛ المراسم 18:45–20:00. مقاعد إضافية وفق أسبقية الوصول من دون تذكرة',
  'Bergen op Zoom':'ذكرى إقليمية مع شهادات أربعة أجيال وموسيقى ولقاء بعد المراسم'}},
 id:{visit:'kunjungan',official:'resmi',titles:{'Vught':'Monumen Nasional Kamp Vught','Sant’Anna di Stazzema':'Peringatan ke-82 pembantaian','Oświęcim / Harmęże':'Peringatan ke-85 wafat Maximilian Kolbe','Breda':'Peringatan Indië di Raffy','Den Haag':'Peringatan Nasional 15 Agustus 1945','Bergen op Zoom':'Peringatan Indië — De belofte'},notes:{'2026-08-11':'Tidak ditemukan acara peringatan tahunan khusus; museum dan bekas kamp terbuka. Perlakukan kunjungan sebagai titik memori terdokumentasi','2026-08-12':'Misa 08.30; peletakan karangan bunga; upacara resmi di Ossuary mulai 09.45; pidato mulai 10.00; Colors for Peace 11.30','2026-08-14':'Transitus 08.00; ziarah; bunga 10.00; misa utama dekat Blok 11 pukul 10.30; ibadat lanjutan','Breda':'Mulai 14.00; pengunjung diminta duduk pukul 13.45; defilé dan peletakan bunga pukul 15.30','Den Haag':'Area dibuka 17.00; upacara 18.45–20.00. Tempat duduk tambahan berdasarkan urutan kedatangan tanpa tiket','Bergen op Zoom':'Peringatan regional dengan kisah empat generasi, musik dan pertemuan setelah upacara'}},
 nl:{visit:'bezoek',official:'officieel',titles:{'Vught':'Nationaal Monument Kamp Vught','Sant’Anna di Stazzema':'82e herdenking van de massamoord','Oświęcim / Harmęże':'85e herdenking van de dood van Maximilian Kolbe','Breda':'Indië-herdenking bij Raffy','Den Haag':'Nationale Herdenking 15 augustus 1945','Bergen op Zoom':'Indië-herdenking — De belofte'},notes:{
  '2026-08-11':'Geen specifieke jaarlijkse Westerweel-herdenking gevonden; museum en voormalig kampterrein zijn open. Behandel het bezoek als een gedocumenteerde herdenkingsstop',
  '2026-08-12':'Mis 08:30; kranslegging; officiële ceremonie bij het Ossuarium vanaf 09:45; toespraken vanaf 10:00; Colors for Peace om 11:30',
  '2026-08-14':'Transitus 08:00; pelgrimstochten; bloemen 10:00; centrale mis bij Blok 11 om 10:30; verdere diensten later op de dag',
  'Breda':'Start 14:00; bezoekers worden gevraagd om 13:45 te zitten; defilé en bloemenlegging om 15:30',
  'Den Haag':'Veld open 17:00; ceremonie 18:45–20:00. Extra zitplaatsen op volgorde van aankomst, zonder ticket',
  'Bergen op Zoom':'Regionale herdenking met verhalen van vier generaties, muziek en ontmoeting na afloop'}}
};
function lang(){const l=localStorage.getItem('luxdot.lang')||document.documentElement.lang||'en';return ['ar','en','nl','id'].includes(l)?l:'en'}
function ui(){return UI[lang()]||UI.en}
function trNode(n){const z=I18N[n.id]?.[lang()];return z?{...n,...z}:n}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(d){try{return new Intl.DateTimeFormat(lang(),{weekday:'short',day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00'))}catch{return d}}
function translateHead(){titleEl.textContent=ui().title;leadEl.textContent=ui().lead}
function fieldNote(f){if(lang()==='en')return f.note;const x=FIELD[lang()];return x?.notes?.[f.city]||x?.notes?.[f.date]||f.note}
function fieldKind(f){if(lang()==='en')return String(f.kind||'').toUpperCase();return (FIELD[lang()]?.[f.kind]||f.kind||'').toUpperCase()}
function fieldTitle(f){if(lang()==='en')return f.title;return FIELD[lang()]?.titles?.[f.city]||f.title}

const TRAGEDY_IDS=new Set(['rufina-secunda','justa-rufina','edith-stein','lawrence-rome','westerweel','stazzema','deportation','kolbe','indies','roger-bialystok','name-truth']);
function tragedy(id){return TRAGEDY_IDS.has(id)}
function bloodMark(id){return tragedy(id)?'<i class="tragedy-mark" aria-hidden="true"></i>':''}
function openNode(id){const raw=DB?.nodes?.find(x=>x.id===id);if(!raw)return;const n=trNode(raw);D.innerHTML=`<article class="node-panel ${tragedy(n.id)?'has-tragedy':''}">${bloodMark(n.id)}<button class="closex" aria-label="${esc(lang()==='ar'?'إغلاق':lang()==='nl'?'Sluiten':'Close')}">×</button><div class="node-meta">${fmt(n.date)} / ${esc(n.theme)} / ${esc(lang()==='en'?n.status:ui().documented)}</div><h2>${esc(n.title)}</h2><div class="node-meta">${esc(n.place)}</div>${n.image?`<img src="${esc(n.image)}" alt="${esc(n.title)}" loading="lazy" referrerpolicy="no-referrer"><div class="credit">${esc(n.imageCredit||'')}</div>`:''}<p>${esc(n.summary)}</p>${n.dossier?`<div class="memory-dossier"><p>${esc(n.dossier)}</p></div>`:''}${n.page?`<div class="memory-dossier-link"><a href="${esc(n.page)}">${esc(lang()==='ar'?'فتح ملف الذاكرة الكامل':lang()==='nl'?'Open volledig geheugendossier':'Open full memory dossier')} →</a></div>`:''}<p class="question">${esc(n.question)}</p><div class="link-row">${[...(n.sources||[]),...(n.media||[])].map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('')}</div></article>`;D.classList.add('on');D.setAttribute('aria-hidden','false');D.querySelector('.closex')?.addEventListener('click',close)}
function close(){D.classList.remove('on');D.setAttribute('aria-hidden','true')}
D.addEventListener('click',e=>{if(e.target===D)close()});addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function tree(){
 const nodes=(DB.nodes||[]).map(trNode);
 const left=nodes.filter((_,i)=>i%2===0), right=nodes.filter((_,i)=>i%2===1);
 const positions={};
 const distribute=(arr,side)=>arr.forEach((n,i)=>{
   const count=Math.max(arr.length,1);
   const y=12+(i+1)*(74/(count+1));
   const tier=i%3;
   const x=side==='left'?(24-tier*2):(76+tier*2);
   positions[n.id]=[x,y];
 });
 distribute(left,'left');distribute(right,'right');
 const branchPath=n=>{
   const [x,y]=positions[n.id]; const side=x<50?-1:1;
   const trunkX=50+side*(2.8+Math.abs(y-50)*.025);
   const elbow1=50+side*8.5, elbow2=x-side*5.2;
   return `M50,86 L50,${Math.max(49,Math.min(65,y+8))} L${trunkX},${Math.max(44,Math.min(68,y+5))} L${elbow1},${y} L${elbow2},${y} L${x},${y}`;
 };
 const roots=[
  'M50,86 L50,91 L43,97 L38,97','M50,86 L50,92 L46,99 L42,99','M50,86 L50,93 L49,100',
  'M50,86 L50,93 L51,100','M50,86 L50,92 L54,99 L58,99','M50,86 L50,91 L57,97 L62,97'
 ];
 const minorRoots=[36,40,44,47,53,56,60,64].map((x,i)=>`M50,88 L${50+(x<50?-1:1)*(2+i%3)},${93+i%2} L${x},100`);
 const defs=`<defs>
   <linearGradient id="treeTrunkGradient" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#5b3a20"/><stop offset=".42" stop-color="#8b6f35"/><stop offset=".72" stop-color="#a88938"/><stop offset="1" stop-color="#6f9d49"/></linearGradient>
   <filter id="treeGlow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation=".45" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
  </defs>`;
 V.innerHTML=`<div class="memory-circuit-tree" role="img" aria-label="شجرة أطلس الذاكرة">
   <svg class="memory-circuit-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${defs}
    <path class="circuit-trunk" d="M50,87 L50,15"/>
    <path class="circuit-trunk-core" d="M49.25,87 L49.25,18 M50.75,87 L50.75,18"/>
    ${roots.concat(minorRoots).map(d=>`<path class="circuit-root" d="${d}"/>`).join('')}
    ${nodes.map(n=>`<path class="circuit-branch" d="${branchPath(n)}"/><path class="circuit-pulse" d="${branchPath(n)}"/>`).join('')}
   </svg>
   <div class="tree-heart" aria-hidden="true"><span>✦</span></div>
   ${nodes.map(n=>{const [x,y]=positions[n.id];const img=n.image||'assets/thumbs-png/event.png';return `<button class="memory-circuit-node ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}" style="left:${x}%;top:${y}%"><span class="circuit-port" aria-hidden="true"></span><span class="node-thumb"><img src="${esc(img)}" alt="" loading="lazy" onerror="this.style.display='none'"></span><span class="node-copy"><b>${esc(n.title)}</b><small>${fmt(n.date)} · ${esc(n.theme)}</small></span></button>`}).join('')}
   <div class="tree-caption">كل ذاكرة غصن من شجرة واحدة، والجذور تحفظ ما لا ينبغي أن يُنسى</div>
  </div>`;
 bindNodes();
}
function timeline(){V.innerHTML=`<div class="timeline">${(DB.nodes||[]).map(trNode).map(n=>`<article class="time-row ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}">${bloodMark(n.id)}<div class="time-date">${fmt(n.date)}</div><div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p></div></article>`).join('')}</div>`;bindNodes()}
function map(){
 const nodes=(DB.nodes||[]).filter(n=>Number.isFinite(n.lat)&&Number.isFinite(n.lon)).map(trNode);
 V.innerHTML=`<div class="map-wrap"><div id="memoryLeafletMap" aria-label="خريطة جغرافية لأطلس الذاكرة"></div><div class="map-list">${nodes.map(n=>`<article class="map-card ${tragedy(n.id)?'has-tragedy':''}" data-id="${esc(n.id)}">${bloodMark(n.id)}<b>${esc(n.title)}</b><small>${esc(n.place)} · ${fmt(n.date)}</small></article>`).join('')}</div></div>`;bindNodes();
 if(!window.L){document.getElementById('memoryLeafletMap').innerHTML='<div class="status">تعذر تحميل خادم الخريطة. تبقى بيانات الأطلس متاحة في القائمة والشجرة</div>';return}
 const m=L.map('memoryLeafletMap',{zoomControl:true,worldCopyJump:true}).setView([50.6,8.0],4);
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m);
 const icon=L.divIcon({className:'lux-pin-wrap',html:'<span class="lux-map-pin"><span class="lux-map-pin-core"></span></span>',iconSize:[30,42],iconAnchor:[15,39],popupAnchor:[0,-38],tooltipAnchor:[0,-34]});
 const group=[];nodes.forEach(n=>{const mk=L.marker([n.lat,n.lon],{icon}).addTo(m);mk.bindTooltip(esc(n.title),{direction:'top'});mk.on('click',()=>openNode(n.id));group.push(mk)});if(group.length){const fg=L.featureGroup(group);m.fitBounds(fg.getBounds().pad(.22),{maxZoom:6})}
}
function field(){V.innerHTML=`<div class="field-grid">${(DB.field||[]).map(f=>`<article class="field-card"><span class="badge">${fmt(f.date)} / ${esc(fieldKind(f))}</span><b>${esc(fieldTitle(f))}</b><small>${esc(f.city)} · ${esc(f.time)}<br>${esc(f.address)}<br><br>${esc(fieldNote(f))}</small></article>`).join('')}</div>`}
function sources(){let all=[];(DB.nodes||[]).forEach(raw=>{const n=trNode(raw);(n.sources||[]).forEach(s=>all.push({...s,node:n.title,date:n.date}))});V.innerHTML=`<div class="source-grid">${all.map(s=>`<article class="source-card"><small>${fmt(s.date)} · ${esc(s.node)}</small><br><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a></article>`).join('')}</div>`}
function bindNodes(){V.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>openNode(el.dataset.id)))}
function render(){if(!DB)return;({tree,timeline,map,field,sources}[view]||tree)()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('on',x===b));render()}));
document.addEventListener('luxlang',()=>{translateHead();render()});
function boot(){translateHead();V.innerHTML=`<div class="status">${esc(ui().loading)}</div>`;if(window.LUXDOT_MEMORY_DB&&Array.isArray(window.LUXDOT_MEMORY_DB.nodes)){DB=window.LUXDOT_MEMORY_DB;render();return}console.error('LuxDot Memory: embedded dataset missing');V.innerHTML=`<div class="status">${esc(ui().error)}</div>`}
boot();
})();