(()=>{"use strict";let DB=null,view='tree';const V=document.getElementById('memoryView'),D=document.getElementById('nodeDialog');
const UI={en:['Memory is not a list of dates','A living atlas of people, places, crimes, rescue, resistance and reconciliation — sourced, versioned and open to correction'],ar:['الذاكرة ليست قائمة تواريخ','أطلس حي للأشخاص والأماكن والجرائم والإنقاذ والمقاومة والمصالحة — موثّق، مؤرشف بالإصدارات، وقابل للتصحيح'],nl:['Herinnering is geen lijst met data','Een levende atlas van mensen, plaatsen, misdaden, redding, verzet en verzoening — met bronnen, versies en ruimte voor correctie'],es:['La memoria no es una lista de fechas','Un atlas vivo de personas, lugares, crímenes, rescate, resistencia y reconciliación — con fuentes, versiones y abierto a corrección'],he:['זיכרון אינו רשימת תאריכים','אטלס חי של אנשים, מקומות, פשעים, הצלה, התנגדות ופיוס — מתועד, בגרסאות ופתוח לתיקון']};
function lang(){return localStorage.getItem('luxdot.lang')||'en'}function translateHead(){let a=UI[lang()]||UI.en;memTitle.textContent=a[0];memLead.textContent=a[1]}
function escape(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(d){return new Intl.DateTimeFormat(lang(),{weekday:'short',day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00'))}
function openNode(id){const n=DB.nodes.find(x=>x.id===id);if(!n)return;D.innerHTML=`<article class="node-panel"><button class="closex" aria-label="Close">×</button><div class="node-meta">${fmt(n.date)} / ${escape(n.theme)} / ${escape(n.status)}</div><h2>${escape(n.title)}</h2><div class="node-meta">${escape(n.place)}</div>${n.image?`<img src="${n.image}" alt="${escape(n.title)}" loading="lazy"><div class="credit">${escape(n.imageCredit||'')}</div>`:''}<p>${escape(n.summary)}</p><p class="question">${escape(n.question)}</p><div class="link-row">${[...(n.sources||[]),...(n.media||[])].map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${escape(s.label)} ↗</a>`).join('')}</div></article>`;D.classList.add('on');D.setAttribute('aria-hidden','false');D.querySelector('.closex').onclick=close}function close(){D.classList.remove('on');D.setAttribute('aria-hidden','true')}D.onclick=e=>{if(e.target===D)close()};addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function tree(){const pts=[[50,15],[77,27],[84,56],[66,80],[34,80],[16,57],[23,28]];V.innerHTML=`<div class="tree-stage"><svg class="tree-lines" viewBox="0 0 100 100" preserveAspectRatio="none">${pts.map(p=>`<line x1="50" y1="50" x2="${p[0]}" y2="${p[1]}" stroke="rgba(125,255,174,.18)" stroke-width=".15"/>`).join('')}<circle cx="50" cy="50" r="24" fill="none" stroke="rgba(210,177,91,.12)" stroke-width=".12" stroke-dasharray="1 2"/></svg><div class="tree-center">LIVING<br>MEMORY</div>${DB.nodes.map((n,i)=>`<button class="memory-node" data-id="${n.id}" style="left:${pts[i][0]}%;top:${pts[i][1]}%"><time>${fmt(n.date)}</time><b>${escape(n.title)}</b><small>${escape(n.theme)}</small></button>`).join('')}</div>`;V.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openNode(b.dataset.id))}
function timeline(){V.innerHTML=`<div class="timeline">${DB.nodes.map(n=>`<article class="time-row" data-id="${n.id}"><div class="time-date">${fmt(n.date)}</div><div><h3>${escape(n.title)}</h3><p>${escape(n.summary)}</p></div></article>`).join('')}</div>`;V.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openNode(b.dataset.id))}
function map(){const bounds={minLat:40,maxLat:55,minLon:-3,maxLon:25};function pos(n){let x=(n.lon-bounds.minLon)/(bounds.maxLon-bounds.minLon)*84+8,y=(bounds.maxLat-n.lat)/(bounds.maxLat-bounds.minLat)*78+11;return[x,y]}V.innerHTML=`<div class="map-wrap"><div class="map-canvas"><svg class="europe" viewBox="0 0 400 300"><path d="M36 71L78 45l46 14 35-27 41 18 25-12 48 22 15 39 48 25 16 48-36 25-9 41-44 6-31-21-31 14-38-24-40-3-22-34-31-11-17-36z" fill="none" stroke="rgba(125,255,174,.5)" stroke-width="2"/><path d="M143 214l26 25-8 43-22 8-17-33zM206 216l25 17 4 50-17 7-17-38z" fill="none" stroke="rgba(125,255,174,.4)"/></svg>${DB.nodes.map(n=>{let p=pos(n);return`<button title="${escape(n.title)}" data-id="${n.id}" class="map-dot" style="left:${p[0]}%;top:${p[1]}%"><span class="map-label">${escape(n.title)}</span></button>`}).join('')}</div><div class="map-list">${DB.nodes.map(n=>`<article class="map-card"><b>${escape(n.title)}</b><small>${escape(n.place)} · ${fmt(n.date)}</small></article>`).join('')}</div></div>`;V.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openNode(b.dataset.id))}
function field(){V.innerHTML=`<div class="field-grid">${DB.field.map(f=>`<article class="field-card"><span class="badge">${fmt(f.date)} / ${f.kind.toUpperCase()}</span><b>${escape(f.title)}</b><small>${escape(f.city)} · ${escape(f.time)}<br>${escape(f.address)}<br><br>${escape(f.note)}</small></article>`).join('')}</div>`}
function sources(){let all=[];DB.nodes.forEach(n=>(n.sources||[]).forEach(s=>all.push({...s,node:n.title,date:n.date})));V.innerHTML=`<div class="source-grid">${all.map(s=>`<article class="source-card"><small>${fmt(s.date)} · ${escape(s.node)}</small><br><a href="${s.url}" target="_blank" rel="noopener">${escape(s.label)} ↗</a></article>`).join('')}</div>`}
function render(){({tree,timeline,map,field,sources}[view]||tree)()}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('on',x===b));render()});document.addEventListener('luxlang',()=>{translateHead();render()});
fetch('data/memory-atlas.json').then(r=>r.json()).then(j=>{DB=j;translateHead();render()}).catch(()=>{V.innerHTML='<div class="status">Memory dataset could not be loaded</div>'});})();