window.LUXDOT_MEMORY_DB = {
  meta:{version:'2026.08.28-memory-september-4.18.53',range:'2026-07-10/2026-09-30',principle:'الوثيقة أولاً، ثم التفسير. الدليل المضاد يبقى ظاهراً دائماً.'},
  nodes:[
    {id:'rufina-secunda',date:'2026-07-10',theme:'الاستشهاد • التقليد',title:'روفينا وسيكوندا (Rufina & Secunda)',place:'روما • طريق كورنيليا (Via Cornelia)',lat:41.9028,lon:12.4964,status:'documented-tradition',summary:'يحيي التقليد المسيحي ذكرى القديستين روفينا وسيكوندا في 10 يوليو، مع فصل قدم التذكار عن التفاصيل السردية اللاحقة.',question:'كيف نكرّم تقليداً قديماً مع إظهار حدود اليقين التاريخي؟',sources:[{label:'Vatican State — Saints Rufina and Secunda',url:'https://www.vaticanstate.va/en/state-and-government/general-informations/saint-of-the-day/2254-july-10-saints-rufina-and-secunda-martyrs.html'}]},
    {id:'justa-rufina',date:'2026-07-17',theme:'الاستشهاد • الذاكرة',title:'يوستا وروفينا الإشبيليتان (Justa & Rufina)',place:'إشبيلية • إسبانيا',lat:37.3891,lon:-5.9845,status:'documented-tradition',summary:'ذاكرة مسيحية قديمة ارتبطت بإشبيلية والفن والحرف، مع فصل العبادة القديمة عن التفاصيل المتأخرة.',question:'كيف نحفظ الذاكرة الفنية والدينية مع إظهار حدود الوثيقة؟',sources:[]},
    {id:'edith-stein',date:'2026-08-09',theme:'التعاطف • الكرامة • الحقيقة',title:'إديث شتاين • تريزا بندكتا للصليب (Edith Stein)',place:'أوروبا → أوشفيتز–بيركيناو',lat:50.0359,lon:19.1783,status:'documented',summary:'فيلسوفة ألمانية يهودية الأصل، راهبة كاثوليكية لاحقاً، قُتلت في أوشفيتز في 9 أغسطس 1942.',question:'كيف يتحول إدراك الآخر بوصفه إنساناً إلى مسؤولية؟',page:'edith-stein.html?v=2.9.8',sources:[]},
    {id:'lawrence-rome',date:'2026-08-10',theme:'الخدمة • المستضعفون',title:'لورنس الروماني (Saint Lawrence)',place:'روما • إيطاليا',lat:41.9028,lon:12.4964,status:'documented-tradition',summary:'تذكار شماس روما الذي ارتبطت ذاكرته بخدمة الفقراء والمستضعفين.',question:'ما الذي يجب أن تحميه المؤسسات أولاً؟',sources:[]},
    {id:'westerweel',date:'2026-08-11',theme:'الإنقاذ',title:'يوب فيسترفيل (Joop Westerweel)',place:'معسكر فوخت • هولندا',lat:51.665,lon:5.258,status:'documented',summary:'معلّم ومقاوم هولندي ساعد يهوداً على الاختباء والهروب وأُعدم في 11 أغسطس 1944.',question:'ماذا تتطلب الحماية عندما يكون الصمت أكثر أماناً؟',page:'westerweel-memory.html?v=4.3.42',sources:[]},
    {id:'stazzema',date:'2026-08-12',theme:'المدنيون',title:'سانت آنا دي ستاتزيما',place:'توسكانا • إيطاليا',lat:43.972,lon:10.273,status:'documented',summary:'ذاكرة مذبحة المدنيين في 12 أغسطس 1944 وموقع تحول لاحقاً إلى مساحة للسلام.',question:'كيف يتحول مكان المجزرة إلى مكان للتعلم والسلام؟',sources:[]},
    {id:'totalitarian-victims',date:'2026-08-23',theme:'سلطة • ضحايا • حدود',title:'23 أغسطس — ضحايا الأنظمة الشمولية والاستبدادية',place:'أوروبا',status:'documented',summary:'ذاكرة أوروبية لضحايا الأنظمة الشمولية والاستبدادية مرتبطة بتاريخ 23 أغسطس 1939.',question:'كيف ندين القمع بمعيار كرامة الإنسان من دون تسطيح اختلاف السياقات؟',page:'totalitarian-victims-memory.html?v=4.3.89',sources:[]},
    {id:'st-bartholomew',date:'2026-08-24',theme:'حروب دينية • مدنيون',title:'24 أغسطس — مجزرة سان بارتيليمي',place:'باريس • فرنسا',lat:48.8566,lon:2.3522,status:'documented',summary:'في 24 أغسطس 1572 انفجرت موجة قتل واسعة للهوغونوت في باريس ثم امتدت إلى مدن أخرى.',question:'متى تتحول الهوية الدينية والسياسة والخوف إلى إذن بقتل الجار؟',page:'st-bartholomew-memory.html?v=4.3.89',sources:[]},

    {id:'nuclear-tests-2026',date:'2026-08-29',theme:'إنسان • سلام • علم',title:'29 أغسطس — مناهضة التجارب النووية',place:'العالم',status:'documented',summary:'اليوم الدولي لمناهضة التجارب النووية يذكّر بأن التقدم العلمي لا ينفصل عن المسؤولية تجاه الإنسان والبيئة.',question:'كيف نحافظ على المعرفة العلمية من دون فصلها عن مسؤولية نتائج استخدامها؟',sources:[{label:'United Nations — International Day against Nuclear Tests',url:'https://www.un.org/en/observances/end-nuclear-tests-day'}]},
    {id:'enforced-disappearances-2026',date:'2026-08-30',theme:'إنسان • ذاكرة • حقوق',title:'30 أغسطس — ضحايا الاختفاء القسري',place:'العالم',status:'documented',summary:'يضع اليوم الدولي لضحايا الاختفاء القسري الضحايا وعائلاتهم وحقهم في الحقيقة والعدالة والجبر في مركز الذاكرة.',question:'ماذا يحدث للذاكرة عندما يُحرم أهل المفقود حتى من معرفة مصيره؟',sources:[{label:'United Nations — Victims of Enforced Disappearances',url:'https://www.un.org/en/observances/victims-enforced-disappearance/'}]},
    {id:'african-descent-2026',date:'2026-08-31',theme:'إنسان • كرامة • ذاكرة',title:'31 أغسطس — الشعوب المنحدرة من أصل أفريقي',place:'العالم',status:'documented',summary:'محطة تربط الكرامة المعاصرة بالذاكرة الطويلة للعبودية والاستعمار والعنصرية ومقاومتها.',question:'كيف تتحول ذاكرة الظلم التاريخي إلى التزام حي بالمساواة؟',sources:[{label:'United Nations — International Day for People of African Descent',url:'https://www.un.org/en/observances/african-descent-day'}]},
    {id:'season-creation-2026',date:'2026-09-01',theme:'إيمان • أرض • ماء',title:'1 سبتمبر — بداية موسم الخليقة 2026',place:'العالم • تقليد مسيحي مسكوني',status:'documented-tradition',summary:'يمتد موسم الخليقة من 1 سبتمبر إلى 4 أكتوبر. موضوع 2026 هو «الماء الحي»، مستلهماً حزقيال 47، ويربط العناية بالخليقة بتجدد المياه والأرض ورفاه الإنسان.',question:'ماذا يعني أن نتعامل مع الماء والأرض كأمانة مشتركة لا كمورد بلا ذاكرة؟',sources:[{label:'Church of England — Season of Creation 2026',url:'https://www.churchofengland.org/about/environment-and-climate-change/season-creation'},{label:'USCCB — Season of Creation',url:'https://www.usccb.org/sjp/season-creation'}]},
    {id:'charity-2026',date:'2026-09-05',theme:'إنسان • عطاء • خدمة',title:'5 سبتمبر — اليوم الدولي للعمل الخيري',place:'العالم',status:'documented',summary:'محطة للعطاء بوصفه ممارسة تحفظ الكرامة وتربط الإنسان بالإنسان، لا مجرد تحويل للمال.',question:'متى يصبح العطاء أثراً مستمراً بدلاً من فعل عابر؟',sources:[{label:'United Nations — International Day of Charity',url:'https://www.un.org/en/observances/charity-day'}]},
    {id:'clean-air-2026',date:'2026-09-07',theme:'أرض • صحة • مسؤولية',title:'7 سبتمبر — هواء نقي لسماء زرقاء',place:'العالم',status:'documented',summary:'اليوم الدولي لنقاوة الهواء يربط البيئة مباشرة بالصحة والعدالة والمسؤولية المشتركة.',question:'كيف نجعل ما لا نراه — الهواء — جزءاً من أخلاقنا اليومية؟',sources:[{label:'United Nations — International Day of Clean Air for blue skies',url:'https://www.un.org/en/observances/clean-air-day'}]},
    {id:'literacy-2026',date:'2026-09-08',theme:'معرفة • كتاب • كرامة',title:'8 سبتمبر — اليوم الدولي لمحو الأمية',place:'العالم',status:'documented',summary:'القراءة والكتابة ليستا مهارتين فقط؛ إنهما باب للمشاركة والذاكرة والوصول إلى المعرفة.',question:'كيف يصبح الكتاب أداة لتحرير المعرفة وتداولها بين الأجيال؟',sources:[{label:'UNESCO — International Literacy Day',url:'https://www.unesco.org/en/days/literacy'}]},
    {id:'protect-education-2026',date:'2026-09-09',theme:'معرفة • أطفال • حماية',title:'9 سبتمبر — حماية التعليم من الهجمات',place:'العالم',status:'documented',summary:'محطة تذكّر بأن المدرسة والجامعة والمعلم والطالب يجب ألا يتحولوا إلى أهداف في النزاعات.',question:'كيف نحمي حق الإنسان في التعلّم عندما يصبح المكان التعليمي نفسه معرضاً للعنف؟',sources:[{label:'United Nations — Protect Education from Attack',url:'https://www.un.org/en/observances/protect-education-day'}]},
    {id:'suicide-prevention-2026',date:'2026-09-10',theme:'إنسان • إصغاء • وقاية',title:'10 سبتمبر — الوقاية من الانتحار',place:'العالم',status:'documented',summary:'موضوع 2024–2026 هو «تغيير السرد حول الانتحار»، مع دعوة إلى كسر الوصمة وفتح محادثات داعمة والوصول إلى المساعدة.',question:'كيف يمكن للإصغاء والمحادثة والرعاية أن تحوّل الصمت إلى فرصة لطلب المساعدة؟',sources:[{label:'WHO — World Suicide Prevention Day 2026',url:'https://www.who.int/campaigns/world-suicide-prevention-day/2026'}]},
    {id:'rosh-hashanah-5787',date:'2026-09-11',theme:'إيمان • تجدد • محاسبة',title:'11–13 سبتمبر — رأس السنة العبرية 5787',place:'العالم اليهودي',status:'documented-tradition',summary:'يبدأ رأس السنة العبرية عند غروب الجمعة 11 سبتمبر وينتهي ليل الأحد 13 سبتمبر. يرتبط بالتجدد وبداية أيام التوبة في التقليد اليهودي.',question:'كيف يمكن لبداية سنة جديدة أن تكون أيضاً مراجعة لما مضى؟',sources:[{label:'Hebcal — Rosh Hashana 2026',url:'https://www.hebcal.com/holidays/rosh-hashana-2026'}]},
    {id:'democracy-2026',date:'2026-09-15',theme:'إنسان • مشاركة • مؤسسات',title:'15 سبتمبر — اليوم الدولي للديمقراطية',place:'العالم',status:'documented',summary:'محطة للتفكير في المشاركة والمساءلة والمؤسسات التي تتيح للناس التأثير في القرارات التي تمس حياتهم.',question:'كيف تبقى المؤسسات خادمة للإنسان وقابلة للمساءلة؟',sources:[{label:'United Nations — International Day of Democracy',url:'https://www.un.org/en/observances/democracy-day'}]},
    {id:'ozone-2026',date:'2026-09-16',theme:'أرض • علم • تعاون',title:'16 سبتمبر — حماية طبقة الأوزون',place:'العالم',status:'documented',summary:'ذاكرة نجاح نسبي للتعاون الدولي بين العلم والسياسة في مواجهة خطر بيئي عالمي.',question:'ما الذي نتعلمه عندما تتحول المعرفة العلمية إلى تعاون دولي قابل للقياس؟',sources:[{label:'United Nations — Ozone Day',url:'https://www.un.org/en/observances/ozone-day'}]},
    {id:'equal-pay-2026',date:'2026-09-18',theme:'إنسان • عدالة • عمل',title:'18 سبتمبر — المساواة في الأجر',place:'العالم',status:'documented',summary:'اليوم الدولي للمساواة في الأجر يضع قيمة العمل والعدالة وعدم التمييز في صلب الذاكرة الاجتماعية.',question:'كيف نقيس العدالة حين يؤدي الناس عملاً متساوي القيمة؟',sources:[{label:'United Nations — International Equal Pay Day',url:'https://www.un.org/en/observances/equal-pay-day'}]},
    {id:'yom-kippur-peace-2026',date:'2026-09-21',theme:'إيمان • سلام • مصالحة',title:'21 سبتمبر — يوم الغفران واليوم الدولي للسلام',place:'العالم',status:'documented-tradition',summary:'ينتهي يوم الغفران اليهودي ليل 21 سبتمبر بعد أن يبدأ عند غروب 20 سبتمبر، وفي 21 سبتمبر أيضاً اليوم الدولي للسلام. نعرضهما كتزامن تقويمي موثق، لا كعلاقة سببية.',question:'كيف يلتقي إصلاح العلاقة مع الذات والآخر مع السعي إلى سلام أوسع؟',sources:[{label:'Hebcal — Yom Kippur 2026',url:'https://www.hebcal.com/holidays/yom-kippur'},{label:'United Nations — International Day of Peace',url:'https://www.un.org/en/observances/international-day-peace'}]},
    {id:'sign-languages-2026',date:'2026-09-23',theme:'إنسان • تواصل • لغة',title:'23 سبتمبر — اليوم الدولي للغات الإشارة',place:'العالم',status:'documented',summary:'التواصل الإنساني أوسع من الصوت والكلمة المكتوبة؛ لغات الإشارة لغات كاملة تحمل معرفة وهوية وذاكرة.',question:'كيف نصمم المعرفة بحيث لا يصبح شكل التواصل حاجزاً أمام المشاركة؟',sources:[{label:'United Nations — International Day of Sign Languages',url:'https://www.un.org/en/observances/sign-languages-day'}]},
    {id:'sukkot-5787',date:'2026-09-25',theme:'إيمان • رحلة • ضيافة',title:'25 سبتمبر — بداية عيد المظال 5787',place:'العالم اليهودي',status:'documented-tradition',summary:'يبدأ عيد المظال عند غروب الجمعة 25 سبتمبر، ويوافق يومه الأول السبت 26 سبتمبر. يرتبط في التقليد اليهودي بالمظال المؤقتة والحصاد وذكرى رحلة بني إسرائيل في البرية.',question:'ماذا يعلّم السكن المؤقت عن الأمان والرحلة والضيافة؟',sources:[{label:'Hebcal — Sukkot 2026',url:'https://www.hebcal.com/holidays/sukkot-2026'}]},
    {id:'nuclear-elimination-2026',date:'2026-09-26',theme:'إنسان • سلام • مسؤولية',title:'26 سبتمبر — الإزالة الكاملة للأسلحة النووية',place:'العالم',status:'documented',summary:'تغلق هذه المحطة قوساً بدأ في 29 أغسطس بمناهضة التجارب النووية: من ذاكرة الاختبار إلى سؤال نزع السلاح.',question:'كيف تتحول ذاكرة الخطر النووي إلى التزام سياسي وأخلاقي طويل الأمد؟',sources:[{label:'United Nations — Total Elimination of Nuclear Weapons',url:'https://www.un.org/en/observances/nuclear-weapons-elimination-day'}]},
    {id:'tourism-memory-2026',date:'2026-09-27',theme:'مكان • زيارة • ذاكرة',title:'27 سبتمبر — يوم السياحة العالمي',place:'العالم',status:'documented',summary:'نقرأ السفر هنا من زاوية المكان والزيارة واللقاء والذاكرة، لا من زاوية الاستهلاك وحده.',question:'متى تتحول زيارة المكان من مرور سريع إلى معرفة واحترام لذاكرته؟',sources:[{label:'United Nations — World Tourism Day',url:'https://www.un.org/en/observances/tourism-day'}]},
    {id:'access-information-2026',date:'2026-09-28',theme:'معرفة • شفافية • حق',title:'28 سبتمبر — الحق في الوصول إلى المعلومات',place:'العالم',status:'documented',summary:'الوصول إلى المعلومات شرط للمساءلة والبحث والمشاركة الواعية، وهو قريب من فكرة المعرفة العامة المفتوحة.',question:'ما قيمة المعرفة إذا تعذر على الناس الوصول إلى الأدلة التي تؤثر في حياتهم؟',sources:[{label:'United Nations — Universal Access to Information',url:'https://www.un.org/en/observances/information-access-day'}]},
    {id:'food-loss-2026',date:'2026-09-29',theme:'أرض • غذاء • كرامة',title:'29 سبتمبر — التوعية بفقد وهدر الغذاء',place:'العالم',status:'documented',summary:'محطة تربط كرامة الطعام بالموارد والعمل والبيئة وبالتفاوت في الوصول إلى الغذاء.',question:'كيف نعيد رؤية الطعام بوصفه ثمرة موارد وعمل ومسؤولية مشتركة؟',sources:[{label:'United Nations — Food Loss and Waste',url:'https://www.un.org/en/observances/end-food-waste-day'}]},
    {id:'translation-2026',date:'2026-09-30',theme:'معرفة • لغة • جسور',title:'30 سبتمبر — اليوم الدولي للترجمة',place:'العالم',status:'documented',summary:'تختم الذاكرة الحية شهر سبتمبر بالترجمة: نقل المعنى بين اللغات مع احترام الاختلاف والسياق، لا استبدال الكلمات آلياً.',question:'كيف نعبر بالمعنى من لغة إلى أخرى من دون أن نفقد صوت صاحبه أو سياقه؟',sources:[{label:'United Nations — International Translation Day',url:'https://www.un.org/en/observances/international-translation-day'}]}
  ],
  field:[
    {date:'2026-08-11',city:'Vught',title:'Nationaal Monument Kamp Vught',kind:'visit',note:'محطة ذاكرة موثقة.'},
    {date:'2026-08-15',city:'Breda',title:'Indië commemoration at Raffy',kind:'official',note:'إحياء إقليمي.'}
  ]
};
