(()=>{
const EN=`<section class="hero"><div class="kicker">LUXDOT · LIVING FILM RESEARCH · 18 AUG 2026</div><h1>Reiderland: the drowned land and a film still being made</h1><p class="lead">A living dossier separating the documented history of <b>Reiderland / Rheiderland</b>, the memory of villages lost to the Dollard, legends of pride, bells and treasure, and the cinematic fiction of <b>Reiderland</b>. Similarity is not evidence: every layer carries its own confidence level.</p><span class="badge">Living research</span><span class="badge">Netherlands × Germany</span><span class="badge">Film in production</span><span class="badge">Memory of place</span></section>
<section class="card film-focus"><span class="fresh">LIVE · last checked 18 August 2026</span><h2>The film and its makers inside the research</h2><p class="welcome">This node studies <b>Reiderland</b> while it is still being made. The film is therefore part of the research itself: who writes it, who shapes its images, who embodies its memory, and how historical and legendary research becomes cinema. The official site identifies <b>Henk and Thomas Hiensch</b> as writers/directors with a sustained interest in history, art, myth and storytelling.</p><div class="people"><div class="person official"><b>Henk Hiensch</b><span class="role">Writer & director · Reiderland</span><p>Co-writer and co-director; the project grows from family ties to Friesland and an interest in history, art and narrative.</p></div><div class="person official"><b>Thomas Hiensch</b><span class="role">Writer & director · Reiderland</span><p>Co-writer and co-director. The brothers describe the production as collaborative filmmaking built through local relationships and participation.</p></div><div class="person"><b>Kees van Wanrooij</b><span class="role">Professor Puttkamer</span><p>Storyteller playing the sympathetic professor with prior knowledge of the treasures of Magna Frisia. He has his own LuxDot node and forms a direct bridge between story, research and film.</p></div><div class="person"><b>Anton van den Heuvel</b><span class="role">King Poppo</span><p>Selected in 2026 to portray Poppo, bringing the historical figure and his modern cinematic image into one traceable research point.</p></div></div><p class="small">People are included only for their publicly documented roles; no personal views or intentions are inferred.</p></section>
<section class="grid"><article class="card"><h2>Central question</h2><p>What remains when villages, churches and roads disappear from the surface, but their names, maps and legends remain? How can a contemporary film turn that memory into adventure without confusing legend with history?</p></article><article class="card"><h2>LuxDot rule</h2><p><b>Documented evidence first.</b> A treasure, curse or crown story does not prove the object or event. But the existence, transmission and social role of the story are themselves researchable facts.</p></article></section>
<section class="card"><h2>1 · The region before the film</h2><p>Reiderland was a historical Frisian region spanning parts of present-day northeastern Groningen and East Frisia. From the late Middle Ages the landscape changed radically as the sea broke through and the Dollard expanded. Current regional scholarship treats this as a long process of floods and land loss, with a major blow in 1509 followed by centuries of reclamation.</p><div class="status"><div class="A"><b>A · strong</b><br>Historical Reiderland and lost settlements.</div><div class="B"><b>B · good</b><br>General flood and reclamation sequence.</div><div class="C"><b>C · tradition</b><br>Underwater bells, curses and punishment tales.</div><div class="E"><b>E · open</b><br>Unverified treasure or crown locations.</div></div></section>
<section class="map"><img src="assets/reiderland-map-1842.jpg" alt="Historical map of drowned Dollard villages"><div class="caption">Later historical map of the memory of drowned Dollard villages. Visual source: De Verhalen van Groningen. Used as a document of place-memory, not as a precise map of the moment of inundation.</div></section>
<section class="grid"><article class="card"><h2>2 · Villages and memory</h2><p>Local sources describe dozens of lost or abandoned settlements. Older lists sometimes inflate totals or repeat uncertain names, so this dossier distinguishes documented settlements from transmitted names. Reiderwolde has a special place in both memory and the film.</p></article><article class="card"><h2>3 · Legend</h2><p>Folklore includes excessive wealth and pride, bells heard from below the water, and in some versions a sea-woman who curses the place. This is <b>folk memory</b>, not a geological explanation.</p></article><article class="card"><h2>4 · Poppo and 734</h2><p>Poppo/Bubo is associated with Frisian resistance to the Franks and with the Battle of the Boarn in 734. Calling him a king or connecting him to a Reiderland crown requires separation: the film builds its own adventure from a historical nucleus.</p></article></section>
<section class="card"><h2>5 · From history to film</h2><div class="timeline"><div class="event"><b>734</b> — Battle of the Boarn and death of Poppo.</div><div class="event"><b>1412 · in the film</b> — Reiderland knights find a sword in a mysterious underground cavity.</div><div class="event"><b>Late Middle Ages–16th century</b> — Dollard expansion and settlement loss feed the drowned-land tradition.</div><div class="event"><b>1949 · in the film</b> — another historical scene, filmed at Gilze-Rijen.</div><div class="event"><b>2025–2026</b> — the production itself becomes living history through locations, reenactment, local performers and cultural funding.</div></div></section>
<section class="card"><h2>6 · The drowned-village atlas</h2><p>LuxDot does not treat “33 villages” as a fixed legendary number. Names are checked against church records, maps and historical lists. Core cases include <b>Oosterreide, Westerreide, Reiderwolde, Torum, Palmar, Fletum, Wilgum, Berum, Ulsda, Megenham, Tijsweer and Zwaag</b>. A historical name is not automatically a confirmed coordinate.</p></section>
<section class="card"><h2>7 · How the Dollard actually formed</h2><p>The historical and archaeological picture does not support a simple story in which all of Reiderland vanished in one night in 1277. Settlement continued in some places into the 15th and 16th centuries. Marine expansion occurred in stages; late-medieval floods and the disaster of 1509 were decisive.</p></section>
<section class="card"><h2>8 · The map that helped make the legend</h2><p>Jacob Vermeersch's 1574 map was among the early maps visualising drowned Reiderland, and later maps repeated the narrative. The map is therefore not only evidence of memory; it can also become a machine that produces memory.</p></section>
<section class="card"><h2>9 · Legend and treasure matrix</h2><div class="grid"><article><h3>Zeewiefke</h3><p>A later folk tale of a captured sea-being who curses Reiderwolde. It preserves cultural fear of the sea, not a causal history of the floods.</p></article><article><h3>Gold and wealth</h3><p>Traditions magnify the region's prosperity through women with heavy gold ornaments, goldsmiths at Torum and many stone houses—part of the transformation of lost farmland into a “lost rich kingdom”.</p></article><article><h3>Bells beneath the water</h3><p>Part of a wider European drowned-church motif; recorded as folklore, not proof of a surviving bell at a specific location.</p></article><article><h3>Poppo's crown</h3><p><b>Cinematic element.</b> Poppo has a historical nucleus; the missing crown and treasure hunt remain film narrative unless independent evidence emerges.</p></article></div></section>
<section class="card"><h2>10 · Religion and churches beneath the mud</h2><p>The story also concerns parishes, churches and monasteries. Some communities and churches shifted toward safer, higher ground. The Dollard therefore becomes an archive of <b>water, sacred space and memory</b>. Westerreide, Reiderwolde and the lost Premonstratensian monastery of Palmar are key cases; Bellingwolde and Blijham help study relocation.</p></section>
<section class="card"><h2>11 · Poppo: the person before the crown</h2><p>The dossier keeps three layers separate: <b>(1)</b> Poppo/Bubo in the Frisian–Frankish conflict; <b>(2)</b> the Battle of the Boarn in 734; <b>(3)</b> the film's reconstruction of him as a king whose grave and crown can drive an adventure.</p></section>
<section class="card watch"><h2>12 · LIVE FILM WATCH</h2><p><span class="fresh">Official site: last modified August 2026</span></p><div class="sourcegrid"><div><b>16 May 2026 · Emmen</b><small>Scene involving two helicopters, Rinse, PVR and a wolfdog.</small></div><div><b>30 May · Kolham</b><small>New material filmed while the team kept its content secret.</small></div><div><b>14 June · Vlaardingen</b><small>Large historical battle filmed in Broekpolder with dozens of reenactors.</small></div><div><b>Current phase</b><small>A second crowdfunding campaign is planned to complete the film.</small></div></div><p><strong>Status: active · August 2026.</strong> Each update is logged by publication date, filming date where different, location, characters and new plot information. Production location, story location and historical location remain separate layers.</p></section>
<section class="card"><h2>13 · LuxDot intersections: questions, not proof</h2><div class="grid"><article><h3>Living memory</h3><p>A village disappears physically while its name survives in texts, maps and legend.</p></article><article><h3>Signal and noise</h3><p>Later sources retell older events; research must separate historical signal from later amplification.</p></article><article><h3>The journey</h3><p>The film turns archives, maps and objects into movement through space; LuxDot can trace the real geography in parallel.</p></article><article><h3>Cinema as memory</h3><p>As audiences encounter Poppo and Reiderland through the film, the cinematic image itself becomes a new layer of regional memory.</p></article></div></section>
<section class="card"><h2>14 · Research route ahead</h2><p>Next: a record for each drowned village; comparison of maps from 1574, 1630, 1722 and 1837; churches and monasteries; an archaeological layer for Punt van Reide; and comparison of film locations with historical geography without conflating them.</p></section>
<section class="card"><h2>15 · To visitors from the Reiderland team</h2><p class="quote">Welcome inside the research.</p><p>LuxDot does not claim to possess a “solution” to the Reiderland legend and does not turn the film's plot into historical fact. The film is here because <b>you are creating a new layer in the memory of this land</b>. We document the historical and legendary sources, observe how cinema reconstructs them, and keep questions open where evidence is insufficient.</p><p>The striking intersection is an invitation to compare: lost land, memory, maps, artefacts, storytelling and the search for signal inside layers of noise. This page remains living throughout production and will be corrected whenever better evidence appears.</p><div class="note"><b>Research policy:</b> documented history ≠ folklore ≠ hypothesis ≠ cinematic fiction.</div></section>
<section class="card links"><h2>Living sources</h2><a href="https://www.reiderlanddefilm.nl/NIEUWS/" target="_blank" rel="noopener">Official film news</a><a href="https://www.reiderlanddefilm.nl/HET-VERHAAL/" target="_blank" rel="noopener">Official story</a><a href="https://www.reiderlanddefilm.nl/CAST-EN-CREW/" target="_blank" rel="noopener">Cast & crew</a><a href="https://www.reiderlanddefilm.nl/CONCEPT-ART/" target="_blank" rel="noopener">Concept art</a><a href="https://www.deverhalenvangroningen.nl/alle-verhalen/verdronken-dorpen" target="_blank" rel="noopener">Drowned villages · Groningen</a><p class="small">Research/editorial review: 18 August 2026 · LuxDot living dossier.</p></section>`;
const NL=`<section class="hero"><div class="kicker">LUXDOT · LEVEND FILMONDERZOEK · 18 AUG 2026</div><h1>Reiderland: het verdronken land en een film die nog wordt gemaakt</h1><p class="lead">Een levend dossier dat de gedocumenteerde geschiedenis van <b>Reiderland / Rheiderland</b>, de herinnering aan dorpen die in de Dollard verdwenen, verhalen over hoogmoed, klokken en schatten, en de filmische fictie van <b>Reiderland</b> uit elkaar houdt. Overeenkomst is geen bewijs: elke laag krijgt een eigen betrouwbaarheidsniveau.</p><span class="badge">Levend onderzoek</span><span class="badge">Nederland × Duitsland</span><span class="badge">Film in productie</span><span class="badge">Geheugen van plaats</span></section>
<section class="card film-focus"><span class="fresh">LIVE · laatst gecontroleerd 18 augustus 2026</span><h2>De film en zijn makers binnen het onderzoek</h2><p class="welcome">Deze knoop onderzoekt <b>Reiderland</b> terwijl de film nog wordt gemaakt. De productie is dus zelf onderdeel van het onderzoek: wie schrijft haar, wie vormt het beeld, wie belichaamt het geheugen en hoe wordt historisch en legendarisch onderzoek cinema? De officiële site noemt <b>Henk en Thomas Hiensch</b> als scenaristen/regisseurs met een blijvende belangstelling voor geschiedenis, kunst, mythe en vertelkunst.</p><div class="people"><div class="person official"><b>Henk Hiensch</b><span class="role">Scenarist & regisseur · Reiderland</span><p>Medeschrijver en mederegisseur; het project groeit uit familiebanden met Friesland en belangstelling voor geschiedenis, kunst en verhaal.</p></div><div class="person official"><b>Thomas Hiensch</b><span class="role">Scenarist & regisseur · Reiderland</span><p>Medeschrijver en mederegisseur. De broers beschrijven de productie als samenwerkend filmmaken dat via lokale relaties en deelname groeit.</p></div><div class="person"><b>Kees van Wanrooij</b><span class="role">Professor Puttkamer</span><p>Verteller in de rol van de sympathieke professor met voorkennis over de schatten van Magna Frisia. Hij heeft een eigen LuxDot-knoop en vormt hier een directe brug tussen verhaal, onderzoek en film.</p></div><div class="person"><b>Anton van den Heuvel</b><span class="role">Koning Poppo</span><p>In 2026 gekozen voor Poppo; zo komen de historische figuur en zijn moderne filmbeeld samen in één traceerbaar onderzoekspunt.</p></div></div><p class="small">Personen worden uitsluitend opgenomen vanwege hun publiek gedocumenteerde rol; persoonlijke opvattingen of intenties worden niet verondersteld.</p></section>
<section class="grid"><article class="card"><h2>Centrale vraag</h2><p>Wat blijft er over wanneer dorpen, kerken en wegen verdwijnen, maar namen, kaarten en verhalen blijven bestaan? Hoe kan een hedendaagse film dat geheugen tot avontuur maken zonder legende en geschiedenis te verwarren?</p></article><article class="card"><h2>LuxDot-regel</h2><p><b>Eerst het gedocumenteerde.</b> Een verhaal over een schat, vloek of kroon bewijst het object of de gebeurtenis niet. Het bestaan, de overdracht en de maatschappelijke rol van het verhaal zijn wél onderzoekbare feiten.</p></article></section>
<section class="card"><h2>1 · De streek vóór de film</h2><p>Reiderland was een historische Friese streek aan weerszijden van de huidige grens tussen noordoost-Groningen en Oost-Friesland. Vanaf de late middeleeuwen veranderde het landschap ingrijpend door doorbraken van de zee en de uitbreiding van de Dollard. Huidig regionaal onderzoek ziet dit als een lang proces van overstromingen en landverlies, met een zware slag in 1509 en daarna eeuwen van inpoldering.</p><div class="status"><div class="A"><b>A · sterk</b><br>Historisch Reiderland en verdwenen nederzettingen.</div><div class="B"><b>B · goed</b><br>Algemene reeks van overstroming en inpoldering.</div><div class="C"><b>C · overlevering</b><br>Klokken onder water, vloeken en strafverhalen.</div><div class="E"><b>E · open</b><br>Niet-bewezen locaties van schatten of kronen.</div></div></section>
<section class="map"><img src="assets/reiderland-map-1842.jpg" alt="Historische kaart van verdronken Dollarddorpen"><div class="caption">Latere historische kaart van de herinnering aan verdronken Dollarddorpen. Beeldbron: De Verhalen van Groningen. Gebruikt als document van plaatsgeheugen, niet als exacte kaart van het moment van overstroming.</div></section>
<section class="grid"><article class="card"><h2>2 · Dorpen en geheugen</h2><p>Lokale bronnen noemen tientallen verdwenen of verlaten nederzettingen. Oude lijsten vergroten soms aantallen of herhalen onzekere namen; daarom onderscheidt dit dossier gedocumenteerde plaatsen van overgeleverde namen. Reiderwolde neemt in herinnering én film een bijzondere plaats in.</p></article><article class="card"><h2>3 · Legende</h2><p>Folklore vertelt over buitensporige rijkdom en hoogmoed, klokken die onder water te horen zouden zijn en in sommige versies een zeevrouw die de plaats vervloekt. Dit is <b>volksgeheugen</b>, geen geologische verklaring.</p></article><article class="card"><h2>4 · Poppo en 734</h2><p>Poppo/Bubo wordt verbonden met Fries verzet tegen de Franken en met de Slag aan de Boorne in 734. De titel ‘koning’ en een Reiderlandse kroon moeten apart worden beoordeeld: de film bouwt een eigen avontuur op een historische kern.</p></article></section>
<section class="card"><h2>5 · Van geschiedenis naar film</h2><div class="timeline"><div class="event"><b>734</b> — Slag aan de Boorne en de dood van Poppo.</div><div class="event"><b>1412 · in de film</b> — ridders van Reiderland vinden een zwaard in een mysterieuze ondergrondse ruimte.</div><div class="event"><b>Late middeleeuwen–16e eeuw</b> — uitbreiding van de Dollard en verlies van nederzettingen voeden de traditie van het verdronken land.</div><div class="event"><b>1949 · in de film</b> — een andere historische scène, opgenomen op Gilze-Rijen.</div><div class="event"><b>2025–2026</b> — de productie zelf wordt levende geschiedenis via locaties, re-enactment, lokale spelers en culturele financiering.</div></div></section>
<section class="card"><h2>6 · Atlas van verdronken dorpen</h2><p>LuxDot behandelt “33 dorpen” niet als een vast legendarisch getal. Namen worden vergeleken met kerkelijke registers, kaarten en historische lijsten. Kerngevallen zijn <b>Oosterreide, Westerreide, Reiderwolde, Torum, Palmar, Fletum, Wilgum, Berum, Ulsda, Megenham, Tijsweer en Zwaag</b>. Een oude naam is niet automatisch een zekere coördinaat.</p></section>
<section class="card"><h2>7 · Hoe de Dollard werkelijk ontstond</h2><p>Het historische en archeologische beeld ondersteunt niet het eenvoudige verhaal dat heel Reiderland in 1277 in één nacht verdween. Op sommige plaatsen bleef bewoning tot in de 15e en 16e eeuw bestaan. De zee breidde zich in fasen uit; laatmiddeleeuwse stormvloeden en de ramp van 1509 waren beslissend.</p></section>
<section class="card"><h2>8 · De kaart die de legende hielp maken</h2><p>De kaart van Jacob Vermeersch uit 1574 behoorde tot de vroege kaarten die het verdronken Reiderland visualiseerden; latere kaarten herhaalden het verhaal. Een kaart kan dus niet alleen geheugen registreren, maar ook geheugen produceren.</p></section>
<section class="card"><h2>9 · Matrix van legende en schat</h2><div class="grid"><article><h3>Zeewiefke</h3><p>Een latere volksvertelling over een gevangen zeewezen dat Reiderwolde vervloekt. Zij bewaart culturele angst voor de zee, niet de causale geschiedenis van de overstromingen.</p></article><article><h3>Goud en rijkdom</h3><p>Overleveringen vergroten de welvaart met vrouwen vol zware gouden sieraden, goudsmeden in Torum en vele stenen huizen: deel van de verandering van verloren landbouwland in een “verloren rijk koninkrijk”.</p></article><article><h3>Klokken onder water</h3><p>Onderdeel van een breder Europees motief van verdronken kerken; folklore, geen bewijs van een specifieke nog aanwezige klok.</p></article><article><h3>Poppo's kroon</h3><p><b>Filmisch element.</b> Poppo heeft een historische kern; de verdwenen kroon en zoektocht blijven filmverhaal zolang onafhankelijk bewijs ontbreekt.</p></article></div></section>
<section class="card"><h2>10 · Religie en kerken onder de klei</h2><p>Het verhaal gaat ook over parochies, kerken en kloosters. Sommige gemeenschappen en kerken verplaatsten zich naar veiliger, hoger terrein. De Dollard wordt zo een archief van <b>water, heilige ruimte en geheugen</b>. Westerreide, Reiderwolde en het verdwenen premonstratenzer klooster Palmar zijn sleutelgevallen; Bellingwolde en Blijham helpen verplaatsing bestuderen.</p></section>
<section class="card"><h2>11 · Poppo: de persoon vóór de kroon</h2><p>Het dossier houdt drie lagen uit elkaar: <b>(1)</b> Poppo/Bubo in het Fries-Frankische conflict; <b>(2)</b> de Slag aan de Boorne in 734; <b>(3)</b> de filmische reconstructie van hem als koning wiens graf en kroon een avontuur kunnen dragen.</p></section>
<section class="card watch"><h2>12 · LIVE FILM WATCH</h2><p><span class="fresh">Officiële site: laatst gewijzigd augustus 2026</span></p><div class="sourcegrid"><div><b>16 mei 2026 · Emmen</b><small>Scène met twee helikopters, Rinse, PVR en een wolfhond.</small></div><div><b>30 mei · Kolham</b><small>Nieuwe opnamen waarvan de inhoud geheim werd gehouden.</small></div><div><b>14 juni · Vlaardingen</b><small>Grote historische veldslag in de Broekpolder met tientallen re-enactors.</small></div><div><b>Huidige fase</b><small>Een tweede crowdfundingcampagne is aangekondigd om de film af te ronden.</small></div></div><p><strong>Status: actief · augustus 2026.</strong> Elke update wordt vastgelegd met publicatiedatum, opnamedatum waar die afwijkt, locatie, personages en nieuwe plotinformatie. Opnamelocatie, locatie in het verhaal en historische locatie blijven afzonderlijke lagen.</p></section>
<section class="card"><h2>13 · LuxDot-kruisingen: vragen, geen bewijs</h2><div class="grid"><article><h3>Levend geheugen</h3><p>Een dorp verdwijnt fysiek terwijl de naam in tekst, kaart en legende blijft bestaan.</p></article><article><h3>Signaal en ruis</h3><p>Latere bronnen vertellen oudere gebeurtenissen opnieuw; onderzoek scheidt historisch signaal van latere versterking.</p></article><article><h3>De reis</h3><p>De film verandert archief, kaart en object in beweging door het landschap; LuxDot kan de werkelijke geografie parallel volgen.</p></article><article><h3>Cinema als geheugen</h3><p>Wanneer publiek Poppo en Reiderland via de film leert kennen, wordt het filmbeeld zelf een nieuwe laag in het regionale geheugen.</p></article></div></section>
<section class="card"><h2>14 · Volgende onderzoeksroute</h2><p>Volgende stappen: een dossier per verdronken dorp; vergelijking van kaarten uit 1574, 1630, 1722 en 1837; kerken en kloosters; een archeologische laag voor Punt van Reide; en vergelijking van filmlocaties met historische geografie zonder ze te verwarren.</p></section>
<section class="card"><h2>15 · Voor bezoekers uit het Reiderland-team</h2><p class="quote">Welkom in het onderzoek.</p><p>LuxDot beweert niet de “oplossing” van de Reiderland-legende te bezitten en maakt van het filmscenario geen historisch feit. De film staat hier omdat <b>jullie nu een nieuwe laag in het geheugen van dit land maken</b>. Wij documenteren historische en legendarische bronnen, volgen hoe cinema ze opnieuw vormgeeft en laten vragen open wanneer bewijs ontbreekt.</p><p>De opvallende kruising is een uitnodiging tot vergelijking: verdwenen land, geheugen, kaarten, artefacten, verhaal en de zoektocht naar signaal tussen lagen ruis. Deze pagina blijft tijdens de productie levend en wordt gecorrigeerd wanneer beter bewijs verschijnt.</p><div class="note"><b>Onderzoeksbeleid:</b> gedocumenteerde geschiedenis ≠ folklore ≠ hypothese ≠ filmische fictie.</div></section>
<section class="card links"><h2>Levende bronnen</h2><a href="https://www.reiderlanddefilm.nl/NIEUWS/" target="_blank" rel="noopener">Officieel filmnieuws</a><a href="https://www.reiderlanddefilm.nl/HET-VERHAAL/" target="_blank" rel="noopener">Officieel verhaal</a><a href="https://www.reiderlanddefilm.nl/CAST-EN-CREW/" target="_blank" rel="noopener">Cast & crew</a><a href="https://www.reiderlanddefilm.nl/CONCEPT-ART/" target="_blank" rel="noopener">Concept art</a><a href="https://www.deverhalenvangroningen.nl/alle-verhalen/verdronken-dorpen" target="_blank" rel="noopener">Verdronken dorpen · Groningen</a><p class="small">Onderzoeks-/redactierevisie: 18 augustus 2026 · LuxDot levend dossier.</p></section>`;

function extras(lang){
 const T={
  ar:{media:'20 · صور وكواليس من الإنتاج',sub:'مواد بصرية من المصادر الرسمية للفيلم، مع خريطة تاريخية محفوظة محلياً داخل LuxDot.',teaser:'الإعلان التشويقي الرسمي',teaserc:'أول teaser منشور للفيلم (2026).',bts:'من كواليس شقة Rinse',btsc:'فيديو Behind-the-scenes من يوم تصوير Leeuwarden في فبراير 2026.',kees:'Kees van Wanrooij · Professor Puttkamer',keesc:'صورة إعلان اختيار كيس للدور، من موقع Reiderland الرسمي.',poppo:'Anton van den Heuvel · Koning Poppo',poppoc:'صورة إعلان اختيار Anton لدور Poppo، من موقع الفيلم الرسمي.',hist:'خريطة Reiderland / Dollard التاريخية',histc:'نسخة 1842 عن خريطة A. Maas القديمة، محفوظة من مجموعة خرائط جامعة خرونينغن.',map:'21 · افتح الخريطة التفاعلية',mapsub:'خريطة حقيقية للمنطقة الحالية: Dollard، Punt van Reide، Bellingwolde وBlijham. المواقع التاريخية غير المؤكدة لا تُعرض كدبابيس قطعية.',open:'فتح الخريطة',close:'إغلاق الخريطة',osm:'فتح في OpenStreetMap',note:'الخريطة الحديثة للسياق الجغرافي؛ لا تعني أن القرى الغارقة كانت في نفس الإحداثيات الحديثة.',punt:'Punt van Reide',bell:'Bellingwolde',blij:'Blijham',doll:'Dollard'},
  en:{media:'20 · Production images & behind the scenes',sub:'Visual material from the film’s official sources, plus a historical map stored locally in LuxDot.',teaser:'Official teaser',teaserc:'The first publicly released Reiderland teaser (2026).',bts:'Behind the scenes: Rinse’s apartment',btsc:'Official BTS video from the Leeuwarden shoot in February 2026.',kees:'Kees van Wanrooij · Professor Puttkamer',keesc:'Official casting announcement image from the Reiderland website.',poppo:'Anton van den Heuvel · King Poppo',poppoc:'Official casting announcement image for Poppo.',hist:'Historical Reiderland / Dollard map',histc:'1842 copy after A. Maas, preserved by the University of Groningen map collection.',map:'21 · Open the interactive map',mapsub:'A real present-day map of the Dollard, Punt van Reide, Bellingwolde and Blijham. Uncertain drowned-village locations are not presented as definitive pins.',open:'Open map',close:'Close map',osm:'Open in OpenStreetMap',note:'Modern map for geographic context; it does not claim drowned villages occupied the same modern coordinates.',punt:'Punt van Reide',bell:'Bellingwolde',blij:'Blijham',doll:'Dollard'},
  nl:{media:'20 · Productiefoto’s & achter de schermen',sub:'Beeldmateriaal uit officiële filmbronnen, plus een historische kaart die lokaal in LuxDot is opgeslagen.',teaser:'Officiële teaser',teaserc:'De eerste openbaar uitgebrachte teaser van Reiderland (2026).',bts:'Behind the scenes: Rinse’s appartement',btsc:'Officiële BTS-video van de draaidag in Leeuwarden, februari 2026.',kees:'Kees van Wanrooij · Professor Puttkamer',keesc:'Officiële castingfoto van de Reiderland-website.',poppo:'Anton van den Heuvel · Koning Poppo',poppoc:'Officiële castingfoto voor de rol van Poppo.',hist:'Historische kaart van Reiderland / Dollard',histc:'Kopie uit 1842 naar A. Maas, bewaard in de kaartenverzameling van de Rijksuniversiteit Groningen.',map:'21 · Open de interactieve kaart',mapsub:'Een echte hedendaagse kaart van de Dollard, Punt van Reide, Bellingwolde en Blijham. Onzekere locaties van verdronken dorpen worden niet als zekere pinnen gepresenteerd.',open:'Open kaart',close:'Sluit kaart',osm:'Open in OpenStreetMap',note:'Moderne kaart voor geografische context; de pins zijn geen claim over exacte middeleeuwse dorpslocaties.',punt:'Punt van Reide',bell:'Bellingwolde',blij:'Blijham',doll:'Dollard'}
 }[lang]||null; if(!T)return;
 const focus=main.querySelector('.film-focus');
 if(focus && !main.querySelector('#reider-media')) focus.insertAdjacentHTML('afterend',`<section id="reider-media" class="card"><h2>${T.media}</h2><p>${T.sub}</p><div class="media-grid">
 <article class="media-card"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/L8Qndly6DUg" title="${T.teaser}" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><div class="media-body"><b>${T.teaser}</b><span>${T.teaserc}</span></div></article>
 <article class="media-card"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/mZwe65WpPS0" title="${T.bts}" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><div class="media-body"><b>${T.bts}</b><span>${T.btsc}</span></div></article>
 <article class="media-card"><img loading="lazy" src="https://reiderlanddefilm.nl/.cm4all/uproc.php/0/.actueel%20productie%20kees%20van%20wanrooij2.jpg/picture-200?_=195235a91c8" alt="Kees van Wanrooij as Professor Puttkamer"><div class="media-body"><b>${T.kees}</b><span>${T.keesc}</span></div></article>
 <article class="media-card"><img loading="lazy" src="https://reiderlanddefilm.nl/.cm4all/uproc.php/0/.actueel%20koning%20poppo.jpg/picture-200?_=19c84a50da8" alt="Anton van den Heuvel as King Poppo"><div class="media-body"><b>${T.poppo}</b><span>${T.poppoc}</span></div></article>
 <article class="media-card"><img class="historic-map" loading="lazy" src="assets/reiderland-map-1842.jpg" alt="Historical map of Reiderland and the Dollard"><div class="media-body"><b>${T.hist}</b><span>${T.histc}</span></div></article>
 </div><p class="play-note">© Film production imagery/video: Reiderland de film / respective creators. Historical map: RUG map collection. Included here for research, commentary and source-linked documentation.</p></section>`);
 const old=main.querySelector('section.map'); if(old) old.remove();
 if(!main.querySelector('#reider-map')){
  const atlas=[...main.querySelectorAll('.card')].find(x=>/Atlas|أطلس|atlas/i.test(x.textContent)) || main.querySelector('.card');
  atlas.insertAdjacentHTML('beforebegin',`<section id="reider-map" class="card"><a id="reider-map-launch" class="map-launch" href="#reider-map-canvas"><span><b>${T.map}</b><br><small>${T.mapsub}</small></span><span>${T.open} ↓</span></a><div id="reider-map-canvas" class="map-shell"><div class="map-actions map-places"><a target="reiderMapFrame" href="https://www.openstreetmap.org/export/embed.html?bbox=6.80%2C53.10%2C7.30%2C53.40&amp;layer=mapnik&amp;marker=53.3000%2C7.0833">${T.punt}</a><a target="reiderMapFrame" href="https://www.openstreetmap.org/export/embed.html?bbox=6.90%2C52.98%2C7.35%2C53.25&amp;layer=mapnik&amp;marker=53.11667%2C7.16528">${T.bell}</a><a target="reiderMapFrame" href="https://www.openstreetmap.org/export/embed.html?bbox=6.82%2C52.98%2C7.30%2C53.24&amp;layer=mapnik&amp;marker=53.10692%2C7.07495">${T.blij}</a><a target="reiderMapFrame" href="https://www.openstreetmap.org/export/embed.html?bbox=6.75%2C53.00%2C7.35%2C53.45&amp;layer=mapnik&amp;marker=53.22%2C7.05">${T.doll}</a></div><iframe name="reiderMapFrame" class="reider-osm" loading="lazy" title="Reiderland / Dollard interactive map" src="https://www.openstreetmap.org/export/embed.html?bbox=6.75%2C53.00%2C7.35%2C53.45&amp;layer=mapnik&amp;marker=53.3000%2C7.0833"></iframe><div class="map-actions"><a class="osm-open" target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat=53.3000&amp;mlon=7.0833#map=10/53.22/7.08">${T.osm}</a><span class="small">${T.note}</span></div></div></section>`);
 }
}

const main=document.querySelector('main.rr'); if(!main)return; const AR=main.innerHTML;
function apply(){const l=(window.LuxLang&&LuxLang.get())||new URLSearchParams(location.search).get('lang')||'ar'; document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';main.innerHTML=l==='nl'?NL:l==='en'?EN:AR;document.title=l==='nl'?'Reiderland · levend onderzoek · LuxDot':l==='en'?'Reiderland · Living Research · LuxDot':'رايدرلاند · بحث حي · LuxDot';extras(l);}
document.addEventListener('luxlang',apply); if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
})();

