(()=>{
const DATA={
 families:[
  {id:'meaning',ar:'الإنسان والمعنى',en:'Human & Meaning',nl:'Mens & Betekenis',idn:'Manusia & Makna',desc:{ar:'الخلاص، التقاليد، النصوص، جاوة',en:'salvation, traditions, texts, Java',nl:'verlossing, tradities, teksten, Java',id:'keselamatan, tradisi, teks, Jawa'}},
  {id:'land',ar:'الأرض والحدود',en:'Land & Borders',nl:'Land & Grenzen',idn:'Tanah & Batas',desc:{ar:'شام، بريدا، بارله، هوخستراتن، ناسو',en:'Chaam, Breda, Baarle, Hoogstraten, Nassau',nl:'Chaam, Breda, Baarle, Hoogstraten, Nassau',id:'Chaam, Breda, Baarle, Hoogstraten, Nassau'}},
  {id:'pilgrimage',ar:'الحج والإشارة',en:'Pilgrimage & Signal',nl:'Bedevaart & Signaal',idn:'Ziarah & Sinyal',desc:{ar:'كيفيلار، بوسمان، الذخائر، الطرق',en:'Kevelaer, Busman, relics, routes',nl:'Kevelaer, Busman, relieken, routes',id:'Kevelaer, Busman, relik, rute'}},
  {id:'choice',ar:'الاختيار والمسؤولية',en:'Choice & Responsibility',nl:'Keuze & Verantwoordelijkheid',idn:'Pilihan & Tanggung Jawab',desc:{ar:'إيراسموس، الجسر، النظام، التوقف',en:'Erasmus, bridge, system, stopping',nl:'Erasmus, brug, systeem, stoppen',id:'Erasmus, jembatan, sistem, berhenti'}},
  {id:'journeys',ar:'رحلات المعرفة',en:'Knowledge Journeys',nl:'Kennisreizen',idn:'Perjalanan Pengetahuan',desc:{ar:'انتقال المعرفة واللغة والاستكشاف',en:'knowledge transfer, language, exploration',nl:'kennisoverdracht, taal, verkenning',id:'transfer pengetahuan, bahasa, eksplorasi'}},
  {id:'lineage',ar:'العائلات والمؤسسات',en:'Families & Institutions',nl:'Families & Instellingen',idn:'Kulawarga & Lembaga',desc:{ar:'النسب، الرعاية الكنسية، السلطة، شبكات العائلات',en:'genealogy, patronage, authority, family networks',nl:'genealogie, patronage, gezag, familienetwerken',id:'silsilah, patronase, panguwasa, jaringan kulawarga'}}
 ],
 nodes:[
  {id:'luxdot',kind:'hub',families:['meaning','land','pilgrimage','choice','journeys'],label:{ar:'LUXDOT',en:'LUXDOT',nl:'LUXDOT',id:'LUXDOT'},sub:{ar:'أطلس البحث',en:'Research Atlas',nl:'Onderzoeksatlas',id:'Atlas Riset'},desc:{ar:'طبقة معرفة تربط المصادر والادعاءات والأحداث والأشخاص والأماكن والفرضيات دون تسوية درجات الثقة بينها.',en:'A knowledge layer linking sources, claims, events, people, places and hypotheses without flattening their confidence levels.',nl:'Een kennislaag die bronnen, claims, gebeurtenissen, personen, plaatsen en hypotheses verbindt zonder hun bewijskracht gelijk te maken.',id:'Lapisan pengetahuan yang menghubungkan sumber, klaim, peristiwa, orang, tempat dan hipotesis tanpa menyamakan tingkat kepastiannya.'}},
  {id:'savior',kind:'research',families:['meaning'],legacy:'001',label:{ar:'أطلس المخلّص',en:'Savior Atlas',nl:'Verlossersatlas',id:'Atlas Penyelamat'},sub:{ar:'تقاليد الخلاص',en:'salvation traditions',nl:'verlossingstradities',id:'tradisi keselamatan'},href:'savior-atlas.html',confidence:'C',desc:{ar:'مقارنة نقدية لتصورات المخلّص والتجديد عبر تقاليد متعددة. وجود التشابه لا يعني التطابق أو التنبؤ.',en:'Critical comparison of savior and renewal traditions; similarity does not establish identity or prediction.',nl:'Kritische vergelijking van verlossers- en vernieuwingsmotieven; gelijkenis bewijst geen identiteit of voorspelling.',id:'Perbandingan kritis tradisi penyelamat dan pembaruan; kemiripan bukan bukti identitas atau ramalan.'}},
  {id:'redheifer',kind:'research',families:['meaning'],legacy:'014',label:{ar:'البقرة الحمراء',en:'Red Heifer',nl:'Rode koe',id:'Sapi Abang',jv:'Sapi Abang',he:'הפרה האדומה'},sub:{ar:'المشيح · 2024 · 2025',en:'Messiah · 2024 · 2025',nl:'Messias · 2024 · 2025',jv:'Mesias · 2024 · 2025',he:'משיח · 2024 · 2025'},href:'red-heifer.html',confidence:'D',desc:{ar:'بحث حي يفصل بين طقس البقرة الحمراء، تقليد الأبقار التسع، ربط موسى بن ميمون العاشرة بالملك المشيح، وفرضية LuxDot حول حدث 1 يوليو 2025.',en:'Living research separating the red-heifer rite, the nine-heifer tradition, Maimonides’ Messiah link and the LuxDot hypothesis around 1 July 2025.',nl:'Levend onderzoek naar de rode koe, de negen-koeien-traditie, de Messias-koppeling bij Maimonides en de LuxDot-hypothese rond 1 juli 2025.',jv:'Panliten urip babagan sapi abang, tradhisi sanga sapi, sambungan Maimonides karo Mesias lan hipotesis LuxDot 1 Juli 2025.',he:'מחקר חי המפריד בין מצוות הפרה האדומה, מסורת תשע הפרות, הקשר למשיח אצל הרמב״ם והשערת LuxDot על 1 ביולי 2025.'}},

  {id:'petgoat',kind:'research',families:['meaning'],legacy:'015',label:{ar:'مسرح العالم: الرموز والأخرويات',en:'World Stage: Symbols & Eschatology',nl:'Wereldpodium: symbolen & eschatologie',id:'Panggung Dunia: Simbol & Eskatologi'},sub:{ar:'Pet Goat · باريس · برمنغهام · لندن · بكين · سوتشي · قطر · طوكيو',en:'Pet Goat · Paris · Birmingham · London · Beijing · Sochi · Qatar · Tokyo',nl:'Pet Goat · Parijs · Birmingham · Londen · Beijing · Sotsji · Qatar · Tokio',id:'Pet Goat · Paris · Birmingham · London · Beijing · Sochi · Qatar · Tokyo'},href:'pet-goat-apocalypse-media.html',confidence:'C',desc:{ar:'تحقيق في أصل سلسلة Pet Goat، رموز Heliofant، وسلسلة Seymour المهدوية اللاحقة، مع فصل الفن عن النبوءة.',en:'Investigation of Pet Goat lineage, Heliofant symbolism and Seymour’s later Mahdist/apocalyptic series, separating art from prophecy.',nl:'Onderzoek naar de Pet Goat-lijn, Heliofant-symboliek en Seymours latere mahdistische/apocalyptische reeks, met scheiding tussen kunst en profetie.',id:'Kajian asal Pet Goat, simbolisme Heliofant lan seri apokaliptik Seymour, misahake seni saka ramalan.'}},  {id:'java',kind:'research',families:['meaning','journeys'],legacy:'002',label:{ar:'جاوة',en:'Java',nl:'Java',id:'Jawa'},sub:{ar:'لغة · مخطوطات',en:'language · manuscripts',nl:'taal · manuscripten',id:'bahasa · naskah'},href:'java-script.html',confidence:'B',desc:{ar:'مسار يقارن التاريخ اللغوي والمخطوطات والتقاليد الجاوية مع قراءات LuxDot، مع إبقاء الرمز منفصلاً عن التاريخ.',en:'A track connecting linguistic history, manuscripts and Javanese traditions while separating LuxDot interpretation from history.',nl:'Een spoor door taalgeschiedenis, manuscripten en Javaanse tradities, met scheiding tussen interpretatie en geschiedenis.',id:'Jalur sejarah bahasa, naskah dan tradisi Jawa dengan pemisahan tafsir dari sejarah.'}},
  {id:'shaam',kind:'research',families:['land'],legacy:'003',label:{ar:'شام–بريدا',en:'Chaam–Breda',nl:'Chaam–Breda',id:'Chaam–Breda'},sub:{ar:'المكان والذاكرة',en:'place & memory',nl:'plaats & geheugen',id:'tempat & memori'},href:'shaam-breda.html',confidence:'B',desc:{ar:'أطلس للمكان والذاكرة والرعاية والتاريخ المحلي، لا يبدأ من افتراض قداسة المكان.',en:'Atlas of place, memory, care and local history that does not begin by assuming sacred status.',nl:'Atlas van plaats, geheugen, zorg en lokale geschiedenis zonder heiligheid vooraf aan te nemen.',id:'Atlas tempat, memori, kepedulian dan sejarah lokal tanpa mengasumsikan kesakralan.'}},
  {id:'erasmus',kind:'research',families:['choice'],legacy:'004',label:{ar:'إيراسموس',en:'Erasmus',nl:'Erasmus',id:'Erasmus'},sub:{ar:'جسر · إرادة · اصطدام',en:'bridge · will · collision',nl:'brug · wil · botsing',id:'jembatan · kehendak · tabrakan'},href:'erasmus.html',confidence:'D',desc:{ar:'حادث حديث يستخدم كاختبار حي: الوقائع التقنية في طبقة، والقراءة الفلسفية والرمزية في طبقة أخرى قابلة للتعديل.',en:'A modern incident used as a living test: technical facts on one layer, philosophical/symbolic interpretation on another.',nl:'Een modern incident als levende test: technische feiten apart van filosofische/symbolische duiding.',id:'Insiden modern sebagai uji hidup: fakta teknis dipisahkan dari tafsir filosofis/simbolis.'}},
  {id:'busman',kind:'research',families:['pilgrimage','land'],legacy:'005',label:{ar:'هندريك بوسمان',en:'Hendrick Busman',nl:'Hendrick Busman',id:'Hendrick Busman'},sub:{ar:'كيفيلار · 1641',en:'Kevelaer · 1641',nl:'Kevelaer · 1641',id:'Kevelaer · 1641'},href:'hendrick-busman.html',confidence:'C',desc:{ar:'يفصل بين ما هو موثق تاريخياً حول نشوء الحج وبين النداء والرواية التعبدية بوصفها تقليداً دينياً.',en:'Separates documented pilgrimage history from the devotional call narrative as religious tradition.',nl:'Scheidt gedocumenteerde bedevaartgeschiedenis van de devotionele roepingsvertelling.',id:'Memisahkan sejarah ziarah terdokumentasi dari kisah panggilan sebagai tradisi devosi.'}},
  {id:'nassau',kind:'research',families:['land'],legacy:'006',label:{ar:'أورانيا × ناسو',en:'Urania × Nassau',nl:'Urania × Nassau',id:'Urania × Nassau'},sub:{ar:'نسب · سلطة · بريدا',en:'lineage · power · Breda',nl:'dynastie · macht · Breda',id:'garis keturunan · kuasa · Breda'},href:'urania-nassau.html',confidence:'B',desc:{ar:'عقدة تاريخية لفصل أورانيا الأدبية عن بيت ناسو وتتبع الروابط السياسية والنَسَبية الموثقة.',en:'Historical node separating literary Urania from the Nassau dynasty and tracing documented political/genealogical links.',nl:'Historische knoop die literaire Urania scheidt van de Nassau-dynastie.',id:'Simpul sejarah yang memisahkan Urania sastra dari dinasti Nassau.'}},
  {id:'kevelaer-chaam',kind:'research',families:['pilgrimage','land'],legacy:'007',label:{ar:'كيفيلار ↔ شام',en:'Kevelaer ↔ Chaam',nl:'Kevelaer ↔ Chaam',id:'Kevelaer ↔ Chaam'},sub:{ar:'خط زمني',en:'audited timeline',nl:'gecontroleerde tijdlijn',id:'linimasa terverifikasi'},href:'kevelaer-chaam-timeline.html',confidence:'B',desc:{ar:'خط زمني يربط نقاطاً موثقة ويحفظ التصحيحات بدلاً من محو الأخطاء القديمة.',en:'Audited timeline linking sourced points and preserving corrections rather than erasing earlier errors.',nl:'Gecontroleerde tijdlijn die correcties bewaart.',id:'Linimasa terverifikasi yang mempertahankan koreksi.'}},
  {id:'hoogstraten',kind:'research',families:['land','pilgrimage'],legacy:'008',label:{ar:'هوخستراتن',en:'Hoogstraten',nl:'Hoogstraten',id:'Hoogstraten'},sub:{ar:'الدم والحدود',en:'blood & borders',nl:'bloed & grenzen',id:'darah & batas'},href:'hoogstraten.html',confidence:'B',desc:{ar:'كنيسة كاترينا كعقدة بين النبلاء والذخيرة الدينية والحج والحدود والحرب وإعادة البناء.',en:'St Catherine’s as a node connecting nobility, relic tradition, pilgrimage, borders, war and reconstruction.',nl:'Sint-Katharina als knoop van adel, reliektraditie, bedevaart, grens, oorlog en wederopbouw.',id:'St Katarina sebagai simpul bangsawan, relik, ziarah, batas, perang dan rekonstruksi.'}},
  {id:'shaamnet',kind:'hub',families:['land','pilgrimage'],label:{ar:'شبكة شام–برابانت',en:'Shaam–Brabant Network',nl:'Netwerk Chaam–Brabant',jv:'Jaringan Chaam–Brabant',he:'רשת שאם–בראבנט'},sub:{ar:'50 كم قلب · 120 كم شبكة',en:'50 km core · 120 km network',nl:'50 km kern · 120 km netwerk',jv:'inti 50 km · jaringan 120 km',he:'ליבה 50 ק״מ · רשת 120 ק״מ'},href:'shaam-brabant-network.html',confidence:'B',desc:{ar:'البحث الأم الذي ينظم ألفن وشام وبريدا وهوخستراتن وناساو وشبكات الأديرة والفرسان ضمن قلب 50 كم وشبكة 120 كم وعقد جذرية أبعد مرتبطة بوثائق.',en:'Parent research organising Alphen, Chaam, Breda, Hoogstraten, Nassau, abbeys and military orders as a 50 km core, 120 km network and documented external roots.',nl:'Moederonderzoek voor Alphen, Chaam, Breda, Hoogstraten, Nassau, abdijen en ridderorden binnen 50 km kern, 120 km netwerk en gedocumenteerde externe wortels.',jv:'Panliten induk kanggo Alphen, Chaam, Breda, Hoogstraten, Nassau, biara lan ordo ksatria.',he:'מחקר־אב המארגן את אלפן, שאם, ברדה, הוחסטראטן, נאסאו, מנזרים ומסדרים צבאיים.'}},
  {id:'sacred25',kind:'research',families:['land','pilgrimage'],legacy:'009',label:{ar:'أطلس شبكة 120 كم',en:'120 km Network Atlas',nl:'Netwerkatlas 120 km',jv:'Atlas Jaringan 120 km',he:'אטלס רשת 120 ק״מ'},sub:{ar:'قلب 50 · شبكة 120',en:'core 50 · network 120',nl:'kern 50 · netwerk 120',jv:'inti 50 · jaringan 120',he:'ליבה 50 · רשת 120'},href:'sacred-120km-network.html',confidence:'B',desc:{ar:'سجل العقد التاريخية والدينية والأثرية: قلب 50 كم حول شام، شبكة رئيسية 120 كم، وعقد خارجية لا تدخل إلا برابط موثق.',en:'Registry of historical, religious and archaeological nodes: 50 km core, 120 km principal network, and external nodes admitted only by documented links.',nl:'Register van historische, religieuze en archeologische knopen: 50 km kern, 120 km hoofdnetwerk en externe knopen alleen via aantoonbare links.',jv:'Register simpul sejarah, agama lan arkeologi: inti 50 km, jaringan 120 km lan simpul njaba sing ana buktine.',he:'מרשם צמתים היסטוריים, דתיים וארכאולוגיים: ליבה 50 ק״מ, רשת 120 ק״מ וצמתים חיצוניים רק בקשר מתועד.'}},
  {id:'alphen',kind:'research',families:['land','journeys'],legacy:'010',label:{ar:'ألفن قبل ألفن',en:'Alphen before Alphen',nl:'Alphen vóór Alphen',jv:'Alphen sadurunge Alphen',he:'אלפן לפני אלפן'},sub:{ar:'401 ← 709',en:'401 → 709',nl:'401 → 709',jv:'401 → 709',he:'401 ← 709'},href:'alphen-before-alphen.html',confidence:'A',desc:{ar:'بحث أثري وتاريخي في مستوطنة كيرك أكّرس والمقبرة الميروفنجية والسكن قرب الكنيسة ووثيقة ألفهايم سنة 709، مع مقياس يقين يفصل الدليل عن الفرضية.',en:'Archaeological and historical research into Kerkakkers, the Merovingian cemetery, church-area occupation and Alfheim 709, with an explicit confidence scale.',nl:'Archeologisch en historisch onderzoek naar Kerkakkers, het Merovingische grafveld, bewoning bij de kerk en Alfheim 709, met een expliciete zekerheidsschaal.',jv:'Panliten arkeologi lan sejarah Kerkakkers, kuburan Meroving, pamukiman cedhak greja lan Alfheim 709 kanthi skala kapercayan.',he:'מחקר ארכאולוגי והיסטורי על קרקאקרס, בית העלמין המרובינגי, ההתיישבות ליד הכנסייה ואלפהיים 709, עם סולם ודאות מפורש.'}},
  {id:'y1648',kind:'time',families:['land','pilgrimage'],label:{ar:'1648',en:'1648',nl:'1648',id:'1648'},sub:{ar:'مونستر · الحدود',en:'Münster · borders',nl:'Münster · grenzen',id:'Münster · batas'},confidence:'A',desc:{ar:'عقدة زمنية تفسيرية: صلح مونستر وتثبيت حدود وسياسات دينية تفسر عدداً من التحولات المحلية أفضل من فرضية المصادفات المستقلة.',en:'Explanatory time node: the Peace of Münster and resulting borders/religious policy explain several local changes better than independent coincidence.',nl:'Tijdknoop: de Vrede van Münster en grens-/religiebeleid verklaren meerdere lokale veranderingen.',id:'Simpul waktu: Perdamaian Münster dan kebijakan batas/agama menjelaskan banyak perubahan lokal.'}},
  {id:'y1944',kind:'time',families:['land'],label:{ar:'1944',en:'1944',nl:'1944',id:'1944'},sub:{ar:'الحرب · الأبراج',en:'war · towers',nl:'oorlog · torens',id:'perang · menara'},confidence:'A',desc:{ar:'عقدة تفسر تكرار تدمير الأبراج ضمن المنطق العسكري للمراقبة والانسحاب، قبل أي قراءة رمزية.',en:'Explains repeated tower destruction through military observation/withdrawal logic before symbolic interpretation.',nl:'Verklaart herhaalde torenvernietiging eerst militair, vóór symbolische duiding.',id:'Menjelaskan penghancuran menara lewat logika militer sebelum tafsir simbolis.'}},
  {id:'memory',kind:'ecosystem',families:['land','meaning'],label:{ar:'الذاكرة الحية',en:'Living Memory',nl:'Levend Geheugen',id:'Memori Hidup'},sub:{ar:'من نتذكر؟',en:'who must be remembered?',nl:'wie herinneren we?',id:'siapa diingat?'},href:'memory.html',confidence:'A',desc:{ar:'مساحة مستقلة للأشخاص والضحايا والشهود. البحث يشير إليها ولا ينسخها.',en:'Independent space for people, victims and witnesses. Research links to it rather than duplicating it.',nl:'Onafhankelijke ruimte voor mensen, slachtoffers en getuigen.',id:'Ruang independen untuk orang, korban dan saksi.'}},
  {id:'library',kind:'ecosystem',families:['meaning','journeys'],label:{ar:'المكتبة',en:'Library',nl:'Bibliotheek',id:'Perpustakaan'},sub:{ar:'النصوص والمصادر',en:'texts & sources',nl:'teksten & bronnen',id:'teks & sumber'},href:'library.html',confidence:'A',desc:{ar:'النص ليس دليلاً لمجرد وجوده؛ المكتبة تحفظ المصدر بينما البحث يفسر ويختبر الادعاءات.',en:'A text is not evidence merely because it exists; the Library preserves sources while Research interprets and tests claims.',nl:'Een tekst is niet automatisch bewijs; de bibliotheek bewaart bronnen, onderzoek test claims.',id:'Teks bukan otomatis bukti; perpustakaan menyimpan sumber, riset menguji klaim.'}},
  {id:'projects',kind:'ecosystem',families:['choice','land'],label:{ar:'المشاريع',en:'Projects',nl:'Projecten',id:'Proyek'},sub:{ar:'الفعل على الأرض',en:'action on the ground',nl:'actie in de praktijk',id:'aksi di lapangan'},href:'projects.html',confidence:'A',desc:{ar:'المشاريع هي أفعال ومبادرات، وليست مكاناً لتخزين التحقيقات النظرية.',en:'Projects are actions and initiatives, not storage for theoretical investigations.',nl:'Projecten zijn acties en initiatieven, geen opslag voor theoretisch onderzoek.',id:'Proyek adalah aksi dan inisiatif, bukan tempat riset teoritis.'}},
  {id:'burckhardt',kind:'research',families:['journeys','pilgrimage'],legacy:'010',label:{ar:'يوهان لودفيغ بوركهارت',en:'Johann Ludwig Burckhardt',nl:'Johann Ludwig Burckhardt',jv:'Johann Ludwig Burckhardt',he:'יוהאן לודוויג בורקהרדט'},sub:{ar:'لغة · البتراء · الحج',en:'language · Petra · Hajj',nl:'taal · Petra · hadj',jv:'basa · Petra · haji',he:'שפה · פטרה · חג׳'},href:'burckhardt.html',confidence:'B',desc:{ar:'رحلة معرفة بدأت بمهمة نحو تمبكتو، ومرت بتعلم العربية وحلب والبتراء والنوبة والحجاز. يفصل البحث بين إعادة التعرف الأوروبية وبين المعرفة المحلية السابقة.',en:'A knowledge journey prepared for Timbuktu that passed through Arabic study, Aleppo, Petra, Nubia and the Hijaz, distinguishing European re-identification from prior local knowledge.',nl:'Een kennisreis richting Timboektoe via Arabisch, Aleppo, Petra, Nubië en de Hidjaz, met onderscheid tussen Europese heridentificatie en eerdere lokale kennis.',jv:'Lelakon kawruh kanggo misi Timbuktu liwat sinau basa Arab, Aleppo, Petra, Nubia lan Hijaz, kanthi mbedakake identifikasi Eropa saka kawruh lokal sing wis ana.',he:'מסע ידע שהוכן לטימבוקטו ועבר דרך לימוד ערבית, חלב, פטרה, נוביה והחיג׳אז, תוך הבחנה בין זיהוי אירופי מחדש לבין ידע מקומי קודם.'}},
  {id:'african-association',kind:'research',families:['journeys'],legacy:'011',label:{ar:'الجمعية الإفريقية',en:'African Association',nl:'African Association',jv:'African Association',he:'האגודה האפריקאית'},sub:{ar:'1788 · الخرائط والنيجر',en:'1788 · maps & Niger',nl:'1788 · kaarten & Niger',jv:'1788 · peta & Niger',he:'1788 · מפות וניז׳ר'},href:'african-association.html',confidence:'A',desc:{ar:'مؤسسة استكشافية بريطانية تكشف تداخل العلم والتجارة والقوة، وتفرض سؤالاً نقدياً: عندما قالت أوروبا «مجهول»، هل كان المكان مجهولاً فعلاً أم مجهولاً لأرشيفها؟',en:'A British exploration society revealing intersections of science, commerce and power, and asking whether “unknown” meant unknown to humanity or to European archives.',nl:'Een Britse exploratievereniging op het kruispunt van wetenschap, handel en macht, met de vraag of “onbekend” menselijk onbekend betekende of slechts Europees onbekend.',jv:'Perkumpulan eksplorasi Inggris ing patemon ilmu, dagang lan kuwasa, kanthi pitakon apa “ora dikenal” kuwi ora dikenal manungsa utawa mung ora ana ing arsip Eropa.',he:'אגודת חקר בריטית החושפת מפגש בין מדע, מסחר וכוח ושואלת האם “לא נודע” פירושו לא נודע לאנושות או רק לארכיונים אירופיים.'}},
  {id:'knowledge-journeys',kind:'hub',families:['journeys'],label:{ar:'رحلات المعرفة',en:'Knowledge Journeys',nl:'Kennisreizen',id:'Perjalanan Pengetahuan'},sub:{ar:'المسار التالي',en:'next research family',nl:'volgende onderzoeksfamilie',id:'keluarga riset berikutnya'},confidence:'D',desc:{ar:'عائلة تربط بوركهارت والجمعية الإفريقية وانتقال المعرفة واللغة والخرائط، مع فحص علاقة الاستكشاف بالقوة والسياق المحلي.',en:'Family linking Burckhardt, the African Association, knowledge transfer, language and mapping while testing how exploration intersects with power and local knowledge.',nl:'Familie die Burckhardt, de African Association, kennisoverdracht, taal en cartografie verbindt en de relatie tussen exploratie, macht en lokale kennis onderzoekt.',id:'Keluarga untuk Burckhardt, perkumpulan eksplorasi, transfer pengetahuan dan bahasa; strukturnya siap tanpa menganggap dossier selesai.'}},
  {id:'chaamdeep',kind:'research',families:['land','pilgrimage','lineage'],legacy:'012',label:{ar:'شام تحت السطح',en:'Chaam Beneath the Surface',nl:'Chaam onder het oppervlak',id:'Chaam ing sangisoring lemah'},sub:{ar:'آثار · مقابر · طوائف',en:'archaeology · cemeteries · confessions',nl:'archeologie · begraafplaatsen · confessies',id:'arkeologi · pasarean · tradhisi'},href:'chaam-deep-history.html',confidence:'B',taxonomy:{religion:['christianity','mixed-christian-site'],historicalType:['archaeology','cemetery','church-site']},desc:{ar:'ملف عميق يفصل بين اللقى المؤكدة، مواقع الدفن، طبقات الكنائس والأسئلة الأثرية في شام.',en:'Deep dossier separating confirmed finds, burial grounds, church layers and open archaeological questions in Chaam.',nl:'Diepdossier dat vondsten, begraafplaatsen, kerklagen en open archeologische vragen in Chaam scheidt.',id:'Dossier jero kanggo mbedakake temuan, pasarean, lapisan greja lan pitakon arkeologi Chaam.'}},
  {id:'chaamgene',kind:'research',families:['lineage','land'],legacy:'014',label:{ar:'الرسم النسبي لشام',en:'Chaam Genealogical Graph',nl:'Genealogische graaf Chaam',id:'Graf Silsilah Chaam'},sub:{ar:'سجلات · تعميد · زواج · وفاة · نسب',en:'records · baptisms · marriages · deaths · kinship',nl:'registers · dopen · huwelijken · overlijden · verwantschap',id:'arsip · baptis · nikah · pati · silsilah'},href:'chaam-genealogy.html',confidence:'A',taxonomy:{religion:['roman-catholic'],historicalType:['family']},desc:{ar:'رسم تفاعلي يفصل القرابة المثبتة عن تشابه الألقاب، ويضم طبقة سجلات مستخرجة زمنياً من القرن 17.',en:'Interactive graph separating proven kinship from surname similarity, with a dated extraction layer from seventeenth-century registers.',nl:'Interactieve graaf die bewezen verwantschap scheidt van naamgelijken, met een gedateerde extractielaag uit zeventiende-eeuwse registers.',id:'Graf interaktif sing misahake paseduluran kabukten saka jeneng padha lan ngemot lapisan arsip abad kaping 17.'}},
  {id:'janssen',kind:'research',families:['land','lineage'],legacy:'013',label:{ar:'عائلة يانسن',en:'Janssen Family',nl:'Familie Janssen',id:'Kulawarga Janssen'},sub:{ar:'شام · بارله · شؤون الكنيسة',en:'Chaam · Baarle · church affairs',nl:'Chaam · Baarle · kerkzaken',id:'Chaam · Baarle · urusan greja'},href:'janssen-family.html',confidence:'B',taxonomy:{religion:['reformed-protestant'],historicalType:['family','government']},desc:{ar:'عقدة نسب مؤسساتية تبدأ بـ J. D. Janssen ووالده وتفصل الاسم المشترك عن صلة النسب المثبتة.',en:'Genealogical-institutional node beginning with J. D. Janssen and his father while separating surname matches from proven kinship.',nl:'Genealogisch-institutionele knoop rond J. D. Janssen en zijn vader, zonder naamgenoten automatisch te verbinden.',id:'Simpul silsilah lan lembaga watara J. D. Janssen lan bapake.'}},
  {id:'tongerlo',kind:'institution',families:['land','lineage'],label:{ar:'دير تونغرلو',en:'Tongerlo Abbey',nl:'Abdij Tongerlo',id:'Biara Tongerlo'},sub:{ar:'نوربرتينيون · 1175',en:'Norbertines · 1175',nl:'Norbertijnen · 1175',id:'Norbertin · 1175'},confidence:'A',taxonomy:{religion:['roman-catholic'],historicalType:['abbey']},desc:{ar:'عقدة مؤسساتية موثقة للرعاية الكنسية والملكية في مجال ألفن–شام منذ 1175.',en:'Documented institutional node for ecclesiastical administration and property in the Alphen–Chaam sphere from 1175.',nl:'Gedocumenteerde instelling voor kerkelijk beheer en bezit in de sfeer Alphen–Chaam vanaf 1175.',id:'Simpul lembaga kanggo pangaturan greja lan tanah wiwit 1175.'}},
  {id:'lordsbreda',kind:'institution',families:['land','lineage'],label:{ar:'سادة بريدا',en:'Lords of Breda',nl:'Heren van Breda',id:'Para Panguwasa Breda'},sub:{ar:'سلطة · أرض · رعاية',en:'authority · land · patronage',nl:'gezag · land · patronage',id:'kuwasa · tanah · patronase'},confidence:'B',taxonomy:{religion:['secular-history'],historicalType:['dynasty']},desc:{ar:'عقدة جامعة لسلاسل السلطة الإقليمية؛ تُفكك إلى بيوت منفصلة عندما يوجد رابط موثق.',en:'Umbrella node for regional lordship, split into individual houses when a documented link exists.',nl:'Verzamelknoop voor regionale heerlijkheid, opgesplitst per huis zodra een bron dat draagt.',id:'Simpul umum panguwasa wilayah sing dipisah dadi dinasti yen ana bukti.'}},
  {id:'polanen',kind:'family',families:['land','lineage'],label:{ar:'بيت فان بولانن',en:'House of Polanen',nl:'Huis Van Polanen',id:'Kulawarga Van Polanen'},sub:{ar:'بريدا · سلالة نبيلة',en:'Breda · noble house',nl:'Breda · adellijk huis',id:'Breda · bangsawan'},confidence:'B',taxonomy:{religion:['secular-history'],historicalType:['dynasty']},desc:{ar:'بيت نبيل في تسلسل سادة بريدا؛ لا تُنسب له صلة مباشرة بشام إلا بوثيقة محددة.',en:'Noble house in the sequence of Lords of Breda; no direct Chaam relation is asserted without a specific source.',nl:'Adellijk huis in de reeks Heren van Breda; een directe Chaamse relatie vereist een afzonderlijke bron.',id:'Dinasti bangsawan ing urutan panguwasa Breda; pranala Chaam kudu ana sumber dhewe.'}},
 ],

 edges:[
  ['luxdot','savior','conceptual','D'],['luxdot','redheifer','living-research','D'],['redheifer','savior','messianic-tradition','C'],['petgoat','savior','media-eschatology','C'],['petgoat','redheifer','symbol-comparison','D'],['petgoat','library','source-comparison','C'],['redheifer','library','source','B'],['luxdot','java','method','B'],['luxdot','shaam','place','B'],['luxdot','erasmus','method','D'],['luxdot','busman','tradition','C'],['luxdot','nassau','historical','B'],['luxdot','hoogstraten','historical','B'],['luxdot','shaamnet','historical','B'],['shaamnet','sacred25','network','B'],['shaamnet','shaam','local-core','B'],['shaamnet','alphen','archaeology','B'],['shaamnet','hoogstraten','border-pilgrimage','B'],['shaamnet','nassau','political','B'],['luxdot','memory','system','A'],['luxdot','library','system','A'],['luxdot','projects','system','A'],['luxdot','knowledge-journeys','roadmap','D'],['alphen','shaam','local-history','B'],['alphen','luxdot','research','A'],['alphen','library','sources','A'],
  ['sacred25','shaam','geographic','A'],['sacred25','hoogstraten','geographic','A'],['sacred25','nassau','political','B'],['sacred25','busman','pilgrimage','C'],['kevelaer-chaam','busman','timeline','A'],['kevelaer-chaam','shaam','geographic','B'],['hoogstraten','y1648','historical','B'],['sacred25','y1648','historical','A'],['shaam','y1648','historical','B'],['nassau','y1648','political','B'],['sacred25','y1944','historical','A'],['shaam','y1944','historical','A'],['hoogstraten','y1944','historical','A'],['memory','y1944','memory','B'],['savior','library','source','B'],['java','library','source','B'],['erasmus','projects','system','E'],['java','knowledge-journeys','conceptual','D'],['knowledge-journeys','burckhardt','biographical','A'],['knowledge-journeys','african-association','institutional','A'],['african-association','burckhardt','commission','A'],['burckhardt','java','language-method','D'],['burckhardt','busman','pilgrimage-comparison','D'],['shaamnet','chaamdeep','deep-local','A'],['chaamdeep','shaam','place-layer','A'],['chaamdeep','tongerlo','ecclesiastical','A'],['chaamdeep','janssen','confessional-history','B'],['tongerlo','alphen','ecclesiastical','A'],['tongerlo','shaam','parish-sphere','B'],['lordsbreda','alphen','lordship','B'],['lordsbreda','shaam','regional-authority','B'],['lordsbreda','polanen','dynastic-sequence','B'],['lordsbreda','nassau','dynastic-sequence','B'],['janssen','y1648','confessional-context','B'],['janssen','shaam','church-history','B'],['chaamgene','janssen','genealogy','A'],['chaamgene','chaamdeep','archival-genealogy','A'],['chaamgene','tongerlo','land-record','A']
 ]
 };
// Five-language overlay for the graph. Legacy data keep their original fields;
// Javanese and Hebrew are attached here so the graph never falls back silently.
const JH={
 luxdot:{jv:['LUXDOT','Atlas Panliten','Lapisan kawruh sing nyambungake sumber, klaim, kedadeyan, wong, papan lan hipotesis tanpa nyamaratakan tingkat buktine.'],he:['LUXDOT','אטלס מחקר','שכבת ידע המחברת מקורות, טענות, אירועים, אנשים, מקומות והשערות בלי להשוות את רמות הוודאות שלהן.']},
 savior:{jv:['Atlas Penyelamat','tradhisi kawilujengan','Perbandingan kritis gagasan penyelamat lan pembaruan; kemiripan ora mbuktekake identitas utawa ramalan.'],he:['אטלס המושיע','מסורות גאולה','השוואה ביקורתית של מסורות מושיע והתחדשות; דמיון אינו מוכיח זהות או נבואה.']},
 java:{jv:['Jawa','basa · naskah','Panliten sejarah basa, naskah lan tradhisi Jawa kanthi misahake tafsir LuxDot saka sejarah.'],he:['ג׳אווה','שפה · כתבי יד','מסלול המחבר היסטוריה לשונית, כתבי יד ומסורות ג׳אווניות תוך הפרדת פרשנות LuxDot מן ההיסטוריה.']},
 shaam:{jv:['Chaam–Breda','papan lan pangeling','Atlas papan, pangeling, kepedulian lan sejarah lokal tanpa miwiti saka anggapan yen papan iku suci.'],he:['שאם–ברדה','מקום וזיכרון','אטלס של מקום, זיכרון, טיפול והיסטוריה מקומית שאינו מתחיל בהנחת קדושה.']},
 erasmus:{jv:['Erasmus','jembatan · karsa · tabrakan','Kedadeyan modern dadi tes urip: fakta teknis dipisah saka tafsir filosofis lan simbolis.'],he:['ארסמוס','גשר · רצון · התנגשות','אירוע מודרני המשמש מבחן חי: עובדות טכניות בשכבה אחת ופרשנות פילוסופית/סמלית בשכבה אחרת.']},
 busman:{jv:['Hendrick Busman','Kevelaer · 1641','Misahake sejarah ziarah sing kacathet saka crita panggilan minangka tradhisi devosi.'],he:['הנדריק בוסמן','קבלאר · 1641','מפריד בין היסטוריה מתועדת של העלייה לרגל לבין סיפור הקריאה כמסורת דתית.']},
 nassau:{jv:['Urania × Nassau','garis keturunan · kuwasa · Breda','Simpul sejarah sing misahake Urania sastra saka dinasti Nassau lan nglacak sambungan politik lan genealogis.'],he:['אוראניה × נאסאו','שושלת · כוח · ברדה','צומת היסטורי המפריד בין אוראניה הספרותית לבית נאסאו ועוקב אחר קשרים פוליטיים ושושלתיים מתועדים.']},
 'kevelaer-chaam':{jv:['Kevelaer ↔ Chaam','garis wektu','Garis wektu sing nyambungake titik bersumber lan njaga koreksi.'],he:['קבלאר ↔ שאם','ציר זמן','ציר זמן מבוקר המחבר נקודות מבוססות מקור ושומר תיקונים.']},
 hoogstraten:{jv:['Hoogstraten','getih lan wates','Greja St Katharina dadi simpul bangsawan, relik, ziarah, wates, perang lan pambangunan maneh.'],he:['הוחסטראטן','דם וגבולות','כנסיית קתרינה כצומת בין אצולה, מסורת שרידים, עלייה לרגל, גבולות, מלחמה ושיקום.']},
 shaamnet:{jv:['Jaringan Chaam–Brabant','inti 50 km · jaringan 120 km','Panliten induk sing nyambungake cabang papan, lembaga lan wektu.'],he:['רשת שאם–בראבנט','ליבה 50 ק״מ · רשת 120 ק״מ','מחקר־אב המחבר את ענפי המקום, המוסדות והזמן.']},
 sacred25:{jv:['Atlas Jaringan 120 km','inti 50 · jaringan 120','Register simpul sejarah, agama lan arkeologi kanthi aturan bukti sing cetha.'],he:['אטלס רשת 120 ק״מ','ליבה 50 · רשת 120','מרשם צמתים היסטוריים, דתיים וארכאולוגיים עם כלל ראיות מפורש.']},
 y1648:{jv:['1648','simpul wektu','Simpul sejarah sing nerangake akeh owah-owahan agama lan wates ing wilayah iki sawise Damai Münster.'],he:['1648','צומת זמן','צומת היסטורי המסביר שינויים דתיים וגבוליים רבים באזור לאחר שלום מינסטר.']},
 y1944:{jv:['1944','perang · menara','Simpul kanggo mbandhingake karusakan menara lan greja kanthi prioritas penjelasan militer sadurunge tafsir simbolis.'],he:['1944','מלחמה · מגדלים','צומת להשוואת הרס מגדלים וכנסיות, תוך העדפת ההסבר הצבאי לפני פרשנות סמלית.']},
 memory:{jv:['Pangeling Urip','wong lan paseksi','Pangeling njaga wong lan kedadeyan; panliten bisa nyambung tanpa ngowahi korban dadi hipotesis.'],he:['זיכרון חי','אנשים ועדות','הזיכרון שומר אנשים ואירועים; מחקר יכול לקשר אליהם בלי להפוך קורבנות להשערות.']},
 library:{jv:['Pustaka','teks lan sumber','Teks ora otomatis dadi bukti; pustaka njaga sumber nalika panliten nguji klaim.'],he:['ספרייה','טקסטים ומקורות','טקסט אינו ראיה רק מפני שהוא קיים; הספרייה שומרת מקורות והמחקר בודק טענות.']},
 projects:{jv:['Proyek','tumindak ing lapangan','Proyek yaiku tumindak nyata lan inisiatif, dudu panggonan nyimpen teori.'],he:['פרויקטים','פעולה בשטח','פרויקטים הם פעולות ויוזמות בשטח, לא מאגר למחקר תאורטי.']},
 chaamdeep:{jv:['Chaam ing sangisoring lemah','arkeologi · pasarean · tradhisi','Dossier jero kanggo arkeologi lan lapisan agama Chaam.'],he:['שאם מתחת לפני השטח','ארכאולוגיה · קבורה · זרמים','תיק עומק לארכאולוגיה ולשכבות הדתיות של שאם.']},
 janssen:{jv:['Kulawarga Janssen','Chaam · Baarle · urusan greja','Simpul silsilah sing misahake jeneng padha saka paseduluran sing kabukten.'],he:['משפחת יאנסן','שאם · בארלה · ענייני כנסייה','צומת גנאלוגי המפריד זהות שם מקרבה מוכחת.']},
 tongerlo:{jv:['Biara Tongerlo','Norbertin · 1175','Simpul lembaga greja Alphen–Chaam.'],he:['מנזר טונגרלו','נורברטינים · 1175','צומת מוסדי במרחב אלפן–שאם.']},
 lordsbreda:{jv:['Para Panguwasa Breda','kuwasa · tanah · patronase','Simpul panguwasa wilayah Breda.'],he:['אדוני ברדה','שלטון · קרקע · חסות','צומת שלטון אזורי של ברדה.']},
 polanen:{jv:['Kulawarga Van Polanen','Breda · bangsawan','Dinasti ing urutan panguwasa Breda.'],he:['בית ואן פולאנן','ברדה · אצולה','בית אצולה ברצף אדוני ברדה.']},
 'knowledge-journeys':{jv:['Lelakon Kawruh','basa · peta · eksplorasi','Kulawarga sing nyambungake Burckhardt, African Association, basa, peta lan pindhahing kawruh nalika nguji sambungane karo kuwasa lan kawruh lokal.'],he:['מסעות ידע','שפה · מפות · חקר','משפחה המחברת את בורקהרדט, האגודה האפריקאית, שפה, מיפוי והעברת ידע תוך בדיקת הקשר בין חקר, כוח וידע מקומי.']}
};
DATA.nodes.forEach(n=>{const x=JH[n.id];if(x){n.label.jv=x.jv[0];n.sub.jv=x.jv[1];n.desc.jv=x.jv[2];n.label.he=x.he[0];n.sub.he=x.he[1];n.desc.he=x.he[2]}});
const FJH={meaning:{jv:['Manungsa lan Makna','kawilujengan, tradhisi, teks, Jawa'],he:['אדם ומשמעות','גאולה, מסורות, טקסטים, ג׳אווה']},land:{jv:['Tanah lan Wates','Chaam, Breda, Baarle, Hoogstraten, Nassau'],he:['ארץ וגבולות','שאם, ברדה, בארלה, הוחסטראטן, נאסאו']},pilgrimage:{jv:['Ziarah lan Tandha','Kevelaer, Busman, relik, dalan'],he:['עלייה לרגל ואות','קבלאר, בוסמן, שרידים, דרכים']},choice:{jv:['Pilihan lan Tanggung Jawab','Erasmus, jembatan, sistem, mandheg'],he:['בחירה ואחריות','ארסמוס, גשר, מערכת, עצירה']},lineage:{jv:['Kulawarga lan Lembaga','silsilah, patronase, panguwasa, jaringan kulawarga'],he:['משפחות ומוסדות','גנאלוגיה, חסות, שלטון ורשתות משפחה']},journeys:{jv:['Lelakon Kawruh','pindhahing kawruh, basa, eksplorasi'],he:['מסעות ידע','העברת ידע, שפה, חקר']}};
DATA.families.forEach(f=>{const x=FJH[f.id];if(x){f.jv=x.jv[0];f.he=x.he[0];f.desc.jv=x.jv[1];f.desc.he=x.he[1]}});
const L=()=>((window.LuxLang&&window.LuxLang.get())||'en');
const langKey=()=>{const l=L();return ['ar','en','nl','jv','he'].includes(l)?l:'en'};
const t=(obj)=>obj?.[langKey()]||obj?.en||obj?.ar||'';

const TAXV={
 'christianity':{ar:'المسيحية',en:'Christianity',nl:'Christendom',jv:'Kristen',he:'נצרות'},
 'mixed-christian-site':{ar:'موقع مسيحي متعدد الطبقات',en:'multi-confessional Christian site',nl:'meerlagige christelijke site',jv:'situs Kristen majemuk',he:'אתר נוצרי רב-שכבתי'},
 'reformed-protestant':{ar:'بروتستانتية إصلاحية',en:'Reformed Protestant',nl:'hervormd/protestants',jv:'Protestan Reformasi',he:'פרוטסטנטיות רפורמית'},
 'roman-catholic':{ar:'كاثوليكية رومانية',en:'Roman Catholic',nl:'rooms-katholiek',jv:'Katulik Roma',he:'קתוליות רומית'},
 'secular-history':{ar:'تاريخ مدني/سياسي',en:'secular/political history',nl:'seculiere/politieke geschiedenis',jv:'sejarah sekuler/politik',he:'היסטוריה חילונית/פוליטית'},
 'archaeology':{ar:'آثار وحفريات',en:'archaeology & excavation',nl:'archeologie & opgraving',jv:'arkeologi & penggalian',he:'ארכאולוגיה וחפירות'},
 'cemetery':{ar:'مقبرة',en:'cemetery',nl:'begraafplaats',jv:'pasarean',he:'בית קברות'},
 'church-site':{ar:'موقع كنسي',en:'church site',nl:'kerklocatie',jv:'situs greja',he:'אתר כנסייתי'},
 'family':{ar:'عائلة/نسب',en:'family/genealogy',nl:'familie/genealogie',jv:'kulawarga/silsilah',he:'משפחה/גנאלוגיה'},
 'government':{ar:'إدارة وسياسة دينية',en:'government & religious policy',nl:'bestuur & religiebeleid',jv:'pamrentahan & kabijakan agama',he:'ממשל ומדיניות דת'},
 'abbey':{ar:'دير ومؤسسة كنسية',en:'abbey & ecclesiastical institution',nl:'abdij & kerkelijke instelling',jv:'biara & lembaga greja',he:'מנזר ומוסד כנסייתי'},
 'dynasty':{ar:'سلالة نبيلة/حاكمة',en:'noble/ruling dynasty',nl:'adellijke/heersende dynastie',jv:'dinasti bangsawan',he:'שושלת אצולה/שלטון'}
};
const taxV=(v)=>TAXV[v]?.[langKey()]||TAXV[v]?.en||v;
const root=document.querySelector('[data-research-graph]'); if(!root)return;
const UI={
 ar:{title:'أطلس أبحاث لوكسدوت',lead:'ليست الأبحاث قائمة ملفات منفصلة. هذه الطبقة تربط الإنسان والمكان والزمن والذاكرة والإشارة، وتُظهر نوع كل علاقة ودرجة الثقة فيها دون خلط الحقيقة بالرواية أو الفرضية.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'المصدر قبل التفسير',method2:'العلاقة لها نوع ودرجة ثقة',method3:'الدليل المضاد جزء من البحث',method4:'الأبحاث القديمة محفوظة كمعرّفات تاريخية',search:'ابحث عن مكان، سنة، شخص، مفهوم أو بحث…',legend:'مقياس الثقة',systems:'فصل الوظائف داخل LuxDot',a:'A · مثبت أولياً',ad:'مصدر أولي أو أرشيف أو دليل قوي مباشر',b:'B · مثبت جيداً',bd:'عدة مصادر موثوقة أو علاقة تاريخية قوية',c:'C · تقليد موثق',cd:'نعرف أن الرواية موجودة تاريخياً؛ الحدث الخارق نفسه غير مثبت',d:'D · فرضية LuxDot',dd:'تفسير قابل للاختبار والمراجعة',e:'E · سؤال مفتوح',ed:'تشابه أو إشارة ضعيفة تُسجل ولا تُعامل كدليل',research:'البحث الحي',researchD:'يفحص ما حدث ولماذا وما الذي يمكن اختباره.',memory:'الذاكرة الحية',memoryD:'تحفظ الأشخاص والشهود والضحايا دون تحويلهم إلى فرضيات.',library:'المكتبة',libraryD:'تحفظ النصوص والمصادر؛ وجود النص لا يجعله دليلاً على تفسير.',projects:'المشاريع',projectsD:'أفعال ومبادرات على الأرض، وليست مخزناً للأبحاث النظرية.'},
 en:{title:'LuxDot Research Atlas',lead:'Research is no longer a list of isolated files. This layer connects human, place, time, memory and signal, showing the type and confidence of each relation without flattening fact, tradition and hypothesis.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Source before interpretation',method2:'Every relation has a type and confidence',method3:'Counter-evidence belongs inside the research',method4:'Old research numbers remain as legacy IDs',search:'Search a place, year, person, concept or dossier…',legend:'Confidence scale',systems:'Functional separation inside LuxDot',a:'A · Primary evidence',ad:'Primary source, archive or strong direct evidence',b:'B · Well established',bd:'Multiple reliable sources or strong historical relation',c:'C · Documented tradition',cd:'The tradition is historically attested; the supernatural event itself is not established',d:'D · LuxDot hypothesis',dd:'Interpretation open to testing and revision',e:'E · Open signal',ed:'Weak intersection or question recorded without treating it as evidence',research:'Living Research',researchD:'Tests what happened, why, and what can be falsified.',memory:'Living Memory',memoryD:'Preserves people, witnesses and victims without turning them into hypotheses.',library:'Library',libraryD:'Preserves texts and sources; a text’s existence does not prove an interpretation.',projects:'Projects',projectsD:'Actions and initiatives on the ground, not storage for theoretical research.'},
 nl:{title:'LuxDot Onderzoeksatlas',lead:'Onderzoek is niet langer een lijst losse bestanden. Deze laag verbindt mens, plaats, tijd, geheugen en signaal en toont het type en de bewijskracht van elke relatie.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Bron vóór interpretatie',method2:'Elke relatie heeft type en bewijskracht',method3:'Tegenbewijs hoort in het onderzoek',method4:'Oude nummers blijven als historische ID’s',search:'Zoek plaats, jaar, persoon, begrip of dossier…',legend:'Bewijsschaal',systems:'Functies binnen LuxDot gescheiden',a:'A · Primair bewijs',ad:'Primaire bron, archief of sterk direct bewijs',b:'B · Goed bevestigd',bd:'Meerdere betrouwbare bronnen of sterke historische relatie',c:'C · Gedocumenteerde traditie',cd:'De traditie is historisch gedocumenteerd; het bovennatuurlijke gebeuren zelf niet',d:'D · LuxDot-hypothese',dd:'Interpretatie die toetsbaar en herzienbaar blijft',e:'E · Open signaal',ed:'Zwakke kruising of vraag, geregistreerd maar niet als bewijs behandeld',research:'Levend Onderzoek',researchD:'Onderzoekt wat gebeurde, waarom en wat toetsbaar is.',memory:'Levend Geheugen',memoryD:'Bewaart mensen, getuigen en slachtoffers zonder ze tot hypotheses te maken.',library:'Bibliotheek',libraryD:'Bewaart teksten en bronnen; bestaan van tekst bewijst geen interpretatie.',projects:'Projecten',projectsD:'Acties en initiatieven in de praktijk, geen opslag voor theorie.'},
 id:{title:'Atlas Riset LuxDot',lead:'Riset bukan lagi daftar berkas terpisah. Lapisan ini menghubungkan manusia, tempat, waktu, memori dan sinyal serta menampilkan jenis dan tingkat keyakinan setiap hubungan.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Sumber sebelum tafsir',method2:'Setiap hubungan punya jenis dan tingkat keyakinan',method3:'Bukti penyangkal adalah bagian riset',method4:'Nomor riset lama tetap sebagai ID historis',search:'Cari tempat, tahun, orang, konsep atau dossier…',legend:'Skala keyakinan',systems:'Pemisahan fungsi di LuxDot',a:'A · Bukti primer',ad:'Sumber primer, arsip atau bukti langsung kuat',b:'B · Terbukti baik',bd:'Beberapa sumber tepercaya atau hubungan sejarah kuat',c:'C · Tradisi terdokumentasi',cd:'Tradisinya tercatat; peristiwa supranaturalnya sendiri tidak terbukti',d:'D · Hipotesis LuxDot',dd:'Tafsir yang terbuka untuk diuji dan direvisi',e:'E · Sinyal terbuka',ed:'Persilangan lemah atau pertanyaan yang dicatat tanpa dianggap bukti',research:'Riset Hidup',researchD:'Menguji apa yang terjadi, mengapa dan apa yang dapat diuji.',memory:'Memori Hidup',memoryD:'Menjaga orang, saksi dan korban tanpa mengubahnya menjadi hipotesis.',library:'Perpustakaan',libraryD:'Menjaga teks dan sumber; keberadaan teks tidak membuktikan tafsir.',projects:'Proyek',projectsD:'Aksi dan inisiatif di lapangan, bukan tempat menyimpan teori.',
 jv:{title:'Atlas Panliten LuxDot',lead:'Panliten ora mung dhaptar berkas. Lapisan iki nyambungake manungsa, papan, wektu, pangeling lan tandha, lan nuduhake jinis lan tingkat bukti saben sambungan.',kicker:'LUXDOT / RESEARCH GRAPH / V4.1',method1:'Sumber sadurunge tafsir',method2:'Saben sambungan duwe jinis lan tingkat bukti',method3:'Bukti sing mbantah uga bagean panliten',method4:'Nomer lawas tetep dadi ID sejarah',search:'Goleki papan, taun, wong, konsep utawa dossier…',legend:'Skala kapercayan',systems:'Pemisahan fungsi ing LuxDot',a:'A · Bukti primer',ad:'Sumber primer, arsip utawa bukti langsung kuwat',b:'B · Kabukten apik',bd:'Akeh sumber dipercaya utawa sambungan sejarah kuwat',c:'C · Tradhisi kacathet',cd:'Tradhisine kacathet; kedadeyan gaib dhewe durung kabukten',d:'D · Hipotesis LuxDot',dd:'Tafsir sing bisa dites lan direvisi',e:'E · Pitakon mbukak',ed:'Persilangan ringkih sing dicathet tanpa dianggep bukti',research:'Panliten Urip',researchD:'Nguji apa sing kedadeyan, sebab lan apa sing bisa dites.',memory:'Pangeling Urip',memoryD:'Njaga wong, saksi lan korban tanpa ngowahi dadi hipotesis.',library:'Pustaka',libraryD:'Njaga teks lan sumber; anane teks ora mbuktekake tafsir.',projects:'Proyek',projectsD:'Tumindak lan inisiatif ing lapangan, dudu gudang teori.'},
 he:{title:'אטלס המחקר של LuxDot',lead:'המחקרים אינם עוד רשימת קבצים נפרדים. שכבה זו מחברת אדם, מקום, זמן, זיכרון ואות ומציגה את סוג הקשר ורמת הוודאות שלו.',kicker:'LUXDOT / RESEARCH GRAPH / V4.1',method1:'מקור לפני פרשנות',method2:'לכל קשר יש סוג ורמת ודאות',method3:'ראיות נגד הן חלק מן המחקר',method4:'מספרי המחקר הישנים נשמרים כמזהים היסטוריים',search:'חפש מקום, שנה, אדם, מושג או תיק…',legend:'סולם ודאות',systems:'הפרדת תפקידים בתוך LuxDot',a:'A · ראיה ראשונית',ad:'מקור ראשוני, ארכיון או ראיה ישירה חזקה',b:'B · מבוסס היטב',bd:'מספר מקורות אמינים או קשר היסטורי חזק',c:'C · מסורת מתועדת',cd:'המסורת מתועדת היסטורית; האירוע העל-טבעי עצמו אינו מוכח',d:'D · השערת LuxDot',dd:'פרשנות הפתוחה לבדיקה ולתיקון',e:'E · שאלה פתוחה',ed:'חפיפה חלשה או שאלה המתועדת בלי להיחשב ראיה',research:'מחקר חי',researchD:'בודק מה קרה, מדוע ומה ניתן להפריך.',memory:'זיכרון חי',memoryD:'שומר אנשים, עדים וקורבנות בלי להפוך אותם להשערות.',library:'ספרייה',libraryD:'שומרת טקסטים ומקורות; קיום טקסט אינו מוכיח פרשנות.',projects:'פרויקטים',projectsD:'פעולות ויוזמות בשטח, לא מאגר למחקר תאורטי.'}}}
function applyUI(){const u=UI[langKey()]||UI.en;document.querySelectorAll('[data-ui]').forEach(el=>{const k=el.dataset.ui;if(u[k]!=null)el.textContent=u[k]});const inp=document.querySelector('.rg-search');if(inp)inp.placeholder=u.search;document.title=u.title+' · LuxDot';}
applyUI();

const svg=root.querySelector('svg');const detail=root.querySelector('.rg-detail');const familyBox=root.querySelector('.rg-family-grid');const search=root.querySelector('.rg-search');
const W=1500,H=860,cx=W/2,cy=H/2;
const familyPos={meaning:[210,145],land:[980,150],pilgrimage:[1010,510],choice:[590,590],journeys:[170,515]};
const positions={petgoat:[420,80],luxdot:[720,405],savior:[165,90],redheifer:[315,90],java:[285,205],shaam:[915,95],erasmus:[650,570],busman:[1040,440],nassau:[850,210],'kevelaer-chaam':[930,410],hoogstraten:[1080,260],shaamnet:[775,325],sacred25:[860,390],alphen:[720,95],y1648:[690,205],y1944:[765,485],memory:[485,120],library:[350,350],projects:[505,525],'knowledge-journeys':[170,500],burckhardt:[285,545],'african-association':[65,430],chaamdeep:[1110,90],janssen:[1260,210],tongerlo:[1010,300],lordsbreda:[1210,380],polanen:[1370,430],chaamgene:[1330,90]};
function renderFamilies(){familyBox.innerHTML='<button class="rg-family active" data-family="all"><strong>'+({ar:'الكل',en:'All research',nl:'Alles',jv:'Kabeh',he:'הכול'}[langKey()]||'All')+'</strong><small>'+({ar:'كل العائلات والعقد',en:'all families and nodes',nl:'alle families en knopen',jv:'kabeh kulawarga lan simpul',he:'כל המשפחות והצמתים'}[langKey()]||'')+'</small></button>'+DATA.families.map(f=>`<button class="rg-family" data-family="${f.id}"><strong>${t({ar:f.ar,en:f.en,nl:f.nl,jv:f.jv,he:f.he})}</strong><small>${t(f.desc)}</small></button>`).join('');}
function renderGraph(){svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=''; const eg=document.createElementNS('http://www.w3.org/2000/svg','g');const ng=document.createElementNS('http://www.w3.org/2000/svg','g');svg.append(eg,ng);
 DATA.edges.forEach((e,i)=>{const [a,b,type,conf]=e,p1=positions[a],p2=positions[b];if(!p1||!p2)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',p1[0]);line.setAttribute('y1',p1[1]);line.setAttribute('x2',p2[0]);line.setAttribute('y2',p2[1]);line.setAttribute('class','rg-edge');line.dataset.a=a;line.dataset.b=b;line.dataset.type=type;line.dataset.confidence=conf;eg.append(line)});
 DATA.nodes.forEach(n=>{const p=positions[n.id];if(!p)return;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','rg-node');g.dataset.id=n.id;g.dataset.kind=n.kind;g.dataset.families=n.families?.join(',')||'';g.setAttribute('transform',`translate(${p[0]} ${p[1]})`);const r=n.kind==='hub'?42:n.kind==='time'?30:34;g.innerHTML=`<circle r="${r}"></circle><text y="-2">${esc(t(n.label))}</text><text class="sub" y="13">${esc(t(n.sub)||n.legacy||'')}</text>`;g.addEventListener('click',()=>openNode(n.id));ng.append(g)});
 applyFilter();}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
let activeFamily='all',query='';
function applyFilter(){document.querySelectorAll('.rg-node').forEach(el=>{const n=DATA.nodes.find(x=>x.id===el.dataset.id);const fam=activeFamily==='all'||n?.families?.includes(activeFamily)||(n?.kind==='hub'&&n?.id==='luxdot');const q=!query||[t(n?.label),t(n?.sub),t(n?.desc),n?.legacy,JSON.stringify(n?.taxonomy||{})].join(' ').toLowerCase().includes(query);el.classList.toggle('dim',!(fam&&q));});document.querySelectorAll('.rg-edge').forEach(el=>{const a=document.querySelector(`.rg-node[data-id="${el.dataset.a}"]`),b=document.querySelector(`.rg-node[data-id="${el.dataset.b}"]`);el.classList.toggle('dim',a?.classList.contains('dim')||b?.classList.contains('dim'));});}
function openNode(id){const n=DATA.nodes.find(x=>x.id===id);if(!n)return;document.querySelectorAll('.rg-node').forEach(x=>x.classList.toggle('active',x.dataset.id===id));const related=DATA.edges.filter(e=>e[0]===id||e[1]===id).map(e=>{const other=e[0]===id?e[1]:e[0];return {n:DATA.nodes.find(x=>x.id===other),type:e[2],conf:e[3]}}).filter(x=>x.n);const openLabel={ar:'فتح العقدة',en:'Open node',nl:'Open knoop',jv:'Bukak simpul',he:'פתח צומת'}[langKey()];const classLabel={ar:'التصنيف',en:'Classification',nl:'Classificatie',jv:'Klasifikasi',he:'סיווג'}[langKey()];const taxLabels={religion:{ar:'دين/طائفة',en:'religion/tradition',nl:'religie/traditie',jv:'agama/tradhisi',he:'דת/מסורת'},historicalType:{ar:'نوع تاريخي',en:'historical type',nl:'historisch type',jv:'jinis sejarah',he:'סוג היסטורי'}};const relLabel={ar:'روابط مباشرة',en:'Direct links',nl:'Directe links',jv:'Sambungan langsung',he:'קישורים ישירים'}[langKey()];detail.innerHTML=`<button class="rg-close" aria-label="close">×</button><div class="rg-kicker">${n.legacy?'LEGACY '+n.legacy:n.kind.toUpperCase()}</div><h3>${esc(t(n.label))}</h3><p>${esc(t(n.desc))}</p><div class="rg-tags">${(n.families||[]).map(f=>`<span class="rg-tag">${esc(tFamily(f))}</span>`).join('')}${n.confidence?`<span class="rg-tag conf">${n.confidence}</span>`:''}${n.taxonomy?Object.entries(n.taxonomy).flatMap(([k,vals])=>(vals||[]).map(v=>`<span class="rg-tag tax">${esc((taxLabels[k]&&taxLabels[k][langKey()])||k)}: ${esc(taxV(v))}</span>`)).join(''):''}</div>${n.href?`<a class="rg-link" href="${n.href}">${openLabel}</a>`:''}<h4>${relLabel}</h4><div class="rg-tags">${related.map(r=>`<button class="rg-btn" data-open="${r.n.id}">${esc(t(r.n.label))} · ${r.type} · ${r.conf}</button>`).join('')}</div>`;detail.classList.add('open');detail.querySelector('.rg-close').onclick=()=>detail.classList.remove('open');detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openNode(b.dataset.open));}
function tFamily(id){const f=DATA.families.find(x=>x.id===id);return f?t({ar:f.ar,en:f.en,nl:f.nl,jv:f.jv,he:f.he}):id}
renderFamilies();renderGraph();familyBox.addEventListener('click',e=>{const b=e.target.closest('[data-family]');if(!b)return;activeFamily=b.dataset.family;familyBox.querySelectorAll('.rg-family').forEach(x=>x.classList.toggle('active',x===b));applyFilter()});search.addEventListener('input',()=>{query=search.value.trim().toLowerCase();applyFilter()});
root.querySelectorAll('[data-conf]').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('active');const c=b.dataset.conf;document.querySelectorAll('.rg-edge').forEach(e=>{if(e.dataset.confidence===c)e.style.display=b.classList.contains('active')?'':'none'})}));
window.addEventListener('storage',e=>{if(e.key==='luxdot.lang')location.reload()});document.querySelectorAll('[data-lang-select]').forEach(sel=>sel.addEventListener('change',()=>setTimeout(()=>location.reload(),80)));
})();
