(()=>{
'use strict';
const root=document.querySelector('[data-research-graph]'); if(!root)return;
const svg=root.querySelector('.rg-canvas'),detail=root.querySelector('.rg-detail'),search=root.querySelector('.rg-search');
const confBtns=[...root.querySelectorAll('[data-conf]')],viewBtns=[...root.querySelectorAll('[data-research-view]')]; if(!svg)return;
const NS='http://www.w3.org/2000/svg',W=1800,H=1020; svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('preserveAspectRatio','xMidYMid meet');
const lang=()=>new URLSearchParams(location.search).get('lang')||document.documentElement.lang||'en';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const safeTitle=t=>String(t||'').replace(/\s*·\s*LuxDot\s*$/i,'').replace(/\s*\|\s*LuxDot\s*$/i,'').trim();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let nodes=[],edges=[],degree={},mode=localStorage.getItem('luxdot.research.view.v4')||'sky',query='';
let activeConf=new Set(['A','B','C','D','E']);
const skipIds=new Set(['research.html','home.html','index.html','faith.html','projects.html','memory.html','library.html','humanity.html','media.html','audiovisual.html','witness.html']);
const GALAXIES=[
{id:'savior',label:{ar:'الخلاص والنبوءات',en:'Savior & Prophecy'},keys:/savior|mahdi|messiah|messian|chosen|red-heifer|apocalyp|qaim|mashiach|مخل|مهدي|مسيح|نبوء/},
{id:'jewish',label:{ar:'اليهودية والسفارديم',en:'Judaism & Sephardim'},keys:/jew|talmud|kabb|seph|maimon|abulafia|karo|yosef|sabbatai|luria|يهود|قبالا|تلمود|سفارد/},
{id:'shaam',label:{ar:'شام وبرابانت',en:'Chaam & Brabant'},keys:/chaam|shaam|brabant|breda|alphen|hoogstraten|tongerlo|nassau|withagen|velthoven|شام|برابانت|بريدا/},
{id:'history',label:{ar:'التاريخ والحضارات',en:'History & Civilizations'},keys:/history|egypt|prewriting|archae|templar|medieval|roman|civilization|تاريخ|حضار|آثار|هيكل/},
{id:'science',label:{ar:'العلوم والحدود',en:'Science & Frontiers'},keys:/science|quantum|genetic|cognition|neuro|biology|physics|chem|psychoactive|علم|كموم|جين|إدراك/},
{id:'memory',label:{ar:'الذاكرة والشهادة',en:'Memory & Witness'},keys:/memory|martyr|ghouta|westerweel|kolbe|stein|roger|witness|ذاكرة|شهيد|غوطة|شهادة/},
{id:'language',label:{ar:'الرمز واللغة والعدد',en:'Symbol, Language & Number'},keys:/letter|number|gematria|jafr|huruf|lexicon|symbol|name-date|حرف|عدد|جفر|رمز|اسم/},
{id:'journey',label:{ar:'الرحلات والحج والإشارة',en:'Journeys & Pilgrimage'},keys:/journey|pilgrim|kevelaer|busman|petra|burckhardt|signal|حج|رحل|بترا|إشارة/},
{id:'people',label:{ar:'الأشخاص والعائلات',en:'People & Families'},keys:/family|network|prince|person|genealog|de-koning|janssen|midwives|عائلة|شبكة|أمير|نسب/},
{id:'knowledge',label:{ar:'المعرفة والمنهج',en:'Knowledge & Method'},keys:/knowledge|law|method|epistem|research-standard|balance|falsification|معرفة|منهج|قانون|تفنيد/}
];
function galaxyOf(n){const z=(n.id+' '+n.title).toLowerCase();return (GALAXIES.find(g=>g.keys.test(z))||GALAXIES[9]).id}
function confOf(r){const c=String(r.confidence||'').toUpperCase();if(/^[A-E]$/.test(c))return c;const s=Number(r.external_sources||0);return s>=12?'A':s>=5?'B':s>=1?'C':'D'}
function build(man){const map=new Map();Object.entries(man||{}).forEach(([id,r])=>{const rid=r.id||id;if(skipIds.has(rid))return;const n={id:rid,title:safeTitle(r.title||rid.replace(/\.html$/,'').replace(/[-_]/g,' ')),href:rid,sources:Number(r.external_sources||0),confidence:confOf(r),related:(r.related||[]).filter(x=>x&&x.id&&!skipIds.has(x.id)),review:r.review_status||'',standard:r.standard||''};n.galaxy=galaxyOf(n);map.set(n.id,n)});for(const n of map.values())for(const rel of n.related){if(!map.has(rel.id)&&/\.html$/i.test(rel.id)){const m={id:rel.id,title:safeTitle(rel.title||rel.id.replace(/\.html$/,'').replace(/[-_]/g,' ')),href:rel.id,sources:0,confidence:'C',related:[],review:'',standard:''};m.galaxy=galaxyOf(m);map.set(m.id,m)}}nodes=[...map.values()];edges=[];degree={};const seen=new Set();for(const n of nodes)for(const rel of n.related){if(!map.has(rel.id))continue;const k=[n.id,rel.id].sort().join('|');if(seen.has(k))continue;seen.add(k);edges.push([n.id,rel.id]);degree[n.id]=(degree[n.id]||0)+1;degree[rel.id]=(degree[rel.id]||0)+1}nodes.forEach(n=>{n.degree=degree[n.id]||0;n.major=n.sources>=8||n.degree>=5||/atlas|galaxy|network|master|matrix/i.test(n.id)})}
function filtered(){return nodes.filter(n=>activeConf.has(n.confidence)&&(!query||(n.title+' '+n.id).toLowerCase().includes(query)))}
function make(tag,attrs={},text=''){const el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,String(v));if(text)el.textContent=text;return el}
function clear(){svg.innerHTML=''}
function tooltip(){let t=document.getElementById('luxResearchHover');if(!t){t=document.createElement('div');t.id='luxResearchHover';document.body.append(t)}return t}
function placeTip(e,t){const pad=14,w=t.offsetWidth||300,h=t.offsetHeight||130;let x=e.clientX+16,y=e.clientY+16;if(x+w>innerWidth-pad)x=e.clientX-w-16;if(y+h>innerHeight-pad)y=e.clientY-h-16;t.style.left=Math.max(pad,x)+'px';t.style.top=Math.max(pad,y)+'px'}
function showHover(n,e){const t=tooltip(),L=lang();t.innerHTML=`<b>${esc(n.title)}</b><div class="meta">${L==='ar'?'الثقة':'Confidence'} ${esc(n.confidence)} · ${L==='ar'?'المصادر':'Sources'} ${n.sources} · ${L==='ar'?'الروابط':'Links'} ${n.degree}</div><div>${esc((GALAXIES.find(g=>g.id===n.galaxy)?.label[L])||(GALAXIES.find(g=>g.id===n.galaxy)?.label.en)||'')}</div><div style="margin-top:7px"><a href="${encodeURI(n.href)}?lang=${encodeURIComponent(L)}">${L==='ar'?'فتح البحث':'Open research'} ↗</a></div>`;t.classList.add('is-open');placeTip(e,t)}
function hideHover(){const t=tooltip();setTimeout(()=>{if(!t.matches(':hover'))t.classList.remove('is-open')},80)}
function showDetail(n){if(!detail)return;detail.innerHTML=`<div class="rg-detail-card"><b>${esc(n.title)}</b><p>${esc(n.id)}</p><p>Confidence ${esc(n.confidence)} · Sources ${n.sources} · Links ${n.degree}</p><a href="${encodeURI(n.href)}?lang=${encodeURIComponent(lang())}">${lang()==='ar'?'فتح البحث':'Open research'} ↗</a></div>`}
function nodeRadius(n){return n.major?12:n.sources>=3?8:6}
function drawNode(layer,n,p,{label=true,minor=false,shape='circle'}={}){const g=make('g',{class:`rg-node ${n.major?'major':''}`,transform:`translate(${p[0]} ${p[1]})`,tabindex:'0','data-id':n.id,'data-title':n.title,'data-href':n.href,'data-confidence':n.confidence,'data-sources':n.sources,'data-links':n.degree});const core=shape==='rect'?make('rect',{x:-30,y:-15,width:60,height:30,rx:6,class:'rg-star-core'}):make('circle',{r:nodeRadius(n),class:'rg-star-core'});g.append(core);if(label)g.append(make('text',{x:0,y:shape==='rect'?27:22,'text-anchor':'middle',class:`rg-node-label ${minor?'minor':''}`},n.title.length>27?n.title.slice(0,25)+'…':n.title));g.addEventListener('click',()=>showDetail(n));g.addEventListener('pointerenter',e=>showHover(n,e));g.addEventListener('pointermove',e=>placeTip(e,tooltip()));g.addEventListener('pointerleave',hideHover);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')location.href=`${n.href}?lang=${encodeURIComponent(lang())}`});layer.append(g)}
function addDust(bg,count=120){for(let i=0;i<count;i++){const x=30+(hash('dx'+i)%(W-60)),y=30+(hash('dy'+i)%(H-60));bg.append(make('circle',{cx:x,cy:y,r:i%11===0?1.4:.55,class:'rg-dust'}))}}
function skyPositions(list){const ordered=[...list].sort((a,b)=>(b.major-a.major)||(b.sources-a.sources)||(b.degree-a.degree)||a.title.localeCompare(b.title));const pos={};ordered.forEach((n,i)=>{const x=90+(hash(n.id+'sx')%(W-180));const diagonal=H*.54+(x-W/2)*.18;const spread=n.major?105:170;const y=clamp(diagonal+(((hash(n.id+'sy')%1000)/1000)-.5)*spread*2,70,H-70);pos[n.id]=[x,y]});return pos}
function renderSky(list){clear();const bg=make('g'),eg=make('g'),ng=make('g');svg.append(bg,eg,ng);addDust(bg,125);const pos=skyPositions(list),ids=new Set(list.map(n=>n.id));edges.filter(([a,b])=>ids.has(a)&&ids.has(b)).sort((e1,e2)=>((degree[e2[0]]||0)+(degree[e2[1]]||0))-((degree[e1[0]]||0)+(degree[e1[1]]||0))).slice(0,180).forEach(([a,b])=>{const p=pos[a],q=pos[b];eg.append(make('path',{d:`M${p[0]},${p[1]} Q${(p[0]+q[0])/2},${(p[1]+q[1])/2-18} ${q[0]},${q[1]}`,class:`rg-edge ${(degree[a]||0)+(degree[b]||0)>=10?'major':''}`}))});list.forEach(n=>drawNode(ng,n,pos[n.id],{label:n.major||n.sources>=4,minor:!n.major}))}
function renderUniverse(list){clear();const bg=make('g'),eg=make('g'),ng=make('g');svg.append(bg,eg,ng);addDust(bg,95);const centers=[[260,220],[610,190],[980,220],[1420,220],[300,585],[680,570],[1060,570],[1460,580],[560,880],[1190,875]];const groups=Object.fromEntries(GALAXIES.map((g,i)=>[g.id,{...g,center:centers[i],nodes:[]}])) ;list.forEach(n=>(groups[n.galaxy]||groups.knowledge).nodes.push(n));const pos={};Object.values(groups).forEach(g=>{const[cx,cy]=g.center;bg.append(make('circle',{cx,cy,r:128,class:'rg-galaxy-halo'}));bg.append(make('text',{x:cx,y:cy-145,'text-anchor':'middle',class:'rg-galaxy-label'},g.label[lang()]||g.label.en));g.nodes.sort((a,b)=>(b.major-a.major)||(b.sources-a.sources));g.nodes.forEach((n,i)=>{const arm=i%3,step=Math.floor(i/3)+1,a=arm*(Math.PI*2/3)+step*.62,r=24+step*22;pos[n.id]=[cx+Math.cos(a)*r,cy+Math.sin(a)*r*.72]})});const ids=new Set(list.map(n=>n.id));edges.filter(([a,b])=>ids.has(a)&&ids.has(b)).slice(0,220).forEach(([a,b])=>{const p=pos[a],q=pos[b];if(!p||!q)return;eg.append(make('path',{d:`M${p[0]},${p[1]} L${q[0]},${q[1]}`,class:'rg-edge'}))});list.forEach(n=>drawNode(ng,n,pos[n.id],{label:n.major}))}
function renderNeural(list){clear();const bg=make('g'),eg=make('g'),ng=make('g');svg.append(bg,eg,ng);const outline='M900 95 C600 70 315 220 245 470 C190 670 300 875 540 930 C710 970 820 900 900 835 C980 900 1090 970 1260 930 C1500 875 1610 670 1555 470 C1485 220 1200 70 900 95 Z';bg.append(make('path',{d:outline,class:'rg-neural-lobe'}));for(let k=0;k<70;k++){const side=k%2?-1:1,sy=145+(hash('ny'+k)%730),sx=900+side*(60+(hash('nx'+k)%560)),ex=900+side*(120+(hash('ne'+k)%620)),ey=120+(hash('ney'+k)%780);bg.append(make('path',{d:`M900,${sy} C${900+side*130},${sy-50} ${sx},${ey+40} ${ex},${ey}`,class:'rg-neural-path'}))}const pos={};const ordered=[...list].sort((a,b)=>(b.major-a.major)||(b.degree-a.degree));ordered.forEach((n,i)=>{const side=i%2?-1:1,band=Math.floor(i/2),x=900+side*(145+(hash(n.id+'nx')%560)),y=120+(band*47)%770+((hash(n.id+'ny')%70)-35);pos[n.id]=[clamp(x,100,W-100),clamp(y,90,H-90)]});const ids=new Set(list.map(n=>n.id));edges.filter(([a,b])=>ids.has(a)&&ids.has(b)).slice(0,220).forEach(([a,b])=>{const p=pos[a],q=pos[b],mx=(p[0]+q[0])/2;eg.append(make('path',{d:`M${p[0]},${p[1]} Q${mx},${(p[1]+q[1])/2-35} ${q[0]},${q[1]}`,class:'rg-neural-path'}))});list.forEach(n=>drawNode(ng,n,pos[n.id],{label:n.major}))}
function renderBoard(list){clear();const bg=make('g'),tr=make('g'),ng=make('g');svg.append(bg,tr,ng);for(let x=55;x<W;x+=58)bg.append(make('line',{x1:x,y1:40,x2:x,y2:H-40,class:'rg-board-grid'}));for(let y=45;y<H;y+=58)bg.append(make('line',{x1:40,y1:y,x2:W-40,y2:y,class:'rg-board-grid'}));const centers=[[250,210],[590,210],[930,210],[1270,210],[1550,210],[300,610],[650,610],[1000,610],[1350,610],[1570,610]];const groups=Object.fromEntries(GALAXIES.map((g,i)=>[g.id,{...g,center:centers[i],nodes:[]}])) ;list.forEach(n=>(groups[n.galaxy]||groups.knowledge).nodes.push(n));const pos={};Object.values(groups).forEach(g=>{const[cx,cy]=g.center;bg.append(make('rect',{x:cx-132,y:cy-92,width:264,height:184,rx:12,class:'rg-board-chip'}));bg.append(make('text',{x:cx,y:cy-108,'text-anchor':'middle',class:'rg-galaxy-label'},g.label[lang()]||g.label.en));g.nodes.sort((a,b)=>(b.major-a.major)||(b.sources-a.sources));g.nodes.slice(0,20).forEach((n,i)=>{const c=i%4,r=Math.floor(i/4);pos[n.id]=[cx-90+c*60,cy-48+r*34]})});const visible=list.filter(n=>pos[n.id]),ids=new Set(visible.map(n=>n.id));edges.filter(([a,b])=>ids.has(a)&&ids.has(b)).slice(0,160).forEach(([a,b])=>{const p=pos[a],q=pos[b],mx=(p[0]+q[0])/2;tr.append(make('path',{d:`M${p[0]},${p[1]} H${mx} V${q[1]} H${q[0]}`,class:'rg-board-trace'}))});visible.forEach(n=>drawNode(ng,n,pos[n.id],{label:n.major,shape:'rect'}))}
function render(){const list=filtered();root.classList.remove('view-sky','view-universe','view-neural','view-motherboard');root.classList.add('view-'+mode);viewBtns.forEach(b=>b.classList.toggle('active',b.dataset.researchView===mode));if(mode==='universe')renderUniverse(list);else if(mode==='neural')renderNeural(list);else if(mode==='motherboard')renderBoard(list);else renderSky(list);const stat=root.querySelector('.rg-stat b');if(stat)stat.textContent=String(nodes.length)+'+'}
function normalizeViewControls(){const sw=root.querySelector('.rg-view-switch');const wrap=root.querySelector('.rg-canvas-wrap');if(sw&&wrap&&sw.nextElementSibling!==wrap)wrap.parentNode.insertBefore(sw,wrap);const sym=root.querySelector('.rg-symbolism'),cos=root.querySelector('.rg-cosmic-model'),fam=root.querySelector('.rg-family-grid');[sym,cos,fam].forEach(el=>{if(el)el.style.display='none'})}
function bind(){if(search){search.placeholder=lang()==='ar'?'ابحث عن بحث أو شخص أو مكان…':'Search research, person or place…';search.addEventListener('input',()=>{query=search.value.trim().toLowerCase();render()})}confBtns.forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.conf;b.classList.toggle('active');b.classList.contains('active')?activeConf.add(c):activeConf.delete(c);render()}));viewBtns.forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.researchView;localStorage.setItem('luxdot.research.view.v4',mode);render()}));const t=tooltip();t.addEventListener('mouseleave',()=>t.classList.remove('is-open'))}
async function boot(){try{normalizeViewControls();const res=await fetch('research-manifest.json?v=4167',{cache:'no-store'});if(!res.ok)throw new Error(`research-manifest ${res.status}`);build(await res.json());bind();render()}catch(err){console.error('[LuxDot Research Engine v4.16.7]',err);if(detail)detail.innerHTML=`<div class="rg-detail-card"><b>Research graph could not load.</b><p>${esc(err.message)}</p></div>`}}
boot();
})();
