(()=>{const p=location.pathname.split('/').pop();const M={
'savior-atlas.html':['001','الإنسان والمعنى','Human & Meaning','Mens & Betekenis','Manungsa lan Makna','אדם ומשמעות'],
'java-script.html':['002','الإنسان والمعنى · رحلات المعرفة','Human & Meaning · Knowledge Journeys','Mens & Betekenis · Kennisreizen','Manungsa lan Makna · Lelakon Kawruh','אדם ומשמעות · מסעות ידע'],
'shaam-breda.html':['003','الأرض والحدود','Land & Borders','Land & Grenzen','Tanah lan Wates','ארץ וגבולות'],
'erasmus.html':['004','الاختيار والمسؤولية','Choice & Responsibility','Keuze & Verantwoordelijkheid','Pilihan lan Tanggung Jawab','בחירה ואחריות'],
'hendrick-busman.html':['005','الحج والإشارة','Pilgrimage & Signal','Bedevaart & Signaal','Ziarah lan Tandha','עלייה לרגל ואות'],
'urania-nassau.html':['006','الأرض والحدود','Land & Borders','Land & Grenzen','Tanah lan Wates','ארץ וגבולות'],
'kevelaer-chaam-timeline.html':['007','الحج والإشارة · الأرض والحدود','Pilgrimage & Signal · Land & Borders','Bedevaart & Signaal · Land & Grenzen','Ziarah lan Tandha · Tanah lan Wates','עלייה לרגל ואות · ארץ וגבולות'],
'hoogstraten.html':['008','الأرض والحدود · الحج والإشارة','Land & Borders · Pilgrimage & Signal','Land & Grenzen · Bedevaart & Signaal','Tanah lan Wates · Ziarah lan Tandha','ארץ וגבולות · עלייה לרגל ואות'],
'sacred-120km-network.html':['009','الأرض والحدود · الحج والإشارة','Land & Borders · Pilgrimage & Signal','Land & Grenzen · Bedevaart & Signaal','Tanah lan Wates · Ziarah lan Tandha','ארץ וגבולות · עלייה לרגל ואות'],
'shaam-brabant-network.html':['NETWORK','الأرض والحدود · البحث الأم','Land & Borders · Parent Research','Land & Grenzen · Moederonderzoek','Tanah lan Wates · Panliten Induk','ארץ וגבולות · מחקר־אב'],
'alphen-before-alphen.html':['010','الأرض والحدود · شبكة شام–برابانت','Land & Borders · Shaam–Brabant Network','Land & Grenzen · Chaam–Brabant','Tanah lan Wates · Chaam–Brabant','ארץ וגבולות · שאם–בראבנט'],
'burckhardt.html':['010','رحلات المعرفة','Knowledge Journeys','Kennisreizen','Lelakon Kawruh','מסעות ידע'],
'chaam-deep-history.html':['012','الأرض والحدود · آثار شام','Land & Borders · Chaam Archaeology','Land & Grenzen · Archeologie Chaam','Tanah lan Wates · Arkeologi Chaam','ארץ וגבולות · ארכאולוגיית שאם'],
'janssen-family.html':['013','العائلات · التاريخ الديني','Families · Religious History','Families · Religiegeschiedenis','Kulawarga · Sejarah Agama','משפחות · היסטוריה דתית'],
'african-association.html':['011','رحلات المعرفة','Knowledge Journeys','Kennisreizen','Lelakon Kawruh','מסעות ידע']};
const d=M[p];if(!d)return;const l=(window.LuxLang&&window.LuxLang.get())||'en',i=l==='ar'?1:l==='nl'?3:l==='jv'?4:l==='he'?5:2;const label={ar:'العودة إلى أطلس الأبحاث',en:'Back to Research Atlas',nl:'Terug naar Onderzoeksatlas',jv:'Bali menyang Atlas Panliten',he:'חזרה לאטלס המחקר'}[l]||'Back to Research Atlas';const legacy={ar:'المعرّف القديم',en:'legacy ID',nl:'oude ID',jv:'ID lawas',he:'מזהה ישן'}[l]||'legacy ID';const bar=document.createElement('div');bar.className='rg-context-bar';bar.innerHTML=`<span class="rg-context-meta">${legacy} ${d[0]} · ${d[i]}</span><a href="research.html">${label} ↗</a>`;const main=document.querySelector('main')||document.body;main.insertBefore(bar,main.firstChild);const st=document.createElement('style');st.textContent='.rg-context-bar{max-width:1180px;margin:14px auto;border:1px solid rgba(99,255,155,.2);background:#041008;border-radius:14px;padding:10px 13px;display:flex;gap:10px;align-items:center;justify-content:space-between;font-size:12px}.rg-context-bar a{color:#63ff9b}.rg-context-meta{color:#9cb0a2}';document.head.append(st)})();