(()=>{
const DATA={
 families:[
  {id:'meaning',ar:'الإنسان والمعنى',en:'Human & Meaning',nl:'Mens & Betekenis',idn:'Manusia & Makna',desc:{ar:'الخلاص، التقاليد، النصوص، جاوة',en:'salvation, traditions, texts, Java',nl:'verlossing, tradities, teksten, Java',id:'keselamatan, tradisi, teks, Jawa'}},
  {id:'land',ar:'الأرض والحدود',en:'Land & Borders',nl:'Land & Grenzen',idn:'Tanah & Batas',desc:{ar:'شام، بريدا، بارله، هوخستراتن، ناسو',en:'Chaam, Breda, Baarle, Hoogstraten, Nassau',nl:'Chaam, Breda, Baarle, Hoogstraten, Nassau',id:'Chaam, Breda, Baarle, Hoogstraten, Nassau'}},
  {id:'pilgrimage',ar:'الحج والإشارة',en:'Pilgrimage & Signal',nl:'Bedevaart & Signaal',idn:'Ziarah & Sinyal',desc:{ar:'كيفيلار، بوسمان، الذخائر، الطرق',en:'Kevelaer, Busman, relics, routes',nl:'Kevelaer, Busman, relieken, routes',id:'Kevelaer, Busman, relik, rute'}},
  {id:'choice',ar:'الاختيار والمسؤولية',en:'Choice & Responsibility',nl:'Keuze & Verantwoordelijkheid',idn:'Pilihan & Tanggung Jawab',desc:{ar:'إيراسموس، الجسر، النظام، التوقف',en:'Erasmus, bridge, system, stopping',nl:'Erasmus, brug, systeem, stoppen',id:'Erasmus, jembatan, sistem, berhenti'}},
  {id:'journeys',ar:'رحلات المعرفة',en:'Knowledge Journeys',nl:'Kennisreizen',idn:'Perjalanan Pengetahuan',desc:{ar:'انتقال المعرفة واللغة والاستكشاف',en:'knowledge transfer, language, exploration',nl:'kennisoverdracht, taal, verkenning',id:'transfer pengetahuan, bahasa, eksplorasi'}}
 ],
 nodes:[
  {id:'luxdot',kind:'hub',families:['meaning','land','pilgrimage','choice','journeys'],label:{ar:'LUXDOT',en:'LUXDOT',nl:'LUXDOT',id:'LUXDOT'},sub:{ar:'أطلس البحث',en:'Research Atlas',nl:'Onderzoeksatlas',id:'Atlas Riset'},desc:{ar:'طبقة معرفة تربط المصادر والادعاءات والأحداث والأشخاص والأماكن والفرضيات دون تسوية درجات الثقة بينها.',en:'A knowledge layer linking sources, claims, events, people, places and hypotheses without flattening their confidence levels.',nl:'Een kennislaag die bronnen, claims, gebeurtenissen, personen, plaatsen en hypotheses verbindt zonder hun bewijskracht gelijk te maken.',id:'Lapisan pengetahuan yang menghubungkan sumber, klaim, peristiwa, orang, tempat dan hipotesis tanpa menyamakan tingkat kepastiannya.'}},
  {id:'savior',kind:'research',families:['meaning'],legacy:'001',label:{ar:'أطلس المخلّص',en:'Savior Atlas',nl:'Verlossersatlas',id:'Atlas Penyelamat'},sub:{ar:'تقاليد الخلاص',en:'salvation traditions',nl:'verlossingstradities',id:'tradisi keselamatan'},href:'savior-atlas.html',confidence:'C',desc:{ar:'مقارنة نقدية لتصورات المخلّص والتجديد عبر تقاليد متعددة. وجود التشابه لا يعني التطابق أو التنبؤ.',en:'Critical comparison of savior and renewal traditions; similarity does not establish identity or prediction.',nl:'Kritische vergelijking van verlossers- en vernieuwingsmotieven; gelijkenis bewijst geen identiteit of voorspelling.',id:'Perbandingan kritis tradisi penyelamat dan pembaruan; kemiripan bukan bukti identitas atau ramalan.'}},
  {id:'java',kind:'research',families:['meaning','journeys'],legacy:'002',label:{ar:'جاوة',en:'Java',nl:'Java',id:'Jawa'},sub:{ar:'لغة · مخطوطات',en:'language · manuscripts',nl:'taal · manuscripten',id:'bahasa · naskah'},href:'java-script.html',confidence:'B',desc:{ar:'مسار يقارن التاريخ اللغوي والمخطوطات والتقاليد الجاوية مع قراءات LuxDot، مع إبقاء الرمز منفصلاً عن التاريخ.',en:'A track connecting linguistic history, manuscripts and Javanese traditions while separating LuxDot interpretation from history.',nl:'Een spoor door taalgeschiedenis, manuscripten en Javaanse tradities, met scheiding tussen interpretatie en geschiedenis.',id:'Jalur sejarah bahasa, naskah dan tradisi Jawa dengan pemisahan tafsir dari sejarah.'}},
  {id:'shaam',kind:'research',families:['land'],legacy:'003',label:{ar:'شام–بريدا',en:'Chaam–Breda',nl:'Chaam–Breda',id:'Chaam–Breda'},sub:{ar:'المكان والذاكرة',en:'place & memory',nl:'plaats & geheugen',id:'tempat & memori'},href:'shaam-breda.html',confidence:'B',desc:{ar:'أطلس للمكان والذاكرة والرعاية والتاريخ المحلي، لا يبدأ من افتراض قداسة المكان.',en:'Atlas of place, memory, care and local history that does not begin by assuming sacred status.',nl:'Atlas van plaats, geheugen, zorg en lokale geschiedenis zonder heiligheid vooraf aan te nemen.',id:'Atlas tempat, memori, kepedulian dan sejarah lokal tanpa mengasumsikan kesakralan.'}},
  {id:'erasmus',kind:'research',families:['choice'],legacy:'004',label:{ar:'إيراسموس',en:'Erasmus',nl:'Erasmus',id:'Erasmus'},sub:{ar:'جسر · إرادة · اصطدام',en:'bridge · will · collision',nl:'brug · wil · botsing',id:'jembatan · kehendak · tabrakan'},href:'erasmus.html',confidence:'D',desc:{ar:'حادث حديث يستخدم كاختبار حي: الوقائع التقنية في طبقة، والقراءة الفلسفية والرمزية في طبقة أخرى قابلة للتعديل.',en:'A modern incident used as a living test: technical facts on one layer, philosophical/symbolic interpretation on another.',nl:'Een modern incident als levende test: technische feiten apart van filosofische/symbolische duiding.',id:'Insiden modern sebagai uji hidup: fakta teknis dipisahkan dari tafsir filosofis/simbolis.'}},
  {id:'busman',kind:'research',families:['pilgrimage','land'],legacy:'005',label:{ar:'هندريك بوسمان',en:'Hendrick Busman',nl:'Hendrick Busman',id:'Hendrick Busman'},sub:{ar:'كيفيلار · 1641',en:'Kevelaer · 1641',nl:'Kevelaer · 1641',id:'Kevelaer · 1641'},href:'hendrick-busman.html',confidence:'C',desc:{ar:'يفصل بين ما هو موثق تاريخياً حول نشوء الحج وبين النداء والرواية التعبدية بوصفها تقليداً دينياً.',en:'Separates documented pilgrimage history from the devotional call narrative as religious tradition.',nl:'Scheidt gedocumenteerde bedevaartgeschiedenis van de devotionele roepingsvertelling.',id:'Memisahkan sejarah ziarah terdokumentasi dari kisah panggilan sebagai tradisi devosi.'}},
  {id:'nassau',kind:'research',families:['land'],legacy:'006',label:{ar:'أورانيا × ناسو',en:'Urania × Nassau',nl:'Urania × Nassau',id:'Urania × Nassau'},sub:{ar:'نسب · سلطة · بريدا',en:'lineage · power · Breda',nl:'dynastie · macht · Breda',id:'garis keturunan · kuasa · Breda'},href:'urania-nassau.html',confidence:'B',desc:{ar:'عقدة تاريخية لفصل أورانيا الأدبية عن بيت ناسو وتتبع الروابط السياسية والنَسَبية الموثقة.',en:'Historical node separating literary Urania from the Nassau dynasty and tracing documented political/genealogical links.',nl:'Historische knoop die literaire Urania scheidt van de Nassau-dynastie.',id:'Simpul sejarah yang memisahkan Urania sastra dari dinasti Nassau.'}},
  {id:'kevelaer-chaam',kind:'research',families:['pilgrimage','land'],legacy:'007',label:{ar:'كيفيلار ↔ شام',en:'Kevelaer ↔ Chaam',nl:'Kevelaer ↔ Chaam',id:'Kevelaer ↔ Chaam'},sub:{ar:'خط زمني',en:'audited timeline',nl:'gecontroleerde tijdlijn',id:'linimasa terverifikasi'},href:'kevelaer-chaam-timeline.html',confidence:'B',desc:{ar:'خط زمني يربط نقاطاً موثقة ويحفظ التصحيحات بدلاً من محو الأخطاء القديمة.',en:'Audited timeline linking sourced points and preserving corrections rather than erasing earlier errors.',nl:'Gecontroleerde tijdlijn die correcties bewaart.',id:'Linimasa terverifikasi yang mempertahankan koreksi.'}},
  {id:'hoogstraten',kind:'research',families:['land','pilgrimage'],legacy:'008',label:{ar:'هوخستراتن',en:'Hoogstraten',nl:'Hoogstraten',id:'Hoogstraten'},sub:{ar:'الدم والحدود',en:'blood & borders',nl:'bloed & grenzen',id:'darah & batas'},href:'hoogstraten.html',confidence:'B',desc:{ar:'كنيسة كاترينا كعقدة بين النبلاء والذخيرة الدينية والحج والحدود والحرب وإعادة البناء.',en:'St Catherine’s as a node connecting nobility, relic tradition, pilgrimage, borders, war and reconstruction.',nl:'Sint-Katharina als knoop van adel, reliektraditie, bedevaart, grens, oorlog en wederopbouw.',id:'St Katarina sebagai simpul bangsawan, relik, ziarah, batas, perang dan rekonstruksi.'}},
  {id:'sacred25',kind:'research',families:['land','pilgrimage'],legacy:'009',label:{ar:'أطلس 25 كم',en:'25 km Sacred Atlas',nl:'25 km Atlas',id:'Atlas 25 km'},sub:{ar:'شبكة الكنائس',en:'church network',nl:'kerkennetwerk',id:'jaringan gereja'},href:'sacred-25km-atlas.html',confidence:'B',desc:{ar:'واجهة شبكية للمواقع الدينية والتاريخية والأثرية حول شام، مع 1648 و1944 كعقد زمنية مفسرة.',en:'Network view of religious, historical and archaeological sites around Chaam, with 1648 and 1944 as explanatory time nodes.',nl:'Netwerk van religieuze, historische en archeologische plaatsen rond Chaam.',id:'Jaringan situs religius, historis dan arkeologis di sekitar Chaam.'}},
  {id:'y1648',kind:'time',families:['land','pilgrimage'],label:{ar:'1648',en:'1648',nl:'1648',id:'1648'},sub:{ar:'مونستر · الحدود',en:'Münster · borders',nl:'Münster · grenzen',id:'Münster · batas'},confidence:'A',desc:{ar:'عقدة زمنية تفسيرية: صلح مونستر وتثبيت حدود وسياسات دينية تفسر عدداً من التحولات المحلية أفضل من فرضية المصادفات المستقلة.',en:'Explanatory time node: the Peace of Münster and resulting borders/religious policy explain several local changes better than independent coincidence.',nl:'Tijdknoop: de Vrede van Münster en grens-/religiebeleid verklaren meerdere lokale veranderingen.',id:'Simpul waktu: Perdamaian Münster dan kebijakan batas/agama menjelaskan banyak perubahan lokal.'}},
  {id:'y1944',kind:'time',families:['land'],label:{ar:'1944',en:'1944',nl:'1944',id:'1944'},sub:{ar:'الحرب · الأبراج',en:'war · towers',nl:'oorlog · torens',id:'perang · menara'},confidence:'A',desc:{ar:'عقدة تفسر تكرار تدمير الأبراج ضمن المنطق العسكري للمراقبة والانسحاب، قبل أي قراءة رمزية.',en:'Explains repeated tower destruction through military observation/withdrawal logic before symbolic interpretation.',nl:'Verklaart herhaalde torenvernietiging eerst militair, vóór symbolische duiding.',id:'Menjelaskan penghancuran menara lewat logika militer sebelum tafsir simbolis.'}},
  {id:'memory',kind:'ecosystem',families:['land','meaning'],label:{ar:'الذاكرة الحية',en:'Living Memory',nl:'Levend Geheugen',id:'Memori Hidup'},sub:{ar:'من نتذكر؟',en:'who must be remembered?',nl:'wie herinneren we?',id:'siapa diingat?'},href:'memory.html',confidence:'A',desc:{ar:'مساحة مستقلة للأشخاص والضحايا والشهود. البحث يشير إليها ولا ينسخها.',en:'Independent space for people, victims and witnesses. Research links to it rather than duplicating it.',nl:'Onafhankelijke ruimte voor mensen, slachtoffers en getuigen.',id:'Ruang independen untuk orang, korban dan saksi.'}},
  {id:'library',kind:'ecosystem',families:['meaning','journeys'],label:{ar:'المكتبة',en:'Library',nl:'Bibliotheek',id:'Perpustakaan'},sub:{ar:'النصوص والمصادر',en:'texts & sources',nl:'teksten & bronnen',id:'teks & sumber'},href:'library.html',confidence:'A',desc:{ar:'النص ليس دليلاً لمجرد وجوده؛ المكتبة تحفظ المصدر بينما البحث يفسر ويختبر الادعاءات.',en:'A text is not evidence merely because it exists; the Library preserves sources while Research interprets and tests claims.',nl:'Een tekst is niet automatisch bewijs; de bibliotheek bewaart bronnen, onderzoek test claims.',id:'Teks bukan otomatis bukti; perpustakaan menyimpan sumber, riset menguji klaim.'}},
  {id:'projects',kind:'ecosystem',families:['choice','land'],label:{ar:'المشاريع',en:'Projects',nl:'Projecten',id:'Proyek'},sub:{ar:'الفعل على الأرض',en:'action on the ground',nl:'actie in de praktijk',id:'aksi di lapangan'},href:'projects.html',confidence:'A',desc:{ar:'المشاريع هي أفعال ومبادرات، وليست مكاناً لتخزين التحقيقات النظرية.',en:'Projects are actions and initiatives, not storage for theoretical investigations.',nl:'Projecten zijn acties en initiatieven, geen opslag voor theoretisch onderzoek.',id:'Proyek adalah aksi dan inisiatif, bukan tempat riset teoritis.'}},
  {id:'knowledge-journeys',kind:'hub',families:['journeys'],label:{ar:'رحلات المعرفة',en:'Knowledge Journeys',nl:'Kennisreizen',id:'Perjalanan Pengetahuan'},sub:{ar:'المسار التالي',en:'next research family',nl:'volgende onderzoeksfamilie',id:'keluarga riset berikutnya'},confidence:'D',desc:{ar:'عائلة مخصصة لبحوث بوركهارت والجمعيات الاستكشافية وانتقال المعرفة واللغة. تظهر كبنية جاهزة دون ادعاء أن صفحاتها مكتملة بعد.',en:'Family reserved for Burckhardt, exploratory societies, knowledge transfer and language. The structure is ready without pretending those dossiers are complete.',nl:'Familie voor Burckhardt, genootschappen, kennisoverdracht en taal; structuur klaar, dossiers nog niet als voltooid voorgesteld.',id:'Keluarga untuk Burckhardt, perkumpulan eksplorasi, transfer pengetahuan dan bahasa; strukturnya siap tanpa menganggap dossier selesai.'}}
 ],
 edges:[
  ['luxdot','savior','conceptual','D'],['luxdot','java','method','B'],['luxdot','shaam','place','B'],['luxdot','erasmus','method','D'],['luxdot','busman','tradition','C'],['luxdot','nassau','historical','B'],['luxdot','hoogstraten','historical','B'],['luxdot','sacred25','historical','B'],['luxdot','memory','system','A'],['luxdot','library','system','A'],['luxdot','projects','system','A'],['luxdot','knowledge-journeys','roadmap','D'],
  ['sacred25','shaam','geographic','A'],['sacred25','hoogstraten','geographic','A'],['sacred25','nassau','political','B'],['sacred25','busman','pilgrimage','C'],['kevelaer-chaam','busman','timeline','A'],['kevelaer-chaam','shaam','geographic','B'],['hoogstraten','y1648','historical','B'],['sacred25','y1648','historical','A'],['shaam','y1648','historical','B'],['nassau','y1648','political','B'],['sacred25','y1944','historical','A'],['shaam','y1944','historical','A'],['hoogstraten','y1944','historical','A'],['memory','y1944','memory','B'],['savior','library','source','B'],['java','library','source','B'],['erasmus','projects','system','E'],['java','knowledge-journeys','conceptual','D']
 ]
};
const L=()=>localStorage.getItem('luxdot.lang')||document.documentElement.lang||'ar';
const langKey=()=>{const l=L();return l==='id'?'id':l};
const t=(obj)=>obj?.[langKey()]||obj?.en||obj?.ar||'';
const root=document.querySelector('[data-research-graph]'); if(!root)return;
const UI={
 ar:{title:'أطلس أبحاث لوكسدوت',lead:'ليست الأبحاث قائمة ملفات منفصلة. هذه الطبقة تربط الإنسان والمكان والزمن والذاكرة والإشارة، وتُظهر نوع كل علاقة ودرجة الثقة فيها دون خلط الحقيقة بالرواية أو الفرضية.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'المصدر قبل التفسير',method2:'العلاقة لها نوع ودرجة ثقة',method3:'الدليل المضاد جزء من البحث',method4:'الأبحاث القديمة محفوظة كمعرّفات تاريخية',search:'ابحث عن مكان، سنة، شخص، مفهوم أو بحث…',legend:'مقياس الثقة',systems:'فصل الوظائف داخل LuxDot',a:'A · مثبت أولياً',ad:'مصدر أولي أو أرشيف أو دليل قوي مباشر',b:'B · مثبت جيداً',bd:'عدة مصادر موثوقة أو علاقة تاريخية قوية',c:'C · تقليد موثق',cd:'نعرف أن الرواية موجودة تاريخياً؛ الحدث الخارق نفسه غير مثبت',d:'D · فرضية LuxDot',dd:'تفسير قابل للاختبار والمراجعة',e:'E · سؤال مفتوح',ed:'تشابه أو إشارة ضعيفة تُسجل ولا تُعامل كدليل',research:'البحث الحي',researchD:'يفحص ما حدث ولماذا وما الذي يمكن اختباره.',memory:'الذاكرة الحية',memoryD:'تحفظ الأشخاص والشهود والضحايا دون تحويلهم إلى فرضيات.',library:'المكتبة',libraryD:'تحفظ النصوص والمصادر؛ وجود النص لا يجعله دليلاً على تفسير.',projects:'المشاريع',projectsD:'أفعال ومبادرات على الأرض، وليست مخزناً للأبحاث النظرية.'},
 en:{title:'LuxDot Research Atlas',lead:'Research is no longer a list of isolated files. This layer connects human, place, time, memory and signal, showing the type and confidence of each relation without flattening fact, tradition and hypothesis.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Source before interpretation',method2:'Every relation has a type and confidence',method3:'Counter-evidence belongs inside the research',method4:'Old research numbers remain as legacy IDs',search:'Search a place, year, person, concept or dossier…',legend:'Confidence scale',systems:'Functional separation inside LuxDot',a:'A · Primary evidence',ad:'Primary source, archive or strong direct evidence',b:'B · Well established',bd:'Multiple reliable sources or strong historical relation',c:'C · Documented tradition',cd:'The tradition is historically attested; the supernatural event itself is not established',d:'D · LuxDot hypothesis',dd:'Interpretation open to testing and revision',e:'E · Open signal',ed:'Weak intersection or question recorded without treating it as evidence',research:'Living Research',researchD:'Tests what happened, why, and what can be falsified.',memory:'Living Memory',memoryD:'Preserves people, witnesses and victims without turning them into hypotheses.',library:'Library',libraryD:'Preserves texts and sources; a text’s existence does not prove an interpretation.',projects:'Projects',projectsD:'Actions and initiatives on the ground, not storage for theoretical research.'},
 nl:{title:'LuxDot Onderzoeksatlas',lead:'Onderzoek is niet langer een lijst losse bestanden. Deze laag verbindt mens, plaats, tijd, geheugen en signaal en toont het type en de bewijskracht van elke relatie.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Bron vóór interpretatie',method2:'Elke relatie heeft type en bewijskracht',method3:'Tegenbewijs hoort in het onderzoek',method4:'Oude nummers blijven als historische ID’s',search:'Zoek plaats, jaar, persoon, begrip of dossier…',legend:'Bewijsschaal',systems:'Functies binnen LuxDot gescheiden',a:'A · Primair bewijs',ad:'Primaire bron, archief of sterk direct bewijs',b:'B · Goed bevestigd',bd:'Meerdere betrouwbare bronnen of sterke historische relatie',c:'C · Gedocumenteerde traditie',cd:'De traditie is historisch gedocumenteerd; het bovennatuurlijke gebeuren zelf niet',d:'D · LuxDot-hypothese',dd:'Interpretatie die toetsbaar en herzienbaar blijft',e:'E · Open signaal',ed:'Zwakke kruising of vraag, geregistreerd maar niet als bewijs behandeld',research:'Levend Onderzoek',researchD:'Onderzoekt wat gebeurde, waarom en wat toetsbaar is.',memory:'Levend Geheugen',memoryD:'Bewaart mensen, getuigen en slachtoffers zonder ze tot hypotheses te maken.',library:'Bibliotheek',libraryD:'Bewaart teksten en bronnen; bestaan van tekst bewijst geen interpretatie.',projects:'Projecten',projectsD:'Acties en initiatieven in de praktijk, geen opslag voor theorie.'},
 id:{title:'Atlas Riset LuxDot',lead:'Riset bukan lagi daftar berkas terpisah. Lapisan ini menghubungkan manusia, tempat, waktu, memori dan sinyal serta menampilkan jenis dan tingkat keyakinan setiap hubungan.',kicker:'LUXDOT / RESEARCH GRAPH / V4',method1:'Sumber sebelum tafsir',method2:'Setiap hubungan punya jenis dan tingkat keyakinan',method3:'Bukti penyangkal adalah bagian riset',method4:'Nomor riset lama tetap sebagai ID historis',search:'Cari tempat, tahun, orang, konsep atau dossier…',legend:'Skala keyakinan',systems:'Pemisahan fungsi di LuxDot',a:'A · Bukti primer',ad:'Sumber primer, arsip atau bukti langsung kuat',b:'B · Terbukti baik',bd:'Beberapa sumber tepercaya atau hubungan sejarah kuat',c:'C · Tradisi terdokumentasi',cd:'Tradisinya tercatat; peristiwa supranaturalnya sendiri tidak terbukti',d:'D · Hipotesis LuxDot',dd:'Tafsir yang terbuka untuk diuji dan direvisi',e:'E · Sinyal terbuka',ed:'Persilangan lemah atau pertanyaan yang dicatat tanpa dianggap bukti',research:'Riset Hidup',researchD:'Menguji apa yang terjadi, mengapa dan apa yang dapat diuji.',memory:'Memori Hidup',memoryD:'Menjaga orang, saksi dan korban tanpa mengubahnya menjadi hipotesis.',library:'Perpustakaan',libraryD:'Menjaga teks dan sumber; keberadaan teks tidak membuktikan tafsir.',projects:'Proyek',projectsD:'Aksi dan inisiatif di lapangan, bukan tempat menyimpan teori.'}}
function applyUI(){const u=UI[langKey()]||UI.en;document.querySelectorAll('[data-ui]').forEach(el=>{const k=el.dataset.ui;if(u[k]!=null)el.textContent=u[k]});const inp=document.querySelector('.rg-search');if(inp)inp.placeholder=u.search;document.title=u.title+' · LuxDot';}
applyUI();

const svg=root.querySelector('svg');const detail=root.querySelector('.rg-detail');const familyBox=root.querySelector('.rg-family-grid');const search=root.querySelector('.rg-search');
const W=1200,H=680,cx=W/2,cy=H/2;
const familyPos={meaning:[210,145],land:[980,150],pilgrimage:[1010,510],choice:[590,590],journeys:[170,515]};
const positions={luxdot:[600,330],savior:[165,90],java:[285,205],shaam:[915,95],erasmus:[650,570],busman:[1040,440],nassau:[850,210],'kevelaer-chaam':[930,410],hoogstraten:[1080,260],sacred25:[775,345],y1648:[690,205],y1944:[765,485],memory:[485,120],library:[350,350],projects:[505,525],'knowledge-journeys':[170,500]};
function renderFamilies(){familyBox.innerHTML='<button class="rg-family active" data-family="all"><strong>'+({ar:'الكل',en:'All research',nl:'Alles',id:'Semua'}[langKey()]||'All')+'</strong><small>'+({ar:'كل العائلات والعقد',en:'all families and nodes',nl:'alle families en knopen',id:'semua keluarga dan simpul'}[langKey()]||'')+'</small></button>'+DATA.families.map(f=>`<button class="rg-family" data-family="${f.id}"><strong>${t({ar:f.ar,en:f.en,nl:f.nl,id:f.idn})}</strong><small>${t(f.desc)}</small></button>`).join('');}
function renderGraph(){svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=''; const eg=document.createElementNS('http://www.w3.org/2000/svg','g');const ng=document.createElementNS('http://www.w3.org/2000/svg','g');svg.append(eg,ng);
 DATA.edges.forEach((e,i)=>{const [a,b,type,conf]=e,p1=positions[a],p2=positions[b];if(!p1||!p2)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',p1[0]);line.setAttribute('y1',p1[1]);line.setAttribute('x2',p2[0]);line.setAttribute('y2',p2[1]);line.setAttribute('class','rg-edge');line.dataset.a=a;line.dataset.b=b;line.dataset.type=type;line.dataset.confidence=conf;eg.append(line)});
 DATA.nodes.forEach(n=>{const p=positions[n.id];if(!p)return;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','rg-node');g.dataset.id=n.id;g.dataset.kind=n.kind;g.dataset.families=n.families?.join(',')||'';g.setAttribute('transform',`translate(${p[0]} ${p[1]})`);const r=n.kind==='hub'?42:n.kind==='time'?30:34;g.innerHTML=`<circle r="${r}"></circle><text y="-2">${esc(t(n.label))}</text><text class="sub" y="13">${esc(t(n.sub)||n.legacy||'')}</text>`;g.addEventListener('click',()=>openNode(n.id));ng.append(g)});
 applyFilter();}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
let activeFamily='all',query='';
function applyFilter(){document.querySelectorAll('.rg-node').forEach(el=>{const n=DATA.nodes.find(x=>x.id===el.dataset.id);const fam=activeFamily==='all'||n?.families?.includes(activeFamily)||(n?.kind==='hub'&&n?.id==='luxdot');const q=!query||[t(n?.label),t(n?.sub),t(n?.desc),n?.legacy].join(' ').toLowerCase().includes(query);el.classList.toggle('dim',!(fam&&q));});document.querySelectorAll('.rg-edge').forEach(el=>{const a=document.querySelector(`.rg-node[data-id="${el.dataset.a}"]`),b=document.querySelector(`.rg-node[data-id="${el.dataset.b}"]`);el.classList.toggle('dim',a?.classList.contains('dim')||b?.classList.contains('dim'));});}
function openNode(id){const n=DATA.nodes.find(x=>x.id===id);if(!n)return;document.querySelectorAll('.rg-node').forEach(x=>x.classList.toggle('active',x.dataset.id===id));const related=DATA.edges.filter(e=>e[0]===id||e[1]===id).map(e=>{const other=e[0]===id?e[1]:e[0];return {n:DATA.nodes.find(x=>x.id===other),type:e[2],conf:e[3]}}).filter(x=>x.n);const openLabel={ar:'فتح العقدة',en:'Open node',nl:'Open knoop',id:'Buka simpul'}[langKey()];const relLabel={ar:'روابط مباشرة',en:'Direct links',nl:'Directe links',id:'Tautan langsung'}[langKey()];detail.innerHTML=`<button class="rg-close" aria-label="close">×</button><div class="rg-kicker">${n.legacy?'LEGACY '+n.legacy:n.kind.toUpperCase()}</div><h3>${esc(t(n.label))}</h3><p>${esc(t(n.desc))}</p><div class="rg-tags">${(n.families||[]).map(f=>`<span class="rg-tag">${esc(tFamily(f))}</span>`).join('')}${n.confidence?`<span class="rg-tag conf">${n.confidence}</span>`:''}</div>${n.href?`<a class="rg-link" href="${n.href}">${openLabel}</a>`:''}<h4>${relLabel}</h4><div class="rg-tags">${related.map(r=>`<button class="rg-btn" data-open="${r.n.id}">${esc(t(r.n.label))} · ${r.type} · ${r.conf}</button>`).join('')}</div>`;detail.classList.add('open');detail.querySelector('.rg-close').onclick=()=>detail.classList.remove('open');detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openNode(b.dataset.open));}
function tFamily(id){const f=DATA.families.find(x=>x.id===id);return f?t({ar:f.ar,en:f.en,nl:f.nl,id:f.idn}):id}
renderFamilies();renderGraph();familyBox.addEventListener('click',e=>{const b=e.target.closest('[data-family]');if(!b)return;activeFamily=b.dataset.family;familyBox.querySelectorAll('.rg-family').forEach(x=>x.classList.toggle('active',x===b));applyFilter()});search.addEventListener('input',()=>{query=search.value.trim().toLowerCase();applyFilter()});
root.querySelectorAll('[data-conf]').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('active');const c=b.dataset.conf;document.querySelectorAll('.rg-edge').forEach(e=>{if(e.dataset.confidence===c)e.style.display=b.classList.contains('active')?'':'none'})}));
window.addEventListener('storage',e=>{if(e.key==='luxdot.lang')location.reload()});document.querySelectorAll('[data-lang-select]').forEach(sel=>sel.addEventListener('change',()=>setTimeout(()=>location.reload(),80)));
})();
