(()=>{'use strict';
const FILE=(location.pathname.split('/').pop()||'').toLowerCase();
const RESEARCH=new Set(["1127-watch.html", "abraham-maimonides-sufi-bridge.html", "abulafia-comparative-lab.html", "abulafia-letters-names.html", "african-association.html", "alphen-before-alphen.html", "border-chapels-route.html", "burckhardt.html", "burial-settlement-layers.html", "chaam-deep-history.html", "chaam-genealogy.html", "chaam-midwives.html", "chosen-balance.html", "chosen-falsification.html", "chosen-hypothesis.html", "christian-apocalyptic-numbers-newton.html", "druze-hikma.html", "egyptology.html", "erasmus.html", "everyday-good.html", "gematria-method-lab.html", "genetics-memory-hypothesis.html", "grote-kerk-north-transept.html", "hallaj.html", "hank-raamsdonk-war-memory.html", "hendrick-busman.html", "history-galaxy.html", "hoogstraten.html", "hurufism-fazlallah-nasimi.html", "ibn-arabi-abulafia-comparison.html", "jafr-ilm-huruf.html", "jan-van-velthoven.html", "jansen-de-koning-network.html", "janssen-family.html", "java-script.html", "jewish-research-center.html", "jewish-source-ladder.html", "jochem-van-velthoven.html", "joseph-karo.html", "karo-decision-method.html", "kees-van-wanrooij.html", "kevelaer-chaam-timeline.html", "knowledge-laws-galaxy.html", "laws-principles-atlas.html", "library.html", "luria-vital-redemption.html", "mahdi-matrix.html", "maimonides-letters-numbers.html", "maimonides-messiah-test.html", "maimonides.html", "memory.html", "messianic-method-comparison.html", "messianic-names-numbers-atlas.html", "name-date-matrix.html", "ovadia-yosef.html", "paulina-withagen-rescue.html", "pet-goat-apocalypse-media.html", "polleke-mummy-cat.html", "prewriting-history.html", "prince-claus-bridge.html", "projects.html", "psychoactive-substances.html", "quantum-entanglement.html", "red-heifer.html", "reiderland-live.html", "sabbatai-nathan-test.html", "sacred-120km-network.html", "safed-kabbalah-messianism.html", "savior-atlas.html", "science-galaxy.html", "sepharad-diaspora.html", "sephardic-continuity-ovadia-yitzhak.html", "sephardic-halakha.html", "shaam-brabant-network.html", "shaam-breda.html", "talmud-messiah.html", "templars-master.html", "tishrei-5787-gates.html", "ter-brake-cadastral-investigation.html", "thijs-loss-consolation.html", "urania-nassau.html", "van-velthoven-family.html", "van-velthoven-grote-kerk.html", "verwithagen-erasmus.html", "war-reconstruction-memory.html", "west-brabant-family-memory-network.html", "willibrord-echternach.html", "withagen-chaam-toponym.html", "withagen-family.html", "withagen-jansen-dekoning.html", "withagen-van-den-boom.html", "withagen-wwii.html", "yitzhak-yosef.html"]);
if(!RESEARCH.has(FILE)&&!document.querySelector('[data-luxdot-research]'))return;
function clean(s){return (s||'').replace(/\s+/g,' ').trim()}
async function sha256(s){if(crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}let h=2166136261;for(const c of s)h=(h^c.charCodeAt(0))*16777619>>>0;return h.toString(16).toUpperCase().padStart(8,'0')}
async function makeReport(){
 const root=document.querySelector('main,article,[data-luxdot-research]')||document.body;
 const title=clean(document.querySelector('h1')?.innerText||document.title);
 const stamp=new Date();const iso=stamp.toISOString();
 const text=clean(root.innerText).slice(0,90000);
 const links=[...root.querySelectorAll('a[href]')].map(a=>({t:clean(a.innerText),u:a.href})).filter(x=>/^https?:/.test(x.u)).slice(0,80);
 const imgs=[...root.querySelectorAll('img[src]')].map(i=>({src:i.src,alt:i.alt||''})).slice(0,12);
 const fingerprint=await sha256([FILE,title,text,links.map(x=>x.u).join('|'),iso].join('\n'));
 const short=`LD-${FILE.replace(/\.html$/,'').toUpperCase().replace(/[^A-Z0-9]+/g,'-').slice(0,18)}-${iso.slice(0,10).replaceAll('-','')}-${fingerprint.slice(0,12)}`;
 const secs=[...root.querySelectorAll('h2,h3')].map(h=>`<li>${clean(h.innerText)}</li>`).slice(0,35).join('');
 const sourceHtml=links.map((x,i)=>`<li><b>${i+1}.</b> ${x.t||x.u}<br><span>${x.u}</span></li>`).join('');
 const imageHtml=imgs.slice(0,6).map(x=>`<figure><img src="${x.src}" alt=""><figcaption>${clean(x.alt)}</figcaption></figure>`).join('');
 const body=clean(text).split(/(?<=[.!؟])\s+/).slice(0,45).join(' ');
 const w=open('','_blank'); if(!w)return alert('Pop-up blocked');
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title} · Executive Snapshot</title><style>
 body{font:15px/1.65 Arial,sans-serif;color:#111;margin:0}.page{max-width:800px;margin:auto;padding:34px 46px}.brand{font-weight:800;color:#176b45;letter-spacing:.08em}.meta{border:1px solid #ccc;padding:14px;margin:18px 0;background:#fafafa}.fp{font-family:monospace;font-size:12px;word-break:break-all}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid figure{margin:0;border:1px solid #ddd;padding:6px}.grid img{max-width:100%;max-height:260px;display:block;margin:auto}.sources{font-size:11px;word-break:break-word}.note{font-size:12px;color:#555;border-top:1px solid #aaa;padding-top:10px;margin-top:24px}@page{size:A4;margin:14mm} @media print{.page{padding:0}.print{display:none}}
 </style></head><body><div class="page"><div class="brand">LUXDOT · LIVING RESEARCH SNAPSHOT</div><h1>${title}</h1><p>This executive report is generated from the living research record at the moment of request. Later revisions may differ.</p><div class="meta"><b>Generated:</b> ${stamp.toLocaleString()}<br><b>Source page:</b> ${location.href}<br><b>Snapshot ID:</b> ${short}<br><b>Content fingerprint (SHA-256):</b><div class="fp">${fingerprint}</div></div><h2>Executive summary</h2><p>${body}</p><h2>Research structure</h2><ul>${secs}</ul>${imageHtml?`<h2>Selected visual evidence</h2><div class="grid">${imageHtml}</div>`:''}<h2>Sources captured in this snapshot</h2><ol class="sources">${sourceHtml}</ol><div class="note">Integrity note: the fingerprint binds this page content, captured links and generation time. It identifies this snapshot; it is not a claim that every proposition is equally certain. Evidence grades in the research remain controlling.</div><p class="print"><button onclick="print()">Print / Save PDF</button></p></div></body></html>`);w.document.close();
}
const b=document.createElement('button');b.className='lux-report-btn';b.type='button';b.textContent='⎙ Executive Report';b.title='Generate a time-stamped research snapshot';b.onclick=makeReport;document.body.appendChild(b);
})();
