const N=[
{id:"place",p:null,s:"verified",ar:"شام–بريدا",en:"Shaam–Breda",arD:"الجذع الجغرافي للبحث هو قرية شام ومحيط بريدا، ويُحافظ على الفصل بين جغرافيا هولندا وبلاد الشام التاريخية",enD:"The geographic trunk is Chaam and the Breda region, while preserving the distinction between Dutch geography and the historical Levant",nl:"Chaam–Breda",nlD:"De geografische stam van het onderzoek is Chaam en de regio Breda, met een strikt onderscheid tussen Nederlandse geografie en de historische Levant",es:"Shaam–Breda",esD:"El tronco geográfico del estudio es Chaam y la región de Breda, manteniendo una distinción estricta entre la geografía neerlandesa y el Levante histórico",he:"שאם–ברדה",heD:"הגזע הגאוגרפי של המחקר הוא Chaam וסביבת ברדה, תוך שמירה על הבחנה ברורה בין הגאוגרפיה ההולנדית לבין א-שאם ההיסטורית",src:["S1","S3"]},
{id:"memory",p:"place",s:"verified",ar:"الشهادة والذاكرة",en:"Witness & memory",arD:"ذاكرة الاضطهاد والحرب والشهادة والتحرير، من تقاليد الشهيدات إلى الذاكرة اليهودية المحلية",enD:"Memory of persecution, witness, war and liberation, from martyr traditions to local Jewish memory",nl:"Getuigenis & herinnering",nlD:"Herinnering aan vervolging, getuigenis, oorlog en bevrijding, van martelaarstradities tot lokale Joodse herinnering",es:"Testimonio y memoria",esD:"Memoria de persecución, testimonio, guerra y liberación, desde tradiciones de mártires hasta la memoria judía local",he:"עדות וזיכרון",heD:"זיכרון של רדיפה, עדות, מלחמה ושחרור, ממסורות מרטירים ועד לזיכרון היהודי המקומי",src:["S5","S6"]},
{id:"rufina",p:"memory",s:"tradition",ar:"روفينا وسيكوندا",en:"Rufina & Secunda",arD:"التقليد المسيحي يحيي ذكرى الشهيدتين الرومانيتين، مع فصل وجود التقليد الموثق عن التفاصيل الهاغيوغرافية المتأخرة",enD:"Christian tradition commemorates the Roman martyrs, while documented tradition is kept distinct from later hagiographic detail",nl:"Rufina & Secunda",nlD:"De christelijke traditie herdenkt de Romeinse martelaressen, terwijl gedocumenteerde traditie wordt onderscheiden van latere hagiografische details",es:"Rufina y Secunda",esD:"La tradición cristiana conmemora a las mártires romanas, distinguiendo la tradición documentada de los detalles hagiográficos posteriores",he:"רופינה וסקונדה",heD:"המסורת הנוצרית מנציחה את המרטיריות הרומיות, תוך הבחנה בין עצם המסורת המתועדת לבין פרטים הגיוגרפיים מאוחרים",src:["S6"]},
{id:"edith",p:"memory",s:"verified",ar:"إديث وروزا شتاين",en:"Edith & Rosa Stein",arD:"اعتُقلتا في هولندا سنة 1942 ثم نُقلتا عبر فيستربورك (Westerbork) إلى أوشفيتز (Auschwitz) حيث قُتلتا في أغسطس من العام نفسه",enD:"Arrested in the Netherlands in 1942 and transported via Westerbork to Auschwitz, where they were killed that August",nl:"Edith & Rosa Stein",nlD:"In 1942 in Nederland gearresteerd en via Westerbork naar Auschwitz gedeporteerd, waar zij in augustus werden vermoord",es:"Edith y Rosa Stein",esD:"Arrestadas en los Países Bajos en 1942 y deportadas vía Westerbork a Auschwitz, donde fueron asesinadas en agosto",he:"אדית ורוזה שטיין",heD:"נעצרו בהולנד ב-1942, הועברו דרך וסטרבורק לאושוויץ ונרצחו שם באוגוסט",src:["S5"]},
{id:"jewish",p:"memory",s:"verified",ar:"يهود بريدا",en:"Jewish Breda",arD:"الذاكرة المحلية للاضطهاد النازي تُقرأ من أسماء الضحايا والعناوين وأحجار أحجار العثرة التذكارية (Stolpersteine)",enD:"Local Nazi persecution is read through victim names, addresses and Stolpersteine",nl:"Joods Breda",nlD:"Lokale vervolging onder het nazisme wordt gelezen via namen van slachtoffers, adressen en Stolpersteine",es:"Breda judía",esD:"La persecución nazi local se estudia a través de nombres de víctimas, direcciones y Stolpersteine",he:"ברדה היהודית",heD:"הרדיפה הנאצית המקומית נבחנת דרך שמות הקורבנות, כתובות ואבני Stolpersteine",src:["S12"]},
{id:"liberation",p:"memory",s:"verified",ar:"الحرب والتحرير",en:"War & liberation",arD:"دُمّر برج كنيسة ليديفارت (Ledevaertkerk) وأجزاء من الكنيسة في 1944، وبقي الجرس من الشواهد المادية على المبنى السابق",enD:"The Ledevaertkerk tower and parts of the church were destroyed in 1944, while the bell remained as a material witness",nl:"Oorlog & bevrijding",nlD:"De toren en delen van de Ledevaertkerk werden in 1944 verwoest; de klok bleef als materiële getuige bestaan",es:"Guerra y liberación",esD:"La torre y partes de Ledevaertkerk fueron destruidas en 1944; la campana permaneció como testimonio material",he:"מלחמה ושחרור",heD:"המגדל וחלקים מכנסיית Ledevaertkerk נהרסו ב-1944, והפעמון נותר כעדות חומרית",src:["S2"]},
{id:"church",p:"place",s:"verified",ar:"الكنيسة والجرس",en:"Church & bell",arD:"كنيسة ليديفارت (Ledevaertkerk) طبقة مادية محورية في تاريخ شام، من البناء القوطي إلى الإصلاح والحرب وإعادة البناء",enD:"Ledevaertkerk is a central material layer of Chaam history, from Gothic construction to Reformation, war and rebuilding",nl:"Kerk & klok",nlD:"Ledevaertkerk vormt een centrale materiële laag van de geschiedenis van Chaam, van gotische bouw tot Reformatie, oorlog en wederopbouw",es:"Iglesia y campana",esD:"Ledevaertkerk es una capa material central de la historia de Chaam, desde la construcción gótica hasta la Reforma, la guerra y la reconstrucción",he:"הכנסייה והפעמון",heD:"Ledevaertkerk היא שכבה חומרית מרכזית בהיסטוריה של Chaam, מן הבנייה הגותית דרך הרפורמציה, המלחמה והשיקום",src:["S1","S2"]},
{id:"bell",p:"church",s:"verified",ar:"جرس ليدينارت (Ledenaert)",en:"Ledenaert bell",arD:"الجرس التاريخي ونقشه عقدة مادية مستقلة يمكن فحصها بعيداً عن التأويل",enD:"The historic bell and inscription are material evidence that can be examined independently of interpretation",nl:"Ledenaert-klok",nlD:"De historische klok en haar inscriptie vormen materieel bewijs dat los van interpretatie kan worden onderzocht",es:"Campana Ledenaert",esD:"La campana histórica y su inscripción son evidencia material que puede examinarse independientemente de la interpretación",he:"פעמון Ledenaert",heD:"הפעמון ההיסטורי והכתובת שעליו הם ראיות חומריות שניתן לבחון בנפרד מן הפרשנות",src:["S2"]},
{id:"invert",p:"bell",s:"hypothesis",ar:"الحرف المقلوب",en:"Inverted letter",arD:"الانقلاب البصري قابل للدراسة رمزياً، لكنه لا يُعامل كإشارة خارقة أو دليل نبوئي من دون سند مستقل",enD:"The visual inversion may be studied symbolically but is not supernatural or prophetic evidence without independent support",nl:"Omgekeerde letter",nlD:"De visuele omkering kan symbolisch worden bestudeerd, maar geldt zonder onafhankelijk bewijs niet als bovennatuurlijk of profetisch teken",es:"Letra invertida",esD:"La inversión visual puede estudiarse simbólicamente, pero sin evidencia independiente no se considera señal sobrenatural ni profética",he:"האות ההפוכה",heD:"ניתן לחקור את ההיפוך החזותי כסמל, אך ללא ראיה עצמאית אין לראות בו אות על-טבעי או נבואי",src:["S2"]},
{id:"devil",p:"bell",s:"tradition",ar:"جسر دوفيلس (Duivelsbrug)",en:"Duivelsbrug",arD:"فولكلور بريدا يربط الشيطان بجرس الكنيسة، بينما المصدر التراثي نفسه يميز الأسطورة عن التفسير التاريخي",enD:"Breda folklore links the devil to a church bell, while the heritage source itself separates legend from historical explanation",nl:"Duivelsbrug",nlD:"Bredase folklore verbindt de duivel met een kerkklok, terwijl de erfgoedbron zelf legende en historische verklaring onderscheidt",es:"Duivelsbrug",esD:"El folclore de Breda vincula al diablo con una campana de iglesia, mientras la propia fuente patrimonial separa leyenda de explicación histórica",he:"Duivelsbrug",heD:"הפולקלור של ברדה קושר את השטן לפעמון כנסייה, בעוד שמקור המורשת עצמו מפריד בין אגדה להסבר היסטורי",src:["S4"]},
{id:"nassau",p:"place",s:"verified",ar:"ناسو والسلطة",en:"Nassau & power",arD:"بريدا مركز مبكر في تاريخ ناسو (Nassau) الهولندية، وتضم الكنيسة الكبرى (Grote Kerk) قبور أسلاف الأسرة المالكة",enD:"Breda is an early center of Dutch Nassau history and the Grote Kerk contains tombs of royal ancestors",nl:"Nassau & macht",nlD:"Breda is een vroeg centrum van de Nederlandse Nassau-geschiedenis en de Grote Kerk bevat graven van koninklijke voorouders",es:"Nassau y poder",esD:"Breda es un centro temprano de la historia neerlandesa de Nassau y la Grote Kerk alberga tumbas de antepasados reales",he:"נסאו וכוח",heD:"ברדה היא מרכז מוקדם בהיסטוריה ההולנדית של נסאו, וב-Grote Kerk קבורים אבות של בית המלוכה",src:["S3"]},
{id:"tombs",p:"nassau",s:"verified",ar:"القبور الأميرية",en:"Princely tombs",arD:"مصلى الأمراء (Prinsenkapel) والقبور يحولان الكنيسة إلى أرشيف حجري لتاريخ ناسو",enD:"The Prinsenkapel and tombs turn the church into a stone archive of Nassau history",nl:"Prinselijke graven",nlD:"De Prinsenkapel en de graven maken van de kerk een stenen archief van de Nassau-geschiedenis",es:"Tumbas principescas",esD:"La Prinsenkapel y las tumbas convierten la iglesia en un archivo de piedra de la historia de Nassau",he:"קברים נסיכיים",heD:"Prinsenkapel והקברים הופכים את הכנסייה לארכיון אבן של תולדות נסאו",src:["S3"]},
{id:"william",p:"nassau",s:"verified",ar:"وليام الصامت",en:"William the Silent",arD:"ترتبط بريدا بجذوره الأسرية والسياسية، بينما يرتبط اغتياله وقبره بدلفت",enD:"Breda belongs to his dynastic and political formation, while his assassination and tomb belong to Delft",nl:"Willem de Zwijger",nlD:"Breda behoort tot zijn dynastieke en politieke vorming; zijn moord en graf horen bij Delft",es:"Guillermo el Taciturno",esD:"Breda pertenece a su formación dinástica y política; su asesinato y su tumba pertenecen a Delft",he:"וילם השתקן",heD:"ברדה קשורה לעיצובו השושלתי והפוליטי, בעוד רציחתו וקברו קשורים לדלפט",src:["S13"]},
{id:"cat",p:"nassau",s:"probable",ar:"بولِكه (Polleke)",en:"Polleke",arD:"القطة المحنطة التي عُثر عليها في الكنيسة الكبرى (Grote Kerk) مؤرخة تقريباً إلى 1440–1460، وتفسيرها كقربان بناء يبقى مرجحاً لا يقينياً",enD:"The mummified cat found in the Grote Kerk dates roughly to 1440–1460, while its interpretation as a building offering remains probable rather than certain",nl:"Polleke",nlD:"De gemummificeerde kat uit de Grote Kerk dateert ongeveer uit 1440–1460; de interpretatie als bouwoffer blijft waarschijnlijk, niet zeker",es:"Polleke",esD:"La gata momificada hallada en la Grote Kerk data aproximadamente de 1440–1460; interpretarla como ofrenda de construcción sigue siendo probable, no segura",he:"Polleke",heD:"החתול החנוט שנמצא ב-Grote Kerk מתוארך בקירוב ל-1440–1460; הפרשנות כמנחת בנייה סבירה אך אינה ודאית",src:["S7"]},
{id:"care",p:"place",s:"verified",ar:"رعاية المستضعفين",en:"Care for the vulnerable",arD:"شبكة عملية للمسنين والأطفال وذوي الإعاقة والفقراء واللاجئين والحيوانات والمتطوعين ضمن 25 كم",enD:"A practical 25 km network for older people, children, disability, poverty, refugees, animals and volunteers",nl:"Zorg voor kwetsbaren",nlD:"Een praktisch netwerk binnen 25 km voor ouderen, kinderen, mensen met een beperking, armoede, vluchtelingen, dieren en vrijwilligers",es:"Cuidado de los vulnerables",esD:"Una red práctica de 25 km para mayores, niños, discapacidad, pobreza, refugiados, animales y voluntariado",he:"דאגה לפגיעים",heD:"רשת מעשית ברדיוס 25 ק״מ לקשישים, ילדים, אנשים עם מוגבלות, עוני, פליטים, בעלי חיים ומתנדבים",src:["S8"]},
{id:"refugees",p:"care",s:"verified",ar:"اللاجئون والضيافة",en:"Refugees & hospitality",arD:"الاستقبال المعاصر يُدرس كعمل مؤسسي قابل للقياس، لا كصفة رومانسية عامة للسكان",enD:"Contemporary reception is studied as measurable institutional action rather than a romanticized trait of local people",nl:"Vluchtelingen & gastvrijheid",nlD:"Hedendaagse opvang wordt bestudeerd als meetbaar institutioneel handelen, niet als geromantiseerde eigenschap van bewoners",es:"Refugiados y hospitalidad",esD:"La acogida contemporánea se estudia como acción institucional medible, no como rasgo romantizado de la población",he:"פליטים ואירוח",heD:"הקליטה העכשווית נבחנת כפעולה מוסדית מדידה ולא כתכונה רומנטית המיוחסת לתושבים",src:["S9"]},
{id:"animals",p:"care",s:"verified",ar:"الحيوان",en:"Animal welfare",arD:"الإنقاذ والرعاية والمزارع التعليمية تدخل في دائرة الرعاية مع حماية المواقع الخاصة الحساسة",enD:"Rescue, welfare and educational farms enter the care circle while sensitive private locations remain protected",nl:"Dierenwelzijn",nlD:"Redding, zorg en educatieve boerderijen horen bij de zorgcirkel, met bescherming van gevoelige privélocaties",es:"Bienestar animal",esD:"Rescate, cuidado y granjas educativas forman parte del círculo de cuidado, protegiendo ubicaciones privadas sensibles",he:"רווחת בעלי חיים",heD:"הצלה, טיפול וחוות חינוכיות הן חלק ממעגל הטיפול, תוך הגנה על מיקומים פרטיים רגישים",src:["S8"]},
{id:"land",p:"place",s:"verified",ar:"الأرض والحياة",en:"Land & life",arD:"شبكة المدن البطيئة (Cittaslow) والطبيعة والهدوء والمشي والدراجات والحدائق تُقرأ كبنية جودة حياة لا كزينة للمكان",enD:"Cittaslow, nature, quiet, walking, cycling and gardens are read as quality-of-life infrastructure rather than decoration",nl:"Land & leven",nlD:"Cittaslow, natuur, rust, wandelen, fietsen en tuinen worden gezien als infrastructuur voor levenskwaliteit, niet als decoratie",es:"Tierra y vida",esD:"Cittaslow, naturaleza, calma, caminar, ciclismo y jardines se leen como infraestructura de calidad de vida, no como decoración",he:"ארץ וחיים",heD:"Cittaslow, טבע, שקט, הליכה, אופניים וגנים נבחנים כתשתית לאיכות חיים ולא כקישוט",src:["S10"]},
{id:"prophecy",p:"place",s:"hypothesis",ar:"النص والنبوءة",en:"Text & prophecy",arD:"مساحة مقارنة للنصوص الدينية مع فصل صريح بين سياقها الأصلي وأي تطبيق رمزي معاصر",enD:"A comparative field for religious texts that explicitly separates original context from modern symbolic application",nl:"Tekst & profetie",nlD:"Een vergelijkend veld voor religieuze teksten dat oorspronkelijke context expliciet scheidt van hedendaagse symbolische toepassing",es:"Texto y profecía",esD:"Un campo comparativo para textos religiosos que separa explícitamente el contexto original de aplicaciones simbólicas modernas",he:"טקסט ונבואה",heD:"מרחב השוואתי לטקסטים דתיים המפריד במפורש בין ההקשר המקורי לבין יישום סמלי מודרני",src:["S11"]},
{id:"isaiah",p:"prophecy",s:"verified",ar:"إشعياء 2 · 11 · 19",en:"Isaiah 2 · 11 · 19",arD:"صور السلام والعدل وإنصاف الضعيف والطريق بين خصوم سابقين تُقرأ أولاً في سياقها النصي ثم كمادة للمقارنة الأخلاقية",enD:"Images of peace, justice, protection of the weak and a road between former enemies are read first in textual context and then comparatively",nl:"Jesaja 2 · 11 · 19",nlD:"Beelden van vrede, rechtvaardigheid, bescherming van zwakken en een weg tussen vroegere vijanden worden eerst tekstueel en daarna vergelijkend gelezen",es:"Isaías 2 · 11 · 19",esD:"Imágenes de paz, justicia, protección de los débiles y un camino entre antiguos enemigos se leen primero en contexto textual y después comparativamente",he:"ישעיהו ב׳ · י״א · י״ט",heD:"דימויים של שלום, צדק, הגנה על החלש ודרך בין אויבים לשעבר נקראים קודם בהקשרם הטקסטואלי ואחר כך בהשוואה אתית",src:["S11"]},
{id:"sham",p:"prophecy",s:"hypothesis",ar:"شام / الشام",en:"Shaam / al-Sham",arD:"التشابه الصوتي مثير رمزياً لكنه لا يشكل دليلاً لغوياً أو جغرافياً على التطابق",enD:"The phonetic resemblance is symbolically suggestive but not linguistic or geographic evidence of identity",nl:"Chaam / al-Sham",nlD:"De klankovereenkomst is symbolisch interessant maar vormt geen taalkundig of geografisch bewijs van identiteit",es:"Shaam / al-Sham",esD:"La semejanza fonética es sugerente simbólicamente, pero no constituye evidencia lingüística ni geográfica de identidad",he:"שאם / א-שאם",heD:"הדמיון הצלילי מעניין מבחינה סמלית אך אינו ראיה לשונית או גאוגרפית לזהות",src:["S14"]},
{id:"minaret",p:"sham",s:"hypothesis",ar:"المنارة البيضاء",en:"White minaret",arD:"نص المنارة البيضاء شرقي دمشق يُقرأ في سياقه، ومطابقته ببرج محلي تبقى فرضية غير مثبتة",enD:"The white-minaret text east of Damascus is read in context, while matching it to a local tower remains unproven",nl:"Witte minaret",nlD:"De tekst over de witte minaret ten oosten van Damascus wordt in context gelezen; koppeling aan een lokale toren blijft onbewezen",es:"Minarete blanco",esD:"El texto del minarete blanco al este de Damasco se lee en contexto; vincularlo a una torre local sigue sin demostrarse",he:"המינרט הלבן",heD:"הטקסט על המינרט הלבן ממזרח לדמשק נקרא בהקשרו; התאמתו למגדל מקומי נותרת לא מוכחת",src:["S14"]},
{id:"ibnarabi",p:"prophecy",s:"hypothesis",ar:"ابن عربي",en:"Ibn ʿArabi",arD:"تُدرس موضوعات الإنسان الكامل والمهدي ووحدة المعنى من دون تحويل حساب الحروف إلى إثبات هوية شخصية",enD:"Themes of the Perfect Human, Mahdi and unity of meaning are explored without turning letter-number calculations into proof of personal identity",nl:"Ibn ʿArabi",nlD:"Thema's als de Volmaakte Mens, de Mahdi en eenheid van betekenis worden onderzocht zonder letter- of getallenrekening als bewijs voor persoonlijke identiteit te gebruiken",es:"Ibn ʿArabi",esD:"Se exploran el Hombre Perfecto, el Mahdi y la unidad de significado sin convertir cálculos de letras y números en prueba de identidad personal",he:"אבן ערבי",heD:"נושאי האדם השלם, המהדי ואחדות המשמעות נחקרים בלי להפוך חישובי אותיות ומספרים להוכחת זהות אישית",src:["S15"]},
{id:"symbol",p:"place",s:"tradition",ar:"الرمز والغموض",en:"Symbol & mystery",arD:"فرع يدرس كيف تتحول الأشياء المادية والأخطاء والأساطير والأعداد إلى معنى جماعي",enD:"A branch studying how material objects, errors, legends and numbers become collective meaning",nl:"Symbool & mysterie",nlD:"Een tak die onderzoekt hoe materiële objecten, fouten, legendes en getallen collectieve betekenis krijgen",es:"Símbolo y misterio",esD:"Una rama que estudia cómo objetos materiales, errores, leyendas y números adquieren significado colectivo",he:"סמל ומסתורין",heD:"ענף הבוחן כיצד חפצים חומריים, טעויות, אגדות ומספרים מקבלים משמעות קולקטיבית",src:["S4","S7"]},
{id:"six",p:"symbol",s:"verified",ar:"666 و616",en:"666 & 616",arD:"رؤيا 13:18 هي المعطى النصي، وربط العدد بـنيرون قيصر (Neron Caesar) تفسير تاريخي قوي، مع قيمة خاصة لشاهد 616 في بعض المخطوطات",enD:"Revelation 13:18 is the textual datum, while Neron Caesar is a strong historical reading, strengthened by the 616 manuscript variant",nl:"666 & 616",nlD:"Openbaring 13:18 is het tekstuele gegeven; Neron Caesar is een sterke historische lezing, mede door de manuscriptvariant 616",es:"666 y 616",esD:"Apocalipsis 13:18 es el dato textual; Neron Caesar es una lectura histórica fuerte, reforzada por la variante manuscrita 616",he:"666 ו-616",heD:"חזון יוחנן י״ג:י״ח הוא הנתון הטקסטואלי; Neron Caesar הוא פירוש היסטורי חזק, שנתמך גם בווריאנט 616 בכתבי יד",src:["S16"]},
{id:"elon",p:"six",s:"pruned",ar:"إيلون ماسك (Elon Musk) = 666؟",en:"Elon Musk = 666?",arD:"المطابقات الرقمية الحديثة تتغير مع التهجئة ونظام الحساب، لذلك تُحفظ كدراسة في صناعة المطابقة العددية ولا تعتمد كدليل",enD:"Modern numerical matches vary with spelling and calculation system, so they are kept as a case study in manufactured numerical matching rather than evidence",nl:"Elon Musk = 666?",nlD:"Moderne numerieke matches veranderen met spelling en rekensysteem; ze blijven een casus over geconstrueerde numerologie, niet bewijs",es:"¿Elon Musk = 666?",esD:"Las coincidencias numéricas modernas cambian con la ortografía y el sistema de cálculo; se conservan como caso de numerología construida, no como evidencia",he:"Elon Musk = 666?",heD:"התאמות מספריות מודרניות משתנות לפי האיות ושיטת החישוב; הן נשמרות כמקרה מבחן בנומרולוגיה מיוצרת ולא כראיה",src:["S17"]}
]
const STATUS={
verified:{c:"#63ff9b",ar:"موثّق",en:"Documented",nl:"Gedocumenteerd",es:"Documentado",he:"מתועד"},
probable:{c:"#85ba68",ar:"مرجّح",en:"Probable",nl:"Waarschijnlijk",es:"Probable",he:"סביר"},
tradition:{c:"#d2b15b",ar:"رواية أو تقليد",en:"Tradition",nl:"Traditie",es:"Tradición",he:"מסורת"},
hypothesis:{c:"#76648f",ar:"فرضية",en:"Hypothesis",nl:"Hypothese",es:"Hipótesis",he:"השערה"},
open:{c:"#57798a",ar:"قيد التحقيق",en:"Open inquiry",nl:"Open onderzoek",es:"Investigación abierta",he:"חקירה פתוחה"},
pruned:{c:"#5e5a51",ar:"فرع موقوف",en:"Pruned branch",nl:"Gestopte tak",es:"Rama detenida",he:"ענף שנעצר"}
}
const SOURCES=[
["S1","Ledevaertkerk / Brabants Erfgoed","Church history and monument record","https://www.brabantserfgoed.nl/collectie/object/enb-321-beeldmateriaal/005bb6be707c2799b41336440131e81c2a0935ed"],
["S2","Ledevaertkerk historical information","1944 destruction and Ledenaert bell","https://ledevaertkerk.nl/documenten/infofolderChaam2014.pdf"],
["S3","Grote Kerk Breda — History","Nassau tombs and Prinsenkapel","https://www.grotekerkbreda.nl/en/about-the-church/history"],
["S4","Erfgoed Breda — Duivelsbrug","Local folklore and historical explanation","https://erfgoed.breda.nl/erfgoed/archief/duivelsbrug-ginneken/"],
["S5","Vatican News — Edith Stein","Biographical and memorial source","https://www.vaticannews.va/en/saints/08/09/st--theresa-benedicta-of-the-cross--edith-stein---carmelitan--vi.html"],
["S6","Vatican State — Rufina & Secunda","Commemoration of Saints Rufina and Secunda","https://www.vaticanstate.va/en/state-and-government/general-informations/saint-of-the-day/2254-july-10-saints-rufina-and-secunda-martyrs.html"],
["S7","Grote Kerk Breda — Polleke","Mummified cat, dating and interpretation","https://www.grotekerkbreda.nl/en/mummiekat"],
["S8","LuxDot Circle of Care 25 km","70-record working dataset","data/care-points.json"],
["S9","Gemeente Alphen-Chaam — refugees","Contemporary refugee reception","https://www.alphen-chaam.nl/vluchtelingen"],
["S10","Gemeente Alphen-Chaam — Cittaslow","Quality of life, landscape and local identity","https://www.alphen-chaam.nl/cittaslow"],
["S11","Isaiah 19:23–25","Textual basis for reconciliation motif","https://www.biblegateway.com/passage/?search=Isaiah%2019%3A23-25"],
["S12","Breda Jewish memory / Stolpersteine","Local Holocaust remembrance","https://www.bredavandaag.nl/algemeen/algemeen/464068/stolpersteine-geplaatst-in-de-dr-van-mierlostraat-ter-nagedac"],
["S13","Stedelijk Museum Breda — William of Orange","Breda and William of Orange","https://www.stedelijkmuseumbreda.nl/en/organisation/news/announcement-william"],
["S14","Sahih Muslim 2937a","White minaret east of Damascus","https://sunnah.com/muslim/54/134"],
["S15","Ibn ʿArabi — Futuhat research trail","Primary-text verification required before quotation","https://archive.org/"],
["S16","Revelation 13:18","Textual datum for 666","https://www.biblegateway.com/passage/?search=Revelation%2013%3A18"],
["S17","Internet numerology example","Preserved only as a claim, not evidentiary support","https://www.reddit.com/" ]
]
const EVENTS=[
["1392",{ar:"جرس ليدنارت",en:"Ledenaert bell",nl:"Ledenaert-klok"},"جرس Ledenaert يدخل الخط الزمني بوصفه شاهداً مادياً مبكراً","Ledenaert enters the timeline as an early material witness","Ledenaert verschijnt op de tijdlijn als vroege materiële getuige"],
["15th–16th c",{ar:"كنيسة ليديفارت",en:"Ledevaertkerk",nl:"Ledevaertkerk"},"بناء الكنيسة القوطية الحالية على موضع أقدم","Construction of the present Gothic church on an older site","Bouw van de huidige gotische kerk op een oudere locatie"],
["1440–1460",{ar:"بوليكه",en:"Polleke",nl:"Polleke"},"الفترة المرجحة لوضع القطة في بنية Grote Kerk","Probable period when the cat was placed within the Grote Kerk structure","Waarschijnlijke periode waarin de kat in de constructie van de Grote Kerk werd geplaatst"],
["16th c",{ar:"ناسو · بريدا",en:"Nassau · Breda",nl:"Nassau · Breda"},"بريدا مركز في تاريخ ناسو والتحولات السياسية والدينية","Breda becomes a center of Nassau and political-religious transformation","Breda wordt een centrum van Nassau en politieke en religieuze verandering"],
["1906",{ar:"اكتشاف بوليكه",en:"Polleke discovered",nl:"Polleke ontdekt"},"اكتشاف القطة المحنطة أثناء الترميم","Mummified cat discovered during restoration","Gemummificeerde kat ontdekt tijdens restauratie"],
["1942",{ar:"إديث وروزا شتاين",en:"Edith & Rosa Stein",nl:"Edith & Rosa Stein"},"الاعتقال في هولندا ثم Westerbork وAuschwitz","Arrest in the Netherlands followed by Westerbork and Auschwitz","Arrestatie in Nederland, gevolgd door Westerbork en Auschwitz"],
["1944",{ar:"الحرب والتحرير",en:"War & liberation",nl:"Oorlog & bevrijding"},"تدمير البرج وأجزاء من الكنيسة في سياق الحرب","Tower and parts of the church destroyed in wartime","Toren en delen van de kerk in oorlogstijd verwoest"],
["2026",{ar:"البحث الحي 002",en:"Living Research 002",nl:"Levend Onderzoek 002"},"تحويل الأطلس إلى شجرة معرفة قابلة للتصحيح والنمو","The atlas becomes a revisionable living knowledge tree","De atlas wordt een herzienbare levende kennisboom"]
]
const POS={place:[600,692],memory:[270,514],church:[453,475],nassau:[660,464],care:[882,500],land:[1010,376],prophecy:[468,268],symbol:[766,270],rufina:[115,355],edith:[205,320],jewish:[295,342],liberation:[365,308],bell:[390,355],invert:[318,210],devil:[410,175],tombs:[615,335],william:[705,318],cat:[785,350],refugees:[885,365],animals:[975,405],isaiah:[430,125],sham:[530,134],minaret:[572,65],ibnarabi:[655,115],six:[785,145],elon:[895,105]}
const CROSS=[
["edith","jewish","verified","ذاكرة اضطهاد مشتركة","shared persecution memory","gedeelde herinnering aan vervolging"],
["liberation","church","verified","الحرب تعيد تشكيل المكان","war reshapes place","oorlog hervormt plaats"],
["william","liberation","probable","المقاومة والحرية","resistance and liberty","verzet en vrijheid"],
["bell","devil","tradition","الجرس كرمز حدودي","bell as liminal symbol","de klok als grenssymbool"],
["isaiah","care","hypothesis","إنصاف الضعيف كمعيار أخلاقي","care for the weak as ethical criterion","zorg voor kwetsbaren als ethisch criterium"],
["sham","care","hypothesis","من بركة المكان إلى فعل الرعاية","from blessed place to caring action","van gezegende plaats naar zorgend handelen"],
["six","elon","pruned","مطابقة عددية غير ثابتة","unstable numerical matching","instabiele numerieke overeenkomst"],
["nassau","church","verified","تاريخ السلطة والمكان المقدس","power and sacred place","macht en heilige plaats"],
["symbol","invert","tradition","الخطأ المادي يولد معنى","material error becomes meaning","materiële fout wordt betekenis"]
]
let mode="all", currentLang=()=>CORE_LANGS.includes(document.documentElement.lang)?document.documentElement.lang:"en"
const svg=document.getElementById("livingTree"),drawer=document.getElementById("nodeDrawer")
function pathBetween(a,b,bend=0){const [x1,y1]=POS[a],[x2,y2]=POS[b],cx=(x1+x2)/2+bend,cy=(y1+y2)/2-30;return `M${x1},${y1} Q${cx},${cy} ${x2},${y2}`}
function cartouchePath(x,y,w,h){const l=x-w/2,r=x+w/2,t=y-h/2,b=y+h/2,tip=12,rr=9;return `M${l+rr},${t} H${r-tip-rr} Q${r-tip},${t} ${r-tip},${t+rr} L${r},${y} L${r-tip},${b-rr} Q${r-tip},${b} ${r-tip-rr},${b} H${l+tip+rr} Q${l+tip},${b} ${l+tip},${b-rr} L${l},${y} L${l+tip},${t+rr} Q${l+tip},${t} ${l+tip+rr},${t} Z`}
function visibleNodes(){return N.filter(n=>mode==="doc"?["verified","probable","tradition"].includes(n.s):mode==="hyp"?["hypothesis","open","pruned"].includes(n.s)||n.id==="place":n.s!=="pruned")}
function renderTree(){const lang=currentLang(),vis=visibleNodes(),ids=new Set(vis.map(n=>n.id));svg.innerHTML=`<defs><filter id="whiteGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="trunkG" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#0b2c19"/><stop offset=".65" stop-color="#1edb72"/><stop offset="1" stop-color="#7dffae"/></linearGradient></defs><path d="M600 758 C590 720 605 690 600 654 C594 610 581 564 592 516 C601 473 608 441 600 409" stroke="url(#trunkG)" stroke-width="18" fill="none" stroke-linecap="round" opacity=".83"/><path d="M600 748 C520 759 465 772 402 786 M600 748 C684 756 756 775 824 788 M600 742 C552 765 526 780 500 790 M600 742 C650 765 674 780 700 790" stroke="#113c22" stroke-width="7" fill="none" stroke-linecap="round"/><circle cx="600" cy="692" r="34" class="tree-ring"/><circle cx="600" cy="692" r="8" class="tree-heart"/><text x="600" y="738" text-anchor="middle" class="tree-root-label">${lang==="ar"?"البحث الحي 002":lang==="nl"?"LEVEND ONDERZOEK 002":"LIVING RESEARCH 002"}</text>`
N.filter(n=>n.p&&ids.has(n.id)&&ids.has(n.p)).forEach(n=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",pathBetween(n.p,n.id,(POS[n.id][0]-POS[n.p][0])*.08));p.setAttribute("class",`branch-main ${n.s}`);const widths={verified:5.2,probable:4,tradition:3.1,hypothesis:2.2,open:2,pruned:1.6};p.setAttribute("stroke",STATUS[n.s].c);p.setAttribute("stroke-width",widths[n.s]);p.setAttribute("opacity",n.s==="verified"?.82:n.s==="pruned"?.38:.62);if(n.s==="pruned")p.setAttribute("stroke-dasharray","6 8");svg.appendChild(p)})
CROSS.filter(c=>ids.has(c[0])&&ids.has(c[1])).forEach(c=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",pathBetween(c[0],c[1],42));p.setAttribute("class",`branch-cross ${c[2]}`);p.dataset.a=c[0];p.dataset.b=c[1];p.addEventListener("click",()=>openCross(c));svg.appendChild(p)})
vis.forEach(n=>{const [x,y]=POS[n.id],g=document.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("class",`leaf ${n.s}`);let w=n.id==="place"?154:Math.max(86,Math.min(146,((n[lang]||n.en).length*7.7)+32)),h=n.id==="place"?42:31;const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",cartouchePath(x,y,w,h));path.setAttribute("class","cartouche");if(n.s==="verified")path.setAttribute("filter","url(#whiteGlow)");const seal=document.createElementNS("http://www.w3.org/2000/svg","circle");seal.setAttribute("cx",x-(w/2)+14);seal.setAttribute("cy",y);seal.setAttribute("r",3.3);seal.setAttribute("class","seal");const t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("x",x);t.setAttribute("y",y+4);t.setAttribute("text-anchor","middle");t.textContent=n[lang]||n.en;g.append(path,seal,t);g.onclick=()=>openNode(n);svg.appendChild(g)})}
function srcLinks(ids){return (ids||[]).map(id=>{const s=SOURCES.find(x=>x[0]===id);return s?`<a href="${s[3]}" target="_blank" rel="noopener">${s[0]}</a>`:""}).join("")}
function openNode(n){const lang=currentLang(),st=STATUS[n.s];drawer.classList.add("show");drawer.innerHTML=`<div class="eyebrow" style="color:${st.c}">${st[lang]||st.en}</div><h3>${n[lang]||n.en}</h3><p>${n[lang+"D"]||n.enD}</p><div class="sources-mini">${srcLinks(n.src)}</div><div class="why">${t("confidenceWhy")}</div><p><button id="closeNode">${t("close")}</button></p>`;document.getElementById("closeNode").onclick=()=>drawer.classList.remove("show")}
function openCross(c){const lang=currentLang();drawer.classList.add("show");const a=N.find(n=>n.id===c[0]),b=N.find(n=>n.id===c[1]);drawer.innerHTML=`<div class="eyebrow" style="color:#d2b15b">${t("knowledgeAnastomosis")}</div><h3>${a[lang]||a.en} ↔ ${b[lang]||b.en}</h3><p>${lang==="ar"?c[3]:lang==="nl"?(c[5]||c[4]):c[4]}</p><div class="why">${t("crossWhy")}</div><p><button id="closeNode">${t("close")}</button></p>`;document.getElementById("closeNode").onclick=()=>drawer.classList.remove("show")}
function setMode(m,b){mode=m;document.querySelectorAll(".tree-toolbar button").forEach(x=>x.classList.remove("on"));b.classList.add("on");drawer.classList.remove("show");renderTree()}
allBtn.onclick=()=>setMode("all",allBtn);docBtn.onclick=()=>setMode("doc",docBtn);hypBtn.onclick=()=>setMode("hyp",hypBtn)
function translateLocal(){renderTree();renderTimeline();renderSources();renderMap()}
document.addEventListener("luxlang",()=>setTimeout(translateLocal,0))
document.querySelectorAll(".r-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".r-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".r-view").forEach(v=>v.classList.remove("active"));document.getElementById(b.dataset.view).classList.add("active");if(b.dataset.view==="mapView"&&map)setTimeout(()=>map.invalidateSize(),80)})
function renderTimeline(){const lang=currentLang();timeline.innerHTML=EVENTS.map(e=>`<div class="timeline-event"><div class="year">${e[0]}</div><h3>${e[1][lang]||e[1].en}</h3><p>${lang==="ar"?e[2]:lang==="nl"?e[4]:e[3]}</p></div>`).join("")}
function renderSources(){const lang=currentLang();sourcesList.innerHTML=SOURCES.map(s=>`<div class="source-row"><b>${s[0]} · ${s[1]}</b><small>${s[2]}</small><a href="${s[3]}" target="_blank" rel="noopener">${t("openSource")} ↗</a></div>`).join("")}
nodeStat.textContent=N.length;sourceStat.textContent=SOURCES.length
let P=Array.isArray(window.CARE_POINTS)?window.CARE_POINTS:[],map=null,activePoint=null
const MAP_BOUNDS={minLat:51.455,maxLat:51.635,minLon:4.64,maxLon:4.965}
function projectPoint(lat,lon,w=1000,h=650){const pad=55;return [pad+(lon-MAP_BOUNDS.minLon)/(MAP_BOUNDS.maxLon-MAP_BOUNDS.minLon)*(w-pad*2),h-pad-(lat-MAP_BOUNDS.minLat)/(MAP_BOUNDS.maxLat-MAP_BOUNDS.minLat)*(h-pad*2)]}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function townLabel(p,lang){return lang==="ar"?(p.displayTownAR||p.town):lang==="nl"?(p.displayTownNL||p.town):lang==="id"?(p.displayTownEN||p.town):(p.displayTownEN||p.town)}
function initMap(){
 const el=document.getElementById("map");if(!el)return
 el.innerHTML='<div class="offline-map" id="offlineMap"><svg id="careSvg" viewBox="0 0 1000 650" role="img" aria-label="LuxDot care network map"></svg><div id="carePopup" class="omap-popup"></div></div>'
 map={invalidateSize(){renderMap()}}
 if(P.length){
   const cats=[...new Set(P.map(x=>x.category))].sort(), towns=[...new Set(P.map(x=>x.town))].sort();
   cats.forEach(x=>mapCat.add(new Option(x,x)));towns.forEach(x=>mapTown.add(new Option(x,x)))
 }
 renderMap()
}
function showCarePopup(p,evt){const pop=document.getElementById('carePopup'),box=document.getElementById('offlineMap');if(!pop||!box)return;const lang=currentLang();pop.innerHTML=`<b>${esc(p.name)}</b><br><small>${esc(townLabel(p,lang))} · ${p.distance.toFixed(1)} km</small><br>${esc(p.category)}<br>${esc(p.serves||'')}${p.location?`<br><small>${esc(p.location)}</small>`:''}${p.phone?`<br>${esc(p.phone)}`:''}${p.url?`<br><a target="_blank" rel="noopener" href="${esc(p.url)}">${lang==='ar'?'المصدر / الموقع':lang==='nl'?'Bron / website':lang==='id'?'Sumber / situs':'Source / website'}</a>`:''}`;let r=box.getBoundingClientRect(),x=(evt?.clientX||r.left+r.width/2)-r.left+12,y=(evt?.clientY||r.top+r.height/2)-r.top+12;pop.style.left=Math.min(x,Math.max(10,r.width-320))+'px';pop.style.top=Math.min(y,Math.max(10,r.height-210))+'px';pop.classList.add('show');activePoint=p.id}
function renderMap(){if(!P.length)return;const lang=currentLang(),z=(mapSearch.value||'').toLowerCase(),f=P.filter(p=>(!mapCat.value||p.category===mapCat.value)&&(!mapTown.value||p.town===mapTown.value)&&(!z||JSON.stringify(p).toLowerCase().includes(z)));mapCount.textContent=t("visiblePoints")+"  "+f.length;mapList.innerHTML=f.map(p=>`<div class="map-item" data-care-id="${p.id}"><b>${esc(p.name)}</b><div class="map-meta">${esc(townLabel(p,lang))} · ${p.distance.toFixed(1)} km · ${esc(p.category)}</div></div>`).join("");
 const svg=document.getElementById('careSvg');if(svg){let out='';for(let x=100;x<1000;x+=100)out+=`<line class="omap-grid" x1="${x}" y1="0" x2="${x}" y2="650"/>`;for(let y=100;y<650;y+=100)out+=`<line class="omap-grid" x1="0" y1="${y}" x2="1000" y2="${y}"/>`;const [cx,cy]=projectPoint(51.506,4.862);const kmPerLon=69.2*Math.cos(51.506*Math.PI/180),rx=25/(kmPerLon)*(890/(MAP_BOUNDS.maxLon-MAP_BOUNDS.minLon)),ry=25/111*(540/(MAP_BOUNDS.maxLat-MAP_BOUNDS.minLat));out+=`<ellipse class="omap-ring" cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}"/><text class="omap-label" x="${cx+12}" y="${cy-12}">${lang==='ar'?'شام': 'Chaam'}</text><circle class="omap-anchor" cx="${cx}" cy="${cy}" r="7"/>`;f.forEach(p=>{const [x,y]=projectPoint(p.lat,p.lon);out+=`<g class="care-pin" data-care-id="${p.id}" tabindex="0" role="button" aria-label="${esc(p.name)}"><circle class="omap-point${activePoint===p.id?' active':''}" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="5.2"><title>${esc(p.name)}</title></circle><circle class="omap-hit" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="20"/></g>`});svg.innerHTML=out;svg.querySelectorAll('[data-care-id]').forEach(n=>{const act=e=>{const p=P.find(x=>x.id===+n.dataset.careId);if(p)showCarePopup(p,e)};n.addEventListener('click',act);n.addEventListener('pointerup',e=>{if(e.pointerType==='touch'){e.preventDefault();act(e)}});n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act(e)}})})}
 document.querySelectorAll('.map-item[data-care-id]').forEach(n=>n.onclick=e=>{const p=P.find(x=>x.id===+n.dataset.careId);if(p)showCarePopup(p,e)})
}
;[mapSearch,mapCat,mapTown].forEach(e=>e.addEventListener(e.tagName==="INPUT"?"input":"change",renderMap))
window.addEventListener("DOMContentLoaded",()=>{translateLocal();initMap();if(location.hash==="#mapView"){const b=document.querySelector('.r-tabs button[data-view="mapView"]');if(b)b.click()}})