const N=[
{id:"place",p:null,s:"verified",ar:"شام–بريدا",en:"Shaam–Breda",arD:"الجذع الجغرافي للبحث هو قرية شام ومحيط بريدا، ويُحافظ على الفصل بين جغرافيا هولندا وبلاد الشام التاريخية",enD:"The geographic trunk is Chaam and the Breda region, while preserving the distinction between Dutch geography and the historical Levant",src:["S1","S3"]},
{id:"memory",p:"place",s:"verified",ar:"الشهادة والذاكرة",en:"Witness & memory",arD:"ذاكرة الاضطهاد والحرب والشهادة والتحرير، من تقاليد الشهيدات إلى الذاكرة اليهودية المحلية",enD:"Memory of persecution, witness, war and liberation, from martyr traditions to local Jewish memory",src:["S5","S6"]},
{id:"rufina",p:"memory",s:"tradition",ar:"روفينا وسيكوندا",en:"Rufina & Secunda",arD:"التقليد المسيحي يحيي ذكرى الشهيدتين الرومانيتين، مع فصل وجود التقليد الموثق عن التفاصيل الهاغيوغرافية المتأخرة",enD:"Christian tradition commemorates the Roman martyrs, while documented tradition is kept distinct from later hagiographic detail",src:["S6"]},
{id:"edith",p:"memory",s:"verified",ar:"إديث وروزا شتاين",en:"Edith & Rosa Stein",arD:"اعتُقلتا في هولندا سنة 1942 ثم نُقلتا عبر Westerbork إلى Auschwitz حيث قُتلتا في أغسطس من العام نفسه",enD:"Arrested in the Netherlands in 1942 and transported via Westerbork to Auschwitz, where they were killed that August",src:["S5"]},
{id:"jewish",p:"memory",s:"verified",ar:"يهود بريدا",en:"Jewish Breda",arD:"الذاكرة المحلية للاضطهاد النازي تُقرأ من أسماء الضحايا والعناوين وأحجار Stolpersteine",enD:"Local Nazi persecution is read through victim names, addresses and Stolpersteine",src:["S12"]},
{id:"liberation",p:"memory",s:"verified",ar:"الحرب والتحرير",en:"War & liberation",arD:"دُمّر برج Ledevaertkerk وأجزاء من الكنيسة في 1944، وبقي الجرس من الشواهد المادية على المبنى السابق",enD:"The Ledevaertkerk tower and parts of the church were destroyed in 1944, while the bell remained as a material witness",src:["S2"]},
{id:"church",p:"place",s:"verified",ar:"الكنيسة والجرس",en:"Church & bell",arD:"Ledevaertkerk طبقة مادية محورية في تاريخ شام، من البناء القوطي إلى الإصلاح والحرب وإعادة البناء",enD:"Ledevaertkerk is a central material layer of Chaam history, from Gothic construction to Reformation, war and rebuilding",src:["S1","S2"]},
{id:"bell",p:"church",s:"verified",ar:"جرس Ledenaert",en:"Ledenaert bell",arD:"الجرس التاريخي ونقشه عقدة مادية مستقلة يمكن فحصها بعيداً عن التأويل",enD:"The historic bell and inscription are material evidence that can be examined independently of interpretation",src:["S2"]},
{id:"invert",p:"bell",s:"hypothesis",ar:"الحرف المقلوب",en:"Inverted letter",arD:"الانقلاب البصري قابل للدراسة رمزياً، لكنه لا يُعامل كإشارة خارقة أو دليل نبوئي من دون سند مستقل",enD:"The visual inversion may be studied symbolically but is not supernatural or prophetic evidence without independent support",src:["S2"]},
{id:"devil",p:"bell",s:"tradition",ar:"Duivelsbrug",en:"Duivelsbrug",arD:"فولكلور بريدا يربط الشيطان بجرس الكنيسة، بينما المصدر التراثي نفسه يميز الأسطورة عن التفسير التاريخي",enD:"Breda folklore links the devil to a church bell, while the heritage source itself separates legend from historical explanation",src:["S4"]},
{id:"nassau",p:"place",s:"verified",ar:"ناسو والسلطة",en:"Nassau & power",arD:"بريدا مركز مبكر في تاريخ Nassau الهولندية، وتضم Grote Kerk قبور أسلاف الأسرة المالكة",enD:"Breda is an early center of Dutch Nassau history and the Grote Kerk contains tombs of royal ancestors",src:["S3"]},
{id:"tombs",p:"nassau",s:"verified",ar:"القبور الأميرية",en:"Princely tombs",arD:"Prinsenkapel والقبور يحولان الكنيسة إلى أرشيف حجري لتاريخ ناسو",enD:"The Prinsenkapel and tombs turn the church into a stone archive of Nassau history",src:["S3"]},
{id:"william",p:"nassau",s:"verified",ar:"وليام الصامت",en:"William the Silent",arD:"ترتبط بريدا بجذوره الأسرية والسياسية، بينما يرتبط اغتياله وقبره بدلفت",enD:"Breda belongs to his dynastic and political formation, while his assassination and tomb belong to Delft",src:["S13"]},
{id:"cat",p:"nassau",s:"probable",ar:"Polleke",en:"Polleke",arD:"القطة المحنطة التي عُثر عليها في Grote Kerk مؤرخة تقريباً إلى 1440–1460، وتفسيرها كقربان بناء يبقى مرجحاً لا يقينياً",enD:"The mummified cat found in the Grote Kerk dates roughly to 1440–1460, while its interpretation as a building offering remains probable rather than certain",src:["S7"]},
{id:"care",p:"place",s:"verified",ar:"رعاية المستضعفين",en:"Care for the vulnerable",arD:"شبكة عملية للمسنين والأطفال وذوي الإعاقة والفقراء واللاجئين والحيوانات والمتطوعين ضمن 25 كم",enD:"A practical 25 km network for older people, children, disability, poverty, refugees, animals and volunteers",src:["S8"]},
{id:"refugees",p:"care",s:"verified",ar:"اللاجئون والضيافة",en:"Refugees & hospitality",arD:"الاستقبال المعاصر يُدرس كعمل مؤسسي قابل للقياس، لا كصفة رومانسية عامة للسكان",enD:"Contemporary reception is studied as measurable institutional action rather than a romanticized trait of local people",src:["S9"]},
{id:"animals",p:"care",s:"verified",ar:"الحيوان",en:"Animal welfare",arD:"الإنقاذ والرعاية والمزارع التعليمية تدخل في دائرة الرعاية مع حماية المواقع الخاصة الحساسة",enD:"Rescue, welfare and educational farms enter the care circle while sensitive private locations remain protected",src:["S8"]},
{id:"land",p:"place",s:"verified",ar:"الأرض والحياة",en:"Land & life",arD:"Cittaslow والطبيعة والهدوء والمشي والدراجات والحدائق تُقرأ كبنية جودة حياة لا كزينة للمكان",enD:"Cittaslow, nature, quiet, walking, cycling and gardens are read as quality-of-life infrastructure rather than decoration",src:["S10"]},
{id:"prophecy",p:"place",s:"hypothesis",ar:"النص والنبوءة",en:"Text & prophecy",arD:"مساحة مقارنة للنصوص الدينية مع فصل صريح بين سياقها الأصلي وأي تطبيق رمزي معاصر",enD:"A comparative field for religious texts that explicitly separates original context from modern symbolic application",src:["S11"]},
{id:"isaiah",p:"prophecy",s:"verified",ar:"إشعياء 2 · 11 · 19",en:"Isaiah 2 · 11 · 19",arD:"صور السلام والعدل وإنصاف الضعيف والطريق بين خصوم سابقين تُقرأ أولاً في سياقها النصي ثم كمادة للمقارنة الأخلاقية",enD:"Images of peace, justice, protection of the weak and a road between former enemies are read first in textual context and then comparatively",src:["S11"]},
{id:"sham",p:"prophecy",s:"hypothesis",ar:"شام / الشام",en:"Shaam / al-Sham",arD:"التشابه الصوتي مثير رمزياً لكنه لا يشكل دليلاً لغوياً أو جغرافياً على التطابق",enD:"The phonetic resemblance is symbolically suggestive but not linguistic or geographic evidence of identity",src:["S14"]},
{id:"minaret",p:"sham",s:"hypothesis",ar:"المنارة البيضاء",en:"White minaret",arD:"نص المنارة البيضاء شرقي دمشق يُقرأ في سياقه، ومطابقته ببرج محلي تبقى فرضية غير مثبتة",enD:"The white-minaret text east of Damascus is read in context, while matching it to a local tower remains unproven",src:["S14"]},
{id:"ibnarabi",p:"prophecy",s:"hypothesis",ar:"ابن عربي",en:"Ibn ʿArabi",arD:"تُدرس موضوعات الإنسان الكامل والمهدي ووحدة المعنى من دون تحويل حساب الحروف إلى إثبات هوية شخصية",enD:"Themes of the Perfect Human, Mahdi and unity of meaning are explored without turning letter-number calculations into proof of personal identity",src:["S15"]},
{id:"symbol",p:"place",s:"tradition",ar:"الرمز والغموض",en:"Symbol & mystery",arD:"فرع يدرس كيف تتحول الأشياء المادية والأخطاء والأساطير والأعداد إلى معنى جماعي",enD:"A branch studying how material objects, errors, legends and numbers become collective meaning",src:["S4","S7"]},
{id:"six",p:"symbol",s:"verified",ar:"666 و616",en:"666 & 616",arD:"رؤيا 13:18 هي المعطى النصي، وربط العدد بـNeron Caesar تفسير تاريخي قوي، مع قيمة خاصة لشاهد 616 في بعض المخطوطات",enD:"Revelation 13:18 is the textual datum, while Neron Caesar is a strong historical reading, strengthened by the 616 manuscript variant",src:["S16"]},
{id:"elon",p:"six",s:"pruned",ar:"Elon Musk = 666؟",en:"Elon Musk = 666?",arD:"المطابقات الرقمية الحديثة تتغير مع التهجئة ونظام الحساب، لذلك تُحفظ كدراسة في صناعة المطابقة العددية ولا تعتمد كدليل",enD:"Modern numerical matches vary with spelling and calculation system, so they are kept as a case study in manufactured numerical matching rather than evidence",src:["S17"]}
]
const STATUS={verified:{c:"#63ff9b",ar:"موثّق",en:"Documented"},probable:{c:"#85ba68",ar:"مرجّح",en:"Probable"},tradition:{c:"#d2b15b",ar:"رواية أو تقليد",en:"Tradition"},hypothesis:{c:"#76648f",ar:"فرضية",en:"Hypothesis"},open:{c:"#57798a",ar:"قيد التحقيق",en:"Open inquiry"},pruned:{c:"#5e5a51",ar:"فرع موقوف",en:"Pruned branch"}}
const SOURCES=[
["S1","Ledevaertkerk / Brabants Erfgoed","Church history and monument record","https://www.brabantserfgoed.nl/collectie/object/enb-321-beeldmateriaal/005bb6be707c2799b41336440131e81c2a0935ed"],
["S2","Ledevaertkerk historical information","1944 destruction and Ledenaert bell","https://ledevaertkerk.nl/documenten/infofolderChaam2014.pdf"],
["S3","Grote Kerk Breda — History","Nassau tombs and Prinsenkapel","https://www.grotekerkbreda.nl/en/about-the-church/history"],
["S4","Erfgoed Breda — Duivelsbrug","Local folklore and historical explanation","https://erfgoed.breda.nl/erfgoed/archief/duivelsbrug-ginneken/"],
["S5","Vatican News — Edith Stein","Biographical and memorial source","https://www.vaticannews.va/en/saints/08/09/st--theresa-benedicta-of-the-cross--edith-stein---carmelitan--vi.html"],
["S6","Vatican State — Rufina & Secunda","Commemoration of Saints Rufina and Secunda","https://www.vaticanstate.va/en/state-and-government/general-informations/saint-of-the-day/2254-july-10-saints-rufina-and-secunda-martyrs.html"],
["S7","Grote Kerk Breda — Polleke","Mummified cat, dating and interpretation","https://www.grotekerkbreda.nl/en/mummiekat"],
["S8","LuxDot Circle of Care 25 km","70-record working dataset","data/care-points.json"],
["S9","Gemeente Alphen-Chaam — refugees","Contemporary refugee reception","https://www.alphen-chaam.nl/vluchtelingen"],
["S10","Gemeente Alphen-Chaam — Cittaslow","Quality of life, landscape and local identity","https://www.alphen-chaam.nl/cittaslow"],
["S11","Isaiah 19:23–25","Textual basis for reconciliation motif","https://www.biblegateway.com/passage/?search=Isaiah%2019%3A23-25"],
["S12","Breda Jewish memory / Stolpersteine","Local Holocaust remembrance","https://www.bredavandaag.nl/algemeen/algemeen/464068/stolpersteine-geplaatst-in-de-dr-van-mierlostraat-ter-nagedac"],
["S13","Stedelijk Museum Breda — William of Orange","Breda and William of Orange","https://www.stedelijkmuseumbreda.nl/en/organisation/news/announcement-william"],
["S14","Sahih Muslim 2937a","White minaret east of Damascus","https://sunnah.com/muslim/54/134"],
["S15","Ibn ʿArabi — Futuhat research trail","Primary-text verification required before quotation","https://archive.org/"],
["S16","Revelation 13:18","Textual datum for 666","https://www.biblegateway.com/passage/?search=Revelation%2013%3A18"],
["S17","Internet numerology example","Preserved only as a claim, not evidentiary support","https://www.reddit.com/" ]
]
const EVENTS=[
["1392","Ledenaert bell","جرس Ledenaert يدخل الخط الزمني بوصفه شاهداً مادياً مبكراً","Ledenaert enters the timeline as an early material witness"],
["15th–16th c","Ledevaertkerk","بناء الكنيسة القوطية الحالية على موضع أقدم","Construction of the present Gothic church on an older site"],
["1440–1460","Polleke","الفترة المرجحة لوضع القطة في بنية Grote Kerk","Probable period when the cat was placed within the Grote Kerk structure"],
["16th c","Nassau · Breda","بريدا مركز في تاريخ ناسو والتحولات السياسية والدينية","Breda becomes a center of Nassau and political-religious transformation"],
["1906","Polleke discovered","اكتشاف القطة المحنطة أثناء الترميم","Mummified cat discovered during restoration"],
["1942","Edith & Rosa Stein","الاعتقال في هولندا ثم Westerbork وAuschwitz","Arrest in the Netherlands followed by Westerbork and Auschwitz"],
["1944","War & liberation","تدمير البرج وأجزاء من الكنيسة في سياق الحرب","Tower and parts of the church destroyed in wartime"],
["2026","Living Research 001","تحويل الأطلس إلى شجرة معرفة قابلة للتصحيح والنمو","The atlas becomes a revisionable living knowledge tree"]
]
const POS={place:[600,692],memory:[270,514],church:[453,475],nassau:[660,464],care:[882,500],land:[1010,376],prophecy:[468,268],symbol:[766,270],rufina:[115,355],edith:[205,320],jewish:[295,342],liberation:[365,308],bell:[390,355],invert:[318,210],devil:[410,175],tombs:[615,335],william:[705,318],cat:[785,350],refugees:[885,365],animals:[975,405],isaiah:[430,125],sham:[530,134],minaret:[572,65],ibnarabi:[655,115],six:[785,145],elon:[895,105]}
const CROSS=[
["edith","jewish","verified","ذاكرة اضطهاد مشتركة","shared persecution memory"],
["liberation","church","verified","الحرب تعيد تشكيل المكان","war reshapes place"],
["william","liberation","probable","المقاومة والحرية","resistance and liberty"],
["bell","devil","tradition","الجرس كرمز حدودي","bell as liminal symbol"],
["isaiah","care","hypothesis","إنصاف الضعيف كمعيار أخلاقي","care for the weak as ethical criterion"],
["sham","care","hypothesis","من بركة المكان إلى فعل الرعاية","from blessed place to caring action"],
["six","elon","pruned","مطابقة عددية غير ثابتة","unstable numerical matching"],
["nassau","church","verified","تاريخ السلطة والمكان المقدس","power and sacred place"],
["symbol","invert","tradition","الخطأ المادي يولد معنى","material error becomes meaning"]
]
let mode="all", currentLang=()=>document.documentElement.lang==="ar"?"ar":"en"
const svg=document.getElementById("livingTree"),drawer=document.getElementById("nodeDrawer")
function pathBetween(a,b,bend=0){const [x1,y1]=POS[a],[x2,y2]=POS[b],cx=(x1+x2)/2+bend,cy=(y1+y2)/2-30;return `M${x1},${y1} Q${cx},${cy} ${x2},${y2}`}
function cartouchePath(x,y,w,h){const l=x-w/2,r=x+w/2,t=y-h/2,b=y+h/2,tip=12,rr=9;return `M${l+rr},${t} H${r-tip-rr} Q${r-tip},${t} ${r-tip},${t+rr} L${r},${y} L${r-tip},${b-rr} Q${r-tip},${b} ${r-tip-rr},${b} H${l+tip+rr} Q${l+tip},${b} ${l+tip},${b-rr} L${l},${y} L${l+tip},${t+rr} Q${l+tip},${t} ${l+tip+rr},${t} Z`}
function visibleNodes(){return N.filter(n=>mode==="doc"?["verified","probable","tradition"].includes(n.s):mode==="hyp"?["hypothesis","open","pruned"].includes(n.s)||n.id==="place":n.s!=="pruned")}
function renderTree(){const lang=currentLang(),vis=visibleNodes(),ids=new Set(vis.map(n=>n.id));svg.innerHTML=`<defs><filter id="whiteGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="trunkG" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#0b2c19"/><stop offset=".65" stop-color="#1edb72"/><stop offset="1" stop-color="#7dffae"/></linearGradient></defs><path d="M600 758 C590 720 605 690 600 654 C594 610 581 564 592 516 C601 473 608 441 600 409" stroke="url(#trunkG)" stroke-width="18" fill="none" stroke-linecap="round" opacity=".83"/><path d="M600 748 C520 759 465 772 402 786 M600 748 C684 756 756 775 824 788 M600 742 C552 765 526 780 500 790 M600 742 C650 765 674 780 700 790" stroke="#113c22" stroke-width="7" fill="none" stroke-linecap="round"/><circle cx="600" cy="692" r="34" class="tree-ring"/><circle cx="600" cy="692" r="8" class="tree-heart"/><text x="600" y="738" text-anchor="middle" class="tree-root-label">LIVING RESEARCH 001</text>`
N.filter(n=>n.p&&ids.has(n.id)&&ids.has(n.p)).forEach(n=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",pathBetween(n.p,n.id,(POS[n.id][0]-POS[n.p][0])*.08));p.setAttribute("class",`branch-main ${n.s}`);const widths={verified:5.2,probable:4,tradition:3.1,hypothesis:2.2,open:2,pruned:1.6};p.setAttribute("stroke",STATUS[n.s].c);p.setAttribute("stroke-width",widths[n.s]);p.setAttribute("opacity",n.s==="verified"?.82:n.s==="pruned"?.38:.62);if(n.s==="pruned")p.setAttribute("stroke-dasharray","6 8");svg.appendChild(p)})
CROSS.filter(c=>ids.has(c[0])&&ids.has(c[1])).forEach(c=>{const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",pathBetween(c[0],c[1],42));p.setAttribute("class",`branch-cross ${c[2]}`);p.dataset.a=c[0];p.dataset.b=c[1];p.addEventListener("click",()=>openCross(c));svg.appendChild(p)})
vis.forEach(n=>{const [x,y]=POS[n.id],g=document.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("class",`leaf ${n.s}`);let w=n.id==="place"?154:Math.max(86,Math.min(146,(n[lang].length*7.7)+32)),h=n.id==="place"?42:31;const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",cartouchePath(x,y,w,h));path.setAttribute("class","cartouche");if(n.s==="verified")path.setAttribute("filter","url(#whiteGlow)");const seal=document.createElementNS("http://www.w3.org/2000/svg","circle");seal.setAttribute("cx",x-(w/2)+14);seal.setAttribute("cy",y);seal.setAttribute("r",3.3);seal.setAttribute("class","seal");const t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("x",x);t.setAttribute("y",y+4);t.setAttribute("text-anchor","middle");t.textContent=n[lang];g.append(path,seal,t);g.onclick=()=>openNode(n);svg.appendChild(g)})}
function srcLinks(ids){return (ids||[]).map(id=>{const s=SOURCES.find(x=>x[0]===id);return s?`<a href="${s[3]}" target="_blank" rel="noopener">${s[0]}</a>`:""}).join("")}
function openNode(n){const lang=currentLang(),st=STATUS[n.s];drawer.classList.add("show");drawer.innerHTML=`<div class="eyebrow" style="color:${st.c}">${st[lang]}</div><h3>${n[lang]}</h3><p>${n[lang+"D"]}</p><div class="sources-mini">${srcLinks(n.src)}</div><div class="why">${lang==="ar"?"درجة الثقة قابلة للتغيير مع ظهور مصادر أقوى أو أدلة مضادة":"Confidence can change when stronger sources or disconfirming evidence appears"}</div><p><button id="closeNode">${lang==="ar"?"إغلاق":"Close"}</button></p>`;document.getElementById("closeNode").onclick=()=>drawer.classList.remove("show")}
function openCross(c){const lang=currentLang();drawer.classList.add("show");const a=N.find(n=>n.id===c[0]),b=N.find(n=>n.id===c[1]);drawer.innerHTML=`<div class="eyebrow" style="color:#d2b15b">${lang==="ar"?"مفاغرة معرفية":"Knowledge anastomosis"}</div><h3>${a[lang]} ↔ ${b[lang]}</h3><p>${lang==="ar"?c[3]:c[4]}</p><div class="why">${lang==="ar"?"هذه الوصلة لا تدمج الفرعين، بل تسجل دعماً أو توتراً بين مسارين مستقلين":"This link does not merge the branches, it records support or tension between independent paths"}</div><p><button id="closeNode">${lang==="ar"?"إغلاق":"Close"}</button></p>`;document.getElementById("closeNode").onclick=()=>drawer.classList.remove("show")}
function setMode(m,b){mode=m;document.querySelectorAll(".tree-toolbar button").forEach(x=>x.classList.remove("on"));b.classList.add("on");drawer.classList.remove("show");renderTree()}
allBtn.onclick=()=>setMode("all",allBtn);docBtn.onclick=()=>setMode("doc",docBtn);hypBtn.onclick=()=>setMode("hyp",hypBtn)
function translateLocal(){const lang=currentLang();document.querySelectorAll("[data-ar]").forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll("[data-ar-ph]").forEach(e=>e.placeholder=e.dataset[lang+"Ph"]||e.dataset.arPh);renderTree();renderTimeline();renderSources();renderMap()}
document.addEventListener("luxlang",()=>setTimeout(translateLocal,0))
document.querySelectorAll(".r-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".r-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".r-view").forEach(v=>v.classList.remove("active"));document.getElementById(b.dataset.view).classList.add("active");if(b.dataset.view==="mapView"&&map)setTimeout(()=>map.invalidateSize(),80)})
function renderTimeline(){const lang=currentLang();timeline.innerHTML=EVENTS.map(e=>`<div class="timeline-event"><div class="year">${e[0]}</div><h3>${e[1]}</h3><p>${lang==="ar"?e[2]:e[3]}</p></div>`).join("")}
function renderSources(){const lang=currentLang();sourcesList.innerHTML=SOURCES.map(s=>`<div class="source-row"><b>${s[0]} · ${s[1]}</b><small>${s[2]}</small><a href="${s[3]}" target="_blank" rel="noopener">${lang==="ar"?"فتح المصدر":"Open source"} ↗</a></div>`).join("")}
nodeStat.textContent=N.length;sourceStat.textContent=SOURCES.length
let P=[],layer=null,map=null
function initMap(){
 if(!window.L){
   const el=document.getElementById("map");
   if(el)el.innerHTML=`<div style="height:100%;display:grid;place-items:center;padding:30px;color:#718279;text-align:center">${currentLang()==="ar"?"الخريطة تحتاج اتصالاً بخادم الخرائط، البحث والشجرة يعملان بشكل مستقل":"The map needs access to the map service, while the research tree works independently"}</div>`;
   return
 }
 map=L.map("map",{zoomControl:true}).setView([51.506,4.862],10)
 L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:19,attribution:"© OpenStreetMap © CARTO"}).addTo(map)
 L.circle([51.506,4.862],{radius:25000,color:"#63ff9b",weight:1.5,fillOpacity:.012,dashArray:"7 8"}).addTo(map)
 L.circleMarker([51.506,4.862],{radius:6,color:"#f3fff7",weight:1,fillColor:"#63ff9b",fillOpacity:1}).addTo(map).bindPopup("<b>شام / Chaam</b>")
 layer=L.layerGroup().addTo(map)
 fetch("data/care-points.json").then(r=>r.json()).then(x=>{P=x;[...new Set(P.map(x=>x.category))].sort().forEach(x=>mapCat.add(new Option(x,x)));[...new Set(P.map(x=>x.town))].sort().forEach(x=>mapTown.add(new Option(x,x)));renderMap()}).catch(()=>{})
}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderMap(){if(!P.length||!layer)return;const lang=currentLang(),z=mapSearch.value.toLowerCase(),f=P.filter(p=>(!mapCat.value||p.category===mapCat.value)&&(!mapTown.value||p.town===mapTown.value)&&(!z||JSON.stringify(p).toLowerCase().includes(z)));mapCount.textContent=(lang==="ar"?"النقاط الظاهرة  ":"Visible points  ")+f.length;mapList.innerHTML=f.map(p=>`<div class="map-item"><b>${esc(p.name)}</b><div class="map-meta">${esc(lang==="ar"?p.displayTownAR:p.displayTownEN)} · ${p.distance.toFixed(1)} km · ${esc(p.category)}</div></div>`).join("");layer.clearLayers();f.forEach(p=>L.circleMarker([p.lat,p.lon],{radius:5,weight:1,color:"#001006",fillColor:"#63ff9b",fillOpacity:.72}).addTo(layer).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.category)}<br><small>${esc(p.location)} · ${p.distance.toFixed(1)} km</small>${p.url?`<br><a target="_blank" rel="noopener" href="${esc(p.url)}">Source / website</a>`:""}`))}
;[mapSearch,mapCat,mapTown].forEach(e=>e.addEventListener(e.tagName==="INPUT"?"input":"change",renderMap))
window.addEventListener("DOMContentLoaded",()=>{translateLocal();initMap();if(location.hash==="#mapView"){const b=document.querySelector('.r-tabs button[data-view="mapView"]');if(b)b.click()}})
