(()=>{
'use strict';
const NAMES={ar:'رافي الحجي',en:'Rafy Alhajji',nl:'Rafy Alhajji',jv:'Rafy Alhajji',he:"ראפי אלחג׳י"};
function lang(){return (window.LuxLang&&window.LuxLang.get())||document.documentElement.lang||'en'}
function replaceNames(){const l=lang(),want=NAMES[l]||NAMES.en;const needles=['رافي الحجي','Rafy Alhajji','Rafy Alhajji','Rafy Alhajji',"ראפי אלחג׳י"];
 const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(n.parentElement&&/SCRIPT|STYLE|TEXTAREA/.test(n.parentElement.tagName))continue;let t=n.nodeValue;for(const s of needles)if(t.includes(s))t=t.split(s).join(want);if(t!==n.nodeValue)n.nodeValue=t}}
function clickParity(){document.querySelectorAll('[data-href]').forEach(c=>{if(c.dataset.clickParity)return;c.dataset.clickParity='1';c.tabIndex=c.tabIndex<0?0:c.tabIndex;c.setAttribute('role','link');const go=()=>{const h=c.dataset.href;if(h)location.href=h};c.addEventListener('click',e=>{if(e.target.closest('a,button,select,input'))return;go()});c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
 document.querySelectorAll('.cards .card').forEach(c=>{const a=c.querySelector('a[href]');if(!a||c.dataset.clickParity)return;c.dataset.clickParity='1';c.tabIndex=0;c.setAttribute('role','link');c.addEventListener('click',e=>{if(e.target.closest('a,button,select,input'))return;location.href=a.href});c.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a,button,select,input')){e.preventDefault();location.href=a.href}})})}
function entryFailSafe(){if(!document.body.classList.contains('home-arrival'))return;const clear=()=>{document.body.classList.remove('home-arrival','home-arrival-go');try{sessionStorage.removeItem('luxdot.entry.point')}catch{}};setTimeout(clear,1250);if(lang()==='ar'||lang()==='he')setTimeout(clear,80)}

function languageSafety(){const l=lang();if(l==='ar')return;const file=(location.pathname.split('/').pop()||'');if(['quran.html','tanakh.html','new-testament.html'].includes(file))return;if(document.body.dataset.fullLocales==='1')return;const main=document.querySelector('main');if(!main)return;const txt=main.innerText||'';const arab=(txt.match(/[\u0600-\u06FF]/g)||[]).length;if(arab<120)return;const links=[...main.querySelectorAll('a[href^="http"]')].slice(0,8).map(a=>[a.href,(a.textContent||'Source').replace(/[\u0600-\u06FF]/g,'').trim()||'Source']);const proper=(document.title||file).split('·')[0].trim();const T={en:['Language-safe dossier','This legacy dossier still contains untranslated Arabic master text. Rather than mix languages, LuxDot hides that layer in this view until a complete translation is available. The original sources remain accessible below.','Sources'],nl:['Taalveilige dossierweergave','Dit oudere dossier bevat nog onvertaalde Arabische mastertekst. In plaats van talen te mengen verbergt LuxDot die laag in deze weergave totdat een volledige vertaling beschikbaar is. De oorspronkelijke bronnen blijven hieronder toegankelijk.','Bronnen'],jv:['Tampilan dossier aman basa','Dossier lawas iki isih nduweni teks master Arab sing durung rampung diterjemahake. Supaya basa ora campur, lapisan iku didhelikake nganti terjemahan lengkap siap. Sumber asli tetep bisa dibukak ing ngisor.','Sumber'],he:['תצוגת תיק בטוחה מבחינת שפה','בתיק הישן עדיין נשאר טקסט מקור ערבי שלא תורגם במלואו. כדי לא לערבב שפות, LuxDot מסתיר שכבה זו בתצוגה הזאת עד להשלמת התרגום. המקורות המקוריים נשארים זמינים למטה.','מקורות']}[l]||null;if(!T)return;main.innerHTML=`<section class="hero"><div class="lux-kicker">LUXDOT</div><h1>${proper||T[0]}</h1><p class="lead">${T[1]}</p></section><section class="card"><h2>${T[2]}</h2>${links.map(x=>`<p><a target="_blank" rel="noopener" href="${x[0]}">${x[1]} ↗</a></p>`).join('')}</section>`}

function run(){replaceNames();clickParity();entryFailSafe();setTimeout(languageSafety,360)}
let timer;const later=()=>{clearTimeout(timer);timer=setTimeout(()=>{replaceNames();clickParity()},80)};document.addEventListener('DOMContentLoaded',()=>{run();const m=new MutationObserver(later);m.observe(document.body,{childList:true,subtree:true})});document.addEventListener('luxlang',()=>setTimeout(run,20));
})();