window.LUX_VALUES = [
{ar:"الكرامة",en:"Dignity",branch:"human",shadow:"الإذلال",behavior:"لا تُختزل قيمة الإنسان في فائدته أو هويته.",links:["الحرية","العدل","الرعاية"]},
{ar:"الحقيقة",en:"Truth",branch:"knowledge",shadow:"الخداع",behavior:"نميّز بين الوقائع والفرضيات ونصحح الخطأ علنًا.",links:["الدقة","الأمانة","التواضع"]},
{ar:"الرحمة",en:"Compassion",branch:"relation",shadow:"القسوة",behavior:"نستجيب للألم دون إذلال صاحبه.",links:["الرعاية","الإحسان","السلام"]},
{ar:"العدل",en:"Justice",branch:"society",shadow:"الظلم",behavior:"نطبق معيارًا قابلًا للتبرير على الجميع.",links:["الكرامة","المسؤولية","الحرية"]},
{ar:"الحرية",en:"Freedom",branch:"human",shadow:"القسر",behavior:"نحمي الاختيار والضمير مع حدود الضرر.",links:["الكرامة","المسؤولية","التسامح"]},
{ar:"المسؤولية",en:"Responsibility",branch:"society",shadow:"التنصل",behavior:"نعلن من اتخذ القرار ونقبل التصحيح.",links:["العدل","الأمانة","الإصلاح"]},
{ar:"الشجاعة",en:"Courage",branch:"self",shadow:"الجبن / التهور",behavior:"نواجه الخطر الضروري دون تمجيد المخاطرة.",links:["الحقيقة","المسؤولية","الأمل"]},
{ar:"الحكمة",en:"Wisdom",branch:"knowledge",shadow:"الرعونة",behavior:"نوازن المعرفة والسياق والعواقب.",links:["التواضع","الدقة","الرحمة"]},
{ar:"الأمانة",en:"Integrity",branch:"knowledge",shadow:"النفاق",behavior:"نصرّح بالمصدر والخطأ وتضارب المصالح.",links:["الحقيقة","المسؤولية","الوفاء"]},
{ar:"التواضع",en:"Humility",branch:"self",shadow:"الغرور",behavior:"نبقي احتمال الخطأ مفتوحًا.",links:["الحكمة","الحقيقة","الفضول"]},
{ar:"التضامن",en:"Solidarity",branch:"relation",shadow:"اللامبالاة",behavior:"لا نترك المتضرر وحده حين نستطيع المساعدة.",links:["الإحسان","العدل","الضيافة"]},
{ar:"الضيافة",en:"Hospitality",branch:"relation",shadow:"الإقصاء",behavior:"نفسح مكانًا للغريب دون محو اختلافه.",links:["التسامح","الكرامة","التضامن"]},
{ar:"الإحسان",en:"Beneficence",branch:"relation",shadow:"الأنانية",behavior:"نحوّل النية الحسنة إلى منفعة قابلة للملاحظة.",links:["الرحمة","التضامن","الرعاية"]},
{ar:"الوفاء",en:"Loyalty",branch:"relation",shadow:"الخيانة / الطاعة العمياء",behavior:"نحفظ العهد دون تعطيل الضمير.",links:["الأمانة","المسؤولية"]},
{ar:"التسامح",en:"Tolerance",branch:"society",shadow:"التعصب",behavior:"نقبل الاختلاف مع حق نقد الضرر.",links:["الحرية","الضيافة","السلام"]},
{ar:"السلام",en:"Peace",branch:"society",shadow:"العنف",behavior:"نقلل العنف ونبني شروط سلام عادل.",links:["العدل","الرحمة","الإصلاح"]},
{ar:"الإصلاح",en:"Repair",branch:"future",shadow:"الإهمال",behavior:"بعد الضرر نسأل: ماذا يمكن إصلاحه فعليًا؟",links:["المسؤولية","السلام","الرعاية"]},
{ar:"الفضول",en:"Curiosity",branch:"knowledge",shadow:"الانغلاق",behavior:"نسأل قبل أن نحكم.",links:["الإبداع","التواضع","الحقيقة"]},
{ar:"الإبداع",en:"Creativity",branch:"future",shadow:"الجمود",behavior:"ننتج بدائل جديدة ونختبرها.",links:["الفضول","الجمال","الأمل"]},
{ar:"الدقة",en:"Precision",branch:"knowledge",shadow:"الالتباس",behavior:"نعرّف المصطلح والمقياس وحدود الاستنتاج.",links:["الحقيقة","الحكمة","الأمانة"]},
{ar:"الرعاية",en:"Care",branch:"earth",shadow:"الإهمال",behavior:"نعتني بالإنسان والكائن والمكان باستمرار.",links:["الرحمة","الاستدامة","الإصلاح"]},
{ar:"الاستدامة",en:"Sustainability",branch:"earth",shadow:"الاستنزاف",behavior:"لا نستهلك المستقبل لمصلحة الحاضر.",links:["الرعاية","المسؤولية"]},
{ar:"الجمال",en:"Beauty",branch:"future",shadow:"الابتذال / الزينة الفارغة",behavior:"نعتني بالشكل دون جعله بديلًا عن الحقيقة.",links:["الإبداع","الحقيقة"]},
{ar:"الأمل",en:"Hope",branch:"future",shadow:"اليأس / الوهم",behavior:"نبقي المستقبل قابلًا للعمل دون إنكار الواقع.",links:["الشجاعة","الإصلاح","الإبداع"]}
];