(()=>{
"use strict";
const I={ar:{k:'LUXDOT · شبكة المستضعفين',title:'دائرة الرعاية · شام + 25 كم',lead:'خريطة تفاعلية محلية تعمل مباشرة من بيانات LuxDot ولا تحتاج إلى Leaflet أو خادم خرائط خارجي. تعرض جهات ومؤسسات عامة، لا أشخاصاً مستضعفين.',points:'نقطة ظاهرة',records:'سجل بحثي',search:'ابحث بالاسم أو الحاجة أو المدينة…',allcat:'كل الفئات',alltown:'كل المناطق',privacy:'خصوصية بالتصميم — لا أسماء أو بيانات شخصية لسكان أو مرضى أو قاصرين أو طالبي لجوء. بعض المواقع الخاصة تقريبية أو مخفية عمداً.',source:'المصدر / الموقع',nomap:'تعذر رسم الخريطة، لكن قائمة الجهات أدناه ما زالت قابلة للبحث.'},en:{k:'LUXDOT · VULNERABILITY NETWORK',title:'Circle of Care · Chaam + 25 km',lead:'A local interactive map rendered directly from LuxDot data. It requires neither Leaflet nor an external map server and shows public organizations, not vulnerable individuals.',points:'visible points',records:'research records',search:'Search name, need, town…',allcat:'All categories',alltown:'All areas',privacy:'Privacy by design — no personal data of residents, patients, minors or asylum seekers. Selected private locations are approximate or intentionally hidden.',source:'Source / website',nomap:'The map could not be drawn, but the searchable organization list remains available.'},nl:{k:'LUXDOT · NETWERK VOOR KWETSBAREN',title:'Zorgcirkel · Chaam + 25 km',lead:'Een lokale interactieve kaart die rechtstreeks uit LuxDot-data wordt getekend. Leaflet of een externe kaartserver is niet nodig. De kaart toont publieke organisaties, geen kwetsbare personen.',points:'zichtbare punten',records:'onderzoeksrecords',search:'Zoek naam, behoefte, plaats…',allcat:'Alle categorieën',alltown:'Alle gebieden',privacy:'Privacy by design — geen persoonsgegevens van bewoners, patiënten, minderjarigen of asielzoekers. Sommige privélocaties zijn benaderd of bewust verborgen.',source:'Bron / website',nomap:'De kaart kon niet worden getekend, maar de doorzoekbare lijst blijft beschikbaar.'},id:{k:'LUXDOT · JARINGAN KERENTANAN',title:'Lingkar Kepedulian · Chaam + 25 km',lead:'Peta interaktif lokal yang digambar langsung dari data LuxDot. Leaflet dan server peta eksternal tidak diperlukan. Peta menampilkan organisasi publik, bukan individu rentan.',points:'titik terlihat',records:'catatan riset',search:'Cari nama, kebutuhan, kota…',allcat:'Semua kategori',alltown:'Semua area',privacy:'Privasi sejak desain — tidak ada data pribadi penghuni, pasien, anak di bawah umur, atau pencari suaka. Beberapa lokasi privat dibuat perkiraan atau sengaja disembunyikan.',source:'Sumber / situs',nomap:'Peta tidak dapat digambar, tetapi daftar organisasi tetap dapat dicari.'}};
const $=id=>document.getElementById(id);
const E={k:$('careKicker'),title:$('careTitle'),lead:$('careLead'),count:$('count'),points:$('pointsLabel'),records:$('recordsLabel'),q:$('q'),cat:$('cat'),town:$('town'),list:$('list'),privacy:$('privacy'),map:$('offlineMap'),svg:$('careSvg'),popup:$('carePopup')};
const raw=Array.isArray(window.CARE_POINTS)?window.CARE_POINTS:[];
const P=raw.map((p,i)=>({...p,id:Number(p.id)||i+1,lat:Number(p.lat),lon:Number(p.lon),distance:Number(p.distance)||0})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));
const B={minLat:51.44,maxLat:51.66,minLon:4.61,maxLon:5.02}; let active=null;
function language(){return localStorage.getItem('luxdot.lang')||document.documentElement.lang||'ar'}
function L(){return I[language()]||I.en}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function project(lat,lon){const w=1000,h=650,p=50;return [p+(lon-B.minLon)/(B.maxLon-B.minLon)*(w-2*p), h-p-(lat-B.minLat)/(B.maxLat-B.minLat)*(h-2*p)]}
function current(){const z=(E.q.value||'').trim().toLocaleLowerCase();return P.filter(p=>(!E.cat.value||p.category===E.cat.value)&&(!E.town.value||p.town===E.town.value)&&(!z||[p.name,p.town,p.location,p.category,p.serves,p.type].join(' ').toLocaleLowerCase().includes(z)))}
function popupFor(p,evt){if(!p||!E.popup||!E.map)return;const r=E.map.getBoundingClientRect();let x=r.width/2+12,y=r.height/2+12;if(evt&&Number.isFinite(evt.clientX)){x=evt.clientX-r.left+12;y=evt.clientY-r.top+12}E.popup.innerHTML=`<b>${esc(p.name)}</b><br><small>${esc(p.town)} · ${p.distance.toFixed(1)} km</small><br>${esc(p.category)}<br>${esc(p.serves||'')}${p.url?`<br><a target="_blank" rel="noopener" href="${esc(p.url)}">${esc(L().source)}</a>`:''}`;E.popup.style.left=Math.max(8,Math.min(x,r.width-310))+'px';E.popup.style.top=Math.max(8,Math.min(y,r.height-175))+'px';E.popup.classList.add('show');active=p.id;draw()}
function draw(){const f=current();E.count.textContent=String(f.length);E.list.innerHTML=f.map(p=>`<button type="button" class="map-item" data-care-id="${p.id}"><b>${esc(p.name)}</b><span class="map-meta">${esc(p.town)} · ${p.distance.toFixed(1)} km · ${esc(p.category)}</span></button>`).join('')||`<div class="map-empty">0</div>`;
 let o='<rect x="0" y="0" width="1000" height="650" class="omap-bg"/>';
 for(let x=100;x<1000;x+=100)o+=`<line class="omap-grid" x1="${x}" y1="0" x2="${x}" y2="650"/>`;for(let y=100;y<650;y+=100)o+=`<line class="omap-grid" x1="0" y1="${y}" x2="1000" y2="${y}"/>`;
 const [cx,cy]=project(51.506,4.862); const kmLon=111.32*Math.cos(51.506*Math.PI/180),rx=25/kmLon*(900/(B.maxLon-B.minLon)),ry=25/111.32*(550/(B.maxLat-B.minLat));
 o+=`<ellipse class="omap-ring" cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}"/><circle class="omap-anchor" cx="${cx}" cy="${cy}" r="7"/><text class="omap-label" x="${cx+12}" y="${cy-12}">${language()==='ar'?'شام':'Chaam'}</text>`;
 for(const p of f){const [x,y]=project(p.lat,p.lon);o+=`<g class="care-pin" data-care-id="${p.id}" tabindex="0" role="button" aria-label="${esc(p.name)}"><circle class="omap-point${active===p.id?' active':''}" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="5.2"/><circle class="omap-hit" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="20"/></g>`}
 E.svg.innerHTML=o; bind();
}
function bind(){document.querySelectorAll('[data-care-id]').forEach(n=>{const act=e=>{const p=P.find(x=>x.id===Number(n.dataset.careId));if(p)popupFor(p,e)};n.addEventListener('click',act);n.addEventListener('pointerup',e=>{if(e.pointerType==='touch'){e.preventDefault();act(e)}});n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();act(e)}})})}
function fill(){for(const x of [...new Set(P.map(p=>p.category).filter(Boolean))].sort())E.cat.add(new Option(x,x));for(const x of [...new Set(P.map(p=>p.town).filter(Boolean))].sort())E.town.add(new Option(x,x))}
function apply(){const x=L();document.documentElement.lang=language();document.documentElement.dir=language()==='ar'?'rtl':'ltr';E.k.textContent=x.k;E.title.textContent=x.title;E.lead.textContent=x.lead;E.points.textContent=x.points;E.records.textContent=x.records;E.q.placeholder=x.search;E.cat.options[0].text=x.allcat;E.town.options[0].text=x.alltown;E.privacy.textContent=x.privacy;draw()}
function boot(){if(Object.values(E).some(x=>!x)){console.error('LuxDot Care Map: missing DOM node',E);return}fill();E.q.addEventListener('input',draw);E.cat.addEventListener('change',draw);E.town.addEventListener('change',draw);document.addEventListener('luxlang',apply);window.addEventListener('storage',e=>{if(e.key==='luxdot.lang')apply()});apply(); if(!P.length){E.svg.innerHTML=`<text x="500" y="325" text-anchor="middle" class="omap-error">${esc(L().nomap)}</text>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();