(()=>{"use strict";
const C=document.getElementById('matrix'),x=C.getContext('2d'),signals=document.getElementById('signals'),gate=document.getElementById('gate'),enter=document.getElementById('enter'),sound=document.getElementById('sound'),sub=document.getElementById('sub'),eyebrow=document.getElementById('eyebrow'),micro=document.getElementById('micro'),burst=document.getElementById('burst'),statusA=document.getElementById('statusA'),statusB=document.getElementById('statusB');
const ordinary=[...'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ','ｱ','ｲ','ｳ','ｴ','ｵ','ｶ','ｷ','ｸ','ｹ','ｺ','+','−','=','∴','∞','Δ','Ω','φ'];
const rareByLang={
 ar:['نور','ذاكرة','شهادة','حقيقة','رحمة','سلام','إشارة','فهم','معرفة','عدل','وعي','E=mc²','∞','Δ','Ω'],
 en:['LIGHT','MEMORY','WITNESS','TRUTH','CARE','PEACE','SIGNAL','UNDERSTANDING','KNOWLEDGE','E=mc²','∞','Δ','Ω'],
 nl:['LICHT','GEHEUGEN','GETUIGENIS','WAARHEID','ZORG','VREDE','SIGNAAL','BEGRIP','KENNIS','E=mc²','∞','Δ','Ω'],
 jv:['CAHYA','PANGELING','SEKSI','KABENERAN','KAWELASAN','TENTREM','TANDHA','PANGERTEN','KAWRUH','E=mc²','∞','Δ','Ω'],
 he:['אור','זיכרון','עדות','אמת','חמלה','שלום','אות','הבנה','ידע','צדק','E=mc²','∞','Δ','Ω']
};
function currentRare(){return rareByLang[lang]||rareByLang.ar}
let W,H,dpr,fs,cols=[],last=0,clarity=0,lastPoint={x:innerWidth/2,y:innerHeight/2};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;C.style.width=W+'px';C.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);fs=W<700?13:16;cols=Array.from({length:Math.ceil(W/fs)},(_,i)=>({x:i*fs,y:Math.random()*H,s:.55+Math.random()*1.45,a:.12+Math.random()*.45}))}addEventListener('resize',resize);resize();
function frame(t){if(t-last<42){requestAnimationFrame(frame);return}last=t;x.fillStyle='rgba(0,4,1,.13)';x.fillRect(0,0,W,H);x.font=`${fs}px monospace`;for(const c of cols){const special=Math.random()<.005+clarity*.005,ch=special?currentRare()[(Math.random()*currentRare().length)|0]:ordinary[(Math.random()*ordinary.length)|0];x.fillStyle=special?`rgba(215,255,226,${.35+c.a})`:`rgba(39,255,104,${c.a})`;x.shadowBlur=special?14:0;x.shadowColor='#4aff89';x.fillText(ch,c.x,c.y);x.shadowBlur=0;c.y+=fs*c.s;if(c.y>H+30&&Math.random()>.91)c.y=-30}requestAnimationFrame(frame)}requestAnimationFrame(frame);
function ghost(){const e=document.createElement('span');e.className='ghost';e.textContent=currentRare()[(Math.random()*currentRare().length)|0];e.style.left=(5+Math.random()*88)+'%';e.style.top=(7+Math.random()*82)+'%';e.style.fontSize=(8+Math.random()*5)+'px';signals.appendChild(e);setTimeout(()=>e.remove(),6200)}setInterval(ghost,900);for(let i=0;i<7;i++)setTimeout(ghost,i*240);
const L={ar:{dir:'rtl',sub:'نقطة الضوء الأولى · حيث يبدأ الفهم',eye:'تقليل الضجيج · زيادة الإشارة',enter:'استقبل الإشارة',micro:'من الضجيج إلى الذاكرة',a:'الإشارة / كامنة',b:'الضجيج ← الوضوح',acq:'الإشارة / تم التقاطها',mem:'الضجيج ← الذاكرة'},en:{dir:'ltr',sub:'The First Point of Light · Where Understanding Begins',eye:'REDUCING NOISE · INCREASING SIGNAL',enter:'RECEIVE THE SIGNAL',micro:'from noise into memory',a:'SIGNAL / LATENT',b:'NOISE → CLARITY',acq:'SIGNAL / ACQUIRED',mem:'NOISE → MEMORY'},nl:{dir:'ltr',sub:'Het eerste lichtpunt · Waar begrip begint',eye:'MINDER RUIS · MEER SIGNAAL',enter:'ONTVANG HET SIGNAAL',micro:'van ruis naar herinnering',a:'SIGNAAL / LATENT',b:'RUIS → HELDERHEID',acq:'SIGNAAL / GEVONDEN',mem:'RUIS → GEHEUGEN'},jv:{dir:'ltr',sub:'Titik cahya kapisan · Papan pangerten diwiwiti',eye:'NYUDA SWARA · NGUWATAKE TANDHA',enter:'TAMPA TANDHA',micro:'saka swara tumuju pangeling',a:'TANDHA / MENENG',b:'SWARA → CETHA',acq:'TANDHA / KATAMPA',mem:'SWARA → PANGELING'},he:{dir:'rtl',sub:'נקודת האור הראשונה · המקום שבו ההבנה מתחילה',eye:'מפחיתים רעש · מגבירים אות',enter:'קבל את האות',micro:'מרעש אל זיכרון',a:'אות / חבוי',b:'רעש ← בהירות',acq:'אות / נקלט',mem:'רעש ← זיכרון'}};
let lang='en';
function setLang(l,selected=false){if(!L[l])return;lang=l;if(selected)localStorage.setItem('luxdot.lang',l);document.documentElement.lang=l;document.documentElement.dir=L[l].dir;sub.textContent=L[l].sub;eyebrow.textContent=L[l].eye;enter.textContent=L[l].enter;micro.textContent=L[l].micro;statusA.textContent=L[l].a;statusB.textContent=L[l].b;const nativeNames={ar:'العربية',en:'English',nl:'Nederlands',jv:'Basa Jawa',he:'עברית'};document.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('on',selected&&b.dataset.lang===l);b.textContent=nativeNames[b.dataset.lang]||b.textContent})}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',e=>{rememberPoint(e);startAmbient();setLang(b.dataset.lang,true)}));setLang('en',false);
let audioCtx,master,on=false,nodes=[];
function startAmbient(){if(on)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioCtx=new AC();master=audioCtx.createGain();master.gain.value=.0001;master.connect(audioCtx.destination);const low=audioCtx.createOscillator();low.type='sine';low.frequency.value=43;const lowGain=audioCtx.createGain();lowGain.gain.value=.022;const fifth=audioCtx.createOscillator();fifth.type='sine';fifth.frequency.value=64.5;const fifthGain=audioCtx.createGain();fifthGain.gain.value=.006;const lfo=audioCtx.createOscillator(),lfoGain=audioCtx.createGain();lfo.frequency.value=.11;lfoGain.gain.value=.003;lfo.connect(lfoGain).connect(lowGain.gain);low.connect(lowGain).connect(master);fifth.connect(fifthGain).connect(master);low.start();fifth.start();lfo.start();master.gain.exponentialRampToValueAtTime(.7,audioCtx.currentTime+.9);nodes=[low,fifth,lfo];on=true;sound.classList.add('on')}
function stopAmbient(){if(!on)return;master.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.28);setTimeout(()=>{nodes.forEach(n=>{try{n.stop()}catch{}});audioCtx.close();on=false;nodes=[];sound.classList.remove('on')},320)}
function toggleSound(){on?stopAmbient():startAmbient()}sound.addEventListener('click',e=>{e.stopPropagation();rememberPoint(e);toggleSound()});
function rememberPoint(e){if(e&&Number.isFinite(e.clientX)){lastPoint={x:e.clientX,y:e.clientY}}}
document.addEventListener('pointerdown',e=>{rememberPoint(e);if(!on&&e.target!==sound)startAmbient()},{once:true});
function cross(e){rememberPoint(e);localStorage.setItem('luxdot.lang',lang);startAmbient();clarity=1;statusA.textContent=L[lang].acq;statusB.textContent=L[lang].mem;const px=(lastPoint.x/innerWidth*100).toFixed(2),py=(lastPoint.y/innerHeight*100).toFixed(2);sessionStorage.setItem('luxdot.entry.point',JSON.stringify({x:px,y:py}));burst.style.setProperty('--bx',lastPoint.x+'px');burst.style.setProperty('--by',lastPoint.y+'px');burst.classList.remove('go');void burst.offsetWidth;burst.classList.add('go');document.documentElement.style.setProperty('--crt-x',lastPoint.x+'px');document.documentElement.style.setProperty('--crt-y',lastPoint.y+'px');document.body.classList.add('crt-out');setTimeout(()=>location.href='home.html',1120)}
enter.addEventListener('click',cross);
})();